/* Source classic registered tab membership; source hidden logo/dummy and excluded songs stay absent. GPLv3. */
package cn.academy.port.display;
import java.util.List;
public final class ClassicCreativeCatalog {
    private ClassicCreativeCatalog(){}
    /** Source declarations define membership. Missing optional/staged devices are skipped until genuinely registered. */
    public static final List<String> ITEMS=List.of(
        "portable_developer",
        "developer_normal",
        "developer_advanced",
        "ability_interferer",
        "magnetic_coil",
        "induction_factor",
        "phase_liquid",
        "machine_frame",
        "constraint_metal_ore",
        "crystal_ore",
        "imag_silicon_ore",
        "reso_crystal_ore",
        "imag_fusor",
        "metal_former",
        "crystal_low",
        "crystal_normal",
        "crystal_pure",
        "calc_chip",
        "data_chip",
        "wafer",
        "constraint_ingot",
        "imag_silicon_ingot",
        "reinforced_iron_plate",
        "imag_silicon_piece",
        "reso_crystal",
        "constraint_plate",
        "brain_component",
        "info_component",
        "resonance_component",
        "energy_convert_component",
        "matter_unit",
        "matter_unit_phase_liquid",
        "terminal_installer",
        "coin",
        "maghook",
        "silbarn",
        "needle",
        "wireless_node_basic",
        "wireless_node_standard",
        "wireless_node_advanced",
        "wireless_matrix",
        "cat_engine",
        "solar_gen",
        "phase_gen",
        "windgen_base",
        "windgen_pillar",
        "windgen_main",
        "energy_unit",
        "matrix_core_0",
        "matrix_core_1",
        "matrix_core_2",
        "windgen_fan",
        "rf_input",
        "rf_output",
        "tutorial",
        "app_skill_tree",
        "app_freq_transmitter",
        "app_media_player");
}
