package cn.academy.port;
import net.neoforged.neoforge.common.ModConfigSpec;
public final class AcademyConfig {
    private static final ModConfigSpec.Builder BUILDER=new ModConfigSpec.Builder();
    public static final ModConfigSpec.BooleanValue ATTACK_PLAYERS=BUILDER.comment("Classic generic.attackPlayer: allow skills to attack players.").define("attackPlayers",true);
    public static final ModConfigSpec.BooleanValue DESTROY_BLOCKS=BUILDER.comment("Classic generic.destroyBlocks: allow ability terrain destruction.").define("destroyBlocks",true);
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends String>> DESTROYING_WORLDS=BUILDER.comment("Classic worldsWhitelistedDestroyingBlocks. Dimension resource IDs, or legacy vanilla IDs 0/-1/1. Overrides only global destroyBlocks; never a skill's local destroy_blocks=false.").defineListAllowEmpty("worldsWhitelistedDestroyingBlocks",java.util.List.of(),v->v instanceof String s&&(s.equals("0")||s.equals("-1")||s.equals("1")||net.minecraft.resources.ResourceLocation.tryParse(s)!=null));
    public static final ModConfigSpec.DoubleValue DAMAGE_SCALE=BUILDER.comment("Classic global skill damage multiplier.").defineInRange("damageScale",1.0,0.0,100.0);
    public static final ModConfigSpec.IntValue CP_RECOVER_COOLDOWN=BUILDER.defineInRange("classicData.cp_recover_cooldown",15,0,12000);
    public static final ModConfigSpec.IntValue OVERLOAD_RECOVER_COOLDOWN=BUILDER.defineInRange("classicData.overload_recover_cooldown",32,0,12000);
    public static final ModConfigSpec.DoubleValue CP_RECOVER_SPEED=BUILDER.defineInRange("classicData.cp_recover_speed",1D,0D,1000D);
    public static final ModConfigSpec.DoubleValue OVERLOAD_RECOVER_SPEED=BUILDER.defineInRange("classicData.overload_recover_speed",1D,0D,1000D);
    public static final ModConfigSpec.DoubleValue MAX_CP_INCREASE_RATE=BUILDER.defineInRange("classicData.maxcp_incr_rate",.0025D,0D,1000D);
    public static final ModConfigSpec.DoubleValue MAX_OVERLOAD_INCREASE_RATE=BUILDER.defineInRange("classicData.maxo_incr_rate",.0058D,0D,1000D);
    public static final ModConfigSpec.DoubleValue PROGRESS_INCREASE_RATE=BUILDER.defineInRange("classicData.prog_incr_rate",1D,0D,1000D);
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends Double>> INITIAL_CP=vector("classicData.init_cp",cn.academy.port.core.ClassicRules.BASE_CP);
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends Double>> INITIAL_OVERLOAD=vector("classicData.init_overload",cn.academy.port.core.ClassicRules.BASE_OVERLOAD);
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends Double>> ADD_CP=vector("classicData.add_cp",cn.academy.port.core.ClassicRules.EXTRA_CP_CAP);
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends Double>> ADD_OVERLOAD=vector("classicData.add_overload",cn.academy.port.core.ClassicRules.EXTRA_OVERLOAD_CAP);
    public static final ModConfigSpec.DoubleValue ELECTROMASTER_PROGRESS=BUILDER.defineInRange("classicCategoryProgress.electromaster",1D,0D,1000D), MELTDOWNER_PROGRESS=BUILDER.defineInRange("classicCategoryProgress.meltdowner",1D,0D,1000D), TELEPORTER_PROGRESS=BUILDER.defineInRange("classicCategoryProgress.teleporter",1D,0D,1000D), VECTOR_PROGRESS=BUILDER.defineInRange("classicCategoryProgress.vecmanip",1D,0D,1000D);
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends String>> SKILL_NUMERIC_OVERRIDES=BUILDER.comment("Canonical category.skill.key=value entries. Preserve classic1.0.7: present cp_consume_speed, overload_consume_speed or overload_incr_speed reads damage_scale, regardless of its own value. exp_incr_speed is ignored. Include damage_scale with a present cost key. Force and raw canPerform bypass these scales.").defineListAllowEmpty("classicSkillOverrides",java.util.List.of(),value->value instanceof String);
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends String>> ENTITY_DIFFICULTIES=BUILDER.comment("Classic EntityAffection ordered name=difficulty entries, captured at world startup. Default legacy aliases preserved; modern resource IDs supported. Unknown entity names ignored. First matching class wins. Finite nonnegative values protect saved CP from invalid input.").defineListAllowEmpty("ac.ability.category.vecmanip.common.affected_entities.difficulties",cn.academy.port.skill.ClassicEntityAffectionConfiguration.DEFAULT_DIFFICULTIES,v->{if(!(v instanceof String s))return false;int at=s.indexOf('=');if(at<1||at==s.length()-1)return false;try{float value=Float.parseFloat(s.substring(at+1).trim());return Float.isFinite(value)&&value>=0;}catch(NumberFormatException ignored){return false;}});
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends String>> ENTITY_EXCLUDED=BUILDER.comment("Classic EntityAffection excluded names; subclass matching. Defaults Item/Mob/Monster/XPOrb. Unknown names ignored. Changing this list requires a new world/server load, matching source startup capture.").defineListAllowEmpty("ac.ability.category.vecmanip.common.affected_entities.excluded",cn.academy.port.skill.ClassicEntityAffectionConfiguration.DEFAULT_EXCLUDED,v->v instanceof String);
    public record SkillFlags(ModConfigSpec.BooleanValue enabled,ModConfigSpec.BooleanValue destroyBlocks){}
    public static final java.util.Map<cn.academy.port.core.ClassicSkillConfiguration.Key,SkillFlags> SKILL_FLAGS=skillFlags();
    public static final ModConfigSpec SPEC=BUILDER.build();
    private static java.util.Map<cn.academy.port.core.ClassicSkillConfiguration.Key,SkillFlags> skillFlags(){var values=new java.util.LinkedHashMap<cn.academy.port.core.ClassicSkillConfiguration.Key,SkillFlags>();SkillCatalog.CONFIG_KEYS.stream().sorted(java.util.Comparator.comparing(cn.academy.port.core.ClassicSkillConfiguration.Key::sourcePath)).forEach(key->{var enabled=BUILDER.comment("Classic source live enabled getter. Registered IDs and saved learned/passive/preset state remain intact. Dependencies are captured when this world's config first loads.").define(key.sourcePath()+".enabled",true);var destroy=BUILDER.comment("Classic local AbilityContext terrain flag; direct-write source exceptions remain separate.").define(key.sourcePath()+".destroy_blocks",true);values.put(key,new SkillFlags(enabled,destroy));});return java.util.Map.copyOf(values);}
    private static java.util.Map<cn.academy.port.core.ClassicSkillConfiguration.Key,cn.academy.port.core.ClassicSkillConfiguration.Flags> flags(){var values=new java.util.LinkedHashMap<cn.academy.port.core.ClassicSkillConfiguration.Key,cn.academy.port.core.ClassicSkillConfiguration.Flags>();SKILL_FLAGS.forEach((key,value)->values.put(key,new cn.academy.port.core.ClassicSkillConfiguration.Flags(value.enabled.get(),value.destroyBlocks.get())));return values;}
    public static void loading(net.neoforged.fml.event.config.ModConfigEvent.Loading event){if(event.getConfig().getSpec()==SPEC){SkillCatalog.initializeConfiguration(flags());cn.academy.port.skill.ClassicEntityAffectionConfiguration.initialize(ENTITY_DIFFICULTIES.get(),ENTITY_EXCLUDED.get());}}
    public static void reloading(net.neoforged.fml.event.config.ModConfigEvent.Reloading event){if(event.getConfig().getSpec()==SPEC)SkillCatalog.refreshConfiguration(flags());}
    public static void unloading(net.neoforged.fml.event.config.ModConfigEvent.Unloading event){if(event.getConfig().getSpec()==SPEC){SkillCatalog.resetConfiguration();cn.academy.port.skill.ClassicEntityAffectionConfiguration.reset();}}
    /** Modern resource-key equivalent of the source legacy dimension-ID whitelist. */
    public static boolean canDestroyBlocks(net.minecraft.world.level.Level world){if(DESTROY_BLOCKS.get())return true;String dimension=world.dimension().location().toString();return DESTROYING_WORLDS.get().stream().map(AcademyConfig::dimensionKey).anyMatch(dimension::equals);}
    private static String dimensionKey(String value){return switch(value){case "0"->"minecraft:overworld";case "-1"->"minecraft:the_nether";case "1"->"minecraft:the_end";default->value;};}
    public static boolean contextTerrain(net.minecraft.world.level.Level world,String category,String skill){return SkillCatalog.configuration().contextTerrain(category,skill,canDestroyBlocks(world));}
    public static boolean contextTerrain(net.minecraft.world.level.Level world,String qualifiedSkill){int dot=qualifiedSkill.indexOf('.');if(dot<1)throw new IllegalArgumentException("qualified source skill required");return contextTerrain(world,qualifiedSkill.substring(0,dot),qualifiedSkill.substring(dot+1));}
    private static ModConfigSpec.ConfigValue<java.util.List<? extends Double>> vector(String name,double[] values){return BUILDER.defineListAllowEmpty(name,java.util.Arrays.stream(values).boxed().toList(),v->v instanceof Number n&&Double.isFinite(n.doubleValue())&&n.doubleValue()>=0);}
    private static double[] data(java.util.List<? extends Double> values){if(values.size()!=6)throw new IllegalStateException("Classic data vectors require six levels");return values.stream().mapToDouble(Number::doubleValue).toArray();}
    public static cn.academy.port.core.SkillConsumption.Config consumptionConfig(){return new cn.academy.port.core.SkillConsumption.Config(CP_RECOVER_COOLDOWN.get(),OVERLOAD_RECOVER_COOLDOWN.get(),MAX_CP_INCREASE_RATE.get(),MAX_OVERLOAD_INCREASE_RATE.get(),CP_RECOVER_SPEED.get(),OVERLOAD_RECOVER_SPEED.get(),PROGRESS_INCREASE_RATE.get(),data(INITIAL_CP.get()),data(INITIAL_OVERLOAD.get()),data(ADD_CP.get()),data(ADD_OVERLOAD.get()),cn.academy.port.core.SkillConsumption.Config.parseOptions(SKILL_NUMERIC_OVERRIDES.get()),java.util.Map.of("electromaster",ELECTROMASTER_PROGRESS.get(),"meltdowner",MELTDOWNER_PROGRESS.get(),"teleporter",TELEPORTER_PROGRESS.get(),"vecmanip",VECTOR_PROGRESS.get()));}
    private AcademyConfig() {}
}
