package cn.academy.port;

import cn.academy.port.core.*;
import cn.academy.port.client.*;
import cn.academy.port.develop.*;
import java.util.*;

/** Focused numeric/state tests; no native world, sockets, audio or pixels are claimed. */
public final class MagneticRegressionTest {
    private static int assertions;
    private static void check(boolean c,String m){assertions++;if(!c)throw new AssertionError(m);}
    private static void close(double a,double b,String m){check(Math.abs(a-b)<1e-6,m+": "+a+" != "+b);}
    private static MagneticRules.Vector v(double x,double y,double z){return new MagneticRules.Vector(x,y,z);}
    private static void develop(AbilityProgress s,String id,DeveloperType type){var skill=SkillCatalog.find(s.category,id).orElseThrow();var battery=new Battery(type);var process=new DevelopmentProcess();process.start(battery,DevelopmentActions.skill(s,skill));while(process.isDeveloping())process.tick();check(process.state()==DevelopmentProcess.State.DONE,"completion validates "+id);check(s.learned(id)&&s.exp(id)==0,"learning creates zero mastery "+id);close(battery.spent,type.actualConsumption(skill.level()==1?3:ClassicRules.learningStimulations(skill.level())),"finite IF paid "+id);}
    public static void main(String[]args){
        var beginner=MagneticRules.movement(0);close(beginner.cpPerTick(),15,"novice cp/tick");close(beginner.overload(),60,"novice strain");close(MagneticRules.movement(1).cpPerTick(),8,"master cp/tick");close(MagneticRules.movement(1).overload(),30,"master strain");
        var manip=MagneticRules.manipulation(0);close(manip.cp(),140,"novice manipulation cp");close(manip.overload(),35,"novice manipulation strain");check(manip.cooldown()==60,"novice cooldown");close(manip.speed(),.5,"novice speed");manip=MagneticRules.manipulation(1);close(manip.cp(),270,"master manipulation cp");close(manip.overload(),20,"master manipulation strain");check(manip.cooldown()==40,"master cooldown");close(manip.speed(),1,"master speed");
        for(int i=0;i<=10000;i++){float e=i/10000f;close(MagneticRules.movement(e).cpPerTick(),15+e*(8-15),"Float movement interpolation");close(MagneticRules.manipulation(e).cp(),140+e*(270-140),"Float manipulation interpolation");check(MagneticRules.manipulation(e).cooldown()==(int)(60+e*(40-60)),"Float cooldown truncation");}
        close(MagneticRules.adjust(0,1),.08,"positive acceleration");close(MagneticRules.adjust(0,-1),-.08,"negative acceleration");close(MagneticRules.adjust(0,.07),.07,"subaccel exact target");close(MagneticRules.adjust(0,.08),.08,"exact threshold");
        var n=MagneticRules.movementVelocity(v(0,0,0),v(0,0,0),v(10,0,0));close(n.x(),.08,"first attraction axis");close(n.y(),0,"first attraction Y");
        n=MagneticRules.movementVelocity(v(0,0,0),v(2,0,0),v(10,0,0));close(n.x(),1.92,"external impulse correction");n=MagneticRules.movementVelocity(v(1,0,0),v(0,1,0),v(10,0,0));close(n.x(),1,"source equal squared-speed does not reset direction");
        for(int i=0;i<100;i++)n=MagneticRules.movementVelocity(n,n,v(10,0,0));close(n.x(),1,"eventual source speed");
        n=MagneticRules.hoverVelocity(v(2,0,0));close(n.x(),.2,"hover threshold4");n=MagneticRules.hoverVelocity(v(1,0,0));close(n.x(),.05,"squared-distance hover easing");n=MagneticRules.hoverVelocity(v(0,0,0));check(n.lengthSquared()==0,"finite zero hover guard");
        n=MagneticRules.nextBlockPosition(v(10,20,30),v(.5,.5,.5),v(1,2,3));close(n.x(),11.5,"Rigidbody plus subclass X");close(n.y(),22.5,"Rigidbody plus subclass Y");close(n.z(),33.5,"Rigidbody plus subclass Z");
        check(MagneticRules.acceptsRelease(24.9999)&&!MagneticRules.acceptsRelease(25)&&!MagneticRules.acceptsRelease(Double.NaN),"strict5-block release");close(MagneticRules.movementExperience(0),.005f,"source invalid/zero travel EXP floor");close(MagneticRules.movementExperience(20),.0011f*20,"source float distance gain");close(MagneticRules.BLOCK_COLLISION_DAMAGE,10,"source fixed damage differs unused lerpf damage");
        for(double exp:new double[]{0,.59,.6,1}){check(MagneticRules.acceptsMovementBlock(exp,false,true),"weak metal accepted at all source mastery");check(MagneticRules.acceptsMovementBlock(exp,true,false),"normal accepted");check(!MagneticRules.acceptsMovementBlock(exp,false,false),"nonmetal rejected");}
        check(!ClassicMagneticTimeline.beamShown(true,.099)&&ClassicMagneticTimeline.beamShown(true,.1),"movement show wiggle strict");check(ClassicMagneticTimeline.beamShown(false,.599)&&!ClassicMagneticTimeline.beamShown(false,.6),"movement hide wiggle strict");check(!ClassicMagneticTimeline.matchingUpdate(2,1,2,1)&&!ClassicMagneticTimeline.matchingUpdate(1,1,1,1)&&ClassicMagneticTimeline.matchingUpdate(1,1,2,1),"stale/wrong effect updates rejected");
        close(ClassicMagneticTimeline.viewOffset(true).x(),-.05,"source first-person hand offsetX");close(ClassicMagneticTimeline.viewOffset(true).y(),-.25,"source first-person hand offsetY");close(ClassicMagneticTimeline.viewOffset(false).x(),.15,"source third-person hand offsetX");close(ClassicMagneticTimeline.viewOffset(false).y(),-.8,"source third-person hand offsetY");var tokens=new ClassicChargingTimeline.Tokens();check(tokens.acceptStart(3,1)&&!tokens.acceptStart(3,1),"start tokens deduplicated");tokens.rememberEnd(3,2);check(!tokens.acceptStart(3,2)&&tokens.acceptStart(3,3),"terminal tombstones prevent delayed reopen");
        var s=new AbilityProgress();var initial=new DevelopmentProcess();var battery=new Battery(DeveloperType.PORTABLE);initial.start(battery,DevelopmentActions.level(s,new DevelopmentActions.CategoryItems(){public Optional<String> differentFactor(String cat){return Optional.of("electromaster");}public boolean hasHeldMagneticCoil(){return false;}public void consumeFactor(String cat){}public void consumeHeldMagneticCoil(){}},bound->0));while(initial.isDeveloping())initial.tick();check(s.category.equals("electromaster")&&s.level==1&&s.experience.isEmpty(),"normal acquisition starts blank category at1");
        develop(s,"arc_gen",DeveloperType.PORTABLE);check(!SkillCatalog.canLearn(s,SkillCatalog.find(s.category,"charging").orElseThrow()),"charging blocked underArc.3");s.addExperience("arc_gen",.3);develop(s,"charging",DeveloperType.PORTABLE);
        var movement=SkillCatalog.find(s.category,"mag_movement").orElseThrow();check(!SkillCatalog.canLearn(s,movement),"movement needslevel2 andcharging.7");
        // Numeric progression uses source experience increments, not test operator/mastery grants.
        for(int i=0;i<10400;i++)s.addExperience("charging",.0001f);check(s.canLevelUp(SkillCatalog.levelSkillCount(s)),"actual skill increments can completelevel1 threshold");
        level(s);check(!SkillCatalog.canLearn(s,movement)||s.exp("charging")>=.7,"charging dependency preserved");develop(s,"mag_movement",DeveloperType.PORTABLE);
        var manipulation=SkillCatalog.find(s.category,"mag_manip").orElseThrow();check(!SkillCatalog.canLearn(s,manipulation),"manip locked belowmovement.5");for(int i=0;i<101;i++)s.addExperience("mag_movement",MagneticRules.movementExperience(0));develop(s,"mag_manip",DeveloperType.PORTABLE);
        for(int i=0;i<201;i++)s.addExperience("mag_manip",.005f);check(s.exp("mag_manip")==1,"200 successful releases reach source master dependency");
        while(!s.canLevelUp(SkillCatalog.levelSkillCount(s)))s.addExperience("arc_gen",.0048f);level(s);check(s.level==3,"normal level2 accumulation upgrades3");
        while(!s.canLevelUp(SkillCatalog.levelSkillCount(s)))s.addExperience("mag_manip",.005f);level(s);check(s.level==4,"lower-tier source usage trainslevel3 without granting unimplemented skills");
        var thunder=SkillCatalog.find(s.category,"thunder_bolt").orElseThrow();check(!DevelopmentActions.canLearn(s,DeveloperType.PORTABLE,thunder)&&!DevelopmentActions.canLearn(s,DeveloperType.NORMAL,thunder),"ThunderBolt requires advanced real developer");develop(s,"thunder_bolt",DeveloperType.ADVANCED);var rail=SkillCatalog.find(s.category,"railgun").orElseThrow();check(!SkillCatalog.canLearn(s,rail),"learned novice ThunderBolt does not grantRailgun");for(int i=0;i<61;i++)s.addExperience("thunder_bolt",.005f);check(SkillCatalog.canLearn(s,rail),"trainedThunderBolt.3 + realMagManip1 satisfy Railgun");develop(s,"railgun",DeveloperType.ADVANCED);
        for(int page=0;page<4;page++)for(int slot=0;slot<4;slot++)check(s.presets.skill(page,slot).isEmpty(),"development never silently auto-binds");
        System.out.println("PASS "+assertions+" magnetic numeric, lifecycle timeline and genuine development-state assertions; no Minecraft launch");
    }
    private static void level(AbilityProgress s){var p=new DevelopmentProcess();p.start(new Battery(s.level<=1?DeveloperType.PORTABLE:DeveloperType.NORMAL),DevelopmentActions.level(s,DevelopmentActions.CategoryItems.NONE,bound->0));while(p.isDeveloping())p.tick();check(p.state()==DevelopmentProcess.State.DONE,"validated level process");}
    private static final class Battery implements DevelopmentProcess.Developer {final DeveloperType type;double remaining,spent;Battery(DeveloperType type){this.type=type;remaining=type.energy;}public DeveloperType type(){return type;}public boolean tryPullEnergy(double amount){if(remaining<amount)return false;remaining-=amount;spent+=amount;return true;}public double energy(){return remaining;}public double maxEnergy(){return type.energy;}}
}
