package cn.academy.port.bridge;

import cn.academy.port.machine.ImagFluxReceiver;
import cn.academy.port.solar.ImagFluxGenerator;
import cn.academy.port.wireless.*;
import java.net.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import net.neoforged.neoforge.energy.IEnergyStorage;

/** Finite production-buffer/real unchanged graph checks; not native game execution or natural-power evidence. */
public final class ClassicEnergyBridgeConservationTest {
    private static int checks;
    private static void check(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}
    private static void equal(double expected,double actual,String why){check(Double.isFinite(actual)&&Math.abs(expected-actual)<1e-8,why+": "+actual);}
    static class Foreign implements IEnergyStorage {
        int energy,capacity=2000000,limit=Integer.MAX_VALUE,receives,extracts;boolean alive=true;
        public int receiveEnergy(int request,boolean simulate){receives++;int moved=alive?Math.min(request,Math.min(limit,capacity-energy)):0;if(!simulate)energy+=moved;return moved;}
        public int extractEnergy(int request,boolean simulate){extracts++;int moved=alive?Math.min(request,Math.min(limit,energy)):0;if(!simulate)energy-=moved;return moved;}
        public int getEnergyStored(){return alive?energy:0;}public int getMaxEnergyStored(){return capacity;}public boolean canReceive(){return alive;}public boolean canExtract(){return alive;}
    }
    public static void main(String[] args)throws Exception{finiteTransfer();foreignManagers();ingredient();graph();commonLink();System.out.println("ClassicEnergyBridgeConservationTest: "+checks+" finite conservation/simulation/foreign callback/real graph/client-denied link checks passed");}
    private static void finiteTransfer(){
        var b=new ClassicEnergyBridgeBuffer();for(double invalid:new double[]{Double.NaN,Double.POSITIVE_INFINITY,-1}){b.load(invalid);equal(0,b.energy(),"malformed IF load bounded");}b.load(9000);equal(2000,b.energy(),"finite capacity clamped");b.load(.125);equal(0,b.extract(4,false),"sub-FE remainder retained");equal(.125,b.energy(),"no subquantum IF loss");equal(0,b.receive(-1,false),"negative FE input rejects");equal(0,b.extract(-1,false),"negative FE output rejects");equal(0,b.pull(Double.NaN),"malformed graph pull rejects");equal(-1,b.add(-1),"negative graph injection unaccepted");
        b.load(0);equal(8000,b.receive(Integer.MAX_VALUE,true),"source capacity and whole IF simulation");equal(0,b.energy(),"receive simulation no mutation");equal(8000,b.receive(Integer.MAX_VALUE,false),"finite source input permits full buffer in one FE call");equal(8000,b.extract(Integer.MAX_VALUE,true),"FE source output has no invented100IF bandwidth");equal(2000,b.energy(),"extract simulation no mutation");
        var foreign=new Foreign();foreign.limit=37;equal(37,b.push(foreign),"one actual foreign call accepted37 FE");equal(1990.75,b.energy(),"only reported actual9.25IF removed");equal(1,foreign.receives,"no repeated call to bypass foreign bandwidth");
        b.load(100);var reentrant=new Foreign(){@Override public int receiveEnergy(int request,boolean simulate){equal(0,b.extract(8000,false),"reentrant FE spend fenced");equal(0,b.pull(2000),"reentrant IF spend fenced");equal(5,b.add(5),"reentrant IF credit unaccepted");return super.receiveEnergy(request,simulate);}};equal(400,b.push(reentrant),"reserved source IF exported once");equal(0,b.energy(),"reserved transfer debits exactlyonce");
        b.load(100);Foreign liar=new Foreign(){@Override public int receiveEnergy(int request,boolean simulate){return Integer.MAX_VALUE;}};equal(400,b.push(liar),"over-report bounded to reserved request");equal(0,b.energy(),"malformed callback cannot make buffer negative");b.load(100);liar=new Foreign(){@Override public int receiveEnergy(int request,boolean simulate){return -1;}};equal(0,b.push(liar),"negative report rejected");equal(100,b.energy(),"rejected report does not mint local IF");
        var random=new Random(107);b.load(0);double supplied=0,removed=0;for(int step=0;step<100000;step++){
            boolean simulate=random.nextBoolean();int amount=random.nextInt(16001);double before=b.energy();if(random.nextBoolean()){int accepted=b.receive(amount,simulate);check(accepted>=0&&accepted<=amount,"bounded receive");if(!simulate)supplied+=accepted/4d;else equal(before,b.energy(),"random receive simulation");}else{int taken=b.extract(amount,simulate);check(taken>=0&&taken<=amount,"bounded extract");if(!simulate)removed+=taken/4d;else equal(before,b.energy(),"random extract simulation");}equal(supplied-removed,b.energy(),"independent integer FE cumulative conservation");check(b.energy()>=0&&b.energy()<=2000,"random finite buffer");}
    }
    private static void foreignManagers(){var endpoint=new Foreign();endpoint.energy=40;equal(0,ClassicForeignEnergyManager.charge(endpoint,10),"real modern4FE-per-IF receive");equal(80,endpoint.energy,"10IF corresponds to40actual FE");equal(1,endpoint.receives,"generic foreign handler calledonce");equal(1,ClassicForeignEnergyManager.pull(endpoint,1),"provider returns1IF for4FE");equal(76,endpoint.energy,"actual provider debit4FE");endpoint.limit=3;equal(.5,ClassicForeignEnergyManager.charge(endpoint,1.25),"foreign partial acceptance remainder");endpoint.alive=false;equal(5,ClassicForeignEnergyManager.charge(endpoint,5),"dead foreign endpoint unaccepted");equal(0,ClassicForeignEnergyManager.pull(endpoint,5),"dead foreign endpoint no power");}
    private static void ingredient(){for(int e=0;e<=10000;e++){int oldGauge=(int)Math.round((1-e/10000d)*13);boolean expected=e==0||oldGauge==0;check(expected==ClassicBridgeEnergyUnitIngredient.acceptsEnergy(e),"independent original metadata0 gauge and genuine empty predicate");}for(double e:new double[]{Double.NaN,Double.POSITIVE_INFINITY,-1,10000.1})check(!ClassicBridgeEnergyUnitIngredient.acceptsEnergy(e),"malformed/out-of-capacity ingredient rejected");check(!ClassicBridgeEnergyUnitIngredient.acceptsEnergy(5000)&&ClassicBridgeEnergyUnitIngredient.acceptsEnergy(0)&&ClassicBridgeEnergyUnitIngredient.acceptsEnergy(10000),"middle charge denied, genuine empty and legacy gauge0 allowed");}
    private static void graph(){
        var input=new ClassicEnergyBridgeBuffer();var output=new ClassicEnergyBridgeBuffer();input.receive(8000,false);var alive=new AtomicBoolean(true);var loaded=new AtomicBoolean(true);var nodePos=new ClassicWirelessGraph.Pos(1,64,1);var inPos=new ClassicWirelessGraph.Pos(2,64,1);var outPos=new ClassicWirelessGraph.Pos(3,64,1);
        ImagFluxNode node=new ImagFluxNode(){double e;public double getEnergy(){return e;}public void setEnergy(double a){e=a;}public double getMaxEnergy(){return 1000;}public double getBandwidth(){return 200;}public int getCapacity(){return 5;}public double getRange(){return 9;}public String getNodeName(){return "finite bridge fixture";}public String getPassword(){return "source-secret";}};
        ImagFluxGenerator generator=new ImagFluxGenerator(){public double getEnergy(){return alive.get()?input.energy():0;}public double getBandwidth(){return 100;}public double getProvidedEnergy(double req){return alive.get()?input.pull(req):0;}};
        ImagFluxReceiver receiver=new ImagFluxReceiver(){public double getEnergy(){return output.energy();}public double getMaxEnergy(){return 2000;}public double getRequiredEnergy(){return 2000-output.energy();}public double getBandwidth(){return 100;}public double injectEnergy(double amount){return output.add(amount);}public double pullEnergy(double amount){return output.pull(amount);}};
        var graph=new ClassicWirelessGraph(new ClassicWirelessGraph.Resolver(){public boolean isLoaded(ClassicWirelessGraph.Pos p){return loaded.get()||p.equals(nodePos);}public ImagFluxNode node(ClassicWirelessGraph.Pos p){return p.equals(nodePos)?node:null;}public ImagFluxMatrix matrix(ClassicWirelessGraph.Pos p){return null;}public ImagFluxGenerator generator(ClassicWirelessGraph.Pos p){return p.equals(inPos)&&alive.get()?generator:null;}public ImagFluxReceiver receiver(ClassicWirelessGraph.Pos p){return p.equals(outPos)?receiver:null;}public List<ClassicWirelessGraph.Pos> wirelessBlocksWithin(ClassicWirelessGraph.Pos p,double range,int max){return List.of(nodePos);}},new Random(107),()->{});
        check(!graph.linkGenerator(nodePos,inPos,"wrong",true),"real graph password rejects");check(graph.linkGenerator(nodePos,inPos,"source-secret",true)&&graph.linkReceiver(nodePos,outPos,"source-secret",true),"correct real graph generator/receiver source roles");check(graph.nodeForReceiver(inPos)==null&&graph.nodeForGenerator(outPos)==null,"no duplicate role");graph.tick();equal(1900,input.energy(),"source input graph100IF debit");equal(2000,input.energy()+node.getEnergy()+output.energy(),"actual graph no invented power");graph.tick();equal(1800,input.energy(),"second source100IF supply");equal(200,output.energy(),"source generator-before-receiver delivers100IF on each tick");equal(2000,input.energy()+node.getEnergy()+output.energy(),"separate source generator/receiver budgets conserve IF");
        loaded.set(false);double before=input.energy();graph.tick();equal(before,input.energy(),"unloaded bridge not queried/transferred");check(graph.nodeForGenerator(inPos)!=null,"source suspended link retained across unload");loaded.set(true);alive.set(false);graph.tick();check(graph.nodeForGenerator(inPos)==null,"removed endpoint pruned by real graph");equal(before,input.energy(),"stale source cannot spend finite old buffer");
    }
    private static void commonLink()throws Exception{List<URL> urls=new ArrayList<>();for(String path:System.getProperty("java.class.path").split(java.io.File.pathSeparator))urls.add(Path.of(path).toUri().toURL());try(var loader=new URLClassLoader(urls.toArray(URL[]::new),ClassLoader.getPlatformClassLoader()){@Override protected Class<?> loadClass(String name,boolean resolve)throws ClassNotFoundException{if(name.startsWith("net.minecraft.client.")||name.startsWith("cn.academy.port.client.")||(name.startsWith("net.neoforged.neoforge.client.")&&!name.equals("net.neoforged.neoforge.client.extensions.IMenuProviderExtension")))throw new ClassNotFoundException("client-denied: "+name);return super.loadClass(name,resolve);}}){for(String name:List.of("ClassicEnergyBridgeBuffer","ClassicEnergyBridgeBlock","ClassicEnergyBridgeBlockEntity","ClassicRFInputBlockEntity","ClassicRFOutputBlockEntity","ClassicEnergyBridgeItem","ClassicEnergyBridges","ClassicForeignEnergyManager","ClassicBridgeEnergyUnitIngredient")){var type=Class.forName("cn.academy.port.bridge."+name,false,loader);type.getDeclaredMethods();type.getDeclaredConstructors();check(true,"common class linked with client denied: "+name);}}}
}
