package cn.academy.port.bridge;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import javax.imageio.ImageIO;
import javax.xml.parsers.DocumentBuilderFactory;
/** Real resources, packaged primary pixels and source standalone-page topology; no visual acceptance claim. */
public final class ClassicEnergyBridgeDataTest {
    private static int checks;
    private static void check(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}
    private static JsonObject json(Path root,String path)throws Exception{return JsonParser.parseString(Files.readString(root.resolve(path))).getAsJsonObject();}
    private static String source(Path root,String path)throws Exception{return Files.readString(root.resolve(path));}
    public static void main(String[] args)throws Exception{
        Path root=Path.of(System.getProperty("academy.energybridges.stage",".")),fixture=root.resolve("src/test/resources/classic-energy-bridges-source");
        for(String name:List.of("rf_input","rf_output")){
            var recipe=json(root,"src/main/resources/data/academy/recipe/classic/"+name+".json");check(recipe.get("type").getAsString().equals("minecraft:crafting_shaped")&&recipe.getAsJsonArray("pattern").toString().equals("[\"abc\",\" d \"]"),"unchanged exact primary two-row shape");
            for(String[] key:new String[][]{{"b","machine_frame"},{"c",name.equals("rf_input")?"constraint_plate":"reso_crystal"},{"d","energy_convert_component"}})check(recipe.getAsJsonObject("key").getAsJsonObject(key[0]).get("item").getAsString().equals("academy:"+key[1]),"exact source primary ingredient "+name+'/'+key[0]);
            check(recipe.getAsJsonObject("key").getAsJsonObject("a").get("type").getAsString().equals("academy:bridge_energy_unit"),"narrow native empty-or-source-gauge0 energy-unit predicate");
            check(recipe.getAsJsonObject("result").get("id").getAsString().equals("academy:"+name)&&recipe.getAsJsonObject("result").get("count").getAsInt()==1,"source primary one-block yield");
            var conversion=json(root,"src/main/resources/data/academy/recipe/classic/"+name+"_conversion.json");check(conversion.getAsJsonArray("pattern").toString().equals("[\"X\"]")&&conversion.getAsJsonObject("key").getAsJsonObject("X").get("item").getAsString().equals("academy:"+(name.equals("rf_input")?"rf_output":"rf_input")),"both one-item source conversion recipes");
            var model=json(root,"src/main/resources/assets/academy/models/block/"+name+".json");check(model.get("parent").getAsString().equals("minecraft:block/cube_all")&&model.getAsJsonObject("textures").get("all").getAsString().equals("academy:blocks/"+name),"original uniform-texture full cube");check(json(root,"src/main/resources/assets/academy/models/item/"+name+".json").get("parent").getAsString().equals("academy:block/"+name),"source ordinary ItemBlock inventory rendering");
            Path image=root.resolve("src/main/resources/assets/academy/textures/blocks/"+name+".png"),primary=fixture.resolve("assets/assets/academy/textures/blocks/"+name+".png");check(Arrays.equals(Files.readAllBytes(image),Files.readAllBytes(primary)),"runtime PNG unchanged from primary packaged source");var pixels=ImageIO.read(image.toFile());check(pixels!=null&&pixels.getWidth()>0&&pixels.getHeight()>0,"original runtime texture decodes");
            var pickaxe=json(root,"src/main/resources/data/minecraft/tags/block/mineable/pickaxe.json").getAsJsonArray("values");check(pickaxe.asList().stream().anyMatch(e->e.getAsString().equals("academy:"+name)),"source pickaxe0 mining path");for(String tag:List.of("needs_stone_tool","needs_iron_tool","needs_diamond_tool")){Path path=root.resolve("src/main/resources/data/minecraft/tags/block/"+tag+".json");if(Files.exists(path))check(json(root,"src/main/resources/data/minecraft/tags/block/"+tag+".json").getAsJsonArray("values").asList().stream().noneMatch(e->e.getAsString().equals("academy:"+name)),"no invented higher-tier mining requirement");}
            for(String locale:List.of("en_us","zh_cn","zh_tw","ja_jp")){var language=json(root,"src/main/resources/assets/academy/lang/"+locale+".json");check(language.get("block.academy."+name).getAsString().equals(language.get("tile.ac_"+name+".name").getAsString()),"source locale name retained "+locale);}
            var pool=json(root,"src/main/resources/data/academy/loot_table/blocks/"+name+".json").getAsJsonArray("pools").get(0).getAsJsonObject();check(pool.get("rolls").getAsInt()==1&&pool.getAsJsonArray("entries").get(0).getAsJsonObject().get("name").getAsString().equals("academy:"+name),"one source block drop, no stored-power loot duplication");
        }
        String registration=source(root,"src/main/java/cn/academy/port/bridge/ClassicEnergyBridges.java");check(registration.contains("ClassicSolarGenerators.IMAG_FLUX,INPUT_TILE")&&registration.contains("MachineDevelopers.IMAG_FLUX,OUTPUT_TILE")&&registration.contains("Capabilities.EnergyStorage.BLOCK,INPUT_TILE")&&registration.contains("Capabilities.EnergyStorage.BLOCK,OUTPUT_TILE"),"actual direction-specific IF/real FE capability registrations");check(!registration.contains("ItemHandler")&&!registration.contains("ModList")&&!registration.contains("energyUnit"),"no invented slots or external RF-mod condition");
        String menu=source(root,"src/main/java/cn/academy/port/wireless/ClassicWirelessMenu.java"),screen=source(root,"src/main/java/cn/academy/port/client/ClassicEnergyBridgeScreen.java"),protocol=source(root,"src/main/java/cn/academy/port/wireless/ClassicWirelessProtocol.java");check(menu.contains("if(!standalone)")&&menu.contains("player.level().getBlockEntity(sourcePos)==standaloneSource"),"zero-inventory source page and replaced-tile menu fence");check(screen.contains("sourceFont.release()")&&screen.contains("public void removed()")&&screen.contains("field.setValue(\"\")"),"actual close releases font textures and clears typed source passwords");check(screen.contains("imageWidth=176;imageHeight=187")&&screen.contains("isPauseScreen(){return false;}")&&!screen.contains("drawInfo")&&!screen.contains("icon_inv")&&!screen.contains("wireless.return"),"only original source wireless page, no invented tabs/inventory/histogram");check(protocol.contains("bridge.getMaxEnergy()")&&protocol.contains("player.closeContainer();return true;")&&protocol.contains("menu.token().equals(request.token)"),"existing real source roles, close-return and server nonce validation");check(source(root,"src/main/java/cn/academy/port/client/ClassicWirelessClient.java").contains("menu.standalone()?new ClassicEnergyBridgeScreen"),"actual client menu factory reaches source standalone UI");check(source(root,"src/main/java/cn/academy/port/AcademyCraft.java").contains("cn.academy.port.bridge.ClassicEnergyBridges.register(bus);"),"actual common registration reached");check(source(root,"src/main/java/cn/academy/port/tutorial/ClassicTutorials.java").contains("page(\"energy_bridge\",List.of(\"rf_input\",\"rf_output\")"),"existing guide source bindings can now unlock real blocks/recipes");
        var parser=DocumentBuilderFactory.newInstance();parser.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);var document=parser.newDocumentBuilder().parse(fixture.resolve("witness/src/main/resources/assets/academy/guis/rework/page_wireless.xml").toFile());var main=document.getDocumentElement().getFirstChild();check(main.getAttributes().getNamedItem("name").getNodeValue().equals("main"),"unchanged original standalone window root");var component=main.getFirstChild();check(component.getAttributes().getNamedItem("class").getNodeValue().endsWith("Transform"),"original standalone transform");check(document.getElementsByTagName("width").item(0).getTextContent().equals("176.0")&&document.getElementsByTagName("height").item(0).getTextContent().equals("187.0"),"independent original176x187 geometry witness");
        check(cn.academy.port.client.ClassicEnergyBridgeLayout.PANEL_X==5.5&&cn.academy.port.client.ClassicEnergyBridgeLayout.PANEL_Y==44.62109375&&cn.academy.port.client.ClassicEnergyBridgeLayout.CONNECTED_Y==34.62109375&&cn.academy.port.client.ClassicEnergyBridgeLayout.ARROW_X==154.5&&cn.academy.port.client.ClassicEnergyBridgeLayout.DOWN_Y==161.20703125,"source fractional centered panel/linked row/arrow positions retained");for(int count=0;count<100;count++)check(cn.academy.port.client.ClassicEnergyBridgeLayout.maxProgress(count)==Math.max(0,count-7),"source115px list retains exactly7fully visible16px rows");
        System.out.println("ClassicEnergyBridgeDataTest: "+checks+" native resource/recipe/pixel/source topology/common binding checks passed; actual client visuals pending");
    }
}
