package cn.academy.port.skill;
import cn.academy.port.*;
import cn.academy.port.core.*;
import cn.academy.port.develop.*;
import cn.academy.port.preset.PresetSkills;
import java.util.*;
public final class MeltdownerLateCombatLearningRegressionTest {
 private static int checks;private static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}
 public static void main(String[] args){check(SkillCatalog.ALL.size()==50,"classic50metadata unchanged");for(String id:List.of("arc_gen","charging","railgun","electron_bomb","threatening_teleport","dir_shock","ground_shock","mag_movement","mag_manip","thunder_bolt","mine_detect","body_intensify","thunder_clap","scatter_bomb","light_shield","meltdowner","mine_ray_basic"))check(PresetSkills.IMPLEMENTED.contains(id)&&SkillAvailability.learnable(id),"each previous17route preserved");
  for(String id:List.of("ray_barrage","jet_engine","electron_missile")){int level=id.equals("electron_missile")?5:4;String parent=id.equals("electron_missile")?"jet_engine":"meltdowner";double threshold=id.equals("ray_barrage")?.5:id.equals("jet_engine")?1:.3;var skill=SkillCatalog.find("meltdowner",id).orElseThrow();check(skill.level()==level&&skill.controllable()&&skill.requirements().equals(List.of(new SkillCatalog.Requirement(parent,threshold))),"canonical level/parent threshold");check(PresetSkills.IMPLEMENTED.contains(id)&&SkillAvailability.learnable(id),"singlecommon implementation/learning registry");var s=ready(level);check(!SkillCatalog.canLearn(s,skill),"unearnedparent denied");s.learn(parent);s.experience.put(parent,Math.nextDown(threshold));check(SkillCatalog.canLearn(s,skill),"double-only predecessor rounds to exact source float and accepts");s.experience.put(parent,(double)Math.nextDown((float)threshold));check(!SkillCatalog.canLearn(s,skill),"onebit belowparent denied");s.experience.put(parent,threshold);check(SkillCatalog.canLearn(s,skill),"exactparent eligible");for(var tier:List.of(DeveloperType.PORTABLE,DeveloperType.NORMAL))check(!DevelopmentActions.canLearn(s,tier,skill),"level4/5 requireAdvanced");check(DevelopmentActions.canLearn(s,DeveloperType.ADVANCED,skill),"Advanced supported");var battery=new Battery(200000);var process=new DevelopmentProcess();var action=DevelopmentActions.skill(s,skill);int stim=level==4?11:15,ticks=stim*16,spent=level==4?7040:9600;check(action.stimulations()==stim,"source11/15stimulation");process.start(battery,action);for(int tick=1;tick<=ticks;tick++){process.tick();if(tick<ticks)check(!s.learned(id),"finite16tickstim noearlylearn");}check(s.learned(id)&&s.exp(id)==0&&process.state()==DevelopmentProcess.State.DONE,"genuinezeroEXPAdvancedlearn");check(battery.energy()==200000-spent,"real finite AdvancedIFdrain");check(s.presets.currentSkill(0).isEmpty(),"noautomaticbinding");s.activated=true;var bound=s;check(s.presets.edit(0,0,id,value->PresetSkills.selectable(bound,value)),"naturallyearned mapping");s=ready(level);s.experience.put(parent,threshold);battery=new Battery(39);process=new DevelopmentProcess();process.start(battery,DevelopmentActions.skill(s,skill));process.tick();check(process.state()==DevelopmentProcess.State.FAILED&&!s.learned(id)&&battery.energy()==39,"insufficient40IF atomic failure");s=ready(level);s.experience.put(parent,threshold);battery=new Battery(200000);process=new DevelopmentProcess();process.start(battery,DevelopmentActions.skill(s,skill));for(int t=1;t<ticks;t++)process.tick();s.experience.remove(parent);process.tick();check(process.state()==DevelopmentProcess.State.FAILED&&!s.learned(id),"completion rechecks requiredparent");}
  System.out.println("PASS "+checks+" canonicallate dependencies, registry and finiteAdvancedlearning checks");}
 private static AbilityProgress ready(int level){var s=new AbilityProgress();s.selectCategory("meltdowner");s.setLevel(level);return s;}
 private static final class Battery implements DevelopmentProcess.Developer{private final cn.academy.port.machine.MachineDeveloperEnergy energy=new cn.academy.port.machine.MachineDeveloperEnergy(DeveloperType.ADVANCED,()->{},()->true);Battery(double n){energy.load(n);}public DeveloperType type(){return DeveloperType.ADVANCED;}public boolean tryPullEnergy(double n){return energy.tryPull(n);}public double energy(){return energy.energy();}public double maxEnergy(){return 200000;}}
}
