package cn.academy.port.skill;
import static cn.academy.port.core.ClassicFloatLedgerExpectations.*;
import cn.academy.port.core.*;
/** Pure captured state tests. Expected constants are written independently from the port's getters. */
public final class MeltdownerLateCombatRegressionTest {
 private static int checks;private static void check(boolean ok,String why){checks++;if(!ok)throw new AssertionError(why);}private static void near(double a,double b,String why){check(Math.abs(a-b)<1E-6,why+" actual="+a+" expected="+b);}private static AbilityProgress state(String id,int level,double exp){var s=new AbilityProgress();s.selectCategory("meltdowner");s.setLevel(level);s.learn(id);s.experience.put(id,exp);s.activated=true;return s;}
 public static void main(String[] args){
  for(double e:new double[]{0,.125,.5,.9,1}){var s=state(RayBarrageRules.ID,4,e);var p=RayBarrageRules.plan(e);float f=(float)e;near(p.cp(),450+f*(380-450),"barrage Float CP");near(p.overload(),300+f*(140-300),"barrage Float overload");near(p.plainDamage(),25+f*(60-25),"barrage plain Floatdamage");near(p.scatteredDamage(),10+f*(18-10),"barrage scattered damage");double before=s.cp;check(RayBarrageRules.debit(s,p,false),"barrage finite debit");near(s.cp,paidCpAfter(before,p.cp(),1),"barrage paidCP");RayBarrageRules.complete(s,p);check(s.cooldowns.get(p==null?"":RayBarrageRules.ID)==(int)(100+f*(40-100)),"barrage source cooldown");near(s.levelExperience,.005F,"barrage EXP");
   s=state(JetEngineSession.ID,4,e);var jet=JetEngineSession.begin(s);check(jet!=null,"jet begin");near(jet.affordability(),170+f*(140-170),"jet named affordability");double cp=s.cp;check(jet.release(false),"jet release");near(s.cp,paidCpAfter(cp,60+f*(50-60),1),"source reversed releaseCP");near(s.overload,170+f*(140-170),"source reversedrelease strain");check(!jet.release(false),"duplicate release never debit");near(s.levelExperience,.004F,"jet sourceEXP");s.experience.put(JetEngineSession.ID,1.0);near(jet.damage(),7+f*(20-7),"jet captureddamage");check(s.cooldowns.get(JetEngineSession.ID)==(int)(60+f*(30-60)),"jet cooldown captured");for(int tick=1;tick<=16;tick++){near(jet.step(),tick/8F,"source trajectory fraction");check(jet.active()==(tick<16),"source terminal tick16");}check(Float.isNaN(jet.step()),"ended jet no more steps");
   s=state(ElectronMissileSession.ID,5,e);var missile=ElectronMissileSession.begin(s,false);near(s.overload,200,"missile overloadfloor debit");int limit=(int)(80+f*(200-80));check(missile.limit()==limit,"missile inclusive lifetime");cp=s.cp;int spawn=0;for(int tick=0;tick<=limit+1;tick++){s.overload=0;var t=missile.tick(false);check(t.index()==tick,"missile tickindex startszero");check(t.body()==(tick<=limit),"missile inclusivebody");check(t.update(),"successful CP tick always update incl timeout");check(t.seek()==(tick<=limit&&tick!=0&&tick%8==0),"tick8 firstattack");if(t.spawn())spawn++;check(t.spawn()==(tick<=40&&tick%10==0),"up to five balls at0,10,20,30,40");near(s.overload,200,"missile keeps floor everytick");}check(spawn==5&&missile.balls()==5,"finite five-ball cap");near(s.cp,paidCpAfter(cp,12+f*(5-12),limit+2),"timeout final paid CPtick");check(missile.complete(),"missile complete once");check(!missile.complete(),"cooldown/cleanup idempotent");check(s.cooldowns.get(ElectronMissileSession.ID)==700,"literal invertedclampi always700");near(s.levelExperience,0,"holdingno EXP");}
  var s=state(RayBarrageRules.ID,4,0);s.cp=0;var plan=RayBarrageRules.plan(0);check(!RayBarrageRules.debit(s,plan,false),"failed barragecost");RayBarrageRules.complete(s,plan);near(s.cp,0,"failedconsume doesnotinvent debit");check(s.cooldowns.get(RayBarrageRules.ID)==100&&s.levelExperience==.005F,"deferredterminate quirk stillcommits sourceexecute");
  s=state(JetEngineSession.ID,4,0);var jet=JetEngineSession.begin(s);s.cp=169.99;check(!jet.affordable(false),"jet marking requires170");s.cp=60;check(jet.release(false),"source release can pay60 even when170 tickgatefails");check(!jet.affordable(false),"postrelease affordability terminatesnexttick");s=state(JetEngineSession.ID,4,0);jet=JetEngineSession.begin(s);s.cp=59;check(!jet.release(false)&&!jet.active(),"failedrelease endsno flight");check(s.cooldowns.isEmpty()&&s.exp(JetEngineSession.ID)==0&&s.overload==0,"failedrelease noinvented EXP orcost");s=state(JetEngineSession.ID,4,0);jet=JetEngineSession.begin(s);jet.discard();check(s.cooldowns.isEmpty()&&s.exp(JetEngineSession.ID)==0,"keyabort marking free");
  s=state(ElectronMissileSession.ID,5,0);var m=ElectronMissileSession.begin(s,false);var t=m.tick(false);check(t.spawn()&&!t.seek(),"tick0ball and noattack");s.cp=59;check(!m.debitAttack(false)&&m.balls()==1,"failedattack keepsorb");s.cp=60;check(m.debitAttack(false)&&m.balls()==0,"successfulattack consumesexactly oneorb");m.completeAttack();near(s.levelExperience,.001F,"canceledworldattack stillsourceEXP");near(s.overload,209,"perattackoverload9");check(!m.debitAttack(false),"noorb no debit");m.complete();check(s.cooldowns.get(ElectronMissileSession.ID)==700,"release700");
  s=state(ElectronMissileSession.ID,5,0);m=ElectronMissileSession.begin(s,false);s.cp=11;check(!m.tick(false).body()&&m.ending()&&m.balls()==0,"failedtick CP before spawn");m.discard();check(s.cooldowns.isEmpty(),"lifecycle discard no cooldown");
  for(String id:new String[]{RayBarrageRules.ID,JetEngineSession.ID,ElectronMissileSession.ID}){s=state(id,id.equals(ElectronMissileSession.ID)?5:4,0);s.activated=false;check(!may(s,id),"inactive blocked");s.activated=true;s.interfering=true;check(!may(s,id),"interferenceblocked");s.interfering=false;s.cooldowns.put(id,1);check(!may(s,id),"cooldownblocked");s.cooldowns.clear();s.category="electromaster";check(!may(s,id),"wrongcategoryblocked");}
  System.out.println("PASS "+checks+" late-combat captured Float/timing/cost/cancel/floor/cooldown checks");
 }
 private static boolean may(AbilityProgress s,String id){return id.equals(RayBarrageRules.ID)?RayBarrageRules.mayStart(s):id.equals(JetEngineSession.ID)?JetEngineSession.mayStart(s):ElectronMissileSession.mayStart(s);}
}
