package cn.academy.port.skill;
import static cn.academy.port.core.ClassicFloatLedgerExpectations.*;
import cn.academy.port.core.*;
import cn.academy.port.skill.lateoracle.*;
import java.util.*;
import java.nio.file.*;
import javax.tools.ToolProvider;
/** Differential against unchanged original MathUtils/Motion3D and compiled ORIGINAL Scala expression lexemes.
 * No expected scalar formula is copied from the port. All oracle input texts are hash-pinned test resources. */
public final class MeltdownerLateCombatOracleTest {
 private static int checks;private static void check(boolean ok,String why){checks++;if(!ok)throw new AssertionError(why);}private static void exact(float a,float b,String why){check(Float.floatToIntBits(a)==Float.floatToIntBits(b),why+" actual="+a+" original="+b);}
 private static String expr(String source,String pattern){var matcher=java.util.regex.Pattern.compile(pattern).matcher(source);if(!matcher.find())throw new AssertionError("Original expression missing "+pattern);return matcher.group(1).trim();}
 private static java.net.URLClassLoader oracle()throws Exception{String rb=LateCombatSourceFixtures.source("academycraft/RayBarrage.scala.txt"),je=LateCombatSourceFixtures.source("academycraft/JetEngine.scala.txt"),em=LateCombatSourceFixtures.source("academycraft/ElectronMissile.scala.txt");var source=new StringBuilder("package cn.academy.port.skill.lateoracle;import static cn.academy.port.skill.lateoracle.MathUtils.*;public class OriginalScalars{\n");
  Map<String,String> expressions=new LinkedHashMap<>();expressions.put("rb_cp",expr(rb,"val cp: Float = (lerpf\\([^\\n]+\\))"));expressions.put("rb_overload",expr(rb,"val overload: Float = (lerpf\\([^\\n]+\\))"));expressions.put("rb_plain",expr(rb,"getPlainDamage\\(exp: Float\\): Float = (lerpf\\([^\\n]+\\))"));expressions.put("rb_scattered",expr(rb,"getScatteredDamage\\(exp: Float\\): Float = (lerpf\\([^\\n]+\\))"));expressions.put("rb_cooldown",expr(rb,"ctx.setCooldown\\((lerpf\\(100, 40, exp\\))\\.toInt\\)"));expressions.put("je_consumption",expr(je,"val consumption: Float = (lerpf\\([^\\n]+\\))"));expressions.put("je_overload",expr(je,"val overload: Float = (lerpf\\([^\\n]+\\))"));expressions.put("je_damage",expr(je,"MDDamageHelper.attack\\(ctx, pos.entityHit, (lerpf\\(7, 20, exp\\))\\)"));expressions.put("je_cooldown",expr(je,"ctx.setCooldown\\((lerpf\\(60, 30, exp\\))\\.toInt\\)"));expressions.put("em_consumption",expr(em,"val consumption: Float = (lerpf\\([^\\n]+\\))"));expressions.put("em_attackCp",expr(em,"val consumption_attacked: Float = (lerpf\\([^\\n]+\\))"));expressions.put("em_attackOverload",expr(em,"val overload_attacked: Float = (lerpf\\([^\\n]+\\))"));expressions.put("em_limit",expr(em,"val timeLimit: Int = (lerpf\\(80, 200, exp\\))\\.toInt"));expressions.put("em_range",expr(em,"val range: Float = (lerpf\\(5, 13, exp\\))"));expressions.put("em_damage",expr(em,"val damage: Float = (lerpf\\(10, 18, exp\\))"));expressions.put("em_cooldown",expr(em,"val cooldown: Int = MathUtils\\.(clampi\\(700, 400, exp\\.toInt\\))").replace("exp.toInt","(int)exp"));
  for(var entry:expressions.entrySet())source.append("public static float ").append(entry.getKey()).append("(float exp){return ").append(entry.getValue()).append(";}\n");source.append("}\n");Path temp=Files.createTempDirectory("academy-late-original-oracle-");Path java=temp.resolve("OriginalScalars.java");Files.writeString(java,source);var compiler=ToolProvider.getSystemJavaCompiler();if(compiler==null)throw new AssertionError("JDK compiler required for source-expression oracle");int result=compiler.run(null,null,null,"-proc:none","-classpath",System.getProperty("java.class.path"),"-d",temp.toString(),java.toString());if(result!=0)throw new AssertionError("Original source-expression compilation failed");return new java.net.URLClassLoader(new java.net.URL[]{temp.toUri().toURL()},MeltdownerLateCombatOracleTest.class.getClassLoader());}
 private static float original(Class<?> scalar,String id,float exp)throws Exception{return(float)scalar.getMethod(id,float.class).invoke(null,exp);}
 public static void main(String[] args)throws Exception{check(LateCombatSourceFixtures.verifyAll()>=30,"all exact original resources verified");try(var loader=oracle()){Class<?> scalar=loader.loadClass("cn.academy.port.skill.lateoracle.OriginalScalars");for(int i=0;i<=1000;i++){float exp=i/1000F;var plan=RayBarrageRules.plan(exp);exact(plan.cp(),original(scalar,"rb_cp",exp),"originalRBcost");exact(plan.overload(),original(scalar,"rb_overload",exp),"originalRBoverload");exact(plan.plainDamage(),original(scalar,"rb_plain",exp),"originalRBplain");exact(plan.scatteredDamage(),original(scalar,"rb_scattered",exp),"originalRBscatter");check(plan.cooldown()==(int)original(scalar,"rb_cooldown",exp),"originalRBcooldown truncation");var s=ready(JetEngineSession.ID,4,exp);var jet=JetEngineSession.begin(s);exact(jet.affordability(),original(scalar,"je_consumption",exp),"originalJEaffordability");exact(jet.releaseCp(),original(scalar,"je_overload",exp),"originalJEreversedCP");exact(jet.releaseOverload(),original(scalar,"je_consumption",exp),"originalJEreversedstrain");exact(jet.damage(),original(scalar,"je_damage",exp),"originalJEdamage");jet.release(false);check(s.cooldowns.get(JetEngineSession.ID)==(int)original(scalar,"je_cooldown",exp),"originalJEcooldown");s=ready(ElectronMissileSession.ID,5,exp);var missile=ElectronMissileSession.begin(s,false);exact(missile.range(),original(scalar,"em_range",exp),"originalEMrange");exact(missile.damage(),original(scalar,"em_damage",exp),"originalEMdamage");check(missile.limit()==(int)original(scalar,"em_limit",exp),"originalEMinclusive limit truncation");double before=s.cp;missile.tick(false);check(s.cp==(float)before-original(scalar,"em_consumption",exp),"originalEMtickCP");before=s.cp;double overload=s.overload;check(missile.debitAttack(false),"originalEMball transaction");check(s.cp==(float)before-original(scalar,"em_attackCp",exp),"originalEMattackCP");check(s.overload==(float)overload+original(scalar,"em_attackOverload",exp),"originalEMattackstrain");missile.complete();check(s.cooldowns.get(ElectronMissileSession.ID)==(int)original(scalar,"em_cooldown",exp),"original actual clampi700");}}
  Random rng=new Random(197107);for(int i=0;i<10000;i++){float yaw=(rng.nextFloat()-.5F)*5000,pitch=(rng.nextFloat()-.5F)*360;double dx=(rng.nextDouble()-.5)*60,dy=(rng.nextDouble()-.5)*60,dz=(rng.nextDouble()-.5)*60;Motion3D original=new Motion3D().setMotion(dx,dy,dz);boolean expected=MathUtils.angleYawinRange(yaw-27.5F,yaw+27.5F,original.getRotationYaw())&&pitch-55<=original.getRotationPitch()&&original.getRotationPitch()<=pitch+55;check(RayBarrageRules.angular(dx,dy,dz,yaw,pitch)==expected,"original inclusive angularwedge");var origDir=new Motion3D().fromRotation(yaw,pitch);var actual=RayBarrageRules.rawDirection(yaw,pitch);check(actual.x()==origDir.vx&&actual.y()==origDir.vy&&actual.z()==origDir.vz,"original unnormalized lookup Motion3D vector");var feet=new ClassicBeamRay.Vec(-.2,2.3,-.1);var bounds=RayBarrageRules.bounds(feet,yaw,pitch);double[] b={feet.x(),feet.y(),feet.z(),feet.x(),feet.y(),feet.z()};for(float y:new float[]{yaw-27.5F,yaw+27.5F})for(float p:new float[]{pitch-55,pitch+55}){var point=new Motion3D(feet.x(),feet.y(),feet.z()).fromRotation(y,p).move(20);b[0]=Math.min(b[0],point.px);b[1]=Math.min(b[1],point.py);b[2]=Math.min(b[2],point.pz);b[3]=Math.max(b[3],point.px);b[4]=Math.max(b[4],point.py);b[5]=Math.max(b[5],point.pz);}check(bounds.equals(new ClassicBeamRay.Box(b[0],b[1],b[2],b[3],b[4],b[5])),"original5corner bounds");}
  String rb=LateCombatSourceFixtures.source("academycraft/RayBarrage.scala.txt"),mgr=LateCombatSourceFixtures.source("academycraft/ContextManager.java.txt"),je=LateCombatSourceFixtures.source("academycraft/JetEngine.scala.txt"),em=LateCombatSourceFixtures.source("academycraft/ElectronMissile.scala.txt");check(rb.contains("if(!ctx.consume(overload, cp)) terminate()\n    sendToSelf(MSG_EXECUTE)"),"source deferredterminate execute ordering");check(mgr.contains("data.disposed = true;")&&mgr.contains("void mToSelf(Context ctx, String channel, Object[] args) {\n            NetworkMessage.sendToSelf(ctx, channel, args);"),"actualContextManager does not suppress immediate execute");check(je.contains("ctx.consume(consumption, overload)")&&je.contains("if (ticks >= LIFETIME)\n        terminate()\n      ticks += 1"),"original reversedconsume and final movementafterterminate");check(em.contains("ticks <= timeLimit")&&em.contains("ticks % 10 == 0")&&em.contains("ticks != 0 && ticks % 8 == 0")&&em.contains("result.hurtResistantTime = -1"),"original schedule and resistance reset");System.out.println("PASS "+checks+" unchanged original Java and source-expression differential checks");}
 private static AbilityProgress ready(String id,int level,float exp){var s=new AbilityProgress();s.selectCategory("meltdowner");s.setLevel(level);s.learn(id);s.experience.put(id,(double)exp);s.activated=true;return s;}
}
