package cn.academy.port.skill;
import static cn.academy.port.core.ClassicFloatLedgerExpectations.*;
import cn.academy.port.core.AbilityProgress;
import java.util.*;
/** Original executable expressions/order, not generic beam-command assertions. */
public final class MeltdownerBeamRegressionTest {
    private static int checks;private static void check(boolean v,String why){++checks;if(!v)throw new AssertionError(why);}private static void exact(float a,float b,String why){check(Float.floatToIntBits(a)==Float.floatToIntBits(b),why+" actual="+a+" source="+b);}private static void close(double a,double b,String why){check(Math.abs(a-b)<1E-8*Math.max(1,Math.abs(b)),why+" actual="+a+" source="+b);}
    public static void main(String[] args){formulasAndCharge();mining();geometry();rangedRay();System.out.println("PASS "+checks+" original Meltdowner charge/mining/ranged-ray differential and source-quirk checks");}
    private static AbilityProgress ready(String id,double exp){var s=new AbilityProgress();s.selectCategory("meltdowner");s.setLevel(3);s.learn(id);s.experience.put(id,exp);s.activated=true;s.cp=100000;return s;}
    private static void formulasAndCharge(){for(int i=0;i<=10000;++i){float e=i/10000F;exact(MeltdownerSession.overload(e),200+(170-200)*e,"source initial overload");exact(MeltdownerSession.consumption(e),10+(15-10)*e,"source CP");exact(MeltdownerSession.reflectedDamage(e),.5F*(20+(50-20)*e),"source reflection rawDamage");exact(MineRayBasicSession.speed(e),.2F+(.4F-.2F)*e,"source mining speed");exact(MineRayBasicSession.consumption(e),12+(7-12)*e,"source mining CP");exact(MineRayBasicSession.overload(e),200+(150-200)*e,"source mining overload");check(MineRayBasicSession.cooldown(e)==(int)(40+(20-40)*e),"source mine cooldown truncation");
        var state=ready(MeltdownerSession.ID,e);var session=MeltdownerSession.begin(state,false);double initial=state.cp;float cost=10+(15-10)*e;for(int tick=1;tick<=101;++tick){boolean end=session.tick(false);close(state.cp,paidCpAfter(initial,cost,tick),"paid101 terminating ticks");check(end==(tick>100),"strict greater100timeout");check(session.ticks()==tick,"one pure tick");}
        check(session.release()==null,"timeout cannot fire or grant EXP");close(state.exp(MeltdownerSession.ID),e,"timeout no EXP");check(state.cooldowns.isEmpty(),"timeout no cooldown");
        for(int ticks=20;ticks<=100;++ticks){int ct=Math.min(ticks,40);float rate=.8F+(1.2F-.8F)*((ct-20F)/20F);var shot=MeltdownerSession.shot(e,ticks);check(shot.charge()==ct,"20..40 cap");exact(shot.radius(),2+(3-2)*e,"source radius");exact(shot.energy(),rate*(300+(700-300)*e),"source energy");exact(shot.damage(),rate*(18+(50-18)*e),"source damage");check(shot.cooldown()==(int)(rate*20*(15+(7-15)*e)),"source captured cooldown");exact(shot.experience(),rate*.002F,"source exp increment");}}
        for(int tick:new int[]{0,1,19,20,40,100}){var s=ready(MeltdownerSession.ID,0);var c=MeltdownerSession.begin(s,false);for(int j=0;j<tick;j++)c.tick(false);s.experience.put(MeltdownerSession.ID,1D);var shot=c.release();check((shot!=null)==(tick>=20),"minimum20server authoritative charge");if(shot!=null){exact(shot.damage(),MeltdownerSession.shot(0,tick).damage(),"captured mastery after concurrent mutation");c.complete(shot);check(s.cooldowns.get(MeltdownerSession.ID)==shot.cooldown(),"post-world completion cooldown");}check(c.release()==null,"release replay rejects");}
        var s=ready(MeltdownerSession.ID,0);s.cp=9;var c=MeltdownerSession.begin(s,false);check(c.tick(false)&&c.ticks()==1&&s.cp==9,"failed CP leaves balance and ends");check(c.release()==null&&s.cooldowns.isEmpty(),"failed charge cannot attack/cooldown");s=ready(MeltdownerSession.ID,0);c=MeltdownerSession.begin(s,false);s.overload=0;c.tick(false);close(s.overload,c.overloadFloor(),"overload hold floor");c.discard();check(!c.active()&&c.release()==null,"abort never fires");s=ready(MeltdownerSession.ID,0);s.overload=s.maxOverload()-10;c=MeltdownerSession.begin(s,false);check(c.ending()&&!s.overloadFine,"startup overloaded termination");}
    private static final class MineWorld implements MineRayBasicSession.World {MineRayBasicSession.Cell hit=new MineRayBasicSession.Cell(5,4,3),metadata;float hardness=.4F;int harvest=2,breaks,permissions,particles;boolean denied;List<MineRayBasicSession.Cell> emitted=new ArrayList<>();public MineRayBasicSession.Cell trace(){return hit;}public boolean denied(MineRayBasicSession.Cell c){permissions++;return denied;}public int harvestLevel(MineRayBasicSession.Cell c,MineRayBasicSession.Cell previous){metadata=previous;return harvest;}public float hardness(MineRayBasicSession.Cell c){return hardness;}public void breakBlock(MineRayBasicSession.Cell c){breaks++;}public void particles(MineRayBasicSession.Cell c){particles++;emitted.add(c);}}
    private static void mining(){for(int i=0;i<=1000;++i){float exp=i/1000F;var s=ready(MineRayBasicSession.ID,exp);var session=MineRayBasicSession.begin(s,false);var w=new MineWorld();float hardness=(i%20)/10F;w.hardness=hardness;float speed=.2F+(.4F-.2F)*exp;session.tick(false,w);exact(session.hardnessLeft(),hardness,"first target captures, no progress");check(w.permissions==1&&w.particles==0&&w.breaks==0,"source acquire order");check(w.metadata.equals(MineRayBasicSession.Cell.NONE),"source old-coordinate metadata bug exposed");int ticks=1;do{hardness-=speed;++ticks;session.tick(false,w);if(hardness>0)exact(session.hardnessLeft(),hardness,"literal float hardness subtraction");}while(hardness>0);check(w.breaks==1&&w.permissions==1,"one acquisition event, no revalidation each progress tick");check(w.emitted.get(w.emitted.size()-1).equals(MineRayBasicSession.Cell.NONE),"break resets coords BEFORE(-1,-1,-1) particles");close(s.cp,paidCpAfter(100000,MineRayBasicSession.consumption(exp),ticks),"finite CP every mining tick");close(s.exp(MineRayBasicSession.ID),masteryAfter(exp,.0005F,1),"break alone awardsEXP");check(session.finish()&&!session.finish(),"cooldown termination replay guarded");check(s.cooldowns.get(MineRayBasicSession.ID)==(int)(40+(20-40)*exp),"captured native cooldown");}
        var s=ready(MineRayBasicSession.ID,0);var c=MineRayBasicSession.begin(s,false);var w=new MineWorld();w.hardness=.2F;c.tick(false,w);s.cp=0;check(c.tick(false,w),"failed tick terminates");check(w.breaks==1&&s.exp(MineRayBasicSession.ID)==(double).0005F&&w.emitted.get(0).equals(MineRayBasicSession.Cell.NONE),"failed consumption still breaks/trains/emits sentinel");c.finish();check(s.cooldowns.get(MineRayBasicSession.ID)==40,"failed termination still cooldown");
        s=ready(MineRayBasicSession.ID,0);c=MineRayBasicSession.begin(s,false);w=new MineWorld();w.harvest=3;for(int i=0;i<5;i++)c.tick(false,w);check(w.permissions==5&&w.breaks==0&&w.particles==0&&c.target().equals(MineRayBasicSession.Cell.NONE),"high tier refused and rechecked each tick");w.harvest=2;w.hardness=-1;c.tick(false,w);for(int i=0;i<5;i++)c.tick(false,w);exact(c.hardnessLeft(),Float.MAX_VALUE,"unbreakable source FloatMAX subtraction");check(w.particles==5&&w.breaks==0,"unbreakable still particles and CP");w.hit=null;c.tick(false,w);check(c.target().equals(MineRayBasicSession.Cell.NONE),"miss clears target");w.hit=new MineRayBasicSession.Cell(1,1,1);w.denied=true;c.tick(false,w);check(c.target().equals(MineRayBasicSession.Cell.NONE),"protection cancels acquisition");c.discard();check(s.cooldowns.isEmpty(),"lifecycle disposal no cooldown");}
    private static final float[] SIN=new float[65536];static{for(int i=0;i<SIN.length;i++)SIN[i]=(float)Math.sin(i*Math.PI*2/65536);}private static float sin(float a){return SIN[(int)(a*10430.378F)&65535];}private static float cos(float a){return SIN[(int)(a*10430.378F+16384F)&65535];}
    private static void geometry(){var r=new java.util.Random(1);for(int i=0;i<100000;++i){float yaw=r.nextFloat()*720-360,pitch=r.nextFloat()*180-90;float a=yaw/180F*(float)Math.PI,b=pitch/180F*(float)Math.PI;double x=-sin(a)*cos(b),y=-sin(b),z=cos(a)*cos(b),norm=Math.sqrt(x*x+y*y+z*z);var slope=ClassicBeamRay.direction(yaw,pitch);close(slope.x(),x/norm,"exact source Motion3D headX");close(slope.y(),y/norm,"exact source headY");close(slope.z(),z/norm,"exact source headZ");float rotYaw=-(float)Math.PI*.5F-(-(float)Math.atan2(x/norm,z/norm)),rotPitch=-(float)Math.atan2(y/norm,Math.sqrt((x*x+z*z)/(norm*norm)));var basis=ClassicBeamRay.basis(slope);close(basis.first().x(),sin(rotYaw),"vp0 rotation");close(basis.first().z(),cos(rotYaw),"vp0Z");close(basis.second().x(),(double)sin(rotPitch)*cos(rotYaw),"vp1X");close(basis.second().y(),cos(rotPitch),"vp1Y");close(basis.second().z(),-(double)sin(rotPitch)*sin(rotYaw),"vp1Z");float damage=r.nextFloat()*50;var target=new ClassicBeamRay.Vec(r.nextDouble()*50-25,r.nextDouble()*10-5,r.nextDouble()*50);double cx=target.y()*slope.z()-target.z()*slope.y(),cy=target.z()*slope.x()-target.x()*slope.z(),cz=target.x()*slope.y()-target.y()*slope.x();float dist=Math.min(50,(float)Math.sqrt(cx*cx+cy*cy+cz*cz));exact(ClassicBeamRay.attackDamage(damage,new ClassicBeamRay.Vec(0,0,0),slope,target),damage*(1+(.2F-1)*(dist/50)),"attenuation lateral cross-product, not axial");}
        var slope=ClassicBeamRay.direction(0,0);var b=ClassicBeamRay.basis(slope);var cells=ClassicBeamRay.startingCells(new ClassicBeamRay.Vec(-.1,-.1,-.1),b,2,new FixedRandom());var unique=new HashSet<String>();for(var c:cells)unique.add(Arrays.toString(c));check(cells.size()>unique.size(),"identity HashSet retains coordinate duplicate lines");check(cells.stream().anyMatch(c->c[2]==0),"negative starting coordinate truncates toward0");check(cells.size()==15,"radius2fixed random literal lattice count");
        var p=new Plotter(0,0,0,1,.8,.7);check(Arrays.equals(p.next(),new int[]{0,1,0}),"Plotter Y beforeZ beforeX");check(Arrays.equals(p.next(),new int[]{0,1,1}),"Plotter Z afterY");check(Arrays.equals(p.next(),new int[]{1,1,1}),"Plotter finally advances dominantX");}
    private static class FixedRandom implements ClassicBeamRay.Random {public double nextDouble(){return .5;}public float nextFloat(){return .5F;}public int nextInt(int bound){return 0;}}
    private static final class RayWorld implements ClassicBeamRay.World {List<ClassicBeamRay.Target> entities=new ArrayList<>();List<Object> attacked=new ArrayList<>();List<Float> amounts=new ArrayList<>();Object reflect;boolean breakEnabled=true,denied;float hardness=0;int blocks,destroys;List<Boolean> sound=new ArrayList<>();public List<ClassicBeamRay.Target> targets(ClassicBeamRay.Box b){return entities;}public boolean attack(ClassicBeamRay.Target t,float damage){attacked.add(t.identity());amounts.add(damage);return t.identity()!=reflect;}public boolean canBreak(){return breakEnabled;}public ClassicBeamRay.Block block(ClassicBeamRay.Cell c){blocks++;return new ClassicBeamRay.Block(hardness,hardness==0);}public boolean denied(ClassicBeamRay.Cell c){return denied;}public void destroy(ClassicBeamRay.Cell c,float chance,boolean probe,ClassicBeamRay.Random r){check(chance==.05F,"source5percent block drop chance");destroys++;sound.add(probe);}}
    private static void rangedRay(){var origin=new ClassicBeamRay.Vec(0,0,0);var eye=new ClassicBeamRay.Vec(0,1.6,0);var dir=ClassicBeamRay.direction(0,0);var w=new RayWorld();w.entities.add(new ClassicBeamRay.Target("far",new ClassicBeamRay.Vec(0,0,40)));w.entities.add(new ClassicBeamRay.Target("near",new ClassicBeamRay.Vec(0,0,5)));w.entities.add(new ClassicBeamRay.Target("outside",new ClassicBeamRay.Vec(3,0,10)));var result=ClassicBeamRay.perform(w,new FixedRandom(),origin,eye,dir,2,240,14.4F);check(w.attacked.equals(List.of("near","far")),"all entities first, sorted feet distances, outside excluded");check(w.amounts.get(0).equals(w.amounts.get(1)),"same lateral distance has samedamage despite longitudinal40");check(result.blockProbes()==result.lines()*51,"51Plotter increments perline, first origin cell skipped");check(result.lines()==15,"literal 15lines source lattice with radius2");
        w=new RayWorld();w.reflect="near";w.entities.add(new ClassicBeamRay.Target("far",new ClassicBeamRay.Vec(0,0,40)));w.entities.add(new ClassicBeamRay.Target(w.reflect,new ClassicBeamRay.Vec(0,0,5)));result=ClassicBeamRay.perform(w,new FixedRandom(),origin,eye,dir,2,240,14.4F);check(w.attacked.size()==1&&result.maximumDistanceSquared()==25,"first reflection suppresses farther entity and squared terrainlimit");check(result.blockProbes()==result.lines()*5,"terrain starts each ray at first step and stops squaredfeetdistance");
        w=new RayWorld();w.hardness=-1;result=ClassicBeamRay.perform(w,new FixedRandom(),origin,eye,dir,2,240,14.4F);check(w.destroys==0&&result.blockProbes()==result.lines(),"negativehardness233333stops first cell");w=new RayWorld();w.denied=true;result=ClassicBeamRay.perform(w,new FixedRandom(),origin,eye,dir,2,240,14.4F);check(result.blockProbes()==result.lines(),"deniedairprobe stops line");w=new RayWorld();w.breakEnabled=false;result=ClassicBeamRay.perform(w,new FixedRandom(),origin,eye,dir,2,240,14.4F);check(result.lines()==0&&w.blocks==0,"config disablesterrain only");w=new RayWorld();w.hardness=.25F;result=ClassicBeamRay.perform(w,new FixedRandom(),origin,eye,dir,2,240,14.4F);check(w.sound.contains(true)&&w.sound.contains(false),"sound only increments<20");
        //5% side probe executes AFTER main failure too; source nextInt6 includes six realForge directions.
        w=new RayWorld();w.denied=true;var side=new ClassicBeamRay.Random(){int n;public double nextDouble(){return ++n<=25?.5:0;}public float nextFloat(){return .5F;}public int nextInt(int b){check(b==6,"source upperexclusive6");return 0;}};result=ClassicBeamRay.perform(w,side,origin,eye,dir,2,240,14.4F);check(result.blockProbes()>result.lines(),"neighbor probe survives failed main destruction");}
}
