package cn.academy.port.skill;
import cn.academy.port.SkillAvailability;
import cn.academy.port.SkillCatalog;
import cn.academy.port.core.AbilityProgress;
import cn.academy.port.develop.*;
import cn.academy.port.preset.PresetSkills;
import java.util.*;
/** Genuine prerequisite validation and finite Normal developer process; no runtime skill/power grant. */
public final class MeltdownerBeamLearningRegressionTest {
 private static int checks;private static void check(boolean v,String why){++checks;if(!v)throw new AssertionError(why);}
 public static void main(String[] args){check(SkillCatalog.ALL.size()==50,"unchanged canonical50skills");var old=new HashSet<>(PresetSkills.IMPLEMENTED);old.remove("meltdowner");old.remove("mine_ray_basic");check(old.containsAll(java.util.List.of("arc_gen","charging","railgun","electron_bomb","threatening_teleport","dir_shock","ground_shock","mag_movement","mag_manip","thunder_bolt","mine_detect","body_intensify","thunder_clap","scatter_bomb","light_shield")),"all15previous actives preserved");
  for(String id:List.of("meltdowner","mine_ray_basic")){var skill=SkillCatalog.find("meltdowner",id).orElseThrow();var expected=id.equals("meltdowner")?List.of(new SkillCatalog.Requirement("scatter_bomb",.8),new SkillCatalog.Requirement("light_shield",.8)):List.of(new SkillCatalog.Requirement("meltdowner",.3));check(skill.level()==3&&skill.controllable()&&skill.requirements().equals(expected),"exact level3canonical dependencies");check(SkillAvailability.learnable(id)&&PresetSkills.IMPLEMENTED.contains(id),"single shared registry drives genuine ingress");var s=ready();check(!SkillCatalog.canLearn(s,skill),"unearned parent blocks");
   for(var req:expected){s.learn(req.id());s.experience.put(req.id(),Math.nextDown(req.exp()));}check(SkillCatalog.canLearn(s,skill),"double-only predecessors round to exact source floats and accept");for(var req:expected)s.experience.put(req.id(),(double)Math.nextDown((float)req.exp()));check(!SkillCatalog.canLearn(s,skill),"justbelow EXP fails");for(var req:expected)s.experience.put(req.id(),req.exp());check(SkillCatalog.canLearn(s,skill),"exact prerequisites permit");for(var req:expected){s.experience.remove(req.id());check(!SkillCatalog.canLearn(s,skill),"each parent must be learned");s.experience.put(req.id(),req.exp());}
   check(!DevelopmentActions.canLearn(s,DeveloperType.PORTABLE,skill),"portable cannot learn level3");check(DevelopmentActions.canLearn(s,DeveloperType.NORMAL,skill)&&DevelopmentActions.canLearn(s,DeveloperType.ADVANCED,skill),"Normal minimum and Advanced eligible");s.level=2;check(!DevelopmentActions.canLearn(s,DeveloperType.NORMAL,skill),"category level below3blocked");s.level=3;
   var battery=new Battery(DeveloperType.NORMAL,50000);var process=new DevelopmentProcess();var action=DevelopmentActions.skill(s,skill);check(action.stimulations()==7,"source floor7stimulations");process.start(battery,action);for(int tick=1;tick<=147;++tick){process.tick();if(tick<147)check(!s.learned(id),"seven21tick stimulations nevercompleteearly");}check(process.state()==DevelopmentProcess.State.DONE&&s.learned(id)&&s.exp(id)==0,"naturallylearned zero mastery");check(Math.abs(battery.energy()-(50000-5145))<1E-8,"real finite5145IF drain, not nominal4900");check(s.presets.currentSkill(0).isEmpty(),"no autobinding");s.activated=true;final var bound=s;check(s.presets.edit(0,0,id,value->PresetSkills.selectable(bound,value)),"normal preset binds naturallylearned skill");check(id.equals("meltdowner")?MeltdownerSession.mayStart(s):MineRayBasicSession.mayStart(s),"zero mastery authentic skill gates pass");
   s=ready();for(var req:expected)s.experience.put(req.id(),req.exp());battery=new Battery(DeveloperType.NORMAL,34);process=new DevelopmentProcess();process.start(battery,DevelopmentActions.skill(s,skill));process.tick();check(process.state()==DevelopmentProcess.State.FAILED&&!s.learned(id)&&battery.energy()==34,"finite insufficient35IFtick leaves Normal battery atomic and grantsnothing");
   battery=new Battery(DeveloperType.NORMAL,50000);process=new DevelopmentProcess();process.start(battery,DevelopmentActions.skill(s,skill));for(int tick=0;tick<146;tick++)process.tick();s.experience.remove(expected.get(0).id());process.tick();check(process.state()==DevelopmentProcess.State.FAILED&&!s.learned(id),"completion revalidates parents");
   s=ready();for(var req:expected)s.experience.put(req.id(),req.exp());battery=new Battery(DeveloperType.PORTABLE,10000);process=new DevelopmentProcess();process.start(battery,DevelopmentActions.skill(s,skill));for(int tick=0;tick<182;++tick)process.tick();check(process.state()==DevelopmentProcess.State.FAILED&&!s.learned(id),"lowerdeveloper cannot complete illicitstart");
  }System.out.println("PASS "+checks+" exact prerequisites, finite Normal learning and authentic binding checks");}
 private static AbilityProgress ready(){var s=new AbilityProgress();s.selectCategory("meltdowner");s.setLevel(3);return s;}
 private static final class Battery implements DevelopmentProcess.Developer {final DeveloperType type;final cn.academy.port.machine.MachineDeveloperEnergy machine;double portable;Battery(DeveloperType type,double energy){this.type=type;machine=type==DeveloperType.PORTABLE?null:new cn.academy.port.machine.MachineDeveloperEnergy(type,()->{},()->true);if(machine!=null)machine.load(energy);else portable=energy;}public DeveloperType type(){return type;}public boolean tryPullEnergy(double amount){if(machine!=null)return machine.tryPull(amount);double before=portable;portable=Math.max(0,portable-amount);return before>=amount;}public double energy(){return machine!=null?machine.energy():portable;}public double maxEnergy(){return type.energy;}}
}
