package cn.academy.port.skill;
import cn.academy.port.skill.oracle.BeamOracleSupport.*;
import cn.academy.port.skill.oracle.RangedRayDamage;
import java.util.*;
/** Differential against the UNCHANGED original RangedRayDamage class body running in test-side stubs. */
public final class MeltdownerBeamUpstreamOracleTest {
 private static int checks;private static void check(boolean v,String why){checks++;if(!v)throw new AssertionError(why);}
 private static void canonicalFixture()throws Exception{try(var in=MeltdownerBeamUpstreamOracleTest.class.getResourceAsStream("/classic-oracles/meltdowner-beams/RangedRayDamage.java.txt")){if(in==null)throw new AssertionError("Missing canonical GPL-noticed ray test resource");String hash=java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(in.readAllBytes()));check(hash.equals("594040499f6bd95f5666a451b898901463efa8ceb6f0b200ac2a3fcf30be9d05"),"canonical original ray fixture SHA256");}}
 public static void main(String[] args)throws Exception{canonicalFixture();for(int angle=0;angle<40;angle++)for(int scenario=0;scenario<5;scenario++){var world=new World();var player=new EntityPlayer(world,-.2,2.3,-.1);player.yaw=angle*9;player.pitch=angle%5*15-30;var ctx=new AbilityContext(player);var slope=ClassicBeamRay.direction(player.yaw,player.pitch);var feet=new ClassicBeamRay.Vec(player.posX,player.posY,player.posZ);var eye=feet.add(new ClassicBeamRay.Vec(0,player.eye,0));var targets=new ArrayList<ClassicBeamRay.Target>();for(int d:new int[]{3,10,30,45}){var v=feet.add(slope.scale(d));var ent=new Entity(world,v.x(),v.y(),v.z());world.entities.add(ent);targets.add(new ClassicBeamRay.Target(ent,v));}if(scenario==1)ctx.reflector=world.entities.get(1);if(scenario==2)world.hardness=-1;if(scenario==3)world.denied=true;if(scenario==4)world.canBreak=false;var oracle=new RangedRayDamage.Reflectible(ctx,2.4F,500,entity->{});oracle.startDamage=30;oracle.perform();
    var probes=new ArrayList<String>();var attacks=new ArrayList<Attack>();var adapter=new ClassicBeamRay.World(){public List<ClassicBeamRay.Target> targets(ClassicBeamRay.Box b){return targets.stream().filter(t->t.feet().x()>=b.minX()&&t.feet().x()<=b.maxX()&&t.feet().y()>=b.minY()&&t.feet().y()<=b.maxY()&&t.feet().z()>=b.minZ()&&t.feet().z()<=b.maxZ()).toList();}public boolean attack(ClassicBeamRay.Target t,float amount){if(t.identity()==ctx.reflector)return false;attacks.add(new Attack((Entity)t.identity(),amount));return true;}public boolean canBreak(){return world.canBreak;}public ClassicBeamRay.Block block(ClassicBeamRay.Cell c){return new ClassicBeamRay.Block(world.hardness,true);}public boolean denied(ClassicBeamRay.Cell c){probes.add(c.x()+","+c.y()+","+c.z());return world.denied;}public void destroy(ClassicBeamRay.Cell c,float chance,boolean sound,ClassicBeamRay.Random r){throw new AssertionError("air oracle has no nonairdestroy");}};
    var random=new ClassicBeamRay.Random(){public double nextDouble(){return .5;}public float nextFloat(){return .5F;}public int nextInt(int n){return 0;}};ClassicBeamRay.perform(adapter,random,feet,eye,slope,2.4F,500,30);check(attacks.size()==ctx.attacks.size(),"upstream entity count angle/scenario "+angle+"/"+scenario);for(int i=0;i<attacks.size();i++){check(attacks.get(i).target()==ctx.attacks.get(i).target(),"source feet-sorted identity");check(Float.floatToIntBits(attacks.get(i).damage())==Float.floatToIntBits(ctx.attacks.get(i).damage()),"source exact lateral Float damage");}Collections.sort(probes);Collections.sort(world.probes);check(probes.equals(world.probes),"literal upstream block-line multiset incl duplicate/truncation/reflection/unbreakable/permission angle/scenario "+angle+"/"+scenario);}
  System.out.println("PASS "+checks+" unchanged upstream executable RangedRayDamage oracle comparisons");}
}
