package cn.academy.port.skill;
import cn.academy.port.*;
import cn.academy.port.core.*;
import cn.academy.port.develop.*;
import cn.academy.port.preset.PresetSkills;
import java.util.*;
public final class TeleporterProgressionLearningRegressionTest {
 static final class Battery implements DevelopmentProcess.Developer{final DeveloperType type;double amount;Battery(DeveloperType type,double amount){this.type=type;this.amount=amount;}public DeveloperType type(){return type;}public boolean tryPullEnergy(double n){double removed=Math.min(amount,n);amount-=removed;return removed==n;}public double energy(){return amount;}public double maxEnergy(){return type.energy;}}
 static void check(boolean b,String reason){if(!b)throw new AssertionError(reason);}static AbilityProgress prerequisites(SkillCatalog.Skill skill){var s=new AbilityProgress();s.selectCategory("teleporter");s.setLevel(skill.level());for(var r:skill.requirements()){s.learn(r.id());s.experience.put(r.id(),r.exp());}return s;}
 public static void main(String[] args){TeleporterSourceFixtures.verify();String category=TeleporterSourceFixtures.source("AcademyCraft-1.0.7","src/main/java/cn/academy/vanilla/teleporter/CatTeleporter.java");for(String s:List.of("penetrateTP.setParent(threateningTP, 0.5f)","markTP.setParent(threateningTP, 0.4f)","fleshRipping.setParent(markTP, 0.5f)","fleshRipping.addSkillDep(penetrateTP, 0.5f)"))TeleporterSourceFixtures.contains(category,s);
 for(String id:List.of("penetrate_teleport","mark_teleport","flesh_ripping")){check(SkillAvailability.learnable(id)&&PresetSkills.IMPLEMENTED.contains(id),"single common implemented registry "+id);var skill=SkillCatalog.find("teleporter",id).orElseThrow();var s=prerequisites(skill);var tier=DeveloperType.minimumForSkill(skill.level());check(!s.learned(id)&&s.exp(id)==0,"never pre-grant target");check(DevelopmentActions.canLearn(s,tier,skill),"canonical dependencies learnable");check(!PresetSkills.selectable(s,id),"unearned target not selectable");for(var req:skill.requirements()){double old=s.exp(req.id());s.experience.put(req.id(),old-.0001);check(!DevelopmentActions.canLearn(s,tier,skill),"all exact prerequisite thresholds");s.experience.put(req.id(),old);s.experience.remove(req.id());check(!DevelopmentActions.canLearn(s,tier,skill),"zero thresholds still require learned skill");s.learn(req.id());s.experience.put(req.id(),old);}s.level--;check(!DevelopmentActions.canLearn(s,tier,skill),"level gate");s.level++;s.category="meltdowner";check(!DevelopmentActions.canLearn(s,tier,skill),"category gate");s.category="teleporter";if(skill.level()==3)check(!DevelopmentActions.canLearn(s,DeveloperType.PORTABLE,skill),"genuine minimum normal");
  var process=new DevelopmentProcess();var battery=new Battery(tier,tier.energy);process.start(battery,DevelopmentActions.skill(s,skill));int ticks=ClassicRules.learningStimulations(skill.level())*tier.ticksPerStimulation();for(int tick=1;tick<=ticks;tick++){process.tick();if(tick<ticks)check(!s.learned(id),"no early completion");}check(process.state()==DevelopmentProcess.State.DONE&&s.learned(id)&&s.exp(id)==0,"finite canonical learning genuinely earns zero-mastery target");TeleporterProgressionRegressionTest.near(battery.amount,tier.energy-tier.actualConsumption(ClassicRules.learningStimulations(skill.level())));s.activated=true;check(PresetSkills.selectable(s,id)&&s.presets.edit(0,0,id,value->PresetSkills.selectable(s,value)),"genuine canonical preset path at zero EXP");var poor=prerequisites(skill);var insufficient=new Battery(tier,1);process.start(insufficient,DevelopmentActions.skill(poor,skill));process.tick();check(process.state()==DevelopmentProcess.State.FAILED&&!poor.learned(id)&&insufficient.amount==0,"finite-power failure drains remainder without grant");}
 System.out.println("PASS all three canonical source dependencies, minimum tiers, finite IF, exact130/147 tick learning and zero-mastery preset eligibility; native menu fixtures compiled separately");}
}
