package cn.academy.port.skill;
import cn.academy.port.skill.vectorcombatoracle.MathUtils;
import com.google.gson.*;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;import java.util.regex.*;
/** Unchanged executable LambdaLib scalar oracle plus expression extraction from packaged pinned Scala.
 * Original Forge1.7 context is inspected, not claimed to be executable on1.21. */
public final class VectorCombatSourceOracleTest {
 private static final String BASE="/classic-oracles/vector-combat-progression/";private static int checks;private static void check(boolean ok,String why){checks++;if(!ok)throw new AssertionError(why);}private static void near(double a,double b,String why){check(Math.abs(a-b)<1E-7,why+" actual="+a+" expected="+b);}
 private static byte[] resource(String path)throws Exception{try(var s=Objects.requireNonNull(VectorCombatSourceOracleTest.class.getResourceAsStream(BASE+path),path)){return s.readAllBytes();}}private static String source(String project,String path)throws Exception{return new String(resource("gameplay-source/"+project+"/"+path+".txt"),StandardCharsets.UTF_8);}private static float number(String s){return Float.parseFloat(s.strip().replace("f",""));}private static float[] pair(String source,String pattern){var m=Pattern.compile(pattern).matcher(source);check(m.find(),"canonical expression "+pattern);return new float[]{number(m.group(1)),number(m.group(2))};}
 public static void main(String[] args)throws Exception{var manifest=JsonParser.parseString(new String(resource("gameplay-source-manifest.json"),StandardCharsets.UTF_8)).getAsJsonObject();check(manifest.get("academycraft_commit").getAsString().equals("00d19ec0cf538f61c1095c9292f5ee6863db4521"),"sourcecommit pinned");for(var e:manifest.getAsJsonArray("sources")){var record=e.getAsJsonObject();byte[] data=resource(record.get("fixture").getAsString());check(data.length==record.get("bytes").getAsInt(),"fixture bytecount");check(HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(data)).equals(record.get("sha256").getAsString()),"immutable sourcehash");}
  String blast=source("academycraft","src/main/scala/cn/academy/vanilla/vecmanip/skill/DirectedBlastwave.scala"),blood=source("academycraft","src/main/scala/cn/academy/vanilla/vecmanip/skill/BloodRetrograde.scala"),storm=source("academycraft","src/main/scala/cn/academy/vanilla/vecmanip/skill/StormWing.scala");
  String numeric="([0-9.]+f?)";float[] bcp=pair(blast,"consumption = lerpf\\("+numeric+", "+numeric+","),bo=pair(blast,"overload = lerpf\\("+numeric+", "+numeric+","),bd=pair(blast,"damage = lerpf\\("+numeric+", "+numeric+","),bp=pair(blast,"breakProb = lerpf\\("+numeric+", "+numeric+","),br=pair(blast,"dropRate = lerpf\\("+numeric+", "+numeric+","),bc=pair(blast,"cooldown = lerpf\\("+numeric+", "+numeric+",");float[] rcp=pair(blood,"consumption = lerpf\\("+numeric+", "+numeric+","),ro=pair(blood,"overload = lerpf\\("+numeric+", "+numeric+","),rd=pair(blood,"damage = lerpf\\("+numeric+", "+numeric+","),rc=pair(blood,"setCooldown\\(lerpf\\("+numeric+", "+numeric+",");float[] wcp=pair(storm,"consumption = lerpf\\("+numeric+", "+numeric+","),wo=pair(storm,"overload = lerpf\\("+numeric+", "+numeric+","),wc=pair(storm,"chargeTime = lerpf\\("+numeric+", "+numeric+","),wd=pair(storm,"setCooldown\\(lerpf\\("+numeric+", "+numeric+",");
  for(int i=0;i<=1000;i++){float e=i/1000F;near(VectorCombatRules.blastCp(e),MathUtils.lerpf(bcp[0],bcp[1],e),"original blastCP");near(VectorCombatRules.blastOverload(e),MathUtils.lerpf(bo[0],bo[1],e),"original blaststrain");near(VectorCombatRules.blastDamage(e),MathUtils.lerpf(bd[0],bd[1],e),"original blastdamage");near(VectorCombatRules.blastBreakProbability(e),MathUtils.lerpf(bp[0],bp[1],e),"original blastprob");near(VectorCombatRules.blastDropRate(e),MathUtils.lerpf(br[0],br[1],e),"original blastdrop");check(VectorCombatRules.blastCooldown(e)==(int)MathUtils.lerpf(bc[0],bc[1],e),"original blastcooldown");near(VectorCombatRules.bloodCp(e),MathUtils.lerpf(rcp[0],rcp[1],e),"original bloodCP");near(VectorCombatRules.bloodOverload(e),MathUtils.lerpf(ro[0],ro[1],e),"original bloodstrain");near(VectorCombatRules.bloodDamage(e),MathUtils.lerpf(rd[0],rd[1],e),"original blooddamage");check(VectorCombatRules.bloodCooldown(e)==(int)MathUtils.lerpf(rc[0],rc[1],e),"original bloodcooldown");near(VectorCombatRules.stormCp(e),MathUtils.lerpf(wcp[0],wcp[1],e),"original stormCP");near(VectorCombatRules.stormOverload(e),MathUtils.lerpf(wo[0],wo[1],e),"original stormstrain");near(VectorCombatRules.stormCharge(e),MathUtils.lerpf(wc[0],wc[1],e),"original stormcharge");check(VectorCombatRules.stormCooldown(e)==(int)MathUtils.lerpf(wd[0],wd[1],e),"original stormcooldown");}
  check(blast.contains("ticker > MIN_TICKS && ticker < MAX_ACCEPTED_TICKS")&&blast.contains("MIN_TICKS = 6")&&blast.contains("MAX_ACCEPTED_TICKS = 50")&&blast.contains("MAX_TOLERANT_TICKS = 200"),"strict sourcechargegates");check(blast.contains("(x - 3) until (x + 3)")&&blast.contains("distSq <= 6")&&blast.contains("math.round(position.x).toInt"),"originalasymmetric rounding and blockbounds");check(blast.indexOf("knockback(entity)")<blast.indexOf("entity.setVel(entity.velocity + delta)"),"sourceimpulseorder");check(blast.contains("delta.yCoord = -0.4f")&&blast.contains("delta * -1.2f")&&blast.contains("normalize() * 0.24"),"exacttwo-normalization knockback");check(blood.contains("tick >= 30.0f")&&blood.contains("setPlayerWalkSpeed(0.1f)")&&blood.contains("Raytrace.traceLiving(player, 2, EntitySelectors.living)"),"originalauto slowreset andtargetrange");check(blood.indexOf("ctx.attack(targ, damage)")<blood.indexOf("ctx.addSkillExp(0.002f)")&&blood.indexOf("ctx.addSkillExp(0.002f)")<blood.indexOf("if(ctx.getSkillExp == 1f)"),"originalbloodpostaward achievement");check(storm.contains("stateTick > chargeTime")&&storm.contains("player.motionY += 0.078")&&storm.contains("player.motionY = 0.1")&&storm.contains("ACCEL = 0.16"),"originalstorm hover axisaccel strictcharge");check(storm.contains("(0 until 40)")&&storm.contains("ctx.getSkillExp < 0.15f")&&storm.contains("hardness <= 0.3f")&&storm.contains("(player.posX + rval).toInt"),"originalsoftblock count threshold truncation");check(storm.indexOf("ctx.addSkillExp(expincr)")<storm.indexOf("ctx.consume(overload, consumption)"),"stormEXPbeforeconsume");check(storm.contains("ctx.getSkillExp == 1.0f")&&source("lambdalib","src/main/java/cn/lambdalib/util/mc/WorldUtils.java").contains("getEntitiesWithinAABBExcludingEntity(null"),"masterburst includesself sourceoddity");
  String cat=source("academycraft","src/main/scala/cn/academy/vanilla/vecmanip/CatVecManip.scala");check(cat.contains("DirectedBlastwave.setParent(Groundshock)")&&cat.contains("StormWing.setParent(VecAccel)")&&cat.contains("BloodRetrograde.setParent(DirectedBlastwave)"),"canonicalparents");check(source("academycraft","src/main/java/cn/academy/ability/develop/condition/DevConditionDep.java").contains("this(_dep, 0.0f)"),"zeroEXPparentgate source");
  String api=source("academycraft","src/main/java/cn/academy/ability/api/AbilityContext.java");check(source("academycraft","src/main/java/cn/academy/ability/api/data/CPData.java").contains("CalcEvent.SkillPerform")&&api.contains("getFinalConsCP")&&api.contains("getFinalExpIncr"),"sharednot-yetfull CalcEvent configledger sourceanchors");System.out.println("PASS "+checks+" packaged sourcehash/executable scalar/source semantic oracle checks");}
}
