package cn.academy.port.skill;
import cn.academy.port.skill.finaloracle.MathUtils;
import java.util.regex.*;
/** Source-derived endpoints compared using unchanged upstream LambdaLib class bodies. */
public final class VectorFinalSourceOracleTest {
 private static int checks;private static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}private static void near(double a,double b,String why){check(Math.abs(a-b)<1E-7,why);}private static float[] pair(String source,String pattern){var m=Pattern.compile(pattern).matcher(source);check(m.find(),"source expression "+pattern);return new float[]{Float.parseFloat(m.group(1)),Float.parseFloat(m.group(2))};}
 public static void main(String[] args)throws Exception{check(VectorFinalSourceFixtures.verifyAll()==39,"39 pinned source/media resources");String reflection=VectorFinalSourceFixtures.source("academy/VecReflection.scala"),plasma=VectorFinalSourceFixtures.source("academy/PlasmaCannon.scala");
  String[] patterns={"overloadToKeep = lerpf\\(([^,]+), ([^,]+),","difficulty \\* lerpf\\(([^,]+), ([^,]+),","consumeWithForce\\(0, lerpf\\(([^,]+), ([^,]+),","ctx.consume\\(0,  lerpf\\(([^,]+), ([^,]+),","reflectDamage = lerpf\\(([^f,]+)f, ([^f,]+)f,"};float[][] pairs=new float[patterns.length][];for(int i=0;i<patterns.length;i++)pairs[i]=pair(reflection,patterns[i]);
  String[] pp={"chargeTime = lerpf\\(([^,]+), ([^,]+),","overloadToKeep = lerpf\\(([^,]+), ([^,]+),","cp = lerpf\\(([^,]+), ([^,]+),","setCooldown\\(lerpf\\(([^,]+), ([^,]+),","ctx.attack\\(entity, lerpf\\(([^,]+), ([^,]+),","lerpf\\(([^f,]+)f, ([^f,]+)f, ctx.getSkillExp\\)\\)"};float[][] pv=new float[pp.length][];for(int i=0;i<pp.length;i++)pv[i]=pair(plasma,pp[i]);
  for(int i=0;i<=10000;i++){float e=i/10000F;float[] got={VecReflectionSession.initialOverload(e),VecReflectionSession.entityCp(e),VecReflectionSession.damageCp(e),VecReflectionSession.normalCp(e),VecReflectionSession.ratio(e)};for(int j=0;j<got.length;j++)near(got[j],MathUtils.lerpf(pairs[j][0],pairs[j][1],e),"original reflection float lerp");float[] pgot={PlasmaCannonSession.chargeTime(e),PlasmaCannonSession.initialOverload(e),PlasmaCannonSession.tickCp(e),PlasmaCannonSession.cooldown(e),PlasmaCannonSession.damage(e),PlasmaCannonSession.explosionPower(e)};for(int j=0;j<pgot.length;j++){float expected=MathUtils.lerpf(pv[j][0],pv[j][1],e);near(pgot[j],j==3?(int)expected:expected,"original plasma float and truncated cooldown");}}
  check(reflection.contains("(false, dmg - reflectDamage)")&&reflection.contains("visited ++= entities")&&reflection.contains("entities.removeAll(visited)"),"passby false and identity visited semantics");check(reflection.indexOf("val reflectDamage")<reflection.indexOf("ctx.addSkillExp(dmg * 0.0004f)"),"ratio precedes award");check(plasma.indexOf("ctx.addSkillExp(0.008f)")<plasma.indexOf("ctx.setCooldown"),"postaward cooldown");check(plasma.contains("localTicker < chargeTime")&&plasma.contains("localTicker == chargeTime.toInt")&&plasma.contains("syncTicker = 5"),"float charge and six tick sync");check(plasma.contains("case _ => explode()")&&plasma.contains("if (localTicker >= 240 || chargePosition.distanceTo(destination) < 1.5)"),"independent collision and arrival explosions");check(plasma.contains("destination.x, destination.y, destination.z")&&plasma.contains("entity.hurtResistantTime = -1"),"destination sphere and reset after attack");String cat=VectorFinalSourceFixtures.source("academy/CatVecManip.scala");check(cat.contains("VecReflection.setParent(VecDeviation)")&&cat.contains("PlasmaCannon.setParent(StormWing)"),"actual source parent edges");String key=VectorFinalSourceFixtures.source("academy/Skill.java");key=key.substring(key.indexOf("class SingleKeyDelegate"));String keyup=key.substring(key.indexOf("public void onKeyUp()"),key.indexOf("public void onKeyAbort()"));check(keyup.contains("context = null")&&!plasma.contains("ActivateHandlers.terminatesContext"),"source released plasma detached from controls");check(VectorFinalSourceFixtures.source("academy/FollowEntitySound.java").contains("this.repeat = true")&&!plasma.contains("sound.setLoop"),"nonlooping default source sound");System.out.println("PASS "+checks+" source-pinned unchanged LambdaLib differential and order checks");}
}
