package cn.academy.port.skill;
import cn.academy.port.*;import cn.academy.port.core.*;import cn.academy.port.develop.*;import cn.academy.port.machine.*;import cn.academy.port.preset.PresetSkills;import java.util.*;
public final class VectorFinalLearningRegressionTest {
 private static int checks;private static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}private static AbilityProgress ready(int level){var s=new AbilityProgress();s.selectCategory("vecmanip");s.setLevel(level);return s;}
 public static void main(String[] args){for(String id:List.of("vec_reflection","plasma_cannon")){int level=id.equals("vec_reflection")?4:5;String parent=level==4?"vec_deviation":"storm_wing";var skill=SkillCatalog.find("vecmanip",id).orElseThrow();check(skill.level()==level&&skill.controllable()&&skill.requirements().equals(List.of(new SkillCatalog.Requirement(parent,0))),"source parent no invented mastery");check(PresetSkills.IMPLEMENTED.contains(id)&&SkillAvailability.learnable(id),"single common availability");var s=ready(level);check(!SkillCatalog.canLearn(s,skill),"missing parent gate");s.learn(parent);check(SkillCatalog.canLearn(s,skill)&&DevelopmentActions.canLearn(s,DeveloperType.ADVANCED,skill),"zero mastery parent accepted");check(!DevelopmentActions.canLearn(s,DeveloperType.PORTABLE,skill)&&!DevelopmentActions.canLearn(s,DeveloperType.NORMAL,skill),"actual Advanced tier required");
  var battery=new Battery(200000);var process=new DevelopmentProcess();var action=DevelopmentActions.skill(s,skill);int stim=level==4?11:15,ticks=stim*16;check(action.stimulations()==stim,"source nonlinear stimulation count");process.start(battery,action);for(int t=1;t<=ticks;t++){process.tick();if(t<ticks)check(!s.learned(id),"no premature target grant");}check(s.learned(id)&&s.exp(id)==0&&process.state()==DevelopmentProcess.State.DONE,"genuine zero mastery completion");check(Math.abs(battery.energy()-200000+ticks*40)<1E-5,"finite Advanced IF7040/9600");s.activated=true;var selected=s;check(s.presets.edit(0,0,id,x->PresetSkills.selectable(selected,x)),"earned preset skill binds");
  s=ready(level);s.learn(parent);battery=new Battery(39);process=new DevelopmentProcess();process.start(battery,DevelopmentActions.skill(s,skill));process.tick();check(process.state()==DevelopmentProcess.State.FAILED&&!s.learned(id),"energy starvation grants nothing");s=ready(level);s.learn(parent);battery=new Battery(200000);process=new DevelopmentProcess();process.start(battery,DevelopmentActions.skill(s,skill));for(int t=1;t<ticks;t++)process.tick();s.experience.remove(parent);process.tick();check(process.state()==DevelopmentProcess.State.FAILED&&!s.learned(id),"parent rechecked on completion");}
  check(SkillAvailability.learnable("vec_accel")&&SkillAvailability.learnable("vec_deviation"),"existing starter learning retained");System.out.println("PASS "+checks+" final VecManip genuine finite-power learning checks");}
 private static final class Battery implements DevelopmentProcess.Developer{final MachineDeveloperEnergy battery;Battery(double energy){battery=new MachineDeveloperEnergy(DeveloperType.ADVANCED,()->{},()->true);battery.load(energy);}public DeveloperType type(){return DeveloperType.ADVANCED;}public boolean tryPullEnergy(double n){return battery.tryPull(n);}public double energy(){return battery.energy();}public double maxEnergy(){return type().energy;}}
}
