package cn.academy.port.skill;
import static cn.academy.port.core.ClassicFloatLedgerExpectations.*;
import cn.academy.port.core.AbilityProgress;
public final class VectorFinalRegressionTest {
 private static int checks;private static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}private static void near(double a,double b,String why){check(Math.abs(a-b)<1E-5,why+" actual="+a+" expected="+b);}
 private static AbilityProgress state(String id,double exp){var s=new AbilityProgress();s.selectCategory("vecmanip");s.setLevel(5);s.learn(id);s.experience.put(id,exp);s.activated=true;return s;}
 public static void main(String[] args){
  for(double e:new double[]{0,.25,.5,.75,1}){var s=state(VecReflectionSession.ID,e);double cp=s.cp;var r=VecReflectionSession.begin(s,false);check(r!=null,"learned reflection starts");near(s.overload,VecReflectionSession.initialOverload(e),"one initial floor");r.beginTick();s.overload=0;r.beginTick();near(s.overload,r.overloadFloor(),"floor retained");check(r.affect(.1F,false),"snowball affordable");near(s.cp,paidCpAfter(cp,.1F*VecReflectionSession.entityCp(e),1),"difficulty-weighted resource");near(s.exp(r.ID),masteryAfter(e,.1F*.0008F,1),"difficulty-weighted EXP");double before=s.cp;float ratio=VecReflectionSession.ratio(s.exp(r.ID)),cost=VecReflectionSession.damageCp(s.exp(r.ID));var pass=r.damage(10,true,false);check(!pass.performed(),"source passby never cancels");near(s.cp,before,"passby no debit");var damage=r.damage(10,false,false);near(damage.reflected(),ratio*10,"preaward dynamic reflect");near(damage.remaining(),10-ratio*10,"literal negative remainder allowed");near(s.cp,paidCpAfter(before,cost*10,1),"forced cost");double exp=s.exp(r.ID);s.cp=0;double extra=s.extraCp;r.damage(5,false,false);near(s.cp,0,"forced zero clamp");near(s.extraCp,cpTrainingAfter(extra,VecReflectionSession.damageCp(exp)*5,1,12000f),"full forced training");check(s.cooldowns.isEmpty(),"no invented reflection cooldown");r.endTick(false);check(r.ending(),"normal CP exhaustion ends toggle");}
  for(double e:new double[]{0,.1,.5,.51,.999,1}){var s=state(PlasmaCannonSession.ID,e);var p=PlasmaCannonSession.begin(s,false);double cp=s.cp;int charged=(int)Math.ceil(p.capturedChargeTime());for(int tick=1;tick<charged;tick++){check(p.tick(false),"finite charge debit");check(!p.ready(),"float threshold not truncated");}check(!p.perform(),"early release denied without award");check(p.tick(false)&&p.ready(),"ceil threshold ready");int paid=0;for(int t=1;t<=charged;t++)if(t<p.capturedChargeTime())paid++;near(s.cp,paidCpAfter(cp,PlasmaCannonSession.tickCp(e),paid),"strict less charge arithmetic");double readyCp=s.cp;for(int i=0;i<100;i++)p.tick(false);near(s.cp,readyCp,"indefinite ready hold is free");check(p.perform(),"ready performs");near(s.exp(p.ID),masteryAfter(e,.008F,1),"release award");check(s.cooldowns.get(p.ID)==PlasmaCannonSession.cooldown(s.exp(p.ID)),"postaward cooldown");check(!p.perform(),"duplicate release denied");for(int tick=0;tick<20;tick++)check(p.syncPosition()==(tick%6==0),"six-tick sync");p.tick(false);check(p.explosions(true,1)==2,"collision plus arrival double explode");check(p.explosions(false,1.5)==0,"strict arrival threshold");for(int t=1;t<240;t++)p.tick(false);check(p.explosions(false,999)==1,"240 tick timeout");}
  double[] from={1,2,3},dest={4,6,3},next=PlasmaCannonSession.move(from,dest);near(next[0],1.6,"unit motion X");near(next[1],2.8,"unit motion Y");check(java.util.Arrays.equals(PlasmaCannonSession.move(from,new double[]{1.5,2,3}),from),"subunit no movement");
  var s=state(PlasmaCannonSession.ID,0);s.cp=17;var p=PlasmaCannonSession.begin(s,false);check(!p.tick(false)&&p.ending()&&!p.perform()&&s.exp(p.ID)==0&&s.cooldowns.isEmpty(),"insufficient charging cancels without award");
  s=state(VecReflectionSession.ID,0);s.cp=299;var r=VecReflectionSession.begin(s,false);check(!r.affect(1,false)&&s.exp(r.ID)==0,"unaffordable entity never redirects or trains");s.cp=Double.NaN;check(!VecReflectionSession.mayStart(s),"nonfinite resources denied");System.out.println("PASS "+checks+" final VecManip state/arithmetic checks");
 }
}
