package cn.academy.port.skill;
import cn.academy.port.*;import cn.academy.port.core.*;import cn.academy.port.develop.*;import cn.academy.port.machine.*;import cn.academy.port.preset.PresetSkills;import java.util.*;
public final class VectorCombatLearningRegressionTest {
 private static int checks;private static void check(boolean ok,String why){checks++;if(!ok)throw new AssertionError(why);}
 public static void main(String[] args){for(String id:List.of("dir_blast","storm_wing","blood_retro")){int level=id.equals("blood_retro")?4:3;String parent=id.equals("dir_blast")?"ground_shock":id.equals("storm_wing")?"vec_accel":"dir_blast";var skill=SkillCatalog.find("vecmanip",id).orElseThrow();check(skill.level()==level&&skill.controllable()&&skill.requirements().equals(List.of(new SkillCatalog.Requirement(parent,0))),"canonical source zeroEXP parent");check(PresetSkills.IMPLEMENTED.contains(id)&&SkillAvailability.learnable(id),"single gameplay/learning registry");var s=ready(level);check(!SkillCatalog.canLearn(s,skill),"missingparent denied");s.learn(parent);check(SkillCatalog.canLearn(s,skill),"learnedzeroEXPparent allowed");check(!DevelopmentActions.canLearn(s,DeveloperType.PORTABLE,skill),"portable tier denied");if(level==4)check(!DevelopmentActions.canLearn(s,DeveloperType.NORMAL,skill),"normal tier deniesLv4");
  for(var type:DeveloperType.values())if(type.supportsSkill(level)){s=ready(level);s.learn(parent);var battery=new Battery(type,type.energy);var p=new DevelopmentProcess();var action=DevelopmentActions.skill(s,skill);int stim=level==3?7:11;check(action.stimulations()==stim,"canonicalstimulation count");p.start(battery,action);int ticks=stim*type.ticksPerStimulation();for(int t=1;t<=ticks;t++){p.tick();if(t<ticks)check(!s.learned(id),"target not granted early");}check(p.state()==DevelopmentProcess.State.DONE&&s.learned(id)&&s.exp(id)==0,"genuine natural learning zeroEXP");check(Math.abs(battery.energy()-(type.energy-type.actualConsumption(stim)))<1E-5,"finite exactIF");s.activated=true;var earned=s;check(s.presets.edit(0,0,id,value->PresetSkills.selectable(earned,value)),"earned selectable");}
  s=ready(level);s.learn(parent);var battery=new Battery(DeveloperType.ADVANCED,39);var p=new DevelopmentProcess();p.start(battery,DevelopmentActions.skill(s,skill));p.tick();check(p.state()==DevelopmentProcess.State.FAILED&&!s.learned(id)&&battery.energy()==39,"finite energyfailure deniesgrant");
  s=ready(level);s.learn(parent);battery=new Battery(DeveloperType.ADVANCED,200000);p=new DevelopmentProcess();p.start(battery,DevelopmentActions.skill(s,skill));int ticks=(level==3?7:11)*16;for(int t=1;t<ticks;t++)p.tick();s.experience.remove(parent);p.tick();check(p.state()==DevelopmentProcess.State.FAILED&&!s.learned(id),"completion revalidates source parent");}
  check(SkillAvailability.learnable("vec_accel")&&SkillAvailability.learnable("vec_deviation")&&SkillAvailability.learnable("ground_shock"),"previous sourcepaths retained");System.out.println("PASS "+checks+" vector combat source learning gates and finite power checks");}
 private static AbilityProgress ready(int l){var s=new AbilityProgress();s.selectCategory("vecmanip");s.setLevel(l);return s;}
 private static final class Battery implements DevelopmentProcess.Developer{final DeveloperType type;final MachineDeveloperEnergy power;Battery(DeveloperType t,double n){type=t;power=new MachineDeveloperEnergy(t,()->{},()->true);power.load(n);}public DeveloperType type(){return type;}public boolean tryPullEnergy(double n){return power.tryPull(n);}public double energy(){return power.energy();}public double maxEnergy(){return type.energy;}}
}
