package cn.academy.port.skill.oracle;
import java.util.*;import java.util.function.Predicate;
/** Minimal world-free1.7/LambdaLib contract stubs solely for executing the unchanged original body. */
public final class BeamOracleSupport {
 private BeamOracleSupport(){}private static final float[] SIN=new float[65536];static{for(int i=0;i<SIN.length;i++)SIN[i]=(float)Math.sin(i*Math.PI*2/65536);}static float sin(float a){return SIN[(int)(a*10430.378F)&65535];}static float cos(float a){return SIN[(int)(a*10430.378F+16384F)&65535];}
 public static final class Vec3 {public double xCoord,yCoord,zCoord;public Vec3(double x,double y,double z){xCoord=x;yCoord=y;zCoord=z;}public Vec3 crossProduct(Vec3 v){return new Vec3(yCoord*v.zCoord-zCoord*v.yCoord,zCoord*v.xCoord-xCoord*v.zCoord,xCoord*v.yCoord-yCoord*v.xCoord);}public double lengthVector(){return Math.sqrt(xCoord*xCoord+yCoord*yCoord+zCoord*zCoord);}public void rotateAroundZ(float a){float c=cos(a),s=sin(a);double x=xCoord*c+yCoord*s,y=yCoord*c-xCoord*s;xCoord=x;yCoord=y;}public void rotateAroundY(float a){float c=cos(a),s=sin(a);double x=xCoord*c+zCoord*s,z=zCoord*c-xCoord*s;xCoord=x;zCoord=z;}}
 public static final class AxisAlignedBB {public double minX,minY,minZ,maxX,maxY,maxZ;static AxisAlignedBB of(double x,double y,double z){var b=new AxisAlignedBB();b.minX=b.maxX=x;b.minY=b.maxY=y;b.minZ=b.maxZ=z;return b;}}
 public static class Entity {public double posX,posY,posZ;public World worldObj;public Entity(World w,double x,double y,double z){worldObj=w;posX=x;posY=y;posZ=z;}public double getDistanceSq(double x,double y,double z){return (posX-x)*(posX-x)+(posY-y)*(posY-y)+(posZ-z)*(posZ-z);}public double getDistanceSqToEntity(Entity e){return getDistanceSq(e.posX,e.posY,e.posZ);}public float getDistanceToEntity(Entity e){return (float)Math.sqrt(getDistanceSqToEntity(e));}}
 public static final class EntityPlayer extends Entity {public double eye=1.6;public float yaw,pitch;public EntityPlayer(World w,double x,double y,double z){super(w,x,y,z);}}
 public static final class Motion3D {Vec3 pos,direction;public Motion3D(EntityPlayer p,boolean head){pos=new Vec3(p.posX,p.posY+p.eye,p.posZ);float yaw=p.yaw/180F*(float)Math.PI,pitch=p.pitch/180F*(float)Math.PI;direction=new Vec3(-sin(yaw)*cos(pitch),-sin(pitch),cos(yaw)*cos(pitch));normalize();}public Motion3D move(double step){pos.xCoord+=direction.xCoord*step;pos.yCoord+=direction.yCoord*step;pos.zCoord+=direction.zCoord*step;return this;}public Motion3D normalize(){double n=direction.lengthVector();direction.xCoord/=n;direction.yCoord/=n;direction.zCoord/=n;return this;}public float getRotationYawRadians(){return -(float)Math.atan2(direction.xCoord,direction.zCoord);}public float getRotationPitchRadians(){return -(float)Math.atan2(direction.yCoord,Math.sqrt(direction.xCoord*direction.xCoord+direction.zCoord*direction.zCoord));}public Vec3 getPosVec(){return pos;}public Vec3 getMotionVec(){return direction;}}
 public static final class VecUtils {public static Vec3 vec(double x,double y,double z){return new Vec3(x,y,z);}public static Vec3 add(Vec3 a,Vec3 b){return vec(a.xCoord+b.xCoord,a.yCoord+b.yCoord,a.zCoord+b.zCoord);}public static Vec3 subtract(Vec3 a,Vec3 b){return vec(a.xCoord-b.xCoord,a.yCoord-b.yCoord,a.zCoord-b.zCoord);}public static Vec3 multiply(Vec3 a,double m){return vec(a.xCoord*m,a.yCoord*m,a.zCoord*m);}}
 public static final class MathUtils {public static final float PI_F=(float)Math.PI;public static float lerpf(float a,float b,float e){return a+(b-a)*e;}}
 public static final class RandUtils {public static double ranged(double a,double b){return a+.5*(b-a);}public static float rangef(float a,float b){return a+.5F*(b-a);}public static int rangei(int a,int b){return a;}}
 public static final class EntitySelectors {public static Predicate<Entity> everything(){return e->true;}public static Predicate<Entity> exclude(Entity e){return target->target!=e;}}
 public static final class WorldUtils {public static AxisAlignedBB minimumBounds(Vec3...p){var b=AxisAlignedBB.of(p[0].xCoord,p[0].yCoord,p[0].zCoord);for(var v:p){b.minX=Math.min(b.minX,v.xCoord);b.minY=Math.min(b.minY,v.yCoord);b.minZ=Math.min(b.minZ,v.zCoord);b.maxX=Math.max(b.maxX,v.xCoord);b.maxY=Math.max(b.maxY,v.yCoord);b.maxZ=Math.max(b.maxZ,v.zCoord);}return b;}public static List<Entity> getEntities(World w,AxisAlignedBB b,Predicate<Entity> filter){return new ArrayList<>(w.entities.stream().filter(e->e.posX>=b.minX&&e.posX<=b.maxX&&e.posY>=b.minY&&e.posY<=b.maxY&&e.posZ>=b.minZ&&e.posZ<=b.maxZ&&filter.test(e)).toList());}}
 public static final class Material {public static final Material air=new Material(),solid=new Material();}
 public static final class Block {public final Sound stepSound=new Sound();public float getBlockHardness(World w,int x,int y,int z){return w.hardness;}public Material getMaterial(){return Material.air;}public void dropBlockAsItemWithChance(World w,int x,int y,int z,int meta,float chance,int fortune){} }
 public static final class Sound {public String getBreakSound(){return "block";}public float getVolume(){return 1;}public float getPitch(){return 1;}}
 public static final class World {public List<Entity> entities=new ArrayList<>();public List<String> probes=new ArrayList<>(),destroyed=new ArrayList<>();public float hardness;public boolean denied,canBreak=true;public Block getBlock(int x,int y,int z){return new Block();}public int getBlockMetadata(int x,int y,int z){return 0;}public void setBlockToAir(int x,int y,int z){destroyed.add(x+","+y+","+z);}public void playSoundEffect(double x,double y,double z,String sound,float vol,float pitch){} }
 public static final class BlockDestroyEvent {final World world;final int x,y,z;public BlockDestroyEvent(EntityPlayer p,int x,int y,int z){world=p.worldObj;this.x=x;this.y=y;this.z=z;}}
 public static final class MinecraftForge {public static final Bus EVENT_BUS=new Bus();public static final class Bus {public boolean post(BlockDestroyEvent e){e.world.probes.add(e.x+","+e.y+","+e.z);return e.world.denied;}}}
 public record Attack(Entity target,float damage){}
 public static final class AbilityContext {public final EntityPlayer player;public final List<Attack> attacks=new ArrayList<>();public Entity reflector;public AbilityContext(EntityPlayer p){player=p;}public boolean canBreakBlock(World w){return w.canBreak;}public void attack(Entity e,float damage){attacks.add(new Attack(e,damage));}public void attackReflect(Entity e,float damage,Runnable reflected){if(e==reflector)reflected.run();else attack(e,damage);}}
 public static final class AbilityPipeline {}
 public enum ForgeDirection {DOWN(0,-1,0),UP(0,1,0),NORTH(0,0,-1),SOUTH(0,0,1),WEST(-1,0,0),EAST(1,0,0),UNKNOWN(0,0,0);public final int offsetX,offsetY,offsetZ;ForgeDirection(int x,int y,int z){offsetX=x;offsetY=y;offsetZ=z;}}
}
