package cn.academy.port.client.terminal;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.net.URLClassLoader;
import javax.tools.ToolProvider;
import java.util.ArrayList;
import java.util.Random;
import static cn.academy.port.client.terminal.TerminalClientFixtures.*;

/** Executes the unchanged classic install class in an independent, game-free compiler harness. */
public final class TerminalClientSourceOracleTest {
    public static void main(String[] args)throws Exception{
        witnesses();try(var oracle=new OriginalTerminalOracle()){
            var sample=oracle.method("cn.academy.terminal.client.InstallProbe","sample",long.class);
                for(long elapsed=0;elapsed<=6000;elapsed++){
                    double[] classic=(double[])sample.invoke(null,elapsed);var port=TerminalTimeline.install(elapsed);
                    equal(classic[0],port.progress(),1e-12,"Original install progress");equal(classic[1],120/255d*port.alpha(),1e-12,"Original texture alpha");equal(classic[2],.1+.9*port.alpha(),1e-12,"Original text minimum alpha");check((classic[3]==1)==port.complete(),"Original completion boundary");check(classic[4]==(port.complete()?1:0)&&classic[5]==classic[4],"Original auto-open and key hint exactly once per disposal frame");
                }
            var clock=new TerminalClock();check(clock.update(100,false)==100,"Source UI clock initial absolute time");check(clock.update(200,false)==200,"Unpaused UI time advances");check(clock.update(1200,true)==200,"Pause freezes source install/FT timers");check(clock.update(3000,true)==200,"Long pause does not time out app");check(clock.update(3100,false)==300,"Resume excludes paused wall interval");check(clock.update(3100,false)==300,"Repeated render in same clock is stable");check(text("GameTimer.java.txt").contains("timeLag = time - storedTime"),"Original pause-time source witness");
            var key=new TerminalTimeline.ReleaseKey();key.replace(false);check(!key.update(true,true),"Hold does not open");check(!key.update(true,true),"Repeat does not open");check(key.update(false,true),"Release opens");check(!key.update(false,true),"Only one release");key.replace(true);check(!key.update(false,false),"Screen-blocked release drained");check(!key.update(false,true),"No deferred screen release");
            var random=new Random(17);for(int i=0;i<10000;i++){int count=random.nextInt(300),scroll=random.nextInt(50),id=random.nextInt(300);long elapsed=random.nextInt(9000);double x=random.nextDouble()*605,y=random.nextDouble()*740;equal(TerminalTimeline.appAlpha(elapsed,id),Math.max(0,Math.min(1,(elapsed-(id+1)*100)/400d)),0,"Source app reveal");check(TerminalTimeline.maxScroll(count)==Math.max(0,(count%3==0?count/3:count/3+1)-3),"Source scroll range");check(TerminalTimeline.selection(x,y)==(int)((y-.01)/740*3)*3+(int)((x-.01)/605*3),"Source virtual cell");check(TerminalTimeline.selectedIndex(scroll,id)==scroll+id,"Preserved source scroll lookup");double from=random.nextDouble()*700,to=random.nextDouble()*700;long dt=random.nextInt(9000);equal(TerminalTimeline.balance(dt,from,to),from+Math.min(3*dt,Math.abs(to-from))*Math.signum(to-from),0,"Source pointer balance");}
            for(int c=0;c<=Character.MAX_VALUE;c++)check(FrequencyTimeline.allowedCharacter((char)c)==(c!=167&&c>=32&&c!=127),"Original chat character predicate");
            check(!FrequencyTimeline.timeout(20000,false)&&FrequencyTimeline.timeout(20001,false),"Original action timeout strict boundary");check(!FrequencyTimeline.timeout(3000,true)&&FrequencyTimeline.timeout(3001,true),"Original transmitting boundary");check(!FrequencyTimeline.returnReady(700)&&FrequencyTimeline.returnReady(701),"Source successful repeated-link delay");check(!FrequencyTimeline.quitReady(1000)&&FrequencyTimeline.quitReady(1001),"Source failure quit delay");
            Object worldA=new Object(),worldB=new Object(),playerA=new Object(),playerB=new Object();var session=new TerminalClientLifecycle.Session();check(session.synchronize(worldA,playerA),"First incoming snapshot establishes session");check(!session.synchronize(worldA,playerA),"Next tick cannot discard first snapshot/effect");check(session.synchronize(worldB,playerA),"World replacement clears previous presentation");check(session.synchronize(worldB,playerB),"Player replacement clears previous presentation");check(session.synchronize(null,null),"Disconnect clears session");check(!session.synchronize(null,null),"Repeated disconnected ticks idempotent");
            var lease=new TerminalClientLifecycle.Lease(worldA,playerA);var disposal=lease.release(worldA,playerA,true);check(disposal.release()&&disposal.notifyServer(),"Miss/quit releases and notifies active server once");check(!lease.release(worldA,playerA,true).release(),"Repeated disposal cannot release twice");var replacement=new TerminalClientLifecycle.Lease(worldA,playerA).release(worldB,playerB,true);check(replacement.release()&&!replacement.notifyServer(),"Old HUD disposal cannot close replacement server session");check(!new TerminalClientLifecycle.Lease(worldA,playerA).release(null,null,false).notifyServer(),"Logout needs no stale server close");
            var replies=new TerminalClientLifecycle.Pending();replies.begin("authorize_node",13,13);check(!replies.accept("authorize_matrix",13,13),"Wrong reply action rejected");check(!replies.accept("authorize_node",14,13),"Wrong target rejected");check(!replies.accept("authorize_node",13,14),"Wrong selected source rejected");check(replies.accept("authorize_node",13,13),"Exact authoritative reply accepted");check(!replies.accept("authorize_node",13,13),"Reply only consumed once");replies.begin("link_node",24,13);replies.clear();check(!replies.accept("link_node",24,13),"Disposed pending link cannot affect replacement");
            var returns=new TerminalCoinReturnLedger();check(returns.claim(1,77),"Local natural-return fallback claims result");check(!returns.claim(1,77),"Later authoritative natural_return packet cannot duplicate result");check(returns.claim(2,77),"Distinct coin owners independent");check(!returns.claim(1,0),"Malformed return token ignored");returns.clear();check(returns.claim(1,77),"Replacement client world has fresh coin ledger");
            String sourceUI=text("TerminalUI.java.txt"),sourceFreq=text("FreqTransmitterUI.java.txt"),sourceSettings=text("SettingsUI.java.txt"),sourceTree=text("SkillTree.scala.txt");
            check(sourceUI.contains("defaultKey = Keyboard.KEY_LMENU")&&sourceUI.contains("public void onKeyUp()"),"Source default/release key witness");check(sourceUI.contains("int lookup = scroll + selection")&&sourceUI.contains("i = scroll * 3"),"Source lookup/layout discrepancy witness");check(sourceUI.indexOf("lastFrameTime = time")==sourceUI.lastIndexOf("lastFrameTime = time"),"Source uses an initial fixed pointer time origin");
            for(String channel:new String[]{"Syncs.querySSID","Syncs.authorizeMatrix","Syncs.authorizeNode","Syncs.linkNodeToMatrix","Syncs.linkUserToNode"})check(sourceFreq.contains(channel),"Source genuine graph ingress "+channel);
            check(sourceFreq.contains("Raytrace.traceLiving(player, 4, EntitySelectors.nothing())"),"Source raycast4");check(sourceSettings.contains("\"attackPlayer\", true, true")&&sourceSettings.contains("\"headsOrTails\", false, false"),"Source settings visibility/default witness");check(sourceTree.contains("ret.getGui.addWidget(Common.initialize())")&&sourceTree.contains("panel.transform.doesDraw = false"),"Source SkillTree app developer=null");
            System.out.println("PASS TerminalClientSourceOracleTest "+assertions+" assertions; unchanged original install source executed; no Minecraft launch");
        }
    }
}
