package cn.academy.port.client.terminal;
import com.google.gson.JsonParser;
import java.nio.file.Files;
import static cn.academy.port.client.terminal.TerminalClientFixtures.*;
public final class TerminalClientIntegrationTest {
    public static void main(String[] args)throws Exception{
        witnesses();for(var entry:JsonParser.parseString(text("asset-manifest.json")).getAsJsonArray()){var e=entry.getAsJsonObject();String resource=e.get("resource").getAsString();try(var stream=TerminalClientIntegrationTest.class.getResourceAsStream("/"+resource)){check(stream!=null,"Packaged safe UI asset "+resource);check(sha(stream.readAllBytes()).equals(e.get("sha256").getAsString()),"Source UI asset integrity "+resource);}check(sha(Files.readAllBytes(root().resolve("src/main/resources/"+resource))).equals(e.get("sha256").getAsString()),"Promoted source asset binding "+resource);}
        String client=production("src/main/java/cn/academy/port/client/terminal/TerminalClient.java"),hud=production("src/main/java/cn/academy/port/client/terminal/TerminalHud.java"),freq=production("src/main/java/cn/academy/port/client/terminal/FrequencyTransmitter.java"),bridge=production("src/main/java/cn/academy/port/client/AcademyClient.java"),dev=production("src/main/java/cn/academy/port/client/ClassicDeveloperScreen.java"),config=production("src/main/java/cn/academy/port/ClassicHudConfig.java");
        for(String kind:new String[]{"terminal_state","terminal_installed","terminal_app_installed","terminal_install_effect","terminal_open","terminal_app","terminal_frequency"})check(bridge.contains('"'+kind+'"'),"Actual production wire callback "+kind);
        check(client.contains("public static void receive(CompoundTag data){\n        session();"),"Session replacement occurs before first snapshot/effect decode");check(client.contains("case \"terminal_app\" -> {receive(TerminalStorage.decode(data),\"\");activate"),"App receives authoritative state before activation");check(client.contains("GLFW.GLFW_KEY_LEFT_ALT")&&client.contains("KEY.update(physicalDown(),allowed)"),"Source default release-open ingress");check(client.contains("event.getAction()==GLFW.GLFW_RELEASE)terminal.click()"),"Source release-click app activation");check(client.contains("TerminalNetwork.requestApp(app)"),"Every app uses genuine installed sender authorization");check(!client.contains("TutorialClient.open()"),"Tutorial launch uses authorized common terminal route and first-open snapshot");check(client.contains("new ClassicDeveloperScreen(true)"),"Source no-developer SkillTree app view");
        check(client.contains("key.getType()==com.mojang.blaze3d.platform.InputConstants.Type.KEYSYM")&&client.contains("return OPEN.isDown();"),"Scan-code bindings retain native mapping state instead of treating scan codes as key symbols");
        check(dev.contains("if(!skillTreeApp)drawMachine")&&dev.contains("if(skillTreeApp)return;"),"Source read-only app hides machine/learning controls");check(dev.contains("if(!skillTreeApp&&state.hasCategory()&&state.canLevelUp"),"App cannot become developer upgrade proxy");check(dev.contains("if(skillTreeApp){console.output"),"No-category/reset app commands cannot send development");
        check(hud.contains("perspective((float)Math.toRadians(50)")&&hud.contains(".35f*aspect,1.2f,-4")&&hud.contains("scale(1/310f,-1/310f,1/310f)"),"Original perspective world HUD");check(hud.contains("isSelected?40:10")&&hud.contains("terminal.select"),"Source selected app projection and audio");
        check(freq.contains("mc.player.pick(4,1,false)")&&freq.contains("TerminalNetwork.requestFrequency"),"Real4-block world raycast/graph wire");check(freq.contains("replies.accept(action,target.asLong(),source.asLong())"),"Stale frequency replies ignored");check(freq.contains("if(!disposal.release())return;closed=true;"),"Repeated/miss disposal releases exactly once even when closed already");check(freq.contains("lease.release(mc.level,mc.player,mc.getConnection()!=null)")&&freq.contains("TerminalNetwork.requestClose()"),"Server authorization closed once only in its original live session");check(freq.contains("entered=linkCreated"),"Repeated-link source20-second origin retained");check(freq.contains("pending=\"\";replies.clear();state(Mode.QUIT,key)"),"Timeout quit invalidates every late response");check(freq.contains("if(transmitting)return;"),"Repeated start clicks cannot race duplicate matrix queries");
        check(config.contains("HEADS_OR_TAILS")&&config.contains("define(\"headsOrTails\",false)"),"Actual false-default coin setting");String coins=production("src/main/java/cn/academy/port/client/ClassicCoinEffects.java");check(coins.contains("if(finished)announceReturn(entry.getKey(),coin.token)")&&coins.contains("tag.getBoolean(\"natural_return\")")&&coins.contains("HEADS_OR_TAILS.get()"),"Natural-return-only local source coin result");String settings=production("src/main/java/cn/academy/port/client/terminal/TerminalSettingsScreen.java");check(settings.contains("minecraft.isLocalServer()")&&settings.contains("AcademyConfig.ATTACK_PLAYERS.set(value)")&&settings.contains("KeyMapping.resetMapping()")&&settings.contains("minecraft.options.save()"),"Actual config/key setting persistence");
        for(String language:new String[]{"en_us","zh_cn","zh_tw","ja_jp"}){var json=JsonParser.parseString(production("src/main/resources/assets/academy/lang/"+language+".json")).getAsJsonObject();check(json.get("item.academy.terminal_installer").equals(json.get("item.ac_terminal_installer.name")),"Classic installer translation alias "+language);for(String app:new String[]{"skill_tree","freq_transmitter","media_player"})check(json.get("item.academy.app_"+app).equals(json.get("item.ac_apps.name")),"Source generic app installer name "+language+app);}
        check(production("src/main/java/cn/academy/port/client/ClassicTerminalDrawing.java").contains("ClassicHudShaders.font"),"Source alpha-test-disabled terminal texture/fill pipeline");
        System.out.println("PASS TerminalClientIntegrationTest "+assertions+" assertions; source/resource/wire bindings only, no live acceptance claim");
    }
}
