/* Shared source consumption/config compatibility and callback tests. GPLv3; see NOTICE. */
package cn.academy.port.core;
import java.util.*;
import java.util.concurrent.atomic.*;
import cn.academy.port.skill.*;
public final class SharedSkillConsumptionRegressionTest {
    private static long checks;
    private static void check(boolean result,String reason){checks++;if(!result)throw new AssertionError(reason);}
    private static void same(double actual,double expected,String reason){check(Double.doubleToLongBits(actual)==Double.doubleToLongBits(expected),reason+" actual="+actual+" expected="+expected);}
    private static void near(double actual,double expected,String reason){check(Math.abs(actual-expected)<1E-7,reason+" actual="+actual+" expected="+expected);}
    private static AbilityProgress state(String category,String id){var state=new AbilityProgress();state.selectCategory(category);state.setLevel(5);state.learn(id);state.activated=true;return state;}
    private static AbilityProgress configuredState(String category,String id,SkillConsumption.Config config){var s=new AbilityProgress();bind(s,config,e->{});s.selectCategory(category);s.setLevel(5);s.learn(id);s.activated=true;return s;}
    private static void bind(AbilityProgress s,SkillConsumption.Config config,SkillConsumption.Mutation event){s.bindConsumption(()->config,event,()->{},()->true);}
    public static void main(String[] arguments){
        // Default numeric acceptance is checked bit-exactly against unchanged upstream by ClassicNumericLedgersSourceOracleTest.
        var s=state("electromaster","arc_gen");s.cp=1;var events=new AtomicInteger();bind(s,SkillConsumption.Config.DEFAULT,e->{events.incrementAndGet();check(e.cp==100,"event precedes insufficient CP");});
        check(!s.consumeSkill("arc_gen",100,20,false)&&events.get()==1&&s.cpDelay==0&&s.extraCp==0,"failure dispatches once but does not debit/train");
        bind(s,SkillConsumption.Config.DEFAULT,e->{e.cp=0;e.overload=2;});check(s.consumeSkill("arc_gen",100,20,false),"event can make action affordable");same(s.cp,1,"zero mutated cost");same(s.overload,2,"mutated O");check(s.cpDelay==15&&s.overloadDelay==32,"zero cost still sets both delays");
        s=state("vecmanip","vec_deviation");s.cp=2;var forced=s;bind(s,SkillConsumption.Config.DEFAULT,e->{check(e.force&&!e.creative,"force keeps actual creative flag");e.cp=120;e.overload=7;});check(s.consumeWithForceSkill("vec_deviation",15,0,false),"force succeeds beyond available CP");same(s.cp,0,"force floors resource");near(s.extraCp,120*.0025f,"force trains full mutation");near(s.extraOverload,7*.0058f,"force trains mutated O");
        s=state("vecmanip","vec_reflection");s.cp=1;s.cpDelay=4;s.overloadDelay=6;bind(s,SkillConsumption.Config.DEFAULT,e->{check(e.creative&&!e.force,"creative normal metadata");e.cp=80;e.overload=1000;});check(s.consumeSkill("vec_reflection",500,1,true),"creative success");same(s.cp,1,"creative resource unchanged");same(s.overload,0,"creative O unchanged");check(s.cpDelay==4&&s.overloadDelay==6,"creative delays unchanged");near(s.extraCp,.2,"creative training still occurs");near(s.extraOverload,1000*.0058f,"creative O training from event");
        s=state("electromaster","arc_gen");s.cp=1;var creativeFlag=new AtomicBoolean(false);bind(s,SkillConsumption.Config.DEFAULT,e->creativeFlag.set(true));s.bindCreativeMode(requested->creativeFlag.get());check(s.consumeSkill("arc_gen",100,20,false),"live creative flag read after mutation");same(s.cp,1,"event creative switch skips drain");same(s.overload,0,"event creative switch skips O");near(s.extraCp,.25,"event creative switch still trains");
        s=state("electromaster","arc_gen");s.cp=1;creativeFlag.set(true);bind(s,SkillConsumption.Config.DEFAULT,e->creativeFlag.set(false));s.bindCreativeMode(requested->creativeFlag.get());check(!s.consumeSkill("arc_gen",100,20,true)&&s.cp==1&&s.extraCp==0,"creative removed inside event restores normal insufficient-CP branch");
        s=state("electromaster","arc_gen");var overloadState=s;var order=new ArrayList<String>();s.bindConsumption(()->SkillConsumption.Config.DEFAULT,e->order.add("cost"),()->{order.add("overload");check(overloadState.overloadFine,"overload handler sees old fine flag");same(overloadState.cp,7988,"overload handler sees debit");check(overloadState.cpDelay==15&&overloadState.overloadDelay==32,"overload handler sees delays");same(overloadState.extraCp,0,"overload handler before CP training");same(overloadState.extraOverload,0,"overload handler before O training");},()->true);
        check(s.consumeSkill("arc_gen",12,500,false),"overload cap success");check(order.equals(List.of("cost","overload"))&&!s.overloadFine,"overload synchronous order");near(s.extraCp,.03,"CP trains after overload callback");near(s.extraOverload,500*.0058f,"O trains after overload callback");same(s.overload,500,"resource uses pre-training cap");check(s.maxOverload()>s.overload,"training raises cap after overload lock");
        s=state("teleporter","mark_teleport");var reentrant=s;var inside=new AtomicBoolean();var sequence=new ArrayList<String>();bind(s,SkillConsumption.Config.DEFAULT,e->{if(inside.compareAndSet(false,true)){sequence.add("outer event");check(reentrant.consumptionInProgress()&&!reentrant.canUse("mark_teleport"),"wire admission fenced during callback");check(reentrant.consumeSkill("mark_teleport",10,1,false),"direct core nested consume retains source semantics");sequence.add("nested returned");}else sequence.add("inner event");});check(s.consumeSkill("mark_teleport",100,5,false),"outer completes after nested");check(sequence.equals(List.of("outer event","inner event","nested returned")),"nested source order");same(s.cp,7890,"nested then outer CP");near(s.extraCp,.275,"nested then outer training");check(!s.consumptionInProgress()&&s.canUse("mark_teleport"),"admission restored after callback");
        s=state("meltdowner","jet_engine");var discarded=new AtomicBoolean();bind(s,SkillConsumption.Config.DEFAULT,e->discarded.set(true));check(!s.consumeSkill("jet_engine",20,40,false,()->!discarded.get()),"explicit lifecycle callback fence");same(s.cp,8000,"disposed operation never debits");same(s.extraCp,0,"disposed operation never trains");
        s=state("teleporter","shift_tp");var allowed=new AtomicBoolean(true);var protectionEvents=new AtomicInteger();bind(s,SkillConsumption.Config.DEFAULT,e->{protectionEvents.incrementAndGet();allowed.set(false);});check(!s.consumeSkill("shift_tp",260,40,false,allowed::get),"permission changed in callback denies placement cost");same(s.cp,8000,"revoked protection no CP debit");same(s.overload,0,"revoked protection no overload");check(protectionEvents.get()==1,"protection recheck does not redispatch event");
        s=state("electromaster","arc_gen");var revoked=s;bind(s,SkillConsumption.Config.DEFAULT,e->revoked.selectCategory("teleporter"));check(!s.consumeSkill("arc_gen",20,2,false),"category callback invalidates operation");same(s.extraCp,0,"revoked category does not train stale skill");
        s=state("electromaster","arc_gen");bind(s,SkillConsumption.Config.DEFAULT,e->{throw new IllegalArgumentException("listener");});boolean thrown=false;try{s.consumeSkill("arc_gen",1,1,false);}catch(IllegalArgumentException expected){thrown=true;}check(thrown&&!s.consumptionInProgress()&&s.cp==8000,"listener exception propagates and clears admission fence");
        for(float invalid:new float[]{-1,Float.NaN,Float.POSITIVE_INFINITY}){s=state("electromaster","arc_gen");float value=invalid;bind(s,SkillConsumption.Config.DEFAULT,e->e.cp=value);check(!s.consumeSkill("arc_gen",20,2,false)&&s.cp==8000&&s.extraCp==0,"unsafe cost mutation rejected");}
        configContracts();sessionMutationContracts();System.out.println("PASS "+checks+" shared consumption/default/config/mutation/force/creative/protection/reentry assertions");
    }
    private static void configContracts(){
        var options=SkillConsumption.Config.parseOptions(List.of("teleporter.flashing.damage_scale=2","teleporter.flashing.cp_consume_speed=99","teleporter.flashing.overload_consume_speed=0","teleporter.flashing.exp_incr_speed=50"));var config=SkillConsumption.Config.DEFAULT.withOptions(options);var s=state("teleporter","flashing");var request=new ArrayList<SkillConsumption.Request>();bind(s,config,request::add);check(s.canPerform(5000,false)&&request.isEmpty(),"raw precheck ignores scale and event");check(s.consumeSkill("flashing",100,20,false),"configured normal consume");check(request.get(0).cp==200&&request.get(0).overload==40,"canonical optional getter bug, scale before event");same(s.cp,7800,"source damage_scale selected for CP");same(s.overload,40,"source damage_scale selected for O");s.addExperience("flashing",.01);same(s.exp("flashing"),.01f,"documented exp_incr_speed ignored");check(s.consumeWithForceSkill("flashing",10,1,false),"configured force");check(request.get(1).cp==10&&request.get(1).overload==1,"force bypasses skill scales");
        options=new HashMap<>(options);options.put("teleporter.flashing.overload_incr_speed",500D);config=SkillConsumption.Config.DEFAULT.withOptions(options);s=state("teleporter","flashing");bind(s,config,e->{});s.addExperience("flashing",.01F);near(s.exp("flashing"),2*.01F,"actual EXP key also reads damage_scale");
        config=SkillConsumption.Config.DEFAULT.withOptions(Map.of("electromaster.arc_gen.damage_scale",2D));s=state("electromaster","arc_gen");bind(s,config,e->{});s.consumeSkill("arc_gen",10,3,false);same(s.cp,7980,"canonical Arc defaults contain CP/O keys");same(s.overload,6,"Arc default presence inherited");same(config.damage("electromaster","arc_gen",7),14,"skill damage multiplier");
        config=SkillConsumption.Config.DEFAULT.withOptions(Map.of("teleporter.flashing.cp_consume_speed",2D));s=state("teleporter","flashing");bind(s,config,e->{});boolean missing=false;try{s.consumeSkill("flashing",1,1,false);}catch(IllegalStateException expected){missing=true;}check(missing&&s.cp==8000,"present optional path without damage_scale fails like source");
        double[] cpBase={1800,1800,2800,4000,5800,10000},oBase={100,100,150,240,350,800},cpCap={0,900,1000,1500,1700,50},oCap={0,40,70,80,100,30};config=new SkillConsumption.Config(4,7,.5,.1,2,3,4,cpBase,oBase,cpCap,oCap,Map.of(),Map.of("teleporter",2D));s=configuredState("teleporter","flashing",config);s.cp=s.maxCp();check(s.consumeSkill("flashing",200,500,false),"custom classic data consume");check(s.cpDelay==4&&s.overloadDelay==7,"configured delays");same(s.extraCp,50,"configured training CP cap");same(s.extraOverload,10,"per-call O increment cap10");same(s.maxCp(),10050,"configured CP base/cap");same(s.maxOverload(),810,"configured O base/cap");s.addExperience("flashing",.01F);near(s.levelExperience,.01F*2*4,"category and global progress float multiplication order");cpBase[5]=1;cpCap[5]=1;s.cp=s.maxCp();same(s.maxCp(),10050,"configuration defensively clones arrays");
        config=new SkillConsumption.Config(15,32,.0025,.0058,1,1,3,ClassicRules.BASE_CP,ClassicRules.BASE_OVERLOAD,ClassicRules.EXTRA_CP_CAP,ClassicRules.EXTRA_OVERLOAD_CAP,Map.of("teleporter.dim_folding_theorem.damage_scale",5D,"teleporter.dim_folding_theorem.overload_incr_speed",99D,"teleporter.space_fluct.damage_scale",7D,"teleporter.space_fluct.overload_incr_speed",99D),Map.of("teleporter",2D));s=state("teleporter","threatening_teleport");bind(s,config,e->{});ThreateningTeleport.recordCritical(s,0);same(s.exp("dim_folding_theorem"),(double).005f,"raw passive award bypasses per-skill EXP scale");same(s.exp("space_fluct"),(double).0001f,"raw second passive also bypasses scale");near(s.levelExperience,.005F*2*3+.0001F*2*3,"raw passive award still uses global/category progress");
        config=new SkillConsumption.Config(15,32,.0025,.0058,1,1,1,new double[]{1800,1800,2800,4000,5800,10000},ClassicRules.BASE_OVERLOAD,ClassicRules.EXTRA_CP_CAP,ClassicRules.EXTRA_OVERLOAD_CAP,Map.of(),Map.of());s=configuredState("meltdowner","rad_intensify",config);s.setLevel(4);near(s.exp("rad_intensify"),.58,"source radiation displayed mastery uses configured level-five CP");
        int bad=0;for(var values:List.of(List.of("oops"),List.of("teleporter.flashing.cp_consume_speed=NaN"),List.of("teleporter.flashing.cp_consume_speed=1","teleporter.flashing.cp_consume_speed=2"))){try{SkillConsumption.Config.parseOptions(values);}catch(IllegalArgumentException expected){bad++;}}check(bad==3,"invalid/duplicate overrides rejected");
    }
    private static void sessionMutationContracts(){
        var s=state("vecmanip",VecDeviationSession.ID);var deviation=VecDeviationSession.begin(s,false);bind(s,SkillConsumption.Config.DEFAULT,e->{check(e.force&&!e.creative,"deviation force metadata fixed");e.cp=99;});double before=s.cp;deviation.affect(1,false);same(s.cp,before-99,"deviation honors force event cost once");near(s.extraCp,99*.0025f,"deviation full forced training");
        s=state("vecmanip",VecReflectionSession.ID);var reflection=VecReflectionSession.begin(s,false);bind(s,SkillConsumption.Config.DEFAULT,e->{check(e.force&&!e.creative,"reflection force metadata fixed");e.cp=7;});before=s.cp;check(reflection.damage(10,false,false).performed(),"reflection force succeeds");same(s.cp,before-7,"reflection honors force event once");
        s=state("meltdowner",JetEngineSession.ID);var jet=JetEngineSession.begin(s);var entered=new AtomicBoolean();var nested=new AtomicBoolean(true);var initialJet=jet;bind(s,SkillConsumption.Config.DEFAULT,e->{if(entered.compareAndSet(false,true))nested.set(initialJet.release(false));});check(jet.release(false)&&!nested.get(),"JetEngine nested release denied");same(s.cp,7940,"JetEngine one source-swapped debit");
        s=state("meltdowner",JetEngineSession.ID);jet=JetEngineSession.begin(s);var disposedJet=jet;bind(s,SkillConsumption.Config.DEFAULT,e->disposedJet.discard());check(!jet.release(false)&&s.cp==8000&&s.extraCp==0,"JetEngine disposal denies debit and flight");
        s=state("vecmanip",VecReflectionSession.ID);reflection=VecReflectionSession.begin(s,false);var disposedReflection=reflection;bind(s,SkillConsumption.Config.DEFAULT,e->disposedReflection.discard());check(!reflection.affect(1,false)&&s.cp==8000,"reflection disposal denies entity debit/award");
        s=state("meltdowner",ElectronMissileSession.ID);var missile=ElectronMissileSession.begin(s,false);missile.tick(false);double cp=s.cp;var disposedMissile=missile;bind(s,SkillConsumption.Config.DEFAULT,e->disposedMissile.discard());check(!missile.debitAttack(false)&&s.cp==cp,"missile disposed callback denies attack before cleared ball use");
        s=state("teleporter",TeleporterProgressionRules.MARK);bind(s,SkillConsumption.Config.DEFAULT,e->{check(e.force&&e.skill.equals("mark_teleport"),"teleport helper real force identity");e.cp=500;});s.cp=1;check(TeleporterProgressionRules.consumeWithForce(s,TeleporterProgressionRules.MARK,20,2,false)&&s.cp==0,"teleport helper honors mutated force overshoot");near(s.extraCp,1.25,"teleport helper full mutated force training");
    }
}
