package cn.academy.port.client.terminal.media;

import java.awt.image.BufferedImage;
import java.io.*;
import java.nio.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import javax.imageio.ImageIO;

/** Exact independent source boundary checks plus finite local-file/transport tests. Does not run native audio or Minecraft. */
public final class MediaRegressionTest {
    private static int checks;
    public static void main(String[]args)throws Exception{MediaSourceFixtures.verifyAll();sourceBoundaries();elementOracle();filesAndSettings();transport();queueTiming();System.out.println("PASS media source/resources, unchanged ElementList differential, local-file/settings, transport cancellation and queue timing: "+checks+" checks; native audio not launched");}
    private static void eq(Object got,Object expected){checks++;if(!Objects.equals(got,expected))throw new AssertionError("Expected "+expected+" got "+got);}
    private static void near(double got,double expected){checks++;if(Math.abs(got-expected)>1e-8)throw new AssertionError("Expected "+expected+" got "+got);}
    private static void yes(boolean value){eq(value,true);}
    private static void sourceBoundaries()throws Exception{
        String manager=MediaSourceFixtures.text("academy/MediaManager.scala"),backend=MediaSourceFixtures.text("academy/MediaBackend.scala"),gui=MediaSourceFixtures.text("academy/MediaGui.scala"),acquire=MediaSourceFixtures.text("academy/MediaAcquireData.scala"),app=MediaSourceFixtures.text("academy/MediaApp.scala");
        yes(manager.contains(".filter(_.getName.endsWith(\".ogg\"))"));yes(manager.contains("sound.getName.takeWhile(_ != '.')"));yes(manager.contains("id + \"_name\", id"));yes(manager.contains("id + \"_desc\", id"));yes(acquire.contains("media.external || bitset.get"));yes(gui.contains("override def doesGuiPauseGame(): Boolean = false"));yes(gui.contains("time - lastTest > 500"));yes(gui.contains("backend.lastPlayed match"));yes(backend.contains("val totalSecs = secs.toInt"));yes(backend.contains("val minutes = totalSecs / 60"));yes(backend.contains("val seconds = totalSecs % 60"));yes(app.contains("new MediaGui"));
        double[] times={0,.99,1,9.999,10,59.99,60,61.9,599,600,3599,3600,5999,6000};String[] expected={"00:00","00:00","00:01","00:09","00:10","00:59","01:00","01:01","09:59","10:00","59:59","60:00","99:59","100:00"};for(int i=0;i<times.length;i++)eq(MediaPlayback.displayTime(times[i]),expected[i]);
        for(String[]pair:new String[][]{{"track.ogg","track"},{"track.alt.ogg","track"},{"Mixed Case.ogg","Mixed Case"},{"日本語.ogg","日本語"},{".ogg",""}})eq(MediaFiles.classicId(pair[0]),pair[1]);
        var layout=MediaLayout.main();near(layout.element("back").box().width(),650);near(layout.element("back").box().height(),504);near(layout.element("back").box().scale(),.32);eq(MediaLayout.visibleRows(),5);
        var title=layout.box("back/title",650,504);near(title.x(),324.4212962962962);near(title.y(),77.81148148148147);var volume=layout.box("back/volume_back",650,504);near(volume.width()*volume.scale(),128);near(layout.box("back/t_one/time",554,60).x(),478);near(layout.box("back/t_one/time",554,60).y(),15);
        var hud=MediaLayout.hud().box("base",427,240);near(hud.x(),276);near(hud.y(),198);near(MediaLayout.hud().element("base/progress").box().height(),1.5);
    }
    private static void elementOracle()throws Exception{for(int count:new int[]{0,1,4,5,6,7,9,10,17,32,64})try(var oracle=new ClassicElementListOracle(count)){eq(MediaLayout.maxScroll(count),oracle.max());for(int request:new int[]{-10,0,1,2,5,12,100}){int first=Math.max(0,Math.min(MediaLayout.maxScroll(count),request));eq(oracle.progress(request),first);List<Integer>expected=new ArrayList<>();for(int row=first;row<Math.min(count,first+MediaLayout.visibleRows());row++)expected.add(row);eq(oracle.visible(),expected);}}}
    private static void filesAndSettings()throws Exception{
        Path work=Files.createTempDirectory("academy-media-boundary-");try{
            Path root=work.resolve("acmedia"),source=root.resolve("source"),cover=root.resolve("cover");Files.createDirectories(source);Files.createDirectories(cover);Files.writeString(root.resolve("README.txt"),"User readme stays");
            byte[]good=framedVorbis(48000,2,240000,0,true);Files.write(source.resolve("own.first.ogg"),good);Files.write(source.resolve("own.second.ogg"),good);Files.write(source.resolve("UPPER.OGG"),good);Files.write(source.resolve(".ogg"),good);Files.write(source.resolve("broken.ogg"),new byte[]{1,2,3});
            var info=MediaFiles.inspectVorbis(source.resolve("own.first.ogg"));eq(info.sampleRate(),48000);eq(info.channels(),2);eq(info.samples(),240000L);near(info.seconds(),5);
            ImageIO.write(new BufferedImage(20,20,BufferedImage.TYPE_INT_ARGB),"png",cover.resolve("own.png").toFile());var scan=MediaFiles.scan(work);eq(scan.tracks().size(),1);eq(scan.tracks().getFirst().id(),"own");yes(scan.tracks().getFirst().cover()!=null);eq(scan.warnings().size(),3);eq(Files.readString(root.resolve("README.txt")),"User readme stays");
            byte[]corrupt=good.clone();corrupt[corrupt.length-1]^=1;Files.write(source.resolve("badcrc.ogg"),corrupt);expectIo(()->MediaFiles.inspectVorbis(source.resolve("badcrc.ogg")));
            Files.write(source.resolve("seq.ogg"),framedVorbis(48000,2,240000,3,true));expectIo(()->MediaFiles.inspectVorbis(source.resolve("seq.ogg")));
            Files.write(source.resolve("noend.ogg"),framedVorbis(48000,2,240000,0,false));expectIo(()->MediaFiles.inspectVorbis(source.resolve("noend.ogg")));
            Files.write(source.resolve("multi.ogg"),concat(good,good));expectIo(()->MediaFiles.inspectVorbis(source.resolve("multi.ogg")));
            Files.write(source.resolve("surround.ogg"),framedVorbis(48000,6,240000,0,true));expectIo(()->MediaFiles.inspectVorbis(source.resolve("surround.ogg")));
            MediaFiles.requireSource(source.resolve("own.first.ogg"));expectIo(()->MediaFiles.requireSource(work.resolve("outside.ogg")));Files.createSymbolicLink(source.resolve("linked.ogg"),source.resolve("own.first.ogg"));yes(MediaFiles.scan(work).warnings().stream().anyMatch(s->s.contains("linked.ogg")));
            Files.delete(cover.resolve("own.png"));Files.createSymbolicLink(cover.resolve("own.png"),work.resolve("outside.png"));eq(MediaFiles.scan(work).tracks().getFirst().cover(),null);
            Files.delete(cover.resolve("own.png"));ImageIO.write(new BufferedImage(2049,1,BufferedImage.TYPE_INT_ARGB),"png",cover.resolve("own.png").toFile());eq(MediaFiles.safeCover(cover.resolve("own.png")),false);
            var settings=new MediaSettings(work);eq(settings.name("own"),"own");eq(settings.description("own"),"own");near(settings.volume(),1);settings.name("own","自分の音楽\nName");settings.description("own","A user-provided sound");settings.volume(.375f);var reload=new MediaSettings(work);eq(reload.name("own"),"自分の音楽\nName");eq(reload.description("own"),"A user-provided sound");near(reload.volume(),.375);settings.volume(-4);near(settings.volume(),0);settings.volume(7);near(settings.volume(),1);settings.volume(Float.NaN);near(settings.volume(),1);
            expectIo(()->settings.name("own","x".repeat(2049)));eq(settings.name("own"),"自分の音楽\nName");Files.delete(root.resolve("metadata.properties"));Path external=work.resolve("outside.properties");Files.writeString(external,"secret=user");Files.createSymbolicLink(root.resolve("metadata.properties"),external);expectIo(()->new MediaSettings(work));expectIo(()->settings.description("own","blocked"));eq(Files.readString(external),"secret=user");
            Files.move(source,root.resolve("saved-source"));Files.createSymbolicLink(source,root.resolve("saved-source"));expectIo(()->MediaFiles.requireSource(source.resolve("own.first.ogg")));expectIo(()->MediaFiles.scan(work));Files.delete(source);Files.move(root.resolve("saved-source"),source);
            // Framing fixtures contain an identification packet and terminal granule only, not a real Vorbis song.
        }finally{try(var all=Files.walk(work)){for(Path p:all.sorted(Comparator.reverseOrder()).toList())Files.delete(p);}}
    }
    private static void transport(){var a=new MediaFiles.Track("a",Path.of("a.ogg"),null,120);var b=new MediaFiles.Track("b",Path.of("b.ogg"),null,90);var p=new MediaPlayback();eq(p.current(),null);eq(p.last(),null);long old=p.request(a);yes(p.loading());p.pause();p.started(old);yes(p.current().paused());p.resume();p.observe(old,true,false,12.5);near(p.current().seconds(),12.5);eq(p.current().displayTime(),"00:12");near(p.current().progress(),12.5/120);p.pause();p.observe(old,false,false,12.5);yes(p.current().paused());p.stop();eq(p.current(),null);eq(p.last(),a);eq(p.accepts(old),false);p.started(old);eq(p.current(),null);long token=p.request(b);p.started(token);p.observe(old,true,false,60);eq(p.current().media(),b);near(p.current().seconds(),0);p.observe(token,true,false,200);near(p.current().progress(),1);p.observe(token,false,true,0);eq(p.current(),null);eq(p.last(),b);long failure=p.request(a);p.failed(failure);eq(p.current(),null);eq(p.accepts(failure),false);eq(p.last(),a);p.reset();eq(p.last(),null);eq(p.current(),null);eq(p.accepts(failure),false);
        Random random=new Random(107);for(int i=0;i<10000;i++){long previous=p.request(random.nextBoolean()?a:b);p.stop();long current=p.request(a);p.started(previous);eq(p.current(),null);p.started(current);p.observe(previous,false,true,10);eq(p.current().media(),a);p.pause();p.resume();eq(p.current().paused(),false);p.observe(current,true,false,random.nextDouble()*120);yes(p.current().seconds()>=0&&p.current().seconds()<=120);}}
    private static void queueTiming(){var q=new MediaQueueTiming();q.queued(48000*4,4,48000);q.queued(48000*4+2048,4,48000);q.queued(24000*4,4,48000);q.queued(0,4,48000);near(q.seconds(4,.4),.4);near(q.seconds(2,.1),2+2048d/4/48000+.1);q.synchronize(1);near(q.seconds(1,0),2.5+2048d/4/48000);q.queued(48000*4,4,48000);near(q.seconds(2,.5),3+2048d/4/48000);near(q.seconds(0,0),3.5+2048d/4/48000);}
    @FunctionalInterface private interface Throwing{void run()throws Exception;}
    private static void expectIo(Throwing action)throws Exception{try{action.run();throw new AssertionError("Expected IOException");}catch(IOException expected){checks++;}}
    private static byte[]framedVorbis(int rate,int channels,long samples,int sequenceGap,boolean eos)throws IOException{byte[]ident=new byte[30];ident[0]=1;System.arraycopy("vorbis".getBytes(StandardCharsets.US_ASCII),0,ident,1,6);ident[11]=(byte)channels;ByteBuffer.wrap(ident).order(ByteOrder.LITTLE_ENDIAN).putInt(12,rate);ident[28]=(byte)0xb8;ident[29]=1;return concat(page(2,0,0,ident),page(eos?4:0,samples,1+sequenceGap,new byte[]{0}));}
    private static byte[]page(int flags,long granule,int sequence,byte[]body)throws IOException{byte[]out=new byte[28+body.length];ByteBuffer h=ByteBuffer.wrap(out).order(ByteOrder.LITTLE_ENDIAN);h.put("OggS".getBytes(StandardCharsets.US_ASCII)).put((byte)0).put((byte)flags).putLong(granule).putInt(107).putInt(sequence).putInt(0).put((byte)1).put((byte)body.length).put(body);int[]table=new int[256];for(int i=0;i<256;i++){int v=i<<24;for(int bit=0;bit<8;bit++)v=(v&0x80000000)!=0?(v<<1)^0x04c11db7:v<<1;table[i]=v;}int crc=0;for(byte b:out)crc=(crc<<8)^table[((crc>>>24)^(b&255))&255];h.putInt(22,crc);return out;}
    private static byte[]concat(byte[]a,byte[]b){byte[]out=Arrays.copyOf(a,a.length+b.length);System.arraycopy(b,0,out,a.length,b.length);return out;}
}
