package cn.academy.port.wind;
import com.google.gson.JsonParser;
import java.nio.file.*;
/** Exact source native recipe identities and actual assembled mod/API/permission bindings. */
public final class ClassicWindDataRegressionTest {
    private static int checks;private static void check(boolean value,String label){checks++;if(!value)throw new AssertionError(label);}
    private static String source(Path root,String path)throws Exception{return Files.readString(root.resolve(path));}
    public static void main(String[] args)throws Exception{Path root=Path.of(System.getProperty("academy.wind.stage","."));String[] names={"base","pillar","main","fan"};String[][] patterns={{"I","F","C"},{"I","R","I"},{" F ","PCP"," F "},{" P ","PIP"," P "}};String[][][] ingredients={{{"I","tag:c:ingots/iron"},{"F","academy:machine_frame"},{"C","academy:energy_convert_component"}},{{"I","minecraft:iron_bars"},{"R","tag:c:dusts/redstone"}},{{"F","academy:machine_frame"},{"P","academy:constraint_plate"},{"C","academy:energy_convert_component"}},{{"P","tag:c:plates/iron"},{"I","minecraft:iron_bars"}}};
        for(int n=0;n<4;n++){var recipe=JsonParser.parseString(source(root,"src/main/resources/data/academy/recipe/classic/windgen_"+names[n]+"_"+(n+10)+".json")).getAsJsonObject();check(recipe.get("type").getAsString().equals("minecraft:crafting_shaped"),"native shaped recipe");for(int row=0;row<patterns[n].length;row++)check(recipe.getAsJsonArray("pattern").get(row).getAsString().equals(patterns[n][row]),"source exact grid");for(var ingredient:ingredients[n]){var key=recipe.getAsJsonObject("key").getAsJsonObject(ingredient[0]);boolean tagged=ingredient[1].startsWith("tag:");check(key.get(tagged?"tag":"item").getAsString().equals(tagged?ingredient[1].substring(4):ingredient[1]),"original OreDictionary key or fixed item identity");check(!key.has(tagged?"item":"tag"),"no narrowed tag or broadened fixed item");};check(recipe.getAsJsonObject("result").get("id").getAsString().equals("academy:windgen_"+names[n])&&recipe.getAsJsonObject("result").get("count").getAsInt()==1,"source exact1 yield");}
        for(int n=0;n<3;n++){var loot=JsonParser.parseString(source(root,"src/main/resources/data/academy/loot_table/blocks/windgen_"+names[n]+".json")).getAsJsonObject();check(loot.getAsJsonArray("pools").size()==1&&loot.getAsJsonArray("pools").get(0).getAsJsonObject().get("rolls").getAsInt()==1,"one clicked-cell block drop");for(String tag:new String[]{"mineable/pickaxe","needs_iron_tool"}){var values=JsonParser.parseString(source(root,"src/main/resources/data/minecraft/tags/block/"+tag+".json")).getAsJsonObject().getAsJsonArray("values");final String id="academy:windgen_"+names[n];check(values.asList().stream().anyMatch(v->v.getAsString().equals(id)),"source pickaxe2 tag");}}
        for(String locale:new String[]{"en_us","zh_cn","zh_tw","ja_jp"}){var dictionary=JsonParser.parseString(source(root,"src/main/resources/assets/academy/lang/"+locale+".json")).getAsJsonObject();for(int n=0;n<3;n++)check(dictionary.get("block.academy.windgen_"+names[n]).equals(dictionary.get("tile.ac_windgen_"+names[n]+".name")),"original localized block name");check(dictionary.get("item.academy.windgen_fan").equals(dictionary.get("item.ac_windgen_fan.name")),"original localized fan name");}
        String registry=source(root,"src/main/java/cn/academy/port/wind/ClassicWindGenerators.java");check(registry.contains("strength(4f)")&&registry.contains("durability(100)")&&registry.contains("ClassicSolarGenerators.IMAG_FLUX"),"authentic hardness/fan/generator identity");check(!registry.contains("Capabilities.FluidHandler")&&!registry.contains("Capabilities.EnergyStorage"),"wind creates no foreign fluid/FE endpoint");check(registry.contains("tile.available()?tile:null")&&registry.contains("tile.available()?tile.itemHandler():null"),"only valid origins expose genuine IF/inventory");
        String block=source(root,"src/main/java/cn/academy/port/wind/ClassicWindBlock.java");check(block.contains("item.is(ClassicWindGenerators.PILLAR_ITEM.get())")&&block.contains("player.isShiftKeyDown()"),"source base pillar placement bypass and sneak rules");check(block.contains("PILLAR_ITEM.get()))return ItemInteractionResult.SKIP_DEFAULT_BLOCK_INTERACTION"),"modern default-block fallback cannot reopen baseGUI before pillar placement");check(block.contains("wire.writeBoolean(root instanceof ClassicWindBaseBlockEntity)")&&block.contains("wire.writeBlockPos(root.getBlockPos())"),"menu opening carries exact kind/origin");
        String protocol=source(root,"src/main/java/cn/academy/port/wireless/ClassicWirelessProtocol.java");for(String guard:new String[]{"open_windgen","menu.isFor(wind)","menu.sourcePos().equals(request.target)","menu.stillValid(player)","wind.getEnergy()","\"max_energy\",20000","wind.getBandwidth()"})check(protocol.contains(guard),"native wireless exact sender/menu/root/capacity binding");check(protocol.contains("wire.writeBoolean(true);wire.writeBlockPos(wind.getBlockPos());"),"return carries native wind menu kind");
        String structure=source(root,"src/main/java/cn/academy/port/wind/ClassicWindStructure.java");for(String guard:new String[]{"isOutsideBuildHeight","getWorldBorder().isWithinBounds","level.hasChunkAt(pos)","level.mayInteract(player,pos)","player.mayUseItemAt","level.isUnobstructed","saveWithFullMetadata","if(!placed)","level.invalidateCapabilities","UPDATE_SUPPRESS_DROPS","Containers.dropContents","developer.clearContent()"})check(structure.contains(guard),"atomic native allcell lifecycle guard "+guard);
        String base=source(root,"src/main/java/cn/academy/port/wind/ClassicWindBaseBlockEntity.java");check(base.indexOf("tile.buffer.generate(")<base.indexOf("tile.updateTower();")&&base.indexOf("tile.updateTower();")<base.indexOf("tile.buffer.charge("),"source generation/refresh/item order");check(base.contains("tile.energyTicks==20")&&base.contains("tile.structureTicks==10")&&base.contains("publishedEnergy"),"source20tick precharge and10tick tower snapshots");check(source(root,"src/main/java/cn/academy/port/AcademyCraft.java").contains("cn.academy.port.wind.ClassicWindGenerators.register(bus);"),"real modbus integration");
        genuineGraphConservation();
        System.out.println("ClassicWindDataRegressionTest: "+checks+" source recipes/materials/tags/menu/wireless/atomic-lifecycle bindings passed");
    }
    private static void genuineGraphConservation(){
        for(var tier:cn.academy.port.wireless.ClassicWirelessRules.NodeType.values()){
            var generatorPos=new cn.academy.port.wireless.ClassicWirelessGraph.Pos(0,80,0);var nodePos=new cn.academy.port.wireless.ClassicWirelessGraph.Pos(2,80,0);
            var buffer=new ClassicWindBuffer();buffer.load(456.375);final double[] energy={0};final boolean[] dormant={false},unloaded={false};
            var node=new cn.academy.port.wireless.ImagFluxNode(){public double getMaxEnergy(){return tier.energy;}public double getEnergy(){return energy[0];}public void setEnergy(double amount){energy[0]=Math.max(0,Math.min(tier.energy,amount));}public double getBandwidth(){return tier.bandwidth;}public int getCapacity(){return tier.capacity;}public double getRange(){return tier.range;}public String getNodeName(){return "Finite source-tier fixture";}public String getPassword(){return "wind-fixture";}};
            var generator=new cn.academy.port.solar.ImagFluxGenerator(){public double getEnergy(){return buffer.energy();}public double getBandwidth(){return ClassicWindRules.BANDWIDTH;}public double getProvidedEnergy(double amount){return buffer.getProvidedEnergy(amount);}};
            var dormantGenerator=new cn.academy.port.solar.ImagFluxGenerator(){public double getEnergy(){return 0;}public double getBandwidth(){return 0;}public double getProvidedEnergy(double amount){return 0;}};
            var resolver=new cn.academy.port.wireless.ClassicWirelessGraph.Resolver(){public boolean isLoaded(cn.academy.port.wireless.ClassicWirelessGraph.Pos p){return !p.equals(generatorPos)||!unloaded[0];}public cn.academy.port.wireless.ImagFluxNode node(cn.academy.port.wireless.ClassicWirelessGraph.Pos p){return p.equals(nodePos)?node:null;}public cn.academy.port.wireless.ImagFluxMatrix matrix(cn.academy.port.wireless.ClassicWirelessGraph.Pos p){return null;}public cn.academy.port.solar.ImagFluxGenerator generator(cn.academy.port.wireless.ClassicWirelessGraph.Pos p){check(isLoaded(p),"real graph must not query unloaded source");return p.equals(generatorPos)?dormant[0]?dormantGenerator:generator:null;}public cn.academy.port.machine.ImagFluxReceiver receiver(cn.academy.port.wireless.ClassicWirelessGraph.Pos p){return null;}public java.util.List<cn.academy.port.wireless.ClassicWirelessGraph.Pos> wirelessBlocksWithin(cn.academy.port.wireless.ClassicWirelessGraph.Pos p,double range,int maximum){return java.util.List.of(nodePos);}};
            var graph=new cn.academy.port.wireless.ClassicWirelessGraph(resolver,new java.util.Random(107),()->{});check(!graph.linkGenerator(nodePos,generatorPos,"wrong",true),"genuine source graph authentication");check(graph.linkGenerator(nodePos,generatorPos,"wind-fixture",true),"genuine windbuffer generator route");check(graph.linkGenerator(nodePos,generatorPos,"wind-fixture",true),"idempotent same-root link");graph.tick();double transferred=Math.min(300,tier.bandwidth);check(Math.abs(energy[0]-transferred)<1e-9&&Math.abs(buffer.energy()-(456.375-transferred))<1e-9,"actual source node/generator min budgets "+tier);
            for(int tick=0;tick<4000;tick++){double before=energy[0]+buffer.energy();double made=buffer.generate(100,true);graph.tick();check(Math.abs(energy[0]+buffer.energy()-before-made)<1e-7,"real graph total IF follows only actual wind generation");check(buffer.energy()>=0&&buffer.energy()<=20000&&energy[0]>=0&&energy[0]<=tier.energy,"real graph finite source/tier capacity");}
            double saved=energy[0]+buffer.energy();dormant[0]=true;graph.tick();check(graph.nodeForGenerator(generatorPos).equals(nodePos)&&Math.abs(saved-energy[0]-buffer.energy())<1e-7,"dormant cross-chunk root retains link without IF creation/debit");unloaded[0]=true;graph.tick();check(graph.nodeForGenerator(generatorPos).equals(nodePos),"real graph preserves unloaded rootlink");var snapshot=graph.snapshot();var restored=new cn.academy.port.wireless.ClassicWirelessGraph(resolver);restored.restore(snapshot);check(restored.nodeForGenerator(generatorPos).equals(nodePos),"real graph persisted connection restores without worldmutation");unloaded[0]=false;dormant[0]=false;restored.tick();check(Math.abs(saved-energy[0]-buffer.energy())<1e-7,"real graph resumed exact conserved finite stores");
        }
    }

}
