/* AcademyCraft1.0.7 BloodRetrograde/BloodRetroContext adaptation, GPLv3; see NOTICE. */
package cn.academy.port.skill;
import cn.academy.port.*;
import net.minecraft.server.level.*;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.level.ClipContext;
import net.minecraft.world.phys.*;
import java.util.*;
/** Source client-selected victim is replaced by a server-owned two-block living ray. */
public final class BloodRetrograde {
 public static final String ID=BloodRetrogradeSession.ID;public static final double RANGE=2;private static final Map<UUID,Hold> HOLDS=new HashMap<>();private static final Map<UUID,Long> INPUTS=new HashMap<>();private static final Set<UUID> COMMITTING=new HashSet<>();private static long token;
 private BloodRetrograde(){}public static boolean start(ServerPlayer p){if(cn.academy.port.AbilityConsumption.busy(p))return false;return start(p,0);}public static boolean start(ServerPlayer p,long input){if(cn.academy.port.AbilityConsumption.busy(p))return false;if(!VectorCombatSupport.ready(p)||input<0||input>0&&input<=INPUTS.getOrDefault(p.getUUID(),0L)||COMMITTING.contains(p.getUUID()))return false;var old=HOLDS.get(p.getUUID());if(old!=null){if(valid(p,old))return false;remove(p);}var s=BloodRetrogradeSession.begin(AbilityStorage.get(p));if(s==null)return false;var h=new Hold(p,s,++token,input);HOLDS.put(p.getUUID(),h);if(input>0)INPUTS.put(p.getUUID(),input);send(p,h,"blood_retro_start",false);return true;}
 private static boolean valid(ServerPlayer p,Hold h){return VectorCombatSupport.ready(p)&&h.level==p.serverLevel()&&h.session.state()==AbilityStorage.get(p)&&VectorCombatSupport.state(h.session.state(),ID,4)&&h.session.active()&&p.serverLevel().getGameTime()>=h.lastTick;}
 public static void tick(ServerPlayer p){if(!VectorCombatSupport.thread(p)||COMMITTING.contains(p.getUUID()))return;var h=HOLDS.get(p.getUUID());if(h==null)return;if(!valid(p,h)){remove(p);return;}long now=p.serverLevel().getGameTime();if(now<=h.lastTick)return;h.lastTick=now;h.session.tick();p.getAbilities().setWalkingSpeed(h.session.walkSpeed());p.onUpdateAbilities();if(h.session.autoRelease())release(p,h.input);}
 public static boolean release(ServerPlayer p){return release(p,0);}public static boolean release(ServerPlayer p,long input){if(!VectorCombatSupport.thread(p)||COMMITTING.contains(p.getUUID()))return false;var h=HOLDS.get(p.getUUID());if(h==null||input>0&&h.input!=input)return false;if(!valid(p,h)){remove(p);return false;}HOLDS.remove(p.getUUID(),h);COMMITTING.add(p.getUUID());boolean success=false;try{Vec3 origin=p.getEyePosition();var hit=ClassicRaytrace.perform(p,origin,origin.add(ClassicRaytrace.direction(p).scale(RANGE)),ClipContext.Fluid.NONE,e->e instanceof LivingEntity);LivingEntity target=hit instanceof EntityHitResult eh&&eh.getEntity() instanceof LivingEntity l?l:null;if(!h.session.release(target!=null,p.getAbilities().instabuild))return false;var t=VectorCombatSupport.packet(p,"blood_retro_perform",h.token,h.input);VectorCombatSupport.position(t,target.position());t.putInt("target",target.getId());t.putFloat("width",target.getBbWidth());t.putFloat("height",target.getBbHeight());VectorCombatSupport.send(h.audience,t);AbilityDamage.attack(p,"vecmanip."+ID,target,h.session.damage());h.session.award();if(h.session.achievement())cn.academy.port.achievements.ClassicAchievements.trigger(p,"vecmanip.blood_retro");success=true;return true;}finally{COMMITTING.remove(p.getUUID());restore(p);send(p,h,"blood_retro_end",success);VectorCombatSupport.sync(p);}}
 /** Classic hard-resets 0.1 rather than preserving a modded previous speed. */
 private static void restore(ServerPlayer p){p.getAbilities().setWalkingSpeed(.1F);p.onUpdateAbilities();}
 public static void abort(ServerPlayer p){abort(p,0);}public static boolean abort(ServerPlayer p,long input){if(!VectorCombatSupport.thread(p)||COMMITTING.contains(p.getUUID()))return false;var h=HOLDS.get(p.getUUID());if(h==null||input>0&&h.input!=input)return false;HOLDS.remove(p.getUUID(),h);h.session.discard();restore(p);send(p,h,"blood_retro_end",false);return true;}
 public static void remove(ServerPlayer p){if(!VectorCombatSupport.thread(p))return;abort(p);INPUTS.remove(p.getUUID());}public static boolean active(ServerPlayer p){return p!=null&&HOLDS.containsKey(p.getUUID());}public static int heldTicks(ServerPlayer p){var h=p==null?null:HOLDS.get(p.getUUID());return h==null?0:h.session.ticks();}public static long input(ServerPlayer p){var h=p==null?null:HOLDS.get(p.getUUID());return h==null?0:h.input;}public static void clear(){HOLDS.clear();INPUTS.clear();COMMITTING.clear();token=0;}private static void send(ServerPlayer p,Hold h,String kind,boolean performed){var t=VectorCombatSupport.packet(p,kind,h.token,h.input);t.putBoolean("performed",performed);t.putFloat("cp",VectorCombatRules.bloodCp(h.session.state().exp(ID)));VectorCombatSupport.send(h.audience,t);}
 private static final class Hold{final ServerLevel level;final BloodRetrogradeSession session;final long token,input;final Set<ServerPlayer> audience;long lastTick;Hold(ServerPlayer p,BloodRetrogradeSession s,long t,long i){level=p.serverLevel();session=s;token=t;input=i;audience=VectorCombatSupport.audience(p);lastTick=level.getGameTime();}}
}
