/* AcademyCraft1.0.7 ElectronMissile/EMContext adaptation. GPLv3; see NOTICE. */
package cn.academy.port.skill;
import cn.academy.port.*;
import net.minecraft.server.level.*;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.phys.*;
import java.util.*;
/** Server-owned logical original MdBalls. Targets are feet-nearest in a sphere, even across walls. */
public final class ElectronMissile {
 public static final String ID=ElectronMissileSession.ID;private static final Map<UUID,Hold> HOLDS=new HashMap<>();private static final Map<UUID,Long> INPUTS=new HashMap<>();private static final Set<UUID> TICKING=new HashSet<>();private static long nextToken;
 private ElectronMissile(){}public static boolean start(ServerPlayer p){if(cn.academy.port.AbilityConsumption.busy(p))return false;return start(p,0);}
 public static boolean start(ServerPlayer p,long nonce){if(cn.academy.port.AbilityConsumption.busy(p))return false;if(!MeltdownerLateSupport.ready(p)||nonce<0||nonce>0&&nonce<=INPUTS.getOrDefault(p.getUUID(),0L)||TICKING.contains(p.getUUID()))return false;var old=HOLDS.get(p.getUUID());if(old!=null){if(valid(p,old))return false;remove(p);}var session=ElectronMissileSession.begin(AbilityStorage.get(p),p.getAbilities().instabuild);if(session==null)return false;var h=new Hold(p,session,++nextToken,nonce);HOLDS.put(p.getUUID(),h);if(nonce>0)INPUTS.put(p.getUUID(),nonce);send(p,h,"electron_missile_start");if(session.ending())finish(p,h,false);return true;}
 private static boolean valid(ServerPlayer p,Hold h){var s=AbilityStorage.get(p);return MeltdownerLateSupport.ready(p)&&h.world==p.serverLevel()&&h.session.state()==s&&h.session.active()&&s.category.equals("meltdowner")&&s.level>=5&&s.learned(ID)&&p.serverLevel().getGameTime()>=h.lastTick;}
 public static void tick(ServerPlayer p){if(!MeltdownerStarterSupport.serverThread(p))return;var h=HOLDS.get(p.getUUID());if(h==null)return;if(!valid(p,h)){remove(p);return;}var s=h.session.state();if(!s.activated||!s.overloadFine||s.interfering){finish(p,h,false);return;}long now=p.serverLevel().getGameTime();if(now<=h.lastTick||!TICKING.add(p.getUUID()))return;h.lastTick=now;try{var tick=h.session.tick(p.getAbilities().instabuild);if(HOLDS.get(p.getUUID())!=h||!valid(p,h))return;if(tick.spawn())spawn(p,h);if(tick.seek()&&!h.balls.isEmpty()){double range=h.session.range();LivingEntity nearest=null;double best=Double.MAX_VALUE;for(var e:p.serverLevel().getEntities(p,new AABB(p.position(),p.position()).inflate(range),e->e instanceof LivingEntity&&e.isAlive()&&e.distanceToSqr(p)<=range*range)){double dist=e.distanceTo(p);if(dist<best){best=dist;nearest=(LivingEntity)e;}}
  if(nearest!=null&&h.session.debitAttack(p.getAbilities().instabuild)){if(HOLDS.get(p.getUUID())!=h||!valid(p,h)||h.balls.isEmpty()||nearest.isRemoved()||nearest.level()!=h.world)return;int index=p.serverLevel().random.nextInt(h.balls.size());var ball=h.balls.remove(index);var tag=MeltdownerLateSupport.packet(p,"electron_missile_ray",h.token,h.nonce);tag.putInt("index",tick.index());tag.putInt("ball",ball.index);MeltdownerLateSupport.ray(tag,ball.position,nearest.position().add(0,nearest.getEyeHeight(),0));MeltdownerStarterSupport.send(h.audience,tag);nearest.invulnerableTime=-1;RadiationMarks.attack(p,"meltdowner."+ID,nearest,h.session.damage());h.session.completeAttack();}}
  if(tick.update()){var tag=MeltdownerLateSupport.packet(p,"electron_missile_update",h.token,h.nonce);tag.putInt("index",tick.index());MeltdownerStarterSupport.send(h.audience,tag);}for(var ball:h.balls)ball.position=p.position().add(ball.offset);if(tick.ending()||!s.overloadFine)finish(p,h,false);
 }finally{TICKING.remove(p.getUUID());}}
 private static void spawn(ServerPlayer p,Hold h){var r=p.serverLevel().random;float pi=(float)Math.PI,theta=-p.getYRot()/180*pi+(-pi*.45F+r.nextFloat()*(pi*.9F));float radius=.8F+r.nextFloat()*(1.3F-.8F);float x=Mth.sin(theta)*radius,z=Mth.cos(theta)*radius,y=-1.2F+r.nextFloat()*(.2F- -1.2F);Vec3 offset=new Vec3(x,y+1.6,z);var ball=new Ball(h.nextBall++,offset,p.position().add(offset));h.balls.add(ball);var tag=MeltdownerLateSupport.packet(p,"electron_missile_ball",h.token,h.nonce);tag.putInt("index",ball.index);tag.putInt("life",ElectronMissileSession.BALL_LIFE);tag.putDouble("offset_x",offset.x);tag.putDouble("offset_y",offset.y);tag.putDouble("offset_z",offset.z);MeltdownerStarterSupport.position(tag,ball.position);MeltdownerStarterSupport.send(h.audience,tag);}
 public static boolean release(ServerPlayer p){return release(p,0);}public static boolean release(ServerPlayer p,long nonce){if(!MeltdownerStarterSupport.serverThread(p))return false;var h=HOLDS.get(p.getUUID());if(h==null||nonce>0&&h.nonce!=nonce)return false;if(!valid(p,h)){remove(p);return false;}finish(p,h,false);return true;}
 public static void abort(ServerPlayer p){release(p);}public static boolean abort(ServerPlayer p,long nonce){return release(p,nonce);}
 public static void remove(ServerPlayer p){if(!MeltdownerStarterSupport.serverThread(p))return;var h=HOLDS.get(p.getUUID());if(h!=null)finish(p,h,true);INPUTS.remove(p.getUUID());TICKING.remove(p.getUUID());}
 private static void finish(ServerPlayer p,Hold h,boolean discard){if(!HOLDS.remove(p.getUUID(),h))return;if(discard)h.session.discard();else h.session.complete();h.balls.clear();send(p,h,"electron_missile_end");if(!discard){AbilityStorage.save(p);AcademyNetwork.sync(p);}}
 private static void send(ServerPlayer p,Hold h,String kind){MeltdownerStarterSupport.send(h.audience,MeltdownerLateSupport.packet(p,kind,h.token,h.nonce));}
 public static boolean active(ServerPlayer p){return p!=null&&HOLDS.containsKey(p.getUUID());}public static int heldTicks(ServerPlayer p){var h=p==null?null:HOLDS.get(p.getUUID());return h==null?0:h.session.ticks();}public static int ballCount(ServerPlayer p){var h=p==null?null:HOLDS.get(p.getUUID());return h==null?0:h.balls.size();}public static void clear(){HOLDS.clear();INPUTS.clear();TICKING.clear();nextToken=0;}
 private static final class Ball{final int index;final Vec3 offset;Vec3 position;Ball(int i,Vec3 o,Vec3 p){index=i;offset=o;position=p;}}
 private static final class Hold{final ServerLevel world;final ElectronMissileSession session;final long token,nonce;final Set<ServerPlayer> audience;final List<Ball> balls=new ArrayList<>();int nextBall;long lastTick;Hold(ServerPlayer p,ElectronMissileSession s,long t,long n){world=p.serverLevel();session=s;token=t;nonce=n;audience=MeltdownerStarterSupport.audience(p);lastTick=world.getGameTime()-1;}}
}
