/* AcademyCraft1.0.7 JEContext adaptation, GPLv3; see NOTICE. */
package cn.academy.port.skill;
import cn.academy.port.*;
import net.minecraft.server.level.*;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.level.ClipContext;
import net.minecraft.world.phys.*;
import java.util.*;
/** Authoritative modern movement: server computes source endpoint, interpolation and all collision damage. */
public final class JetEngine {
 public static final String ID=JetEngineSession.ID;private static final Map<UUID,Hold> HOLDS=new HashMap<>();private static final Map<UUID,Long> INPUTS=new HashMap<>();private static final Set<UUID> TICKING=new HashSet<>();private static long nextToken;
 private JetEngine(){}public static boolean start(ServerPlayer p){if(cn.academy.port.AbilityConsumption.busy(p))return false;return start(p,0);}
 public static boolean start(ServerPlayer p,long nonce){if(cn.academy.port.AbilityConsumption.busy(p))return false;if(!MeltdownerLateSupport.ready(p)||nonce<0||nonce>0&&nonce<=INPUTS.getOrDefault(p.getUUID(),0L)||TICKING.contains(p.getUUID()))return false;var old=HOLDS.get(p.getUUID());if(old!=null){if(valid(p,old))return false;remove(p);}var session=JetEngineSession.begin(AbilityStorage.get(p));if(session==null)return false;var h=new Hold(p,session,++nextToken,nonce);HOLDS.put(p.getUUID(),h);if(nonce>0)INPUTS.put(p.getUUID(),nonce);send(p,h,"jet_engine_start");return true;}
 private static boolean valid(ServerPlayer p,Hold h){var s=AbilityStorage.get(p);return MeltdownerLateSupport.ready(p)&&p.serverLevel()==h.world&&h.session.state()==s&&s.category.equals("meltdowner")&&s.level>=4&&s.learned(ID)&&h.session.active()&&p.serverLevel().getGameTime()>=h.lastTick;}
 public static void tick(ServerPlayer p){if(!MeltdownerStarterSupport.serverThread(p))return;var h=HOLDS.get(p.getUUID());if(h==null)return;if(!valid(p,h)){remove(p);return;}var s=h.session.state();if(!s.activated||!s.overloadFine||s.interfering||!h.session.affordable(p.getAbilities().instabuild)){finish(p,h,false);return;}long now=p.serverLevel().getGameTime();if(now<=h.lastTick)return;h.lastTick=now;if(!h.session.triggering())return;if(!TICKING.add(p.getUUID()))return;try{
  // Vanilla movement packets are never an input to the ability trajectory or authoritative damage.
  Vec3 from=h.lastPosition;float fraction=h.session.step();Vec3 to=h.start.lerp(h.target,fraction);if(!MeltdownerStarterSupport.finite(to)||!p.serverLevel().hasChunkAt(net.minecraft.core.BlockPos.containing(to))||!p.serverLevel().getWorldBorder().isWithinBounds(net.minecraft.core.BlockPos.containing(to))){finish(p,h,false);return;}
  p.stopRiding();p.teleportTo(to.x,to.y,to.z);p.setDeltaMovement(h.velocity);p.fallDistance=0;p.hurtMarked=true;h.lastPosition=to;
  // Source setPosition traverses solid blocks; block-hit ray still occludes living collision damage.
  var hit=ClassicRaytrace.perform(p,from,to,ClipContext.Fluid.NONE,e->e instanceof LivingEntity);if(hit instanceof EntityHitResult eh)RadiationMarks.attack(p,"meltdowner."+ID,eh.getEntity(),h.session.damage());
  var tag=MeltdownerLateSupport.packet(p,"jet_engine_step",h.token,h.nonce);tag.putInt("index",h.session.ticks());MeltdownerStarterSupport.position(tag,to);MeltdownerStarterSupport.send(h.audience,tag);if(!h.session.active())finish(p,h,false);
 }finally{TICKING.remove(p.getUUID());}}
 public static boolean release(ServerPlayer p){return release(p,0);}public static boolean release(ServerPlayer p,long nonce){if(cn.academy.port.AbilityConsumption.busy(p)||!MeltdownerStarterSupport.serverThread(p))return false;var h=HOLDS.get(p.getUUID());if(h==null||nonce>0&&h.nonce!=nonce)return false;if(!valid(p,h)){remove(p);return false;}if(h.session.triggering())return false;send(p,h,"jet_engine_mark_end");if(!h.session.release(p.getAbilities().instabuild)){finish(p,h,false);return false;}if(HOLDS.get(p.getUUID())!=h||!valid(p,h))return false;cn.academy.port.achievements.ClassicAchievements.trigger(p,"meltdowner.jet_engine");h.start=p.position();h.lastPosition=h.start;h.target=MeltdownerLateSupport.destination(p,12,false).add(0,1.65,0);h.velocity=h.target.subtract(h.start).scale(1.0/8);h.noGravity=p.isNoGravity();p.setNoGravity(true);var tag=MeltdownerLateSupport.packet(p,"jet_engine_trigger",h.token,h.nonce);MeltdownerStarterSupport.position(tag,h.start);MeltdownerLateSupport.target(tag,h.target);MeltdownerStarterSupport.send(h.audience,tag);AbilityStorage.save(p);AcademyNetwork.sync(p);return true;}
 /** Abort ends marking/flight without release debit or any invented end cooldown. */
 public static void abort(ServerPlayer p){abort(p,0);}public static boolean abort(ServerPlayer p,long nonce){if(!MeltdownerStarterSupport.serverThread(p))return false;var h=HOLDS.get(p.getUUID());if(h==null||nonce>0&&h.nonce!=nonce)return false;finish(p,h,false);return true;}
 public static void remove(ServerPlayer p){if(!MeltdownerStarterSupport.serverThread(p))return;var h=HOLDS.get(p.getUUID());if(h!=null)finish(p,h,true);INPUTS.remove(p.getUUID());TICKING.remove(p.getUUID());}
 private static void finish(ServerPlayer p,Hold h,boolean discard){if(!HOLDS.remove(p.getUUID(),h))return;if(h.session.triggering()){p.setNoGravity(h.noGravity);p.fallDistance=0;}h.session.discard();send(p,h,"jet_engine_end");if(!discard){AbilityStorage.save(p);AcademyNetwork.sync(p);}}
 public static boolean active(ServerPlayer p){return p!=null&&HOLDS.containsKey(p.getUUID());}public static boolean triggering(ServerPlayer p){var h=p==null?null:HOLDS.get(p.getUUID());return h!=null&&h.session.triggering();}public static int flightTicks(ServerPlayer p){var h=p==null?null:HOLDS.get(p.getUUID());return h==null?0:h.session.ticks();}public static Vec3 target(ServerPlayer p){var h=p==null?null:HOLDS.get(p.getUUID());return h==null?null:h.target;}public static void clear(){HOLDS.clear();INPUTS.clear();TICKING.clear();nextToken=0;}
 private static void send(ServerPlayer p,Hold h,String kind){MeltdownerStarterSupport.send(h.audience,MeltdownerLateSupport.packet(p,kind,h.token,h.nonce));}
 private static final class Hold{final ServerLevel world;final JetEngineSession session;final long token,nonce;final Set<ServerPlayer> audience;long lastTick;Vec3 start,target,velocity,lastPosition;boolean noGravity;Hold(ServerPlayer p,JetEngineSession s,long token,long nonce){world=p.serverLevel();session=s;this.token=token;this.nonce=nonce;audience=MeltdownerStarterSupport.audience(p);lastTick=world.getGameTime()-1;}}
}
