/* AcademyCraft1.0.7 MTContext adaptation. GPLv3; see NOTICE. */
package cn.academy.port.skill;
import cn.academy.port.core.AbilityProgress;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.level.ClipContext;
import net.minecraft.world.phys.*;
import static cn.academy.port.skill.TeleporterProgressionRules.*;
/** Server held ticks determine the expanding endpoint; entity targets retain source feet+eye result. */
public final class MarkTeleport {
 public static final String ID=MARK;private MarkTeleport(){}
 public static boolean start(ServerPlayer p){if(cn.academy.port.AbilityConsumption.busy(p))return false;return start(p,0);}public static boolean start(ServerPlayer p,long nonce){if(cn.academy.port.AbilityConsumption.busy(p))return false;return TeleporterProgressionSupport.start(p,ID,nonce)!=null;}public static void tick(ServerPlayer p){TeleporterProgressionSupport.tick(p,ID);}
 public static Vec3 destination(Entity p,double exp,double cp,int ticks){double range=markMaxDistance(exp,cp,ticks);var eye=p.getEyePosition();var hit=ClassicRaytrace.perform(p,eye,eye.add(TeleporterProgressionSupport.direction(p).scale(range)),ClipContext.Fluid.NONE,e->true);if(hit instanceof BlockHitResult b&&hit.getType()==HitResult.Type.BLOCK){var out=markBlock(TeleporterProgressionSupport.point(hit.getLocation()),b.getDirection().get3DDataValue(),b.getBlockPos().getY(),(x,y,z)->p.level().isEmptyBlock(new BlockPos(x,y,z)));return TeleporterProgressionSupport.vector(out);}if(hit instanceof EntityHitResult e)return hit.getLocation().add(0,e.getEntity().getEyeHeight(),0);return p.getEyePosition().add(TeleporterProgressionSupport.direction(p).scale(range));}
 public static boolean release(ServerPlayer p){return release(p,0);}public static boolean release(ServerPlayer p,long nonce){var h=TeleporterProgressionSupport.terminal(p,ID,nonce);if(h==null)return false;TeleporterProgressionSupport.COMMITTING.add(p.getUUID());try{Vec3 eye=p.getEyePosition(),end=eye.add(TeleporterProgressionSupport.direction(p).scale(markMaxDistance(h.state.exp(ID),h.state.cp,h.ticks)));if(!TeleporterProgressionSupport.loaded(p,eye,end)){TeleporterProgressionSupport.send(p,ID,h,"end",null,false,-1);return false;}Vec3 at=destination(p,h.state.exp(ID),h.state.cp,h.ticks);float distance=(float)p.position().distanceTo(at);if(distance<3||!TeleporterProgressionSupport.destinationSafe(p,at)){TeleporterProgressionSupport.send(p,ID,h,"end",at,false,-1);return false;}if(!consumeWithForce(h.state,ID,distance*markConsumption(h.exp),markOverload(h.exp),p.getAbilities().instabuild))return false;TeleporterProgressionSupport.teleport(p,at,false);h.state.addExperience(ID,markExperience(distance));h.state.setCooldown(ID,markCooldown(h.exp));TeleporterProgressionSupport.send(p,ID,h,"end",at,true,-1);TeleporterProgressionSupport.save(p);return true;}finally{TeleporterProgressionSupport.COMMITTING.remove(p.getUUID());}}
 public static void abort(ServerPlayer p){abort(p,0);}public static boolean abort(ServerPlayer p,long nonce){return TeleporterProgressionSupport.abort(p,ID,nonce);}public static void remove(ServerPlayer p){TeleporterProgressionSupport.remove(p,ID);}public static boolean active(ServerPlayer p){return TeleporterProgressionSupport.active(p,ID);}public static int heldTicks(ServerPlayer p){var h=p==null?null:TeleporterProgressionSupport.HOLDS.get(ID).get(p.getUUID());return h==null?0:h.ticks;}public static boolean canUse(AbilityProgress s){return TeleporterProgressionSupport.usable(s,ID);}public static void clear(){TeleporterProgressionSupport.clear(ID);}
}
