/* Packaged original PNG/GUI geometry and source TextBox interaction checks. GPLv3/MIT. */
package cn.academy.port.client;
import com.google.gson.JsonParser;
import java.io.*;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import javax.imageio.ImageIO;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.*;
public final class ClassicInterfererVisualRegressionTest {
    private static int checks;
    private static void check(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}
    private static void equal(double expected,double actual,String why){check(Math.abs(expected-actual)<1e-7,why+": "+actual);}
    private static Element widget(Document document,String name){var nodes=document.getElementsByTagName("Widget");for(int i=0;i<nodes.getLength();i++){Element element=(Element)nodes.item(i);if(name.equals(element.getAttribute("name")))return element;}throw new AssertionError(name);}
    private static Element transform(Element widget){for(Node child=widget.getFirstChild();child!=null;child=child.getNextSibling())if(child instanceof Element e&&e.getTagName().equals("Component")&&e.getAttribute("class").endsWith("Transform"))return e;throw new AssertionError("Transform");}
    private static double value(Element component,String tag){return Double.parseDouble(component.getElementsByTagName(tag).item(0).getTextContent());}
    public static void main(String[] args)throws Exception{
        Path root=Path.of(System.getProperty("academy.interferer.stage",".")),fixture=root.resolve("src/test/resources/classic-interferer-source");var manifest=JsonParser.parseString(Files.readString(fixture.resolve("witness-manifest.json"))).getAsJsonObject();int assets=0;for(var entry:manifest.getAsJsonArray("files")){var e=entry.getAsJsonObject();String path=e.get("path").getAsString();if(!path.startsWith("assets/"))continue;byte[] original=Files.readAllBytes(fixture.resolve(path)),modern=Files.readAllBytes(root.resolve("src/main/resources/assets/academy/"+path.substring(7)));check(Arrays.equals(original,modern),"original byte-identical runtime texture "+path);var image=ImageIO.read(new ByteArrayInputStream(modern));check(image!=null&&image.getWidth()>0&&image.getHeight()>0,"genuine PNG decodes "+path);assets++;}check(assets==15,"all15 original on/off/GUI textures packaged and bound");
        var factory=DocumentBuilderFactory.newInstance();factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);var doc=factory.newDocumentBuilder().parse(fixture.resolve("AcademyCraft/src/main/resources/assets/academy/guis/rework/page_interfere.xml").toFile());var main=transform(widget(doc,"main"));var list=transform(widget(doc,"panel_whitelist"));var config=transform(widget(doc,"panel_config"));equal(176,value(main,"width"),"source page width");equal(187,value(main,"height"),"source page height");equal(160,value(list,"width"),"source whitelist width");equal(100,value(list,"height"),"source whitelist height");equal(35,value(list,"y"),"source whitelist center offset");equal((187-100)/2d+35,ClassicInterfererVisualRules.LIST_Y,"derived source whitelist absolute offset");equal(25,value(config,"y"),"source config Y");equal(32,value(config,"height"),"source config height");equal(16,value(transform(widget(doc,"element")),"height"),"source whitelist row16");equal(80,value(transform(widget(doc,"zone_whitelist")),"height"),"source fully visible80-pixel list");
        for(int width:new int[]{320,854,1180,1920}){equal((width-172)/2d,ClassicInterfererVisualRules.rootX(width),"plain CGuiScreen centered172 root");equal((width-176)/2d,ClassicInterfererVisualRules.pageX(width),"176 page centered inside root");}for(int height:new int[]{240,812,1080})equal((height-187)/2d,ClassicInterfererVisualRules.pageY(height),"source centered187 page");
        for(String status:List.of("off","on")){var model=JsonParser.parseString(Files.readString(root.resolve("src/main/resources/assets/academy/models/block/ability_interferer_"+status+".json"))).getAsJsonObject();var element=model.getAsJsonArray("elements").get(0).getAsJsonObject();check(element.getAsJsonArray("from").toString().equals("[0,0,0]")&&element.getAsJsonArray("to").toString().equals("[16,16,16]"),"source unit cube mesh");var faces=element.getAsJsonObject("faces");check(faces.size()==6,"all six original dynamic block faces");for(var face:faces.entrySet())check(!face.getValue().getAsJsonObject().has("cullface"),"original renderBlockAllFaces retained");check(model.getAsJsonObject("textures").get("all").getAsString().equals("academy:blocks/ability_interf_"+status),"exact original on/off texture identity");}
        var item=JsonParser.parseString(Files.readString(root.resolve("src/main/resources/assets/academy/models/item/ability_interferer.json"))).getAsJsonObject();check(item.get("parent").getAsString().equals("academy:block/ability_interferer_off"),"source ItemBlock always off cube");String screen=Files.readString(root.resolve("src/main/java/cn/academy/port/client/ClassicInterfererScreen.java"));check(screen.contains("\"Swtich:\"")&&screen.contains("\"Range:\""),"original unlocalized template text and typo retained");check(!screen.contains("ClassicWirelessTabButton")&&screen.contains("ui/ui_interfere")&&screen.contains("isPauseScreen(){return false;}"),"original single inventory-icon page and nonpause UI");
        editor();System.out.println("ClassicInterfererVisualRegressionTest: "+checks+" immutable runtime textures/source geometry/model faces/original textbox interactions passed; actual rendered UI acceptance unclaimed");
    }
    private static void editor(){
        java.util.function.ToDoubleFunction<String> width=value->value.length()*9d;var e=new ClassicInterfererEditor();for(char c:"abcdef".toCharArray())e.type(c,width);check(e.content().equals("abcdef")&&e.caret()==6&&e.offset()==2,"source caret scrolls just beyond40px");check(e.display(width).equals("cdef"),"source display from updated offset");e.left();e.left();e.type('X',width);check(e.content().equals("abcdXef")&&e.caret()==5,"source insert at actual caret");e.paste("ZZ");check(e.content().equals("abcdXZZef")&&e.caret()==5,"source paste inserts but keeps caret");e.backspace(width);check(e.content().equals("abcdZZef")&&e.caret()==4,"source backspace before caret");e.delete();check(e.content().isEmpty()&&e.caret()==0&&e.offset()==0,"source Delete clears full content");for(char c:"abcde".toCharArray())e.type(c,width);check(ClassicInterfererEditor.emit("abcde",40,width).equals("abcde"),"source emit includes final width-crossing glyph");e.left();e.left();e.left();e.left();e.left();check(e.caret()==0&&e.offset()==0,"source left arrow moves display offset back");e.click(14,width);check(e.caret()==2,"source nearest mouse caret midpoint");e.paste("q\nr");check(e.content().equals("abqrcde")&&e.caret()==2,"documented paste control filtering adaptation");for(int i=0;i<100;i++)e.type('x',width);check(e.content().length()==64,"bounded packet/editor length adaptation");check(!e.content().contains("\u00a7"),"source section-sign forbidden char");}
}
