package cn.academy.port.client;
import cn.academy.port.wind.ClassicWindRules;
import com.google.gson.JsonParser;
import java.io.*;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import javax.imageio.ImageIO;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.*;
/** Portable original-byte/topology/UV/layout checks; these do not imply rendered visual acceptance. */
public final class ClassicWindVisualRegressionTest {
    private static int checks;
    private static final String ASSET_MANIFEST_SHA="19946e186c3ef73fbeadd3433137f5178e050632783340d8deb43f3eefd9605f";
    private static void check(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}
    private static void equal(double expected,double actual,String why){check(Math.abs(expected-actual)<1e-6,why+": "+actual);}
    private static String sha(byte[] bytes)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}
    private static void geometry(Path root,String name,int positionsExpected,int uvExpected,int normalsExpected,int facesExpected)throws Exception{String obj=Files.readString(root.resolve("src/main/resources/assets/academy/models/windgen_"+name+".obj"));var mesh=ClassicDeveloperObj.parse(new StringReader(obj));var positions=new ArrayList<float[]>();var uv=new ArrayList<float[]>();var faces=new ArrayList<String[]>();int normals=0;for(String line:obj.split("\\R")){if(line.startsWith("v ")){String[] values=line.trim().split("\\s+");positions.add(new float[]{Float.parseFloat(values[1]),Float.parseFloat(values[2]),Float.parseFloat(values[3])});}else if(line.startsWith("vt ")){String[] values=line.trim().split("\\s+");uv.add(new float[]{Float.parseFloat(values[1]),1-Float.parseFloat(values[2])});}else if(line.startsWith("vn "))normals++;else if(line.startsWith("f ")){var values=line.trim().split("\\s+");check(values.length==4,"unchanged wind OBJ uses original triangles");faces.add(Arrays.copyOfRange(values,1,4));}}
        check(mesh.positionCount()==positionsExpected&&mesh.uvCount()==uvExpected&&mesh.normalCount()==normalsExpected&&normals==normalsExpected,"exact original "+name+" topology");check(mesh.triangles().size()==facesExpected&&faces.size()==facesExpected,"every original "+name+" triangle exactlyonce");
        for(int i=0;i<faces.size();i++){String[] refs=faces.get(i);var vertices=List.of(mesh.triangles().get(i).a(),mesh.triangles().get(i).b(),mesh.triangles().get(i).c());float[] average={0,0};float[][] raw=new float[3][];for(int vertex=0;vertex<3;vertex++){var indices=refs[vertex].split("/");raw[vertex]=uv.get(Integer.parseInt(indices[1])-1);average[0]+=raw[vertex][0];average[1]+=raw[vertex][1];}average[0]/=3;average[1]/=3;
            for(int vertex=0;vertex<3;vertex++){var p=positions.get(Integer.parseInt(refs[vertex].split("/")[0])-1);var v=vertices.get(vertex);equal(p[0],v.x(),"original faceX");equal(p[1],v.y(),"original faceY");equal(p[2],v.z(),"original faceZ");equal(raw[vertex][0]+(raw[vertex][0]>average[0]?-.0005f:.0005f),v.u(),"source perface U inset");equal(raw[vertex][1]+(raw[vertex][1]>average[1]?-.0005f:.0005f),v.v(),"source flippedV/inset");}
        }
        if(name.equals("fan")){var b=mesh.bounds();double radius=positions.stream().mapToDouble(p->Math.hypot(p[0],p[1])).max().orElseThrow();check(radius+.5<8&&Math.max(Math.abs(b.minZ()+.82),Math.abs(b.maxZ()+.82))+1<8,"finite modern8block rotor box contains full original sweptmesh");}
    }
    private static Element widget(Document doc,String name){var list=doc.getElementsByTagName("Widget");for(int i=0;i<list.getLength();i++){var element=(Element)list.item(i);if(element.getAttribute("name").equals(name))return element;}throw new AssertionError(name);}
    private static Element component(Element widget,String ending){for(Node n=widget.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element e&&e.getTagName().equals("Component")&&e.getAttribute("class").endsWith(ending))return e;throw new AssertionError(ending);}
    private static double value(Element component,String tag){return Double.parseDouble(component.getElementsByTagName(tag).item(0).getTextContent());}
    public static void main(String[] args)throws Exception{Path root=Path.of(System.getProperty("academy.wind.stage","."));Path fixtures=root.resolve("src/test/resources/classic-wind-source");byte[] manifest=Files.readAllBytes(fixtures.resolve("asset-manifest.json"));check(sha(manifest).equals(ASSET_MANIFEST_SHA),"immutable asset manifest");for(var item:JsonParser.parseString(new String(manifest,java.nio.charset.StandardCharsets.UTF_8)).getAsJsonArray()){var expected=item.getAsJsonObject();var bytes=Files.readAllBytes(root.resolve(expected.get("path").getAsString()));check(sha(bytes).equals(expected.get("sha256").getAsString()),"original byte-identical asset");if(expected.get("path").getAsString().endsWith(".png")){var image=ImageIO.read(new ByteArrayInputStream(bytes));check(image!=null&&image.getWidth()>0&&image.getHeight()>0,"valid original PNG");}}
        geometry(root,"base",98,290,432,144);geometry(root,"pillar",18,50,50,32);geometry(root,"main",50,37,18,56);geometry(root,"fan",116,84,157,216);
        var factory=DocumentBuilderFactory.newInstance();factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);var doc=factory.newDocumentBuilder().parse(fixtures.resolve("witness/page_windbase.xml").toFile());var transform=component(widget(doc,"main"),"Transform");equal(176,value(transform,"width"),"source inventorywidth");equal(187,value(transform,"height"),"source inventoryheight");String[] names={"main","middle","base"};int[] y={13,31,49};for(int i=0;i<3;i++){var icon=widget(doc,"icon_"+names[i]);var t=component(icon,"Transform");equal(24,value(t,"width"),"source iconwidth");equal(24,value(t,"height"),"source iconheight");equal(y[i],value(t,"y"),"source iconvertical position");check(t.getElementsByTagName("alignWidth").item(0).getTextContent().equals("CENTER"),"source icon center alignment");check(component(icon,"DrawTexture").getElementsByTagName("texture").item(0).getTextContent().equals("academy:textures/guis/icons/icon_wind_"+names[i]+".png"),"original iconidentity");}
        double[][] alpha={{.2,.2,1},{.2,1,1},{1,1,1},{.6,1,1}};for(int status=0;status<4;status++)for(int icon=0;icon<3;icon++)equal(alpha[status][icon],ClassicWindVisualRules.iconAlpha(ClassicWindRules.Completeness.values()[status])[icon],"source fourstate icon alpha table");for(boolean fan:new boolean[]{false,true})for(boolean noObstacle:new boolean[]{false,true})check(ClassicWindVisualRules.showFan(fan,noObstacle)==(fan&&noObstacle),"literal source fan visibility");
        equal(179,ClassicWindVisualRules.INFO_X,"source172+7 infoareaX");for(int width:new int[]{320,854,1920}){equal((width-172)/2.0-18,ClassicWindVisualRules.mainX(width),"source centered172root plusminus18");equal((width-172)/2.0-20,ClassicWindVisualRules.inventoryX(width),"source176page centered inside172root");equal((width-207)/2,ClassicWindVisualRules.slotX(width),"source GuiContainer176+31 native slotanchor");}equal(99,ClassicWindVisualRules.BASE_INFO_HEIGHT,"source histogram/property/separator height");equal(50,ClassicWindVisualRules.MAIN_INFO_HEIGHT,"source main property minimumheight");check(ClassicWindVisualRules.BUFFER_COLOR==0xff25f7ff,"source histBuffer distinctcyan");
        for(String name:List.of("base","pillar","main")){var json=JsonParser.parseString(Files.readString(root.resolve("src/main/resources/assets/academy/models/item/windgen_"+name+".json"))).getAsJsonObject();check(json.get("parent").getAsString().equals("minecraft:item/generated")&&json.getAsJsonObject("textures").get("layer0").getAsString().equals("academy:blocks/windgen_"+name),"original flat block-icon item");}var fanJson=JsonParser.parseString(Files.readString(root.resolve("src/main/resources/assets/academy/models/item/windgen_fan.json"))).getAsJsonObject();check(fanJson.getAsJsonObject("textures").get("layer0").getAsString().equals("academy:items/windgen_fan"),"original flat fanicon");
        String screen=Files.readString(root.resolve("src/main/java/cn/academy/port/client/ClassicWindScreen.java"));check(screen.contains("if(menu.base())addRenderableWidget(new ClassicWirelessTabButton")&&screen.contains("ui/ui_windbase")&&screen.contains("ui/ui_windmain"),"source two screens/base-only wirelesspage");String renderer=Files.readString(root.resolve("src/main/java/cn/academy/port/client/ClassicWindRenderer.java"));check(renderer.contains("poses.translate(0,.5,.82)")&&renderer.contains("Axis.ZP.rotationDegrees(-main.lastRotation)")&&!renderer.contains("poses.scale("),"literal original rotor transform and meshscale");
        System.out.println("ClassicWindVisualRegressionTest: "+checks+" original asset/topology/UV/GUI/layout/flat-item checks passed; no native rendering acceptance inferred");
    }
}
