package cn.academy.port.client;
import cn.academy.port.skill.LateCombatSourceFixtures;
import com.google.gson.*;
import java.util.*;
import java.nio.file.*;
import javax.tools.ToolProvider;
import static cn.academy.port.client.ClassicMeltdownerLateTimeline.*;
/** Original renderer expression oracle, asset bytes, source caller distinction and independent ordering fences.
 * Native buffer compilation is checked separately; this does not claim rendered pixels/audio parity. */
public final class MeltdownerLateCombatVisualRegressionTest {
 private static int checks;private static void check(boolean ok,String why){checks++;if(!ok)throw new AssertionError(why);}private static void near(double a,double b,String why){check(Math.abs(a-b)<1E-7,why+" actual="+a+" original="+b);}
 private static String method(String text,String signature){int start=text.indexOf(signature);if(start<0)throw new AssertionError("Original missing "+signature);int open=text.indexOf('{',start),depth=0;for(int i=open;i<text.length();i++){char c=text.charAt(i);if(c=='{')depth++;if(c=='}'&&--depth==0)return text.substring(start,i+1);}throw new AssertionError("Unclosed source method");}
 private static java.net.URLClassLoader original()throws Exception{String ripple=LateCombatSourceFixtures.source("academycraft/RippleMarkRender.java.txt"),pre=LateCombatSourceFixtures.source("academycraft/EntityBarrageRayPre.java.txt");String source="package cn.academy.port.skill.lateoracle;public class OriginalVisual{final long CYCLE=3600;long dt;public int life=30;long getDeltaTime(){return dt;}public float height(long m){return getHeight(m);}public float alpha(long m){return getAlpha(m);}public float size(long m){return getSize(m);}public double width(long d,int l){dt=d;life=l;return getWidth();}"+method(ripple,"private float getHeight")+method(ripple,"private float getAlpha")+method(ripple,"private float getSize")+method(pre,"public double getWidth")+"}";Path dir=Files.createTempDirectory("academy-original-late-visual-");Path java=dir.resolve("OriginalVisual.java");Files.writeString(java,source);int result=ToolProvider.getSystemJavaCompiler().run(null,null,null,"-proc:none","-classpath",System.getProperty("java.class.path"),"-d",dir.toString(),java.toString());if(result!=0)throw new AssertionError("Original Java renderer methods compilationfailed");return new java.net.URLClassLoader(new java.net.URL[]{dir.toUri().toURL()},MeltdownerLateCombatVisualRegressionTest.class.getClassLoader());}
 public static void main(String[] args)throws Exception{try(var loader=original()){var type=loader.loadClass("cn.academy.port.skill.lateoracle.OriginalVisual");Object oracle=type.getConstructor().newInstance();for(long m=0;m<3600;m+=7){near(rippleHeight(m),((Number)type.getMethod("height",long.class).invoke(oracle,m)).doubleValue(),"originalripple height");near(rippleAlpha(m),((Number)type.getMethod("alpha",long.class).invoke(oracle,m)).doubleValue(),"originalripple alpha");near(rippleSize(m),((Number)type.getMethod("size",long.class).invoke(oracle,m)).doubleValue(),"originalripple size");}for(int life:new int[]{30,50})for(long age=0;age<=life*50+50;age+=19)near(width(life==30?PRE_PLAIN:PRE_HIT,age,.1),((Number)type.getMethod("width",long.class,int.class).invoke(oracle,age,life)).doubleValue(),"actual invertedclampd preray fullwidth");}
  check(SMALL.lifeTicks()==14&&SMALL.blendIn()==200&&SMALL.blendOut()==400&&SMALL.inner()==.03&&SMALL.outer()==.045&&SMALL.glowWidth()==.3,"original small ray visualspec");check(PRE_PLAIN.lifeTicks()==30&&PRE_HIT.lifeTicks()==50&&PRE_HIT.inner()==.045&&PRE_HIT.outer()==.052&&PRE_HIT.glowWidth()==.4,"distinct originalpre specs");check(BARRAGE_RAY.lifeTicks()==50&&BARRAGE_RAY.blendIn()==100&&BARRAGE_RAY.blendOut()==300&&BARRAGE_RAY.shrink()==300,"barrage inheritsEntityRayBase timings");near(width(SMALL,450,.1),.5,"smallwidth ignoreswiggle");near(width(BARRAGE_RAY,2400,.1),.1+1-200/300.0,"barrage sourcewidthwiggle");
  Random r=new Random(197107);for(int pass=0;pass<1000;pass++){var rays=subrays(r);check(rays.size()>=25&&rays.size()<30,"source25..29subrays");for(var ray:rays)check(Math.abs(ray.yaw())<60&&Math.abs(ray.pitch())<30,"original subray ranges");int count=missileParticleCount(r);check(count>=1&&count<3,"source1..2EMparticles");}
  String missile=LateCombatSourceFixtures.source("academycraft/ElectronMissile.scala.txt"),scatter=LateCombatSourceFixtures.source("academycraft/ScatterBomb.scala.txt"),electron=LateCombatSourceFixtures.source("academycraft/ElectronBomb.scala.txt");check(missile.contains("new EntityMdRaySmall(world)")&&!missile.contains("viewOptimize"),"missile leavestrue viewoptimization");check(scatter.contains("raySmall.viewOptimize = false")&&electron.contains("raySmall.viewOptimize = false"),"earlier callers explicitlydisablefix");String barrage=LateCombatSourceFixtures.source("academycraft/EntityMdRayBarrage.java.txt");check(barrage.contains("return false;")&&barrage.contains("this.plainDoRender"),"barrage explicitnofix and sharedwiggle");String je=LateCombatSourceFixtures.source("academycraft/JetEngine.scala.txt");check(je.contains("for (i <- 0 to 10)")&&je.contains("setPlayerWalkSpeed(0.07f)")&&je.contains("setPlayerWalkSpeed(0.1f)"),"original11jetparticles andwalkspeedrestore");check(!missile.contains("HandRender")&&!je.contains("HandRender"),"noinvented arm/bodypose override");
  var input=new ClassicMeltdownerStarterTimeline.Input();long first=input.press();input.end();check(input.accepts(first)&&!input.mayShowStart(first),"earlyrelease correlatesterminal buthides marker");long second=input.press();check(!input.accepts(first)&&input.accepts(second),"staleinput cannot affectnewpress");input.clear();check(!input.accepts(second)&&input.accepts(0),"worldreplace inputcleared");var tokens=new ClassicMeltdownerBeamTimeline.Tokens();var id=new ClassicMeltdownerBeamTimeline.Caster(7,UUID.randomUUID());var replacement=new ClassicMeltdownerBeamTimeline.Caster(7,UUID.randomUUID());check(tokens.start(id,1)&&!tokens.start(id,1),"duplicatestart rejected");check(tokens.end(id,1)&&!tokens.end(id,1)&&!tokens.start(id,1),"terminaltombstone replayrejects");check(tokens.start(replacement,1)&&tokens.active(replacement,1),"reusedentityid isolatedbyUUID");var clock=new ClassicMeltdownerStarterTimeline.PauseClock();clock.update(1000,true);clock.update(1200,true);clock.update(5000,false);clock.update(5100,true);check(clock.elapsed()==300,"pauseclock freezesrenderage");
  var assets=JsonParser.parseString(resource("classic-oracles/meltdowner-late-combat/assets.json")).getAsJsonObject();for(var entry:assets.getAsJsonArray("assets")){var o=entry.getAsJsonObject();byte[] bytes=bytes("assets/academy/"+o.get("path").getAsString());String sha=HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(bytes));check(sha.equals(o.get("sha256").getAsString()),"identical source asset "+o.get("path"));}var sounds=JsonParser.parseString(resource("assets/academy/sounds.json")).getAsJsonObject();for(var entry:assets.getAsJsonObject("events").entrySet()){var old=entry.getValue().getAsJsonObject().getAsJsonArray("sounds");var modern=sounds.getAsJsonObject(entry.getKey()).getAsJsonArray("sounds");check(old.size()==modern.size(),"originalsoundcount");for(int i=0;i<old.size();i++)check(modern.get(i).getAsJsonObject().get("name").getAsString().equals("academy:"+old.get(i).getAsJsonObject().get("name").getAsString()),"original audio path preserved");}check(sounds.size()>20,"complete sounds registry preserved");
  var mesh=ClassicDeveloperObj.parse(new java.io.StringReader(resource("assets/academy/models/silbarn.obj")));check(!mesh.triangles().isEmpty(),"realoriginal OBJ parsed");for(var context:ClassicPortableTransform.Context.values()){var m=ClassicSilbarnTransform.matrix(context,false);check(Float.isFinite(m.determinant())&&Math.abs(m.determinant())>0,"finite originalSilbarn matrix");}System.out.println("PASS "+checks+" pinnedoriginal visuals/assets/caller distinctions and replay/lifecycle mathchecks; pixels/audio pending");}
 private static byte[] bytes(String path)throws Exception{try(var in=MeltdownerLateCombatVisualRegressionTest.class.getResourceAsStream("/"+path)){if(in==null)throw new AssertionError("Missing runtimeclasspath resource "+path);return in.readAllBytes();}}private static String resource(String path)throws Exception{return new String(bytes(path),java.nio.charset.StandardCharsets.UTF_8);}
}
