package cn.academy.port.client;
import cn.academy.port.skill.TeleporterSourceFixtures;
import com.google.gson.JsonParser;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
public final class TeleporterProgressionVisualRegressionTest {
 static void check(boolean b,String s){if(!b)throw new AssertionError(s);}public static void main(String[] args)throws Exception{TeleporterSourceFixtures.verify();String render=TeleporterSourceFixtures.source("AcademyCraft-1.0.7","src/main/java/cn/academy/vanilla/teleporter/client/MarkRender.java");for(String s:List.of("getEffectSeq(\"tp_mark\", 7)","mark.ticksExisted / 2.5","GL11.GL_DEPTH_TEST","GL11.glScaled(-1, -1, 1)","GL11.glColor4d(1, 0.2, 0.2, 1)","model.draw()"))TeleporterSourceFixtures.contains(render,s);String fr=TeleporterSourceFixtures.skill("FleshRipping");for(String s:List.of("setColor4i(74, 74, 74, 160)","setColor4i(185, 25, 25, 180)","at.target.width * 1.2f","at.target.height * 1.2f","\"tp.guts\", 0.6f","0.5 * RandUtils.ranged(0.8 * e.width, e.width)"))TeleporterSourceFixtures.contains(fr,s);for(int tick=0;tick<350;tick++)check(ClassicTeleporterTimeline.markFrame(tick)==(int)((tick/2.5)%7),"seven frames 2.5tick cycle");check(ClassicTeleporterTimeline.BIPED.size()==7,"static source biped including headwear");int vertices=0;for(var box:ClassicTeleporterTimeline.BIPED){check(ClassicTeleporterTimeline.mesh(box).size()==6,"six ModelBox faces");for(var q:ClassicTeleporterTimeline.mesh(box))for(var v:List.of(q.a(),q.b(),q.c(),q.d())){check(Double.isFinite(v.x()+v.y()+v.z()),"finite geometry");check(v.u()>=0&&v.u()<=1&&v.v()>=0&&v.v()<=1,"legacy64x32 UV bounds");vertices++;}}check(vertices==168,"seven boxes six quads four vertices");check(ClassicTeleporterTimeline.bloodCount(4)==5&&ClassicTeleporterTimeline.bloodCount(5)==6,"source inclusive range after exclusive RNG");check(ClassicTeleporterTimeline.bloodAlive(9)&&!ClassicTeleporterTimeline.bloodAlive(10),"ten tick blood lifecycle");check(ClassicTeleporterTimeline.particleAlpha(0)==0&&ClassicTeleporterTimeline.particleAlpha(5)==1&&ClassicTeleporterTimeline.particleAlpha(20)==1&&ClassicTeleporterTimeline.particleAlpha(40)==0,"TP5fadein20life20fade");int count=0;try(var in=TeleporterProgressionVisualRegressionTest.class.getResourceAsStream("/classic-teleporter-source/media-hashes.json")){var manifest=JsonParser.parseString(new String(in.readAllBytes(),StandardCharsets.UTF_8)).getAsJsonObject();for(var e:manifest.getAsJsonArray("media")){var entry=e.getAsJsonObject();String path="/assets/academy/"+entry.get("path").getAsString();try(var asset=TeleporterProgressionVisualRegressionTest.class.getResourceAsStream(path)){check(asset!=null,"missing original asset "+path);String hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(asset.readAllBytes()));check(hash.equals(entry.get("sha256").getAsString()),"original media SHA256 "+path);count++;}}}System.out.println("PASS source destination-biped/color/UV/corner/blood/particle contracts and "+count+" exact original media hashes; GPU/audio/physical input remain pending");}
}
