package cn.academy.port.client;
import cn.academy.port.skill.VectorFinalSourceFixtures;
import cn.academy.port.skill.finaloracle.*;
import java.util.*;
/** Pinned shader/mesh/animation contract; native pixel and audible acceptance are separate. */
public final class VectorFinalVisualRegressionTest {
 private static int checks;private static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}private static void near(double a,double b,String why){check(Math.abs(a-b)<1E-7,why+" actual="+a+" expected="+b);}
 public static void main(String[] args)throws Exception{
  String wave=VectorFinalSourceFixtures.source("academy/WaveEffect.scala"),ui=VectorFinalSourceFixtures.source("academy/WaveEffectUI.scala"),body=VectorFinalSourceFixtures.source("academy/PlasmaBodyEffect.scala"),tornado=VectorFinalSourceFixtures.source("academy/TornadoEffect.scala"),skill=VectorFinalSourceFixtures.source("academy/PlasmaCannon.scala"),shader=VectorFinalSourceFixtures.source("academy/plasma_body.frag");
  check(VectorFinalSourceFixtures.source("lambdalib/MeshUtils.java").contains("{ x1, y1, 0 }"),"original billboard x1,y1 endpoint semantics");
  check(wave.contains("MeshUtils.createBillboard(mesh, -.5, -.5, 1, 1)")&&wave.contains("val life = 15"),"source asymmetric1.5 wave quad and life15");check(ui.contains("if (RandUtils.nextFloat < deltaTime * intensity)")&&ui.contains("size + timeAlive * 20"),"frame Bernoulli and linear expansion");check(VectorFinalSourceFixtures.source("academy/VecReflection.scala").contains("new WaveEffectUI(0.4f, 110, 1.6f)"),"exact reflection ripple parameters");
  check(body.contains("0 until 4")&&body.contains("0 until rangei(4, 6)")&&body.contains("val size = 22")&&body.contains("val alpha = math.pow(eff.alpha, 2).toFloat"),"source8/9 metaballs,22 billboard,squared alpha");check(body.contains("initTime = GameTimer.getTime")&&body.contains("val deltaTime = eff.deltaTime"),"reset frame delta preserves source phase quirk");check(tornado.contains("val divide = 40")&&tornado.contains("val div = 20")&&skill.contains("new TornadoEffect(12, 8, 1, 0.3)"),"literal source tornado parameters");check(skill.contains("if (deadTick == 30)")&&skill.contains("1 - deadTick / 20.0f"),"negative tail until thirty ticks retained");
  for(int i=0;i<2000;i++){double x=(i-1000)/23.0,y=i/57.0,z=i/71.0;near(ClassicVectorFinalNoise.noise(x,y,z),ClassicNoiseOracle.noise(x,y,z),"unchanged source noise implementation");}
  for(int seed=0;seed<200;seed++){var balls=ClassicVectorFinalTimeline.balls(new Random(seed));check(balls.size()==8||balls.size()==9,"exclusive small-count bounds");for(int i=0;i<balls.size();i++){var b=balls.get(i);check(i<4?b.size()>=1&&b.size()<1.5:b.size()>=.1&&b.size()<.3,"source ball size ranges");for(float dt:new float[]{0,.016F,.05F,1}){double[] at=ClassicVectorFinalTimeline.ball(b,dt);near(at[3],b.size(),"sphere radius");check(Double.isFinite(at[0]+at[1]+at[2]),"finite source animation");}}var rings=ClassicVectorFinalTimeline.rings(new Random(seed));check(!rings.isEmpty()&&rings.size()<200,"density source ring generation");for(var r:rings)for(double time:new double[]{0,1,100}){double[] v=ClassicVectorFinalTimeline.ring(r,time);double ny=r.y()/12,t=time*.1;near(v[0],ClassicVectorFinalNoise.noise(ny,t)*(.3+Math.pow(ny*2,1.4))*8*.3,"noise drift X");near(v[3],.1*(1+.5*ny)*time+r.phase(),"source radianlike texture phase");}}
  for(int age=0;age<50;age++){near(ClassicVectorFinalTimeline.tornadoAlpha(age,false,0),(age<20?age/20F:1)*.5*.7,"fade in source float");near(ClassicVectorFinalTimeline.tornadoAlpha(age,true,age),(1-age/20F)*.5*.7,"negative source fade raw");}
  near(ClassicVectorFinalTimeline.bodyAlpha(.1F,.5F,false),.1F+.5F*.3F,"slow body alpha rise");near(ClassicVectorFinalTimeline.bodyAlpha(.2F,.5F,true),0,"fast body alpha fall");check(shader.contains("dir *= 0.15")&&shader.contains("i < 20 && accum.a < 1")&&shader.contains("float alpha = 0.075 * density")&&shader.contains("2 * accum.a - 0.2"),"literal raymarch core retained");String modern;try(var in=VectorFinalVisualRegressionTest.class.getResourceAsStream("/assets/academy/shaders/core/classic_plasma_body.fsh")){check(in!=null,"modern shader exists");modern=new String(in.readAllBytes(),java.nio.charset.StandardCharsets.UTF_8);}
  for(String function:List.of("vec4 rayMarch","void main")){int a=shader.indexOf(function),b=modern.indexOf(function);String tail=shader.substring(a).replace("gl_FragColor = rc;","fragColor = rc;");check(modern.substring(b).equals(tail),"unchanged original shader tail "+function);}
  var sample=ClassicVectorFinalTimeline.rayMarch(new double[]{0,0,12},List.of(new double[]{0,0,12,1}),1);check(sample[3]>0&&sample[3]<=1,"source CPU raymarch finite nonempty density");
  var tokens=new ClassicVectorStarterTimeline.Tokens();check(tokens.start("plasma_cannon",3,1),"new token");check(tokens.end("plasma_cannon",3,1),"terminal tombstone");check(!tokens.start("plasma_cannon",3,1)&&!tokens.live("plasma_cannon",3,1),"late start cannot resurrect");check(tokens.start("plasma_cannon",3,2)&&!tokens.end("plasma_cannon",3,1),"old terminal cannot end replacement");
  for(String media:List.of("sounds/vecmanip/vec_reflection.ogg","sounds/vecmanip/plasma_cannon.ogg","sounds/vecmanip/plasma_cannon_t.ogg","textures/effects/glow_circle.png","textures/effects/tornado_ring.png")){byte[] expected=VectorFinalSourceFixtures.bytes("media/"+media);try(var in=VectorFinalVisualRegressionTest.class.getResourceAsStream("/assets/academy/"+media)){check(in!=null&&Arrays.equals(expected,in.readAllBytes()),"original hashed production media "+media);}}
  System.out.println("PASS "+checks+" source-pinned final vector visual/media/transport checks");
 }
}
