package oracle;
import cn.academy.support.rf.*;import cn.academy.support.EnergyBlockHelper;import cn.lambdalib.s11n.network.NetworkMessage;import net.minecraft.tileentity.TileEntity;import net.minecraft.nbt.NBTTagCompound;import net.minecraftforge.common.util.ForgeDirection;import cofh.api.energy.*;import java.util.*;
public class OriginalRFHarness{
 public final TileRFInput input=new TileRFInput();public final TileRFOutput output=new TileRFOutput();public OriginalRFHarness(double a,double b){input.setEnergy(a);output.energy=b;}
 public double inputEnergy(){return input.getEnergy();}public double outputEnergy(){return output.energy;}
 public int receive(int amount,boolean simulation){return input.receiveEnergy(ForgeDirection.UP,amount,simulation);}public int extract(int amount,boolean simulation){return output.extractEnergy(ForgeDirection.UP,amount,simulation);}
 public double provide(double amount){return input.getProvidedEnergy(amount);}public double inject(double amount){return output.injectEnergy(amount);}
 public double inputCapacity(){return input.bufferSize;}public double outputCapacity(){return output.getMaxEnergy();}public double inputBandwidth(){return input.bandwidth;}public double outputBandwidth(){return output.getBandwidth();}public int inputInventory(){return input.size;}public int outputInventory(){return output.size;}
 public boolean allFaces(){for(var face:ForgeDirection.values())if(!input.canConnectEnergy(face)||!output.canConnectEnergy(face))return false;return true;}
 public double inputReload(){var tag=new NBTTagCompound();input.writeToNBT(tag);var other=new TileRFInput();other.readFromNBT(tag);return other.getEnergy();}public double outputReload(){var tag=new NBTTagCompound();output.writeToNBT(tag);var other=new TileRFOutput();other.readFromNBT(tag);return other.energy;}
 public double managerCharge(double amount){var receiver=new Foreign();return new RFReceiverManager().charge(receiver,amount,false);}public double managerStored(){var provider=new Foreign();return new RFProviderManager().getEnergy(provider);}public double managerPull(double amount){var provider=new Foreign();return new RFProviderManager().pull(provider,amount,false);}
 public double helperCharge(double amount){EnergyBlockHelper.register(new RFReceiverManager());return EnergyBlockHelper.charge(new Foreign(),amount,false);}
 public int recipeCount()throws Exception{var init=RFSupport.class.getDeclaredMethod("init");init.setAccessible(true);init.invoke(null);return cpw.mods.fml.common.registry.GameRegistry.recipes.size();}
 public String recipe(int index){var row=cpw.mods.fml.common.registry.GameRegistry.recipes.get(index);StringBuilder result=new StringBuilder(((net.minecraft.block.Block)((net.minecraft.item.ItemStack)row[0]).item).name);for(int i=1;i<row.length;i++){Object v=row[i];if(v instanceof net.minecraft.item.Item item)v=item.name;else if(v instanceof net.minecraft.item.ItemStack item)v=((net.minecraft.block.Block)item.item).name;result.append('|').append(v);}return result.toString();}
 public String order(){NetworkMessage.sent.clear();StringBuilder calls=new StringBuilder();for(var face:ForgeDirection.VALID_DIRECTIONS){var endpoint=new Foreign(){@Override public int receiveEnergy(ForgeDirection from,int amount,boolean simulate){calls.append(face).append(':').append(from).append('|');return Math.min(4,amount);}};output.getWorldObj().put(face.offsetX,face.offsetY,face.offsetZ,endpoint);}output.updateEntity();return calls.toString();}
 public double tickPublication(){NetworkMessage.sent.clear();output.energy=100;var endpoint=new Foreign(){public int receiveEnergy(ForgeDirection face,int amount,boolean simulate){return Math.min(amount,4);}};output.getWorldObj().put(0,-1,0,endpoint);for(int t=0;t<20;t++)output.updateEntity();return NetworkMessage.sent.get(0).energy();}
 public static class Foreign extends TileEntity implements IEnergyProvider,IEnergyReceiver{int stored=40;public boolean canConnectEnergy(ForgeDirection dir){return true;}public int getEnergyStored(ForgeDirection dir){return stored;}public int getMaxEnergyStored(ForgeDirection dir){return 10000;}public int receiveEnergy(ForgeDirection dir,int amount,boolean simulate){if(!simulate)stored+=amount;return amount;}public int extractEnergy(ForgeDirection dir,int amount,boolean simulate){int moved=Math.min(stored,amount);if(!simulate)stored-=moved;return moved;}}
}

