/* Unchanged LambdaLib scheduler/ElementList differential, packaged original Scala/Java witnesses. */
package cn.academy.port.interferer;
import cn.academy.port.client.ClassicInterfererVisualRules;
import com.google.gson.JsonParser;
import java.net.URLClassLoader;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.function.Supplier;
import javax.tools.ToolProvider;
/** The unchanged Scala Interferer is a witness, not claimed to have been compiled by javac. */
public final class ClassicInterfererSourceOracleTest {
    private static int checks;
    private static final String MANIFEST_SHA="43471a12761aa399cf4fe39bd1a09c2be186a3843448521ce2a03e36312c3cda";
    private static void check(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}
    private static String sha(byte[] bytes)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}
    public static void main(String[] args)throws Exception{
        Path root=Path.of(System.getProperty("academy.interferer.stage",".")),fixture=root.resolve("src/test/resources/classic-interferer-source");byte[] manifest=Files.readAllBytes(fixture.resolve("witness-manifest.json"));check(sha(manifest).equals(MANIFEST_SHA),"independently frozen unchanged-original manifest");for(var entry:JsonParser.parseString(new String(manifest,java.nio.charset.StandardCharsets.UTF_8)).getAsJsonObject().getAsJsonArray("files")){var e=entry.getAsJsonObject();check(sha(Files.readAllBytes(fixture.resolve(e.get("path").getAsString()))).equals(e.get("sha256").getAsString()),"unchanged packaged original "+e.get("path"));}
        String source=Files.readString(fixture.resolve("AcademyCraft/src/main/scala/cn/academy/ability/block/AbilityInterferer.scala"));String effect=source.substring(source.indexOf("// Check player in the area"),source.indexOf("// Sync data to client"));check(!effect.contains("whitelist")&&!effect.contains("placer")&&!effect.contains("energy")&&effect.contains("boundingBox.isVecInside")&&effect.contains("!player.capabilities.isCreativeMode"),"exact original captured-predicate whitelist omission/creative exception");check(source.contains("class TileAbilityInterferer extends TileEntity")&&source.contains("scheduler.every(10)")&&source.contains("scheduler.every(20)")&&source.contains("TargetPoints.convert(this, 15)"),"plain unpowered tile/source10/20/15 values");String persist=source.substring(source.indexOf("override def readFromNBT"),source.indexOf("class AbilityInterferer extends"));check(!persist.contains("placer_")&&persist.contains("tag.getFloat(\"range_\")")&&persist.contains("tag.setFloat(\"range_\", range_.toFloat)"),"unchanged original float-save and omitted placer");String module=Files.readString(fixture.resolve("AcademyCraft/src/main/java/cn/academy/ability/ModuleAbility.java"));String declaration=module.substring(module.lastIndexOf("@RegBlock",module.indexOf("public static AbilityInterferer")),module.indexOf("public static AbilityInterferer")+70);check(!declaration.contains("RecipeName"),"source registration has no recipe alias");String recipe=Files.readString(fixture.resolve("AcademyCraft/src/main/resources/assets/academy/recipes/default.recipe"));check(!recipe.toLowerCase(Locale.ROOT).contains("interfer"),"unchanged49-declaration default recipes never acquire Interferer");
        String serializer=Files.readString(fixture.resolve("LambdaLib/src/main/java/cn/lambdalib/s11n/nbt/NBTS11n.java"));check(serializer.contains("tag.setInteger(\"size\", length)")&&serializer.contains("tag.setTag(String.valueOf(i), writeBase(Array.get(obj, i), baseType))"),"unchanged original compound array size/index representation");
        Path output=Files.createTempDirectory("academy-interferer-original-");try{
            List<String> compile=new ArrayList<>(List.of("-proc:none","-encoding","UTF-8","-d",output.toString()));compile.add(fixture.resolve("LambdaLib/src/main/java/cn/lambdalib/util/helper/TickScheduler.java").toString());compile.add(fixture.resolve("LambdaLib/src/main/java/cn/lambdalib/cgui/gui/component/ElementList.java").toString());try(var paths=Files.walk(fixture.resolve("stubs"))){paths.filter(p->p.toString().endsWith(".java")).sorted().forEach(p->compile.add(p.toString()));}var compiler=ToolProvider.getSystemJavaCompiler();check(compiler!=null&&compiler.run(null,null,null,compile.toArray(String[]::new))==0,"unchanged upstream scheduler/list compile independently against minimal old-boundary stubs");
            try(var loader=new URLClassLoader(new java.net.URL[]{output.toUri().toURL()},ClassLoader.getPlatformClassLoader())){scheduler(loader);lists(loader);}
        }finally{try(var paths=Files.walk(output)){for(var path:paths.sorted(Comparator.reverseOrder()).toList())Files.delete(path);}}
        System.out.println("ClassicInterfererSourceOracleTest: "+checks+" unchanged-original scheduler/list differential and immutable source acquisition/quirk witnesses passed; original Scala tile compilation and native execution unclaimed");
    }
    @SuppressWarnings({"unchecked","rawtypes"}) private static void scheduler(ClassLoader loader)throws Exception{
        var type=loader.loadClass("cn.lambdalib.util.helper.TickScheduler");var side=loader.loadClass("cpw.mods.fml.relauncher.Side");Object server=Enum.valueOf((Class)side,"SERVER");Random random=new Random(107);
        for(int run=0;run<64;run++){Object original=type.getConstructor().newInstance();boolean[] enabled={false};int[] fired={0,0};Object scan=type.getMethod("every",int.class).invoke(original,10);scan.getClass().getMethod("atOnly",side).invoke(scan,server);scan.getClass().getMethod("condition",Supplier.class).invoke(scan,(Supplier<Boolean>)()->enabled[0]);scan.getClass().getMethod("run",Runnable.class).invoke(scan,(Runnable)()->fired[0]++);Object sync=type.getMethod("every",int.class).invoke(original,20);sync.getClass().getMethod("atOnly",side).invoke(sync,server);sync.getClass().getMethod("run",Runnable.class).invoke(sync,(Runnable)()->fired[1]++);var modern=new ClassicInterfererRules.Clock();
            for(int tick=0;tick<4000;tick++){enabled[0]=run==0||run>1&&random.nextInt(7)!=0;int a=fired[0],b=fired[1];type.getMethod("runTick").invoke(original);var due=modern.tick(enabled[0]);check(due.scan()==(fired[0]!=a)&&due.sync()==(fired[1]!=b),"exact unchanged condition-sensitive10/20 schedule "+run+"/"+tick);}
        }
    }
    private static void lists(ClassLoader loader)throws Exception{
        var list=loader.loadClass("cn.lambdalib.cgui.gui.component.ElementList");var widget=loader.loadClass("cn.lambdalib.cgui.gui.Widget");var component=loader.loadClass("cn.lambdalib.cgui.gui.component.Component");
        for(int count=0;count<=128;count++){Object old=list.getConstructor().newInstance();Object area=component.getField("widget").get(old);Object transform=widget.getField("transform").get(area);transform.getClass().getField("height").setDouble(transform,80);for(int n=0;n<count;n++){Object row=widget.getConstructor().newInstance();Object rt=widget.getField("transform").get(row);rt.getClass().getField("height").setDouble(rt,16);list.getMethod("addWidget",widget).invoke(old,row);}list.getMethod("onAdded").invoke(old);int maximum=(int)list.getMethod("getMaxProgress").invoke(old);check(maximum==ClassicInterfererVisualRules.maxProgress(count),"unchanged list maximum including source5-row equality quirk");for(int progress=-1;progress<=maximum+1;progress++){list.getMethod("setProgress",int.class).invoke(old,progress);int actual=(int)list.getMethod("getProgress").invoke(old);List<?> children=(List<?>)list.getMethod("getSubWidgets").invoke(old);int visible=0;for(Object child:children){Object t=widget.getField("transform").get(child);if(t.getClass().getField("doesDraw").getBoolean(t))visible++;}check(visible==ClassicInterfererVisualRules.visibleRows(count,actual),"unchanged fully-visible-list rows");}}
    }
}
