package cn.academy.port.gametest;
import cn.academy.port.energy.*;
import cn.academy.port.fusion.*;
import cn.academy.port.fusion.phase.*;
import cn.academy.port.machine.MachineDevelopers;
import cn.academy.port.solar.*;
import cn.academy.port.survival.ClassicMaterials;
import com.mojang.authlib.GameProfile;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.core.registries.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.RandomSource;
import net.minecraft.world.*;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.item.*;
import net.minecraft.world.item.crafting.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.feature.*;
import net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration;
import net.minecraft.world.phys.*;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.neoforge.common.util.FakePlayer;
import net.neoforged.neoforge.event.level.LevelEvent;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.capability.IFluidHandler;
import net.neoforged.neoforge.gametest.*;

/** Native fixtures report seeded terrain/raw materials explicitly, with no forged charged/fluid payload. */
@GameTestHolder("academy") @PrefixGameTestTemplate(false) @EventBusSubscriber(modid="academy")
public final class AcademyFusionRuntimeTests {
    private static final String TEMPLATE="runtime_empty",WIDE="fusion_runtime_empty",BATCH="academy_fusion";
    private static final BlockPos BASE=new BlockPos(3,1,4);
    private static final IFluidHandler.FluidAction EXEC=IFluidHandler.FluidAction.EXECUTE,SIM=IFluidHandler.FluidAction.SIMULATE;
    private AcademyFusionRuntimeTests(){}
    private static ResourceLocation id(String path){return ResourceLocation.parse(path.contains(":")?path:"academy:"+path);}
    private static void equal(GameTestHelper h,double expected,double actual,String label){h.assertTrue(Double.isFinite(actual)&&Math.abs(expected-actual)<1e-7,label+": "+actual);}
    private static ClassicFusorBlockEntity fusor(GameTestHelper h){h.setBlock(BASE,ClassicFusion.FUSOR_BLOCK.get());return (ClassicFusorBlockEntity)h.getBlockEntity(BASE);}
    private static FakePlayer player(GameTestHelper h){var p=new FakePlayer(h.getLevel(),new GameProfile(UUID.randomUUID(),"[AC-Fusion-Test]"));var at=h.absoluteVec(new Vec3(3.5,1,2.5));p.moveTo(at.x,at.y,at.z,0,0);p.getAbilities().instabuild=false;return p;}
    private static ItemStack craft(GameTestHelper h,String recipe,int width,int height,ItemStack... cells){var nativeRecipe=(CraftingRecipe)h.getLevel().getRecipeManager().byKey(id("classic/"+recipe)).orElseThrow().value();var input=CraftingInput.of(width,height,List.of(cells));h.assertTrue(nativeRecipe.matches(input,h.getLevel()),"actual native source grid "+recipe);return nativeRecipe.assemble(input,h.getLevel().registryAccess());}
    private static ItemStack s(Item item){return new ItemStack(item);}private static ItemStack e(){return ItemStack.EMPTY;}
    @SubscribeEvent public static void installTemplate(LevelEvent.Load event){if(!GameTestHooks.isGametestEnabled()||!(event.getLevel() instanceof ServerLevel level))return;var tag=new CompoundTag();var size=new ListTag();for(int v:new int[]{40,48,56})size.add(IntTag.valueOf(v));tag.put("size",size);var origin=new ListTag();for(int i=0;i<3;i++)origin.add(IntTag.valueOf(0));var air=new CompoundTag();air.put("pos",origin);air.putInt("state",0);var blocks=new ListTag();blocks.add(air);tag.put("blocks",blocks);tag.put("entities",new ListTag());var palette=new ListTag();var name=new CompoundTag();name.putString("Name","minecraft:air");palette.add(name);tag.put("palette",palette);level.getStructureManager().getOrCreate(id(WIDE)).load(level.registryAccess().lookupOrThrow(Registries.BLOCK),tag);}

    @GameTest(template=TEMPLATE,batch=BATCH)
    public static void fusion_native_identity_source_slots_and_sided_rules(GameTestHelper h){var p=player(h);var tile=fusor(h);var level=h.getLevel();
        equal(h,0,tile.getEnergy(),"new genuine machine empty");h.assertValueEqual(tile.liquid(),0,"new genuine tank empty");equal(h,2000,tile.getMaxEnergy(),"source capacity");equal(h,50,tile.getBandwidth(),"source bandwidth");
        h.assertTrue(level.getCapability(MachineDevelopers.IMAG_FLUX,tile.getBlockPos(),Direction.NORTH)==tile,"genuine native IF receiver");h.assertTrue(level.getCapability(Capabilities.FluidHandler.BLOCK,tile.getBlockPos(),Direction.UP)==tile.fluidHandler(),"genuine native imagProj tank");
        h.assertTrue(Arrays.equals(tile.getSlotsForFace(Direction.UP),new int[]{0,2}),"source top input/matter");h.assertTrue(Arrays.equals(tile.getSlotsForFace(Direction.DOWN),new int[]{1,4,3}),"source bottom crystal/matter/energy order");h.assertTrue(Arrays.equals(tile.getSlotsForFace(Direction.NORTH),new int[]{3}),"source side energy");h.assertTrue(!tile.canTakeItemThroughFace(0,s(ClassicMaterials.CRYSTAL_LOW.get()),Direction.UP),"top extraction denied");
        h.assertValueEqual(tile.fluidHandler().fill(new FluidStack(net.minecraft.world.level.material.Fluids.WATER,1000),EXEC),0,"water is never substitute phase");h.assertTrue(!new ItemStack(Items.WOODEN_PICKAXE).isCorrectToolForDrops(tile.getBlockState()),"source harvest stone tier");h.assertTrue(new ItemStack(Items.STONE_PICKAXE).isCorrectToolForDrops(tile.getBlockState()),"source stone tier sufficient");
        var menu=(ClassicFusorMenu)tile.createMenu(1,p.getInventory(),p);h.assertValueEqual(menu.slots.size(),41,"five source machine+36player slots");int[] order={0,1,2,4,3};for(int index=0;index<5;index++)h.assertValueEqual(menu.slots.get(index).getContainerSlot(),order[index],"source menu/raw slot mapping");
        h.assertTrue(!menu.slots.get(1).mayPlace(s(ClassicMaterials.CRYSTAL_NORMAL.get()))&&!menu.slots.get(3).mayPlace(s(ClassicFusion.MATTER_UNIT.get())),"source output slots deny placement");p.getInventory().setItem(0,s(ClassicEnergyItems.ENERGY_UNIT.get()));h.assertTrue(!menu.quickMoveStack(p,5).isEmpty()&&tile.getItem(3).is(ClassicEnergyItems.ENERGY_UNIT.get()),"shift energy goes to raw energy3/menu4");h.assertTrue(!menu.quickMoveStack(p,4).isEmpty()&&tile.getItem(3).isEmpty(),"energy can shift back, corrected source off-by-one mapping");h.succeed();
    }
    @GameTest(template=TEMPLATE,batch=BATCH)
    public static void fusion_native_finite_fluid_container_and_energy_unit_exchange(GameTestHelper h){var phase=new FluidStack(ClassicFusion.PHASE_SOURCE.get(),1000);var empty=s(ClassicFusion.MATTER_UNIT.get());var handler=empty.getCapability(Capabilities.FluidHandler.ITEM);
        h.assertTrue(handler!=null,"matter native fluid capability");h.assertValueEqual(handler.fill(phase,SIM),1000,"source complete-unit simulatedfill");h.assertTrue(handler.getContainer().is(ClassicFusion.MATTER_UNIT.get()),"simulation does not swap");h.assertValueEqual(handler.fill(new FluidStack(ClassicFusion.PHASE_SOURCE.get(),999),EXEC),0,"partial matterfill denied");h.assertValueEqual(handler.fill(phase,EXEC),1000,"source1000mB fill");h.assertTrue(handler.getContainer().is(ClassicFusion.PHASE_MATTER_UNIT.get()),"actual filled material variant");h.assertTrue(handler.drain(999,EXEC).isEmpty(),"source indivisible drain");h.assertValueEqual(handler.drain(1000,EXEC).getAmount(),1000,"source1000mB returned");h.assertTrue(handler.getContainer().is(ClassicFusion.MATTER_UNIT.get()),"empty container refund");
        var unit=s(ClassicEnergyItems.ENERGY_UNIT.get());var energyFluid=unit.getCapability(Capabilities.FluidHandler.ITEM);h.assertTrue(energyFluid!=null,"real source energy-unit fluid registration");h.assertValueEqual(energyFluid.fill(phase,SIM),1000,"source energyfill simulation");equal(h,0,ClassicEnergyItemHelper.getEnergy(unit),"simulation no IF mint");h.assertValueEqual(energyFluid.fill(phase,EXEC),1000,"source1000mB to full10000IF");equal(h,10000,ClassicEnergyItemHelper.getEnergy(unit),"finite source full payload");h.assertValueEqual(energyFluid.drain(1000,SIM).getAmount(),1000,"source full payload simulation");equal(h,10000,ClassicEnergyItemHelper.getEnergy(unit),"simulated drain no debit");h.assertValueEqual(energyFluid.drain(1000,EXEC).getAmount(),1000,"source full to1000mB");equal(h,0,ClassicEnergyItemHelper.getEnergy(unit),"actual drain empties energy");ClassicEnergyItemHelper.setEnergy(unit,1234);h.assertTrue(energyFluid.drain(1000,EXEC).isEmpty(),"partial IF cannot synthesize full fluid unit");h.assertValueEqual(energyFluid.fill(phase,EXEC),0,"partial IF is not sourceemptyvariant");equal(h,1234,ClassicEnergyItemHelper.getEnergy(unit),"rejected transfers retain partial finite IF");ClassicEnergyItemHelper.setEnergy(unit,9890);h.assertValueEqual(unit.getDamageValue(),0,"source rounded gauge mayshowfull while IFispartial");h.assertTrue(energyFluid.drain(1000,EXEC).isEmpty(),"damage0 partial unit cannotroundmintfluid");equal(h,9890,ClassicEnergyItemHelper.getEnergy(unit),"rounded-endpoint rejection conserves IF");ClassicEnergyItemHelper.setEnergy(unit,100);h.assertValueEqual(unit.getDamageValue(),13,"source rounded gauge mayshowempty while IFispartial");h.assertValueEqual(energyFluid.fill(phase,EXEC),0,"damage13 partial unit is not exact empty endpoint");var stacked=new ItemStack(ClassicFusion.MATTER_UNIT.get(),2);h.assertValueEqual(stacked.getCapability(Capabilities.FluidHandler.ITEM).fill(phase,EXEC),0,"capability requires one container, no whole-stack swap");h.succeed();
    }
    @GameTest(template=TEMPLATE,batch=BATCH)
    public static void fusion_native_nbt_tank_inventory_progress_reset_and_once_drop(GameTestHelper h){var tile=fusor(h);var level=h.getLevel();tile.injectEnergy(2000);tile.fluidHandler().fill(new FluidStack(ClassicFusion.PHASE_SOURCE.get(),3000),EXEC);tile.setItem(0,s(ClassicMaterials.CRYSTAL_LOW.get()));var battery=s(ClassicEnergyItems.ENERGY_UNIT.get());ClassicEnergyItemHelper.setEnergy(battery,456.375);tile.setItem(3,battery);for(int i=0;i<20;i++)ClassicFusorBlockEntity.serverTick(level,tile.getBlockPos(),tile.getBlockState(),tile);h.assertTrue(tile.workProgress()>0,"actual partial work");tile.pullEnergy(.375);double before=tile.getEnergy(),charge=ClassicEnergyItemHelper.getEnergy(battery);var tag=tile.saveWithFullMetadata(level.registryAccess());tile.clearContent();tile.loadWithComponents(tag,level.registryAccess());equal(h,before,tile.getEnergy(),"fractional source buffer survives");h.assertValueEqual(tile.liquid(),3000,"source real tank persisted");equal(h,charge,ClassicEnergyItemHelper.getEnergy(tile.getItem(3)),"inventory energy payload persists");h.assertTrue(!tile.isWorking()&&tile.workProgress()==0,"source recipe/progress omitted from NBT");
        tag.putDouble("energy",Double.NaN);tile.loadWithComponents(tag,level.registryAccess());equal(h,0,tile.getEnergy(),"malformed storage finite");var stale=tile.fluidHandler();var pos=tile.getBlockPos();level.destroyBlock(pos,true);h.assertValueEqual(stale.fill(new FluidStack(ClassicFusion.PHASE_SOURCE.get(),1000),EXEC),0,"removed tank cannot accept phantom fluid");h.assertTrue(stale.drain(1000,EXEC).isEmpty(),"removed tank cannot output phantom fluid");int machines=0,crystals=0,batteries=0;for(var entity:level.getEntitiesOfClass(ItemEntity.class,new AABB(pos).inflate(3))){var stack=entity.getItem();if(stack.is(ClassicFusion.FUSOR_ITEM.get()))machines+=stack.getCount();if(stack.is(ClassicMaterials.CRYSTAL_LOW.get()))crystals+=stack.getCount();if(stack.is(ClassicEnergyItems.ENERGY_UNIT.get()))batteries+=stack.getCount();}h.assertValueEqual(machines,1,"one source machine loot");h.assertValueEqual(crystals,1,"source crystal inventory drops once");h.assertValueEqual(batteries,1,"source battery drops once");h.succeed();
    }

    @GameTest(template=TEMPLATE,batch=BATCH)
    public static void phase_native_original_quanta_downflow_lateral_reach_and_light(GameTestHelper h){
        var level=h.getLevel();var center=h.absolutePos(new BlockPos(3,2,4));
        for(int x=-3;x<=3;x++)for(int z=-3;z<=3;z++){level.setBlock(center.offset(x,-1,z),Blocks.STONE.defaultBlockState(),Block.UPDATE_CLIENTS);level.setBlock(center.offset(x,0,z),Blocks.AIR.defaultBlockState(),Block.UPDATE_CLIENTS);level.setBlock(center.offset(x,1,z),Blocks.AIR.defaultBlockState(),Block.UPDATE_CLIENTS);}
        level.setBlock(center,ClassicFusion.PHASE_BLOCK.get().defaultBlockState(),Block.UPDATE_CLIENTS);var source=level.getFluidState(center);h.assertTrue(source.isSource()&&source.getAmount()==3,"original3quanta source");equal(h,.875,source.getOwnHeight(),"source Forge render surface .875");h.assertValueEqual(level.getBlockState(center).getLightEmission(level,center),5,"source phase block light5 not type8");source.tick(level,center);
        var first=center.east();h.assertTrue(level.getBlockState(first).is(ClassicFusion.PHASE_BLOCK.get()),"registered fluid tick runs genuine original flow");h.assertValueEqual(level.getBlockState(first).getValue(LiquidBlock.LEVEL),1,"source first horizontal metadata1");h.assertValueEqual(level.getFluidState(first).getAmount(),2,"metadata1 means2quanta");h.assertValueEqual(level.getBlockState(first).getLightEmission(level,first),2,"first flow light2");level.getFluidState(first).tick(level,first);var second=center.east(2);h.assertValueEqual(level.getBlockState(second).getValue(LiquidBlock.LEVEL),2,"source second horizontal metadata2");h.assertValueEqual(level.getBlockState(second).getLightEmission(level,second),0,"last flow light0");level.getFluidState(second).tick(level,second);h.assertTrue(level.getBlockState(center.east(3)).isAir(),"two-cell maximum source lateral reach");h.assertTrue(!level.getFluidState(first).isSource()&&!level.getFluidState(second).isSource(),"flow never regenerates source cells");
        var top=center.above(2);level.setBlock(top.below(),Blocks.AIR.defaultBlockState(),Block.UPDATE_CLIENTS);level.setBlock(top,ClassicFusion.PHASE_BLOCK.get().defaultBlockState(),Block.UPDATE_CLIENTS);level.getFluidState(top).tick(level,top);h.assertValueEqual(level.getBlockState(top.below()).getValue(LiquidBlock.LEVEL),1,"original downward metadata1, no native full8waterfall");h.assertValueEqual(level.getFluidState(top.below()).getAmount(),2,"downflow2quanta");h.succeed();
    }

    /** Seeded source Feature creates all14collected blocks; finite solar supplies all4356IF fusion work. */
    @GameTest(template=WIDE,batch="academy_fusion_acquisition",timeoutTicks=20)
    public static void source_feature_matter_collection_solar_low_normal_pure_and_normal_craft(GameTestHelper h){
        var level=h.getLevel();var p=player(h);var origin=h.absolutePos(new BlockPos(20,1,24));int chunkX=origin.getX()>>4,chunkZ=origin.getZ()>>4;long seed=4096;var draw=new Random(seed);PhaseLiquidRandom random=new PhaseLiquidRandom(){public int nextInt(int bound){return draw.nextInt(bound);}public double nextDouble(){return draw.nextDouble();}};var start=PhaseLiquidRules.drawStart(true,true,random,chunkX,chunkZ);h.assertTrue(start!=null,"declared seed selects authentic0.3chance");
        Map<BlockPos,BlockState> restored=new LinkedHashMap<>();long oldTime=level.getDayTime();boolean oldRain=level.isRaining(),oldThunder=level.isThundering();
        try{
            // Declared fixture: an all-solid source lake shell, not prefilled liquid or charged inventory.
            for(int x=start.x()-8;x<start.x()+8;x++)for(int z=start.z()-8;z<start.z()+8;z++)for(int y=start.y()-4;y<start.y()+4;y++){var pos=new BlockPos(x,y,z);restored.put(pos,level.getBlockState(pos));level.setBlock(pos,Blocks.STONE.defaultBlockState(),Block.UPDATE_CLIENTS);}
            var feature=ClassicFusion.PHASE_FEATURE.get();h.assertTrue(feature.place(new FeaturePlaceContext<>(Optional.empty(),level,level.getChunkSource().getGenerator(),RandomSource.create(seed),new BlockPos(chunkX*16,0,chunkZ*16),NoneFeatureConfiguration.INSTANCE)),"real registered source native Feature generates realfluid");
            ItemStack emptyCraft=ItemStack.EMPTY;for(int batch=0;batch<4;batch++){var produced=craft(h,"matter_unit_17",3,3,e(),s(ClassicMaterials.CONSTRAINT_PLATE.get()),e(),s(ClassicMaterials.CONSTRAINT_PLATE.get()),s(Items.GLASS),s(ClassicMaterials.CONSTRAINT_PLATE.get()),e(),s(ClassicMaterials.CONSTRAINT_PLATE.get()),e());h.assertValueEqual(produced.getCount(),4,"source craft yieldsfour");if(emptyCraft.isEmpty())emptyCraft=produced;else emptyCraft.grow(produced.getCount());}
            p.setItemInHand(InteractionHand.MAIN_HAND,emptyCraft);int collected=0;
            for(int x=start.x()-8;x<start.x()+8&&collected<14;x++)for(int z=start.z()-8;z<start.z()+8&&collected<14;z++)for(int y=start.y()-1;y>=start.y()-4&&collected<14;y--){var pos=new BlockPos(x,y,z);if(!level.getBlockState(pos).is(ClassicFusion.PHASE_BLOCK.get())||!level.getBlockState(pos.above()).isAir())continue;
                // Fixture access shaft: expose the generated top cell without changing any fluid block.
                for(int dy=1;dy<=4;dy++){var shaft=pos.above(dy);restored.putIfAbsent(shaft,level.getBlockState(shaft));level.setBlock(shaft,Blocks.AIR.defaultBlockState(),Block.UPDATE_CLIENTS);}
                p.moveTo(x+.5,y+2,z+.5,0,90);var held=p.getItemInHand(InteractionHand.MAIN_HAND);var used=held.getItem().use(level,p,InteractionHand.MAIN_HAND);h.assertTrue(used.getResult().consumesAction(),"real matter rightclick collects source-generated liquid");p.setItemInHand(InteractionHand.MAIN_HAND,used.getObject());h.assertTrue(!level.getBlockState(pos).is(ClassicFusion.PHASE_BLOCK.get()),"real collection consumes one generated block");collected++;
            }
            h.assertValueEqual(collected,14,"fourteen genuine generated fluid blocks collected");int filled=0;for(int i=0;i<p.getInventory().getContainerSize();i++){var stack=p.getInventory().getItem(i);if(stack.is(ClassicFusion.PHASE_MATTER_UNIT.get()))filled+=stack.getCount();}h.assertValueEqual(filled,14,"collection earned fourteen filled matter containers");
            // Remaining native material inputs are declared source-material fixtures; M08 separately
            // verifies the mined/smelted material→converter→solar craft chain without granted IF.
            var sourceFusor=craft(h,"imag_fusor_23",3,3,s(ClassicMaterials.CONSTRAINT_PLATE.get()),s(ClassicMaterials.CRYSTAL_LOW.get()),s(ClassicMaterials.CONSTRAINT_PLATE.get()),s(ClassicMaterials.CALC_CHIP.get()),s(ClassicMaterials.MACHINE_FRAME.get().asItem()),s(ClassicMaterials.CALC_CHIP.get()),s(ClassicMaterials.CONSTRAINT_PLATE.get()),s(ClassicFusion.MATTER_UNIT.get()),s(ClassicMaterials.CONSTRAINT_PLATE.get()));h.assertTrue(sourceFusor.is(ClassicFusion.FUSOR_ITEM.get()),"source Fusor genuinely craftable");
            var tile=fusor(h);var solarPos=new BlockPos(3,1,12);h.setBlock(solarPos,ClassicSolarGenerators.BLOCK.get());var solar=(ClassicSolarBlockEntity)h.getBlockEntity(solarPos);var absolute=solar.getBlockPos();for(int y=absolute.getY()+1;y<level.getMaxBuildHeight();y++)level.setBlock(new BlockPos(absolute.getX(),y,absolute.getZ()),Blocks.AIR.defaultBlockState(),Block.UPDATE_CLIENTS);level.setDayTime(1000);level.setWeatherParameters(24000,0,false,false);var battery=s(ClassicEnergyItems.ENERGY_UNIT.get());equal(h,0,ClassicEnergyItemHelper.getEnergy(battery),"empty real source energyunit");solar.setItem(0,battery);for(int tick=0;tick<3334;tick++)ClassicSolarBlockEntity.serverTick(level,absolute,solar.getBlockState(),solar);equal(h,10000,ClassicEnergyItemHelper.getEnergy(battery),"all IF earned from actual finite solar ticks");battery=solar.removeItem(0,1);tile.setItem(3,battery);
            ItemStack matter=ItemStack.EMPTY;for(int i=0;i<p.getInventory().getContainerSize();i++)if(p.getInventory().getItem(i).is(ClassicFusion.PHASE_MATTER_UNIT.get())){var earned=p.getInventory().removeItem(i,16);if(matter.isEmpty())matter=earned;else matter.grow(earned.getCount());}tile.setItem(2,matter);tile.setItem(0,new ItemStack(ClassicMaterials.CRYSTAL_LOW.get(),2));for(int tick=0;tick<270;tick++)ClassicFusorBlockEntity.serverTick(level,tile.getBlockPos(),tile.getBlockState(),tile);h.assertTrue(tile.getItem(1).is(ClassicMaterials.CRYSTAL_NORMAL.get())&&tile.getItem(1).getCount()==2,"two genuine low to normal upgrades with source ticks");var normalForMachine=tile.removeItem(1,2);tile.setItem(0,normalForMachine.split(1));for(int tick=0;tick<140;tick++)ClassicFusorBlockEntity.serverTick(level,tile.getBlockPos(),tile.getBlockState(),tile);h.assertTrue(tile.getItem(1).is(ClassicMaterials.CRYSTAL_PURE.get()),"genuine normal to pure");h.assertValueEqual(tile.liquid(),0,"fourteen collected units drain exact14000mB");h.assertValueEqual(tile.getItem(4).getCount(),14,"all empty containers refunded");equal(h,10000-4356,ClassicEnergyItemHelper.getEnergy(battery)+tile.getEnergy(),"exact1452IF per fusion, conserved solar energy");
            var basic=craft(h,"matrix_core_0_28",3,3,e(),s(ClassicMaterials.CRYSTAL_LOW.get()),e(),s(ClassicMaterials.CALC_CHIP.get()),s(ClassicMaterials.RESO_CRYSTAL.get()),s(ClassicMaterials.DATA_CHIP.get()),e(),s(ClassicMaterials.ENERGY_CONVERT_COMPONENT.get()),e());h.assertTrue(basic.is(ClassicFusion.MATRIX_CORE_BASIC.get()),"authentic inert source basic core");
            var normalMachine=craft(h,"developer_normal_45",3,3,s(ClassicMaterials.BRAIN_COMPONENT.get()),s(ClassicMaterials.INFO_COMPONENT.get()),s(ClassicMaterials.ENERGY_CONVERT_COMPONENT.get()),basic,s(Items.RED_BED),s(Items.PISTON),normalForMachine,s(ClassicMaterials.MACHINE_FRAME.get().asItem()),s(Items.REDSTONE));h.assertTrue(normalMachine.is(MachineDevelopers.NORMAL_ITEM.get()),"both actual acquisition dependencies now support authentic normal recipe");h.succeed();
        }finally{for(var entry:restored.entrySet())level.setBlock(entry.getKey(),entry.getValue(),Block.UPDATE_CLIENTS);level.setDayTime(oldTime);level.setWeatherParameters(0,0,oldRain,oldThunder);}
    }
}
