/* Compiled-only native RF/IF/FE fixtures. GPLv3; see NOTICE. Owner owns actual execution. */
package cn.academy.port.gametest;

import cn.academy.port.bridge.*;
import com.mojang.serialization.JsonOps;
import io.netty.buffer.Unpooled;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.world.item.crafting.Ingredient;
import cn.academy.port.energy.*;
import cn.academy.port.machine.MachineDevelopers;
import cn.academy.port.solar.ClassicSolarGenerators;
import cn.academy.port.skill.ChargingEnergy;
import cn.academy.port.survival.ClassicMaterials;
import cn.academy.port.tutorial.TutorialStorage;
import cn.academy.port.wireless.*;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.inventory.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.phys.*;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.capabilities.*;
import net.neoforged.neoforge.energy.IEnergyStorage;
import net.neoforged.neoforge.gametest.*;

/** Supplies explicitly declared finite fixture energy; no external mod or natural FE acquisition is claimed. */
@GameTestHolder("academy") @PrefixGameTestTemplate(false)
@EventBusSubscriber(modid="academy",bus=EventBusSubscriber.Bus.MOD)
public final class AcademyEnergyBridgeRuntimeTests {
    private static final String TEMPLATE="runtime_empty",BATCH="academy_energy_bridges";
    private static final BlockPos INPUT=new BlockPos(2,2,2),OUTPUT=new BlockPos(4,2,2),NODE=new BlockPos(3,2,4);
    private record Key(Level level,BlockPos pos){}
    private static final Map<Key,Foreign> FOREIGN=new HashMap<>();
    private static final class Foreign implements IEnergyStorage {
        final Level level;final BlockPos pos;final BlockEntity entity;final Direction ingress;final List<Direction> queries=new ArrayList<>();int energy,limit=37,calls;
        Foreign(Level level,BlockPos pos,Direction ingress){this.level=level;this.pos=pos;entity=level.getBlockEntity(pos);this.ingress=ingress;}
        boolean available(){return FOREIGN.get(new Key(level,pos))==this&&level.hasChunkAt(pos)&&level.getBlockEntity(pos)==entity&&level.getBlockState(pos).is(Blocks.CHEST);}
        public int receiveEnergy(int amount,boolean simulate){if(!available()||amount<=0)return 0;calls++;int moved=Math.min(amount,Math.min(limit,8000-energy));if(!simulate)energy+=moved;return moved;}
        public int extractEnergy(int amount,boolean simulate){if(!available()||amount<=0)return 0;int moved=Math.min(amount,energy);if(!simulate)energy-=moved;return moved;}
        public int getEnergyStored(){return available()?energy:0;}public int getMaxEnergyStored(){return 8000;}public boolean canReceive(){return available();}public boolean canExtract(){return available();}
    }
    /** Test-only FE on an actual native Chest BE. Excluded from release jar; no foreign gameplay store is invented. */
    @SubscribeEvent public static void fixtureCapabilities(RegisterCapabilitiesEvent event){if(!GameTestHooks.isGametestEnabled())return;event.registerBlock(Capabilities.EnergyStorage.BLOCK,(level,pos,state,entity,side)->{var endpoint=FOREIGN.get(new Key(level,pos));if(endpoint!=null)endpoint.queries.add(side);return endpoint!=null&&endpoint.available()&&side==endpoint.ingress?endpoint:null;},Blocks.CHEST);}
    private static void equal(GameTestHelper h,double expected,double actual,String why){h.assertTrue(Double.isFinite(actual)&&Math.abs(expected-actual)<1e-8,why+": "+actual);}
    private static ClassicRFInputBlockEntity input(GameTestHelper h){h.setBlock(INPUT,ClassicEnergyBridges.INPUT.get());return (ClassicRFInputBlockEntity)h.getBlockEntity(INPUT);}
    private static ClassicRFOutputBlockEntity output(GameTestHelper h){h.setBlock(OUTPUT,ClassicEnergyBridges.OUTPUT.get());return (ClassicRFOutputBlockEntity)h.getBlockEntity(OUTPUT);}
    private static void near(ServerPlayer player,BlockPos pos){player.moveTo(pos.getX()+.5,pos.getY(),pos.getZ()-1.5,0,0);}
    private static ClassicWirelessProtocol.Request request(ClassicWirelessMenu menu,String action,BlockPos pos,String pass){return new ClassicWirelessProtocol.Request(menu.containerId,menu.token(),action,pos,"",pass);}
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void bridge_native_real_registry_directional_caps_all_faces_and_simulation(GameTestHelper h){var input=input(h);var output=output(h);var level=h.getLevel();for(Direction face:Direction.values()){
        var receive=level.getCapability(Capabilities.EnergyStorage.BLOCK,input.getBlockPos(),face);var provide=level.getCapability(Capabilities.EnergyStorage.BLOCK,output.getBlockPos(),face);
        h.assertTrue(receive!=null&&receive.canReceive()&&!receive.canExtract()&&provide!=null&&!provide.canReceive()&&provide.canExtract(),"actual FE directional semantics all6 source faces");h.assertValueEqual(receive.getMaxEnergyStored(),8000,"input2000IF=8000FE");h.assertValueEqual(provide.getMaxEnergyStored(),8000,"output2000IF=8000FE");h.assertValueEqual(receive.receiveEnergy(3,false),0,"source whole-IF acceptance truthful remainder fix");h.assertValueEqual(receive.receiveEnergy(400,true),400,"actual input simulation");equal(h,0,input.getEnergy(),"simulation remains empty");}
        var receive=input.forgeEnergy();h.assertValueEqual(receive.receiveEnergy(8000,false),8000,"declared finite external8000FE enters once");equal(h,2000,input.getEnergy(),"same IF store");equal(h,100,input.getBandwidth(),"source wireless bandwidth");h.assertTrue(level.getCapability(ClassicSolarGenerators.IMAG_FLUX,input.getBlockPos(),Direction.UP)==input&&level.getCapability(MachineDevelopers.IMAG_FLUX,input.getBlockPos(),Direction.UP)==null,"actual input generator-only role");h.assertTrue(level.getCapability(MachineDevelopers.IMAG_FLUX,output.getBlockPos(),Direction.UP)==output&&level.getCapability(ClassicSolarGenerators.IMAG_FLUX,output.getBlockPos(),Direction.UP)==null,"actual output receiver-only role");output.injectEnergy(.75);h.assertValueEqual(output.forgeEnergy().extractEnergy(3,true),3,"actual fractional output simulation");equal(h,.75,output.getEnergy(),"fractional simulation no debit");h.assertValueEqual(output.forgeEnergy().extractEnergy(3,false),3,"source defect corrected to actual3FE debit");equal(h,0,output.getEnergy(),"one actual.75IF debit");h.succeed();}
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void bridge_native_source_six_neighbors_opposite_faces_and_conservation(GameTestHelper h){var output=output(h);var level=h.getLevel();List<Foreign> endpoints=new ArrayList<>();try{for(Direction face:Direction.values()){var at=output.getBlockPos().relative(face);level.setBlockAndUpdate(at,Blocks.CHEST.defaultBlockState());var endpoint=new Foreign(level,at,face.getOpposite());FOREIGN.put(new Key(level,at),endpoint);endpoints.add(endpoint);}output.injectEnergy(100);ClassicEnergyBridgeBlockEntity.serverTick(level,output.getBlockPos(),output.getBlockState(),output);int supplied=0;for(var endpoint:endpoints){h.assertValueEqual(endpoint.calls,1,"one source-order native neighbor receive");h.assertValueEqual(endpoint.energy,37,"real foreign endpoint limit37FE");h.assertTrue(endpoint.queries.equals(List.of(endpoint.ingress)),"opposite source face queried once");supplied+=endpoint.energy;}equal(h,100,output.getEnergy()+supplied/4d,"actual foreign/native IF+FE conserved");h.succeed();}finally{for(var endpoint:endpoints)FOREIGN.remove(new Key(level,endpoint.pos));}}
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void bridge_native_generic_managers_up_face_foreign_and_native_precedence(GameTestHelper h){var level=h.getLevel();var pos=h.absolutePos(INPUT);level.setBlockAndUpdate(pos,Blocks.CHEST.defaultBlockState());var endpoint=new Foreign(level,pos,Direction.UP);FOREIGN.put(new Key(level,pos),endpoint);try{
        endpoint.limit=40;var chest=level.getBlockEntity(pos);equal(h,0,ClassicEnergyBlockHelper.charge(chest,10,false),"real foreign UP40FE charge");h.assertValueEqual(endpoint.energy,40,"generic actual1IF=4FE");equal(h,10,ClassicEnergyBlockHelper.getEnergy(chest),"foreign getEnergy divides by4");equal(h,1,ClassicEnergyBlockHelper.pull(chest,1,false),"foreign provider returns removed1IF");h.assertValueEqual(endpoint.energy,36,"actual4FE foreign debit");h.assertTrue(endpoint.queries.stream().allMatch(side->side==Direction.UP),"source generic managers always UP");level.setBlockAndUpdate(pos,Blocks.AIR.defaultBlockState());equal(h,5,ClassicEnergyBlockHelper.charge(chest,5,false),"stale foreign BE cannot retain old capability");equal(h,0,ClassicEnergyBlockHelper.pull(chest,5,false),"stale foreign no energy extraction");var output=output(h);equal(h,0,ClassicEnergyBlockHelper.charge(output,.375,false),"native receiver selected before its FE representation");equal(h,.375,output.getEnergy(),"fractional IF native charge bypasses lossy integer FE exactlyonce");h.assertTrue(!ClassicForeignEnergyManager.isSupported(output),"no overlapping native/foreign representation");h.succeed();}finally{FOREIGN.remove(new Key(level,pos));}}
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void bridge_native_source_empty_page_nonce_graph_bandwidth_and_stale_replacement(GameTestHelper h){try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){var player=actors.player();var input=input(h);var output=output(h);h.setBlock(NODE,ClassicWirelessDevices.STANDARD.get());var node=(ClassicWirelessNodeBlockEntity)h.getBlockEntity(NODE);node.setPlacer(player);node.setPassword("finite-rf-fixture");near(player,input.getBlockPos());input.getBlockState().useWithoutItem(h.getLevel(),player,new BlockHitResult(Vec3.atCenterOf(input.getBlockPos()),Direction.UP,input.getBlockPos(),false));h.assertTrue(player.containerMenu instanceof ClassicWirelessMenu,"actual source block rightclick opens existing genuine menu");var menu=(ClassicWirelessMenu)player.containerMenu;h.assertTrue(menu.standalone()&&menu.slots.isEmpty(),"source converter has no machine or player inventoryslots");equal(h,2000,menu.snapshot().getDouble("max_energy"),"genuine source generator snapshotcapacity");h.assertFalse(ClassicWirelessProtocol.handle(player,request(menu,"link",node.getBlockPos(),"wrong")),"source password rejection");h.assertTrue(ClassicWirelessProtocol.handle(player,request(menu,"link",node.getBlockPos(),"finite-rf-fixture")),"source real graph generatorlink");input.forgeEnergy().receiveEnergy(8000,false);var graph=ClassicWirelessSavedData.get(h.getLevel()).graph();graph.tick();equal(h,1900,input.getEnergy(),"source100IF wireless debit");equal(h,100,node.getEnergy(),"same source100IF nodecredit");near(player,output.getBlockPos());h.assertTrue(ClassicWirelessProtocol.open(player,output.getBlockPos(),ClassicWirelessMenu.Kind.USER),"output real source receiverpage opens");var outputMenu=(ClassicWirelessMenu)player.containerMenu;h.assertTrue(ClassicWirelessProtocol.handle(player,request(outputMenu,"link",node.getBlockPos(),"finite-rf-fixture")),"output genuine receiverbranch");graph.tick();equal(h,100,output.getEnergy(),"source receiver100IF from finite node");equal(h,2000,input.getEnergy()+node.getEnergy()+output.getEnergy(),"actual IF graph totalconserved");var stale=output.forgeEnergy();var level=h.getLevel();var saved=output.saveWithFullMetadata(level.registryAccess());level.removeBlockEntity(output.getBlockPos());var fresh=(ClassicRFOutputBlockEntity)BlockEntity.loadStatic(output.getBlockPos(),output.getBlockState(),saved,level.registryAccess());level.setBlockEntity(fresh);h.assertFalse(outputMenu.stillValid(player),"same-position replacedBE invalidates source menuidentity");h.assertFalse(ClassicWirelessProtocol.handle(player,request(outputMenu,"unlink",node.getBlockPos(),"")),"stale nonce/sourceBE cannot reinterpret graphmutation");h.assertValueEqual(stale.extractEnergy(400,false),0,"retained old FE adapter no longer spends");equal(h,100,fresh.getEnergy(),"fresh actual store preserved");h.succeed();}}
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void bridge_native_persistence_fractional_input_output_and_no_spontaneous_generation(GameTestHelper h){var input=input(h);var output=output(h);var level=h.getLevel();input.forgeEnergy().receiveEnergy(496,false);input.getProvidedEnergy(.375);output.injectEnergy(456.375);for(var tile:List.of(input,output)){double expected=tile.getEnergy();var tag=tile.saveWithFullMetadata(level.registryAccess());level.removeBlockEntity(tile.getBlockPos());var fresh=(ClassicEnergyBridgeBlockEntity)BlockEntity.loadStatic(tile.getBlockPos(),tile.getBlockState(),tag,level.registryAccess());level.setBlockEntity(fresh);equal(h,expected,fresh.getEnergy(),"real native registry NBT restores exact fractionalIF");for(int tick=0;tick<20;tick++)ClassicEnergyBridgeBlockEntity.serverTick(level,fresh.getBlockPos(),fresh.getBlockState(),fresh);equal(h,expected,fresh.getEnergy(),"no neighbor/genuine zero generation remainsfinite");equal(h,expected,fresh.getUpdatePacket().getTag().getDouble("energy"),"20tick source energy publication");h.assertValueEqual(tile.forgeEnergy().getEnergyStored(),0,"old replaced native endpoint no access");var corrupt=tag.copy();corrupt.putDouble("energy",Double.NaN);var safe=(ClassicEnergyBridgeBlockEntity)BlockEntity.loadStatic(fresh.getBlockPos(),fresh.getBlockState(),corrupt,level.registryAccess());equal(h,0,safe.presentationEnergy(),"corrupt native load cannot producepower");}h.succeed();}
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void bridge_native_source_four_resultslot_recipes_and_existing_guide_unlock(GameTestHelper h){try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){var player=actors.player();var table=h.absolutePos(NODE);h.getLevel().setBlockAndUpdate(table,Blocks.CRAFTING_TABLE.defaultBlockState());ItemStack e=ItemStack.EMPTY;ItemStack[][] grids={{new ItemStack(ClassicEnergyItems.ENERGY_UNIT.get()),new ItemStack(ClassicMaterials.MACHINE_FRAME.get()),new ItemStack(ClassicMaterials.CONSTRAINT_PLATE.get()),e,new ItemStack(ClassicMaterials.ENERGY_CONVERT_COMPONENT.get()),e,e,e,e},{new ItemStack(ClassicEnergyItems.ENERGY_UNIT.get()),new ItemStack(ClassicMaterials.MACHINE_FRAME.get()),new ItemStack(ClassicMaterials.RESO_CRYSTAL.get()),e,new ItemStack(ClassicMaterials.ENERGY_CONVERT_COMPONENT.get()),e,e,e,e},{new ItemStack(ClassicEnergyBridges.OUTPUT_ITEM.get()),e,e,e,e,e,e,e,e},{new ItemStack(ClassicEnergyBridges.INPUT_ITEM.get()),e,e,e,e,e,e,e,e}};Item[] expected={ClassicEnergyBridges.INPUT_ITEM.get(),ClassicEnergyBridges.OUTPUT_ITEM.get(),ClassicEnergyBridges.INPUT_ITEM.get(),ClassicEnergyBridges.OUTPUT_ITEM.get()};for(int i=0;i<4;i++){var menu=new CraftingMenu(90+i,player.getInventory(),ContainerLevelAccess.create(h.getLevel(),table));player.containerMenu=menu;for(int slot=0;slot<9;slot++)menu.getSlot(slot+1).set(grids[i][slot]);h.assertTrue(menu.getSlot(0).getItem().is(expected[i]),"actual registered source four-recipe result");var earned=menu.getSlot(0).remove(1);menu.getSlot(0).onTake(player,earned);for(int slot=1;slot<=9;slot++)h.assertTrue(menu.getSlot(slot).getItem().isEmpty(),"source actual ingredient debitonce");player.closeContainer();}h.assertTrue(TutorialStorage.get(player).visible("energy_bridge"),"actual crafted events unlock existing source Energy Bridge guide");h.succeed();}}
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void bridge_native_publication_precedes_six_neighbor_output_and_break_closes_retained_fe(GameTestHelper h){var output=output(h);var level=h.getLevel();var pos=output.getBlockPos().below();level.setBlockAndUpdate(pos,Blocks.CHEST.defaultBlockState());var endpoint=new Foreign(level,pos,Direction.UP);endpoint.limit=4;FOREIGN.put(new Key(level,pos),endpoint);try{output.injectEnergy(100);for(int tick=0;tick<20;tick++)ClassicEnergyBridgeBlockEntity.serverTick(level,output.getBlockPos(),output.getBlockState(),output);equal(h,81,output.getUpdatePacket().getTag().getDouble("energy"),"source twentieth publication before push");equal(h,80,output.getEnergy(),"twentieth source push follows publication");equal(h,80,endpoint.energy,"actual exported80FE");var old=output.forgeEnergy();level.destroyBlock(output.getBlockPos(),true);h.assertValueEqual(old.extractEnergy(8000,false),0,"broken source oldcap cannot spend");equal(h,0,output.pullEnergy(100),"broken source nativeIF endpoint dead");h.succeed();}finally{FOREIGN.remove(new Key(level,pos));}}
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void bridge_native_narrow_energy_unit_ingredient_codec_stream_and_charge_state_predicate(GameTestHelper h){
        var ingredient=new ClassicBridgeEnergyUnitIngredient().toVanilla();h.assertTrue(ingredient.isCustom()&&!ingredient.isSimple()&&!ingredient.hasNoItems(),"actual non-simple source metadata native ingredient");
        var ops=h.getLevel().registryAccess().createSerializationContext(JsonOps.INSTANCE);var encoded=Ingredient.CODEC.encodeStart(ops,ingredient).getOrThrow();h.assertTrue(encoded.getAsJsonObject().get("type").getAsString().equals("academy:bridge_energy_unit"),"genuine registered source predicate codec identity");var decoded=Ingredient.CODEC.parse(ops,encoded).getOrThrow();h.assertTrue(decoded.equals(ingredient),"stateless native ingredient codec equality");var wire=new RegistryFriendlyByteBuf(Unpooled.buffer(),h.getLevel().registryAccess());Ingredient network;
        try{Ingredient.CONTENTS_STREAM_CODEC.encode(wire,ingredient);network=Ingredient.CONTENTS_STREAM_CODEC.decode(wire);h.assertTrue(wire.readableBytes()==0&&network.equals(ingredient),"native registered non-simple stream codec fully consumed");}finally{wire.release();}
        for(double energy:new double[]{0,.125,123.625,5000,9615,9800,10000}){var stack=new ItemStack(ClassicEnergyItems.ENERGY_UNIT.get());ClassicEnergyItemHelper.setEnergy(stack,energy);var before=stack.copy();boolean expected=energy==0||ClassicEnergy.damage(energy,10000)==0;h.assertTrue(ingredient.test(stack)==expected&&decoded.test(stack)==expected&&network.test(stack)==expected,"actual native ingredient rejects intermediate charge but accepts empty/source-equivalent gauge0");h.assertTrue(ItemStack.isSameItemSameComponents(before,stack),"ingredient test never mutates actual unitpayload");}
        h.assertFalse(ingredient.test(new ItemStack(Items.DIAMOND)),"actual wrong item rejects");h.succeed();
    }

}
