/* AcademyCraft1.0.7 VecManip Lv3/Lv4 native fixtures, GPLv3; see NOTICE. */
package cn.academy.port.gametest;
import cn.academy.port.*;import cn.academy.port.api.*;import cn.academy.port.core.*;import cn.academy.port.develop.*;import cn.academy.port.machine.*;import cn.academy.port.skill.*;
import com.mojang.authlib.GameProfile;import io.netty.channel.embedded.EmbeddedChannel;
import net.minecraft.network.Connection;import net.minecraft.network.protocol.PacketFlow;import net.minecraft.server.network.CommonListenerCookie;
import net.minecraft.core.*;import net.minecraft.core.registries.Registries;import net.minecraft.gametest.framework.*;import net.minecraft.nbt.*;import net.minecraft.resources.ResourceLocation;import net.minecraft.server.level.*;
import net.minecraft.world.*;import net.minecraft.world.entity.*;import net.minecraft.world.entity.ai.attributes.Attributes;import net.minecraft.world.entity.npc.Villager;import net.minecraft.world.item.*;import net.minecraft.world.item.context.BlockPlaceContext;import net.minecraft.world.level.GameType;import net.minecraft.world.level.block.Blocks;import net.minecraft.world.phys.*;
import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;import net.neoforged.neoforge.common.NeoForge;import net.neoforged.neoforge.common.util.FakePlayer;import net.neoforged.neoforge.event.level.*;import net.neoforged.neoforge.gametest.*;import net.neoforged.neoforge.network.registration.NetworkRegistry;
import java.util.*;
/** Learning fixtures never grant target skills. Combat fixtures explicitly seed learned state.
 * Any movement uses PlayerList-admitted ServerPlayer with official mock Connection, never FakePlayer teleport. */
@GameTestHolder("academy") @PrefixGameTestTemplate(false) @EventBusSubscriber(modid="academy")
public final class AcademyVectorCombatRuntimeTests {
 private static final String TEMPLATE="vector_combat_empty";private AcademyVectorCombatRuntimeTests(){}
 @SubscribeEvent public static void install(LevelEvent.Load e){if(!GameTestHooks.isGametestEnabled()||!(e.getLevel() instanceof ServerLevel w))return;var t=new CompoundTag();var size=new ListTag();for(int value:new int[]{64,16,64})size.add(IntTag.valueOf(value));t.put("size",size);var blocks=new ListTag();var b=new CompoundTag();var pos=new ListTag();for(int i=0;i<3;i++)pos.add(IntTag.valueOf(0));b.put("pos",pos);b.putInt("state",0);blocks.add(b);t.put("blocks",blocks);t.put("entities",new ListTag());var palette=new ListTag();var air=new CompoundTag();air.putString("Name","minecraft:air");palette.add(air);t.put("palette",palette);w.getStructureManager().getOrCreate(ResourceLocation.fromNamespaceAndPath("academy",TEMPLATE)).load(w.registryAccess().lookupOrThrow(Registries.BLOCK),t);}
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=15)
 public static void blast_native_paid_miss_zeroEXP_sourceparent_and_strict_duration(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,"dir_blast",3,0);double cp=s.cp;h.assertTrue(DirectedBlastwave.start(p,1),"native authenticated hold");h.runAtTickTime(6,()->{h.assertFalse(DirectedBlastwave.release(p,1),"tick6 strict rejects");near(h,s.cp,cp,"early cancel free");h.assertTrue(DirectedBlastwave.start(p,2),"fresh source hold");});h.runAtTickTime(13,()->{h.assertTrue(DirectedBlastwave.release(p,2),"tick7 accepts paid miss");near(h,s.cp,cp-160,"source160CP");near(h,s.overload,50,"source50strain");near(h,s.exp("dir_blast"),.0012F,"source ineffectiveEXP");h.assertValueEqual(s.cooldowns.get("dir_blast"),80,"source captured80cooldown");h.assertFalse(DirectedBlastwave.release(p,2),"replay no seconddebit");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=55)
 public static void blast_exact_tick50_timeout_free_and_forged_nonce_keeps_context(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,"dir_blast",3,0);double cp=s.cp;DirectedBlastwave.start(p,1);h.assertFalse(DirectedBlastwave.release(p,2),"forgedterminal denies");h.assertTrue(DirectedBlastwave.active(p),"forgedterminal preserveshold");h.runAtTickTime(50,()->{h.assertFalse(DirectedBlastwave.release(p,1),"exact50 rejects");near(h,s.cp,cp,"late cancel free");h.assertTrue(s.cooldowns.isEmpty()&&s.exp("dir_blast")==0,"late noEXP or cooldown");h.assertFalse(DirectedBlastwave.start(p,1),"inputtombstone deniesreplay");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=12)
 public static void blast_native_all_entities_get10damage_knockback_lift_and_protected_hitEXP(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,"dir_blast",3,0);var target=f.target(p.position().add(0,0,3));var second=f.target(p.position().add(1,0,3));var hook=new Hook(p);hook.zero=true;hook.reenter=true;f.hook(hook);double y=target.getY();DirectedBlastwave.start(p,1);h.runAtTickTime(7,()->{h.assertTrue(DirectedBlastwave.release(p,1),"native burst");h.assertValueEqual(hook.count(target),1,"source primaryattempt");h.assertValueEqual(hook.count(second),1,"source areaattempt");near(h,hook.damage(target),10,"captured rawdamage10");near(h,target.getHealth(),200,"mutable native protection zero honored");near(h,target.getY(),y+.1,"source .1lift");h.assertTrue(target.getDeltaMovement().y>0&&target.getDeltaMovement().z>0,"source strongandextra impulse");near(h,s.exp("dir_blast"),.0025F,"entities effective even rejectedhurt");h.assertFalse(hook.reentered,"event reentry fence");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=12)
 public static void blast_center_softstone_destroy_protection_and_no_bedrock_break(GameTestHelper h){var f=new Fixture(h);var p=f.player();ready(p,"dir_blast",3,0);var sourceCenter=p.position().add(Vec3.directionFromRotation(p.getXRot(),p.getYHeadRot()).scale(4));var center=new BlockPos((int)Math.round(sourceCenter.x),(int)Math.round(sourceCenter.y),(int)Math.round(sourceCenter.z));var bedrock=center.offset(2,0,0);h.getLevel().setBlock(center,Blocks.STONE.defaultBlockState(),3);h.getLevel().setBlock(bedrock,Blocks.BEDROCK.defaultBlockState(),3);DirectedBlastwave.start(p,1);h.runAtTickTime(7,()->{h.assertTrue(DirectedBlastwave.release(p,1),"native blockperform");h.assertTrue(h.getLevel().getBlockState(center).isAir(),"unconditionalcenter hardness1.5 destroyed");h.assertTrue(h.getLevel().getBlockState(bedrock).is(Blocks.BEDROCK),"negativehardness neverdestroyed");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=12)
 public static void blast_native_blockdestroy_hook_preserves_center_and_rng_debit(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,"dir_blast",3,0);var sourceCenter=p.position().add(Vec3.directionFromRotation(p.getXRot(),p.getYHeadRot()).scale(4));var center=new BlockPos((int)Math.round(sourceCenter.x),(int)Math.round(sourceCenter.y),(int)Math.round(sourceCenter.z));h.getLevel().setBlock(center,Blocks.STONE.defaultBlockState(),3);var hook=new Hook(p);hook.block=center;f.hook(hook);double cp=s.cp;DirectedBlastwave.start(p,1);h.runAtTickTime(7,()->{h.assertTrue(DirectedBlastwave.release(p,1),"native paid protectedblocks");h.assertTrue(hook.blockCalls>0&&h.getLevel().getBlockState(center).is(Blocks.STONE),"native sourceblockevent canceled");near(h,s.cp,cp-160,"blockprotection doesnotrefund");near(h,s.exp("dir_blast"),.0012F,"blockonly source ineffectiveEXP");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=12)
 public static void blood_immediate_native_living_trace_dynamiccost_captured30_and_single_spend(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,"blood_retro",4,0);var target=f.target(p.position().add(0,0,1.5));var hook=new Hook(p);hook.zero=true;hook.reenter=true;f.hook(hook);double cp=s.cp;h.assertTrue(BloodRetrograde.start(p,1)&&BloodRetrograde.release(p,1),"source immediate keyup accepted");near(h,s.cp,cp-280,"source280CP");near(h,s.overload,55,"source55strain");near(h,hook.damage(target),30,"captured30 damage");near(h,s.exp("blood_retro"),.002F,"protected attemptstillEXP");h.assertValueEqual(s.cooldowns.get("blood_retro"),90,"source90ticks");near(h,p.getAbilities().getWalkingSpeed(),.1F,"classic reset.1");h.assertFalse(BloodRetrograde.release(p,1)||hook.reentered,"replay andreentry fenced");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=35)
 public static void blood_native_tick20slow_tick30auto_hit_reset_and_nonliving_miss(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,"blood_retro",4,0);var target=f.target(p.position().add(0,0,1.5));var hook=new Hook(p);f.hook(hook);p.getAbilities().setWalkingSpeed(.2F);BloodRetrograde.start(p,1);for(int t=1;t<=30;t++){int now=t;h.runAtTickTime(t,()->{BloodRetrograde.tick(p);if(now==20){near(h,p.getAbilities().getWalkingSpeed(),.007F,"exact20tickfloor");h.assertTrue(BloodRetrograde.active(p),"chargeheldbefore30");}if(now==30){h.assertFalse(BloodRetrograde.active(p),"source auto30end");h.assertValueEqual(hook.count(target),1,"sourceauto livingattack");near(h,p.getAbilities().getWalkingSpeed(),.1F,"source hardreset ignoresprevious.2");near(h,s.exp("blood_retro"),.002F,"oneEXPaward");h.succeed();}});}}
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=10)
 public static void blood_native_wall_occludes_and_failedCP_free_cancel_resets(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,"blood_retro",4,0);var target=f.target(p.position().add(0,0,2));var wall=BlockPos.containing(p.getEyePosition().add(0,0,.5));h.getLevel().setBlock(wall,Blocks.BEDROCK.defaultBlockState(),3);double cp=s.cp;BloodRetrograde.start(p,1);h.assertFalse(BloodRetrograde.release(p,1),"nativeblockoccludeslivingfeet");near(h,s.cp,cp,"notarget free");h.getLevel().setBlock(wall,Blocks.AIR.defaultBlockState(),3);target.setPos(p.position().add(0,0,1.5));s.cp=279;BloodRetrograde.start(p,2);h.assertFalse(BloodRetrograde.release(p,2),"sourcefailed280CP");near(h,s.cp,279,"failedconsume unchangedCP");h.assertTrue(s.cooldowns.isEmpty()&&s.exp("blood_retro")==0,"noinventedfailureaward");near(h,p.getAbilities().getWalkingSpeed(),.1F,"failure speedrestore");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=80)
 public static void storm_native_playerlist_charge71_firstpaidtick_direction_forge_and_toggle_restore(GameTestHelper h){
  var f=new Fixture(h);var p=f.connectedPlayer();var s=ready(p,"storm_wing",3,0);p.setNoGravity(false);p.getAbilities().mayfly=false;f.floor(p);double cp=s.cp;
  h.assertTrue(bind(s,"storm_wing"),"naturally selectable context slot");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:1")),"native charged toggle owning slot");h.assertTrue(p.getAbilities().mayfly,"source allowflying while charging");h.assertFalse(StormWing.direction(p,1,0),"direction cannot skip charge");
  // Advance this owned fixture in one callback per tick; native tick deduplication remains authoritative.
  for(int tick=1;tick<=72;tick++){int t=tick;h.runAtTickTime(t,()->{
   StormWing.tick(p);int held=StormWing.ticks(p);StormWing.tick(p);h.assertValueEqual(StormWing.ticks(p),held,"same native time never advances twice");
   if(t==70){h.assertValueEqual(StormWing.phase(p),0,"strict greater than70");h.assertValueEqual(held,70,"independently advanced charge ticks");near(h,s.cp,cp,"charge free");}
   if(t==71){h.assertValueEqual(StormWing.phase(p),1,"native charge71 transition");near(h,s.cp,cp,"transition free");h.assertFalse(StormWing.direction(p,2,0),"forged context nonce denied");h.assertFalse(StormWing.direction(p,1,4),"bounded direction");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("storm_direction","1:1:0")),"wrong original slot denied");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("storm_direction","0:1:00")),"noncanonical direction denied");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("storm_direction","0:1:0")),"owned bounded W ingress");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("preset_switch","1"))&&StormWing.active(p),"source preset flush preserves charged toggle");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("storm_direction","0:1:0")),"original slot remains owner after preset flush");}
   if(t==72){near(h,s.cp,cp-40,"first active source CP40");near(h,s.exp("storm_wing"),.00005F,"first active EXP");near(h,p.fallDistance,0,"owned native zero fall");h.assertTrue(p.getZ()>h.absoluteVec(new Vec3(10.5,1,10.5)).z,"native admitted player moved forward");h.assertTrue(StormWing.release(p,1)&&StormWing.active(p),"key release leaves toggle alive");h.assertTrue(StormWing.start(p,2),"second keypress toggles off");h.assertFalse(StormWing.active(p)||p.getAbilities().mayfly,"exact previous allowFlying restore");h.assertValueEqual(s.cooldowns.get("storm_wing"),29,"source postEXP float cooldown truncation");h.succeed();}
  });}
 }
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=40)
 public static void storm_native_master_charge31_failedCP_awards_beforeconsume_and_preserves_preexisting_mayfly(GameTestHelper h){
  var f=new Fixture(h);var p=f.connectedPlayer();var s=ready(p,"storm_wing",3,1);p.setNoGravity(false);p.getAbilities().mayfly=true;f.floor(p);h.assertTrue(StormWing.start(p,1),"master source context starts");
  for(int tick=1;tick<=32;tick++){int t=tick;h.runAtTickTime(t,()->{
   StormWing.tick(p);int held=StormWing.ticks(p);StormWing.tick(p);h.assertValueEqual(StormWing.ticks(p),held,"native master same-time deduplication");
   if(t==30){h.assertValueEqual(StormWing.phase(p),0,"master strict30");h.assertValueEqual(held,30,"master fixture independently advanced");}
   if(t==31){h.assertValueEqual(StormWing.phase(p),1,"master transition31");s.cp=24;s.cpDelay=15;}
   if(t==32){h.assertFalse(StormWing.active(p),"25CP failed active ends");near(h,s.exp("storm_wing"),1,"master EXP cap before fail");h.assertTrue(p.getAbilities().mayfly,"preexisting permission retained");h.assertValueEqual(s.cooldowns.get("storm_wing"),10,"master end10");h.succeed();}
  });}
 }
 @GameTest(template=TEMPLATE,batch="academy_vector_combat",timeoutTicks=10)
 public static void nonce_authenticated_slot_ingress_and_lifecycle_restore_with_finite_guards(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,"blood_retro",4,0);bind(s,"blood_retro");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:01")),"noncanonicalinputdenied");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:1")),"actualboundslotstart");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_release","0")),"legacyterminalblocked");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_abort_token","0:2")),"forgedabort blocked");h.assertTrue(BloodRetrograde.active(p),"forgedrequests preservecontext");p.getAbilities().setWalkingSpeed(.007F);BloodRetrograde.remove(p);near(h,p.getAbilities().getWalkingSpeed(),.1F,"lifecycleclassicrestore");s=ready(p,"storm_wing",3,0);p.getAbilities().mayfly=false;StormWing.start(p,1);StormWing.remove(p);h.assertFalse(p.getAbilities().mayfly||StormWing.active(p),"lifecycleownedpermissionrestore");h.assertTrue(s.cooldowns.isEmpty(),"discard categorylifecycle no new cooldown");s.cp=Double.NaN;h.assertFalse(StormWing.start(p,2),"nonfinitecpdenied");s.cp=s.maxCp();p.setYHeadRot(Float.NaN);h.assertFalse(StormWing.start(p,2),"nonfiniteaimdenied");p.setYHeadRot(0);h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_vector_combat_learning",timeoutTicks=30)
 public static void physical_Advanced_GUI_learns_three_zeroEXPtargets_from_zeroEXPparents_with_finite_IF(GameTestHelper h){var f=new Fixture(h);var p=f.player();var item=MachineDevelopers.ADVANCED_ITEM.get();var stack=new ItemStack(item);p.setItemInHand(InteractionHand.MAIN_HAND,stack);var base=h.absolutePos(new BlockPos(10,1,14));h.assertTrue(item.place(new BlockPlaceContext(p,InteractionHand.MAIN_HAND,stack,new BlockHitResult(Vec3.atCenterOf(base),Direction.UP,base,false))).consumesAction(),"physical eightcellAdvanced");var machine=(MachineDeveloperBlockEntity)h.getLevel().getBlockEntity(base);p.moveTo(base.getX()+.5,base.getY(),base.getZ()-1.5,0,0);
  for(String id:List.of("dir_blast","storm_wing","blood_retro")){DevelopmentController.remove(p);var s=AbilityStorage.get(p);s.selectCategory("vecmanip");int level=id.equals("blood_retro")?4:3;s.setLevel(level);var skill=SkillCatalog.find("vecmanip",id).orElseThrow();h.assertFalse(s.learned(id),"targetneverfixturegranted");machine.battery().load(200000);h.assertTrue(machine.use(p),"nativeAdvancedmenusession");String nonce=MachineDeveloperSessions.activeToken(p).orElseThrow().toString();h.assertFalse(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",UUID.randomUUID()+":"+id)),"forgedlearningtoken denied");h.assertFalse(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",nonce+":"+id)),"missingparent denies");for(var req:skill.requirements()){s.learn(req.id());h.assertTrue(req.exp()==0&&s.exp(req.id())==0,"sourcezeroEXPparent sufficient");}h.assertTrue(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",nonce+":"+id)),"sharednaturalavailability accepts");int ticks=(level==3?7:11)*16;for(int tick=1;tick<=ticks;tick++){DevelopmentController.tick(p,v->{});if(tick<ticks)h.assertFalse(s.learned(id),"noearlylearninggrant");}h.assertTrue(s.learned(id)&&s.exp(id)==0&&DevelopmentController.process(p).state()==DevelopmentProcess.State.DONE,"genuinezeromasterydevelopment");near(h,machine.battery().getEnergy(),200000-(level==3?4480:7040),"actualfiniteIF");h.assertTrue(s.presets.currentSkill(0).isEmpty(),"learnneverautobinds");s.activated=true;h.assertTrue(bind(s,id),"naturalearnedpresetingress");}
  h.succeed();}
 private static boolean bind(AbilityProgress s,String id){return s.presets.edit(0,0,id,value->cn.academy.port.preset.PresetSkills.selectable(s,value));}private static AbilityProgress ready(ServerPlayer p,String id,int level,double exp){var s=AbilityStorage.get(p);s.selectCategory("vecmanip");s.setLevel(level);s.learn(id);s.experience.put(id,exp);s.activated=true;return s;}private static void near(GameTestHelper h,double actual,double expected,String why){h.assertTrue(Math.abs(actual-expected)<1E-5,why+" actual="+actual+" expected="+expected);}
 private static final class Fixture{final GameTestHelper h;final List<ServerPlayer> players=new ArrayList<>();final List<EmbeddedChannel> channels=new ArrayList<>();final List<Entity> entities=new ArrayList<>();final List<Object> hooks=new ArrayList<>();boolean closed;Fixture(GameTestHelper h){this.h=h;h.testInfo.addListener(new GameTestListener(){public void testStructureLoaded(GameTestInfo i){}public void testPassed(GameTestInfo i,GameTestRunner r){cleanup();}public void testFailed(GameTestInfo i,GameTestRunner r){cleanup();}public void testAddedForRerun(GameTestInfo i,GameTestInfo n,GameTestRunner r){cleanup();}});}FakePlayer player(){var p=new FakePlayer(h.getLevel(),new GameProfile(UUID.randomUUID(),"[AC-VectorCombat]"));players.add(p);position(p);return p;}
 ServerPlayer connectedPlayer(){var w=h.getLevel();var server=w.getServer();var cookie=CommonListenerCookie.createInitial(new GameProfile(UUID.randomUUID(),"ACVectorWingProbe"),false);var p=new ServerPlayer(server,w,cookie.gameProfile(),cookie.clientInformation());players.add(p);var connection=new Connection(PacketFlow.SERVERBOUND);var channel=new EmbeddedChannel(connection);channels.add(channel);NetworkRegistry.configureMockConnection(connection);try{server.getPlayerList().placeNewPlayer(connection,p,cookie);h.assertTrue(server.getPlayerList().getPlayer(p.getUUID())==p,"nativePlayerList exactownedflightfixture");position(p);p.setGameMode(GameType.SURVIVAL);return p;}catch(RuntimeException failure){try{cleanup();}catch(RuntimeException next){failure.addSuppressed(next);}throw failure;}}
 void position(ServerPlayer p){var at=h.absoluteVec(new Vec3(10.5,1,10.5));p.moveTo(at.x,at.y,at.z,0,0);p.setYHeadRot(0);p.setNoGravity(true);p.setDeltaMovement(Vec3.ZERO);p.getAbilities().instabuild=false;}void floor(ServerPlayer p){var at=BlockPos.containing(p.position()).below();for(int x=-8;x<=8;x++)for(int z=-8;z<=8;z++)h.getLevel().setBlock(at.offset(x,0,z),Blocks.BEDROCK.defaultBlockState(),3);}
 Villager target(Vec3 at){var v=h.spawnWithNoFreeWill(EntityType.VILLAGER,new Vec3(1,1,1));entities.add(v);v.moveTo(at.x,at.y,at.z,0,0);v.setNoAi(true);v.setNoGravity(true);v.setDeltaMovement(Vec3.ZERO);v.getAttribute(Attributes.MAX_HEALTH).setBaseValue(200);v.setHealth(200);return v;}void hook(Object obj){hooks.add(obj);NeoForge.EVENT_BUS.register(obj);}void cleanup(){if(closed)return;closed=true;for(var hook:hooks)NeoForge.EVENT_BUS.unregister(hook);for(var p:players){DirectedBlastwave.remove(p);StormWing.remove(p);BloodRetrograde.remove(p);DevelopmentController.remove(p);MachineDeveloperSessions.close(p);AbilityStorage.remove(p);var list=h.getLevel().getServer().getPlayerList();if(list.getPlayer(p.getUUID())==p)list.remove(p);else p.discard();}for(var e:entities)e.discard();for(var channel:channels)channel.finishAndReleaseAll();}}
 public static final class Hook{final ServerPlayer owner;final Map<Entity,Integer> count=new IdentityHashMap<>();final Map<Entity,Double> damage=new IdentityHashMap<>();boolean zero,reenter,reentered;BlockPos block;int blockCalls;Hook(ServerPlayer p){owner=p;}@SubscribeEvent public void attack(SkillAttackEvent e){if(e.player!=owner||!Set.of("vecmanip.dir_blast","vecmanip.blood_retro").contains(e.skill))return;count.merge(e.target,1,Integer::sum);damage.put(e.target,e.amount);if(zero)e.amount=0;if(reenter)reentered|=e.skill.equals("vecmanip.dir_blast")?DirectedBlastwave.start(owner,2):BloodRetrograde.start(owner,2);}@SubscribeEvent public void block(SkillBlockDestroyEvent e){if(e.player==owner&&e.position.equals(block)){blockCalls++;e.setCanceled(true);}}int count(Entity e){return count.getOrDefault(e,0);}double damage(Entity e){return damage.getOrDefault(e,0D);}}
}
