/* Declared finite native fixtures for source Phase Generator. GPLv3. See NOTICE. */
package cn.academy.port.gametest;

import cn.academy.port.AcademyCraft;
import cn.academy.port.energy.ClassicEnergyItemHelper;
import cn.academy.port.energy.ClassicEnergyItems;
import cn.academy.port.fusion.ClassicFusion;
import cn.academy.port.phasegen.*;
import cn.academy.port.solar.ClassicSolarGenerators;
import cn.academy.port.survival.ClassicMaterials;
import cn.academy.port.wireless.*;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.inventory.ContainerLevelAccess;
import net.minecraft.world.inventory.CraftingMenu;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.Vec3;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.capability.IFluidHandler.FluidAction;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;

/** Main alone runs these. Raw material/fluid fixture provenance is explicit; no natural playthrough claim. */
@GameTestHolder("academy")
@PrefixGameTestTemplate(false)
public final class AcademyPhaseGeneratorRuntimeTests {
    private static final String TEMPLATE="runtime_empty",BATCH="academy_phase_generator";
    private static final BlockPos BASE=new BlockPos(3,1,4),NODE=new BlockPos(5,1,4);
    private AcademyPhaseGeneratorRuntimeTests(){}
    private static ItemStack s(net.minecraft.world.item.Item item){return new ItemStack(item);}
    private static void equal(GameTestHelper h,double expected,double actual,String label){h.assertTrue(Double.isFinite(actual)&&Math.abs(expected-actual)<1e-7,label+": "+actual);}
    private static ClassicPhaseGeneratorBlockEntity tile(GameTestHelper h){h.setBlock(BASE,ClassicPhaseGenerators.BLOCK.get());return (ClassicPhaseGeneratorBlockEntity)h.getBlockEntity(BASE);}
    private static void tick(GameTestHelper h,ClassicPhaseGeneratorBlockEntity tile,int count){for(int i=0;i<count;i++)ClassicPhaseGeneratorBlockEntity.serverTick(h.getLevel(),tile.getBlockPos(),tile.getBlockState(),tile);}
    private static void near(ServerPlayer p,BlockPos pos){p.moveTo(pos.getX()+.5,pos.getY(),pos.getZ()-1.5,0,0);}
    private static ClassicWirelessProtocol.Request request(ClassicWirelessMenu menu,String action,BlockPos target,String password){return new ClassicWirelessProtocol.Request(menu.containerId,menu.token(),action,target,"",password);}

    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void phase_generator_native_identity_cube_harvest_slots_and_shift_mapping(GameTestHelper h){
        try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){
            var p=actors.player();var absolute=h.absolutePos(BASE);near(p,absolute);
            var item=s(ClassicPhaseGenerators.ITEM.get());p.setItemInHand(InteractionHand.MAIN_HAND,item);
            h.assertTrue(ClassicPhaseGenerators.ITEM.get().place(new BlockPlaceContext(p,InteractionHand.MAIN_HAND,item,new BlockHitResult(Vec3.atCenterOf(absolute),Direction.UP,absolute,false))).consumesAction()&&item.isEmpty(),"actual source single-cell BlockItem placement");
            var tile=(ClassicPhaseGeneratorBlockEntity)h.getBlockEntity(BASE);var level=h.getLevel();
            h.assertTrue(BuiltInRegistries.BLOCK.get(ResourceLocation.parse("academy:phase_gen"))==ClassicPhaseGenerators.BLOCK.get()&&BuiltInRegistries.ITEM.get(ResourceLocation.parse("academy:phase_gen"))==ClassicPhaseGenerators.ITEM.get(),"actual registry identities");
            h.assertTrue(Block.isShapeFullBlock(tile.getBlockState().getCollisionShape(level,absolute)),"source full-cell collision without facing state");equal(h,2.5,tile.getBlockState().getDestroySpeed(level,absolute),"source hardness");
            h.assertFalse(s(Items.WOODEN_PICKAXE).isCorrectToolForDrops(tile.getBlockState()),"source stone-tier harvest rejects wood");h.assertTrue(s(Items.STONE_PICKAXE).isCorrectToolForDrops(tile.getBlockState()),"source stone-tier harvest accepts stone");
            var hit=new BlockHitResult(Vec3.atCenterOf(absolute),Direction.NORTH,absolute,false);p.setShiftKeyDown(true);h.assertFalse(tile.getBlockState().useWithoutItem(level,p,hit).consumesAction(),"source sneaking passes");p.setShiftKeyDown(false);tile.getBlockState().useWithoutItem(level,p,hit);
            h.assertTrue(p.containerMenu instanceof ClassicPhaseGeneratorMenu,"actual ServerPlayer owns opened generator menu");var menu=(ClassicPhaseGeneratorMenu)p.containerMenu;h.assertValueEqual(menu.slots.size(),39,"three source slots plus36player");h.assertTrue(menu.isFor(tile)&&menu.sourcePos().equals(absolute),"native menu binds exact world tile");
            int[] x={45,112,42},y={12,51,80};for(int i=0;i<3;i++){h.assertValueEqual(menu.slots.get(i).x,x[i],"source X");h.assertValueEqual(menu.slots.get(i).y,y[i],"source Y");h.assertValueEqual(menu.slots.get(i).getContainerSlot(),i,"source raw slot");}
            h.assertTrue(menu.slots.get(0).mayPlace(s(ClassicFusion.PHASE_MATTER_UNIT.get()))&&menu.slots.get(1).mayPlace(s(ClassicFusion.PHASE_MATTER_UNIT.get())),"literal source imagPhase filter in both manual matter slots");h.assertFalse(menu.slots.get(1).mayPlace(s(ClassicFusion.MATTER_UNIT.get())),"literal source empty-return manual-placement quirk");h.assertFalse(menu.slots.get(2).mayPlace(s(Items.DIAMOND)),"native IF filter");
            p.getInventory().clearContent();p.getInventory().setItem(0,s(ClassicEnergyItems.ENERGY_UNIT.get()));h.assertFalse(menu.quickMoveStack(p,3).isEmpty(),"first player hotbar mapped safely");h.assertTrue(tile.getItem(2).is(ClassicEnergyItems.ENERGY_UNIT.get()),"native energy priority slot2");p.getInventory().setItem(8,s(ClassicFusion.PHASE_MATTER_UNIT.get()));h.assertFalse(menu.quickMoveStack(p,11).isEmpty(),"last hotbar mapped safely");h.assertTrue(tile.getItem(0).is(ClassicFusion.PHASE_MATTER_UNIT.get()),"native matter insertion slot0");tile.setItem(1,new ItemStack(ClassicFusion.MATTER_UNIT.get(),3));for(int i=0;i<3;i++)h.assertFalse(menu.quickMoveStack(p,i).isEmpty(),"all machine slots extract into real player inventory");h.assertTrue(tile.isEmpty(),"no duplicate machine payload remains");
            var hopper=level.getCapability(Capabilities.ItemHandler.BLOCK,absolute,Direction.DOWN);h.assertTrue(hopper!=null&&hopper.insertItem(1,s(Items.DIAMOND),false).isEmpty()&&tile.getItem(1).is(Items.DIAMOND),"source unrestricted TileInventory hopper insertion retained");
            p.moveTo(absolute.getX()+20,absolute.getY(),absolute.getZ(),0,0);h.assertFalse(menu.stillValid(p),"modern native menu reach fence");h.succeed();
        }
    }
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void phase_generator_native_fluid_simulation_all_sides_foreign_rejection_and_stale_fence(GameTestHelper h){
        var tile=tile(h);var level=h.getLevel();var pos=tile.getBlockPos();var phase=new FluidStack(ClassicFusion.PHASE_SOURCE.get(),9000);
        for(var side:Direction.values())h.assertTrue(level.getCapability(Capabilities.FluidHandler.BLOCK,pos,side)==tile.fluidHandler(),"source handler accessible on all6faces");var fluid=tile.fluidHandler();h.assertValueEqual(fluid.getTankCapacity(0),8000,"source native tank");h.assertValueEqual(fluid.fill(phase,FluidAction.SIMULATE),8000,"capacity-bounded simulated fill");h.assertValueEqual(tile.liquid(),0,"simulation no mutation");h.assertValueEqual(fluid.fill(new FluidStack(net.minecraft.world.level.material.Fluids.WATER,1000),FluidAction.EXECUTE),0,"foreign fill denied");h.assertValueEqual(fluid.fill(phase,FluidAction.EXECUTE),8000,"native full tank bounded");
        h.assertTrue(fluid.drain(new FluidStack(net.minecraft.world.level.material.Fluids.WATER,1000),FluidAction.EXECUTE).isEmpty(),"modern native drain contract rejects requested foreign fluid");h.assertValueEqual(fluid.drain(123,FluidAction.SIMULATE).getAmount(),123,"native simulated drain");h.assertValueEqual(tile.liquid(),8000,"simulated drain no debit");h.assertValueEqual(fluid.drain(123,FluidAction.EXECUTE).getAmount(),123,"native actual drain");h.assertValueEqual(tile.liquid(),7877,"actual finite debit");var snapshot=fluid.getFluidInTank(0);snapshot.setAmount(1);h.assertValueEqual(tile.liquid(),7877,"snapshot cannot mutate server tank");level.removeBlock(pos,false);h.assertValueEqual(fluid.fill(phase,FluidAction.EXECUTE),0,"retained removed handler cannot accept");h.assertTrue(fluid.drain(100,FluidAction.EXECUTE).isEmpty()&&fluid.getFluidInTank(0).isEmpty(),"retained removed handler cannot expose/debit phantomtank");h.succeed();
    }
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void phase_generator_native_strict_unit_boundary_refund_blocking_and_update_order(GameTestHelper h){
        var tile=tile(h);tile.setItem(0,new ItemStack(ClassicFusion.PHASE_MATTER_UNIT.get(),2));tile.buffer().load(6000,7000);tick(h,tile,1);h.assertValueEqual(tile.getItem(0).getCount(),2,"source exactly1000space rejects acquisition");h.assertValueEqual(tile.liquid(),7000,"saturated buffer consumes no liquid");tile.buffer().load(6000,6999);tick(h,tile,1);h.assertValueEqual(tile.getItem(0).getCount(),1,"strict1001space permits one real unit");h.assertValueEqual(tile.liquid(),7999,"one indivisible1000mB added");h.assertTrue(tile.getItem(1).is(ClassicFusion.MATTER_UNIT.get())&&tile.getItem(1).getCount()==1,"one real shell refunded");
        tile.buffer().load(0,0);tile.setItem(1,ItemStack.EMPTY);tick(h,tile,1);h.assertTrue(tile.getItem(0).isEmpty(),"last whole input consumed");h.assertValueEqual(tile.liquid(),1000,"fresh unit acquired after generation");equal(h,0,tile.getEnergy(),"source new unit cannot generate until nexttick");tick(h,tile,1);h.assertValueEqual(tile.liquid(),900,"source actual100mB drain");equal(h,50,tile.getEnergy(),"source actual0.5IF/mB");
        tile.setItem(0,s(ClassicFusion.PHASE_MATTER_UNIT.get()));tile.setItem(1,new ItemStack(ClassicFusion.MATTER_UNIT.get(),16));tile.buffer().load(6000,0);tick(h,tile,1);h.assertValueEqual(tile.liquid(),0,"full source16shell return blocks acquisition");h.assertValueEqual(tile.getItem(0).getCount(),1,"blocked transaction conserves fullunit");tile.setItem(1,s(Items.DIAMOND));tick(h,tile,1);h.assertValueEqual(tile.liquid(),0,"foreign returnslot blocks acquisition");tile.setItem(1,s(ClassicFusion.PHASE_MATTER_UNIT.get()));tick(h,tile,1);h.assertValueEqual(tile.liquid(),0,"literal menu-permitted filled return blocks actual acquisition");h.succeed();
    }
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void phase_generator_native_finite_generation_item_bandwidth_capacity_and_fractional_stop(GameTestHelper h){
        var tile=tile(h);tile.buffer().load(0,1000);var unit=s(ClassicEnergyItems.ENERGY_UNIT.get());tile.setItem(2,unit);tick(h,tile,1);equal(h,20,ClassicEnergyItemHelper.getEnergy(unit),"source native item20IF bandwidth");equal(h,30,tile.getEnergy(),"actual accepted20 debit from generated50");h.assertValueEqual(tile.liquid(),900,"generation before native item charge");
        var portable=s(AcademyCraft.DEVELOPER.get());tile.setItem(2,portable);tile.buffer().load(0,1000);tick(h,tile,1);equal(h,50,ClassicEnergyItemHelper.getEnergy(portable),"source generatorMK1 and portable50bandwidth");equal(h,0,tile.getEnergy(),"no finite generatedIF duplication");tile.setItem(2,ItemStack.EMPTY);tile.buffer().load(5999.75,1000);tick(h,tile,1);equal(h,5999.75,tile.getEnergy(),"source integer drain truncates sub0.5IF gap");h.assertValueEqual(tile.liquid(),1000,"sub1mB requirement consumes no fluid");tile.buffer().load(5999.5,1000);tick(h,tile,1);equal(h,6000,tile.getEnergy(),"source exact1mB fills remaining0.5IF");h.assertValueEqual(tile.liquid(),999,"source exact1mB debit");tick(h,tile,1);h.assertValueEqual(tile.liquid(),999,"full buffer burns no furtherfuel");
        var cap=h.getLevel().getCapability(ClassicSolarGenerators.IMAG_FLUX,tile.getBlockPos(),Direction.UP);h.assertTrue(cap==tile,"genuine shared generator capability");equal(h,50,cap.getBandwidth(),"sourceMK1 bandwidth");equal(h,125,cap.getProvidedEnergy(125),"source graph caller owns requestbandwidth");equal(h,5875,tile.getEnergy(),"exact finite extraction");equal(h,0,cap.getProvidedEnergy(-1),"modern negative request fence");equal(h,0,cap.getProvidedEnergy(Double.NaN),"modern nonfinite request fence");h.succeed();
    }
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void phase_generator_native_fresh_nbt_load_finite_payload_client_tag_and_single_drop(GameTestHelper h){
        var tile=tile(h);var level=h.getLevel();var pos=tile.getBlockPos();tile.buffer().load(123.625,2345);tile.setItem(0,new ItemStack(ClassicFusion.PHASE_MATTER_UNIT.get(),2));tile.setItem(1,new ItemStack(ClassicFusion.MATTER_UNIT.get(),3));var unit=s(ClassicEnergyItems.ENERGY_UNIT.get());ClassicEnergyItemHelper.setEnergy(unit,456.375);unit.set(DataComponents.CUSTOM_NAME,Component.literal("Declared finite phase battery"));tile.setItem(2,unit);
        var saved=tile.saveWithFullMetadata(level.registryAccess());h.assertTrue(saved.getString("id").equals("academy:phase_gen"),"real registered savedidentity");var restored=BlockEntity.loadStatic(pos,tile.getBlockState(),saved.copy(),level.registryAccess());h.assertTrue(restored instanceof ClassicPhaseGeneratorBlockEntity&&restored!=tile,"genuine registry constructs freshBE");level.removeBlockEntity(pos);level.setBlockEntity(restored);var loaded=(ClassicPhaseGeneratorBlockEntity)restored;equal(h,123.625,loaded.getEnergy(),"modern adaptation preserves conserved fractionalIF");h.assertValueEqual(loaded.liquid(),2345,"source liquid persistence");equal(h,456.375,ClassicEnergyItemHelper.getEnergy(loaded.getItem(2)),"native itempayload persists");h.assertTrue(loaded.getItem(2).getHoverName().getString().equals("Declared finite phase battery"),"unrelated component preserved");h.assertValueEqual(loaded.getItem(0).getCount(),2,"input persists");h.assertValueEqual(loaded.getItem(1).getCount(),3,"emptyrefunds persist");equal(h,0,tile.getProvidedEnergy(50),"old replacedBE cannotprovide");
        var clientTag=loaded.getUpdateTag(level.registryAccess());h.assertFalse(clientTag.contains("Items"),"presentation tag never resets native inventory");loaded.handleUpdateTag(clientTag,level.registryAccess());h.assertValueEqual(loaded.getItem(0).getCount(),2,"same view update leaves inventory payload intact");var malformed=saved.copy();malformed.putDouble("energy",Double.NaN);malformed.putInt("liquid",Integer.MAX_VALUE);var sanitized=(ClassicPhaseGeneratorBlockEntity)BlockEntity.loadStatic(pos,loaded.getBlockState(),malformed,level.registryAccess());equal(h,0,sanitized.presentationEnergy(),"malformed IF finite");h.assertValueEqual(sanitized.liquid(),8000,"malformed liquidcapacity bounded");level.destroyBlock(pos,true);
        int generators=0,full=0,empty=0,batteries=0;for(var dropped:level.getEntitiesOfClass(ItemEntity.class,new AABB(pos).inflate(3))){var stack=dropped.getItem();if(stack.is(ClassicPhaseGenerators.ITEM.get()))generators+=stack.getCount();if(stack.is(ClassicFusion.PHASE_MATTER_UNIT.get()))full+=stack.getCount();if(stack.is(ClassicFusion.MATTER_UNIT.get()))empty+=stack.getCount();if(stack.is(ClassicEnergyItems.ENERGY_UNIT.get())){batteries+=stack.getCount();equal(h,456.375,ClassicEnergyItemHelper.getEnergy(stack),"broken machine refunds exact real battery");}}h.assertValueEqual(generators,1,"one blockloot");h.assertValueEqual(full,2,"all actual inputunit loot once");h.assertValueEqual(empty,3,"all actual shell loot once");h.assertValueEqual(batteries,1,"one actual native battery loot");h.succeed();
    }
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void phase_generator_native_wireless_open_link_return_nonce_and_conserved_graph_transfer(GameTestHelper h){
        try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){
            var p=actors.player();var tile=tile(h);h.setBlock(NODE,ClassicWirelessDevices.BASIC.get());var node=(ClassicWirelessNodeBlockEntity)h.getBlockEntity(NODE);node.setPlacer(p);node.setPassword("phase-local-fixture");near(p,tile.getBlockPos());var hit=new BlockHitResult(Vec3.atCenterOf(tile.getBlockPos()),Direction.NORTH,tile.getBlockPos(),false);tile.getBlockState().useWithoutItem(h.getLevel(),p,hit);var inventory=(ClassicPhaseGeneratorMenu)p.containerMenu;
            var open=new ClassicWirelessProtocol.Request(inventory.containerId,ClassicWirelessProtocol.OPEN_TOKEN,"open_phasegen",tile.getBlockPos(),"","");h.assertTrue(ClassicWirelessProtocol.handle(p,open),"native exact phase inventory authorization opens wirelesspage");var menu=(ClassicWirelessMenu)p.containerMenu;h.assertValueEqual(menu.snapshot().getDouble("max_energy"),6000D,"source correctcapacity snapshot");h.assertValueEqual(menu.snapshot().getDouble("bandwidth"),50D,"source correctbandwidth snapshot");h.assertFalse(menu.snapshot().contains("password"),"no local node secret disclosure");h.assertFalse(ClassicWirelessProtocol.handle(p,request(menu,"link",node.getBlockPos(),"wrong")),"source node password required");h.assertTrue(ClassicWirelessProtocol.handle(p,request(menu,"link",node.getBlockPos(),"phase-local-fixture")),"actual phase links generatorbranch");var graph=ClassicWirelessSavedData.get(h.getLevel()).graph();var own=ClassicWirelessSavedData.pos(tile.getBlockPos());h.assertTrue(graph.nodeForGenerator(own).equals(ClassicWirelessSavedData.pos(node.getBlockPos()))&&graph.nodeForReceiver(own)==null,"phase is generator in actualgraph");tile.buffer().load(123.625,0);node.setEnergy(0);graph.tick();equal(h,73.625,tile.getEnergy(),"graph debits source50bandwidth");equal(h,50,node.getEnergy(),"node receives exact same50IF");equal(h,123.625,tile.getEnergy()+node.getEnergy(),"wireless totalIF conserved");
            h.assertTrue(ClassicWirelessProtocol.handle(p,request(menu,"return",tile.getBlockPos(),""))&&p.containerMenu instanceof ClassicPhaseGeneratorMenu,"real return opens original nativeinventory");h.assertFalse(ClassicWirelessProtocol.handle(p,request(menu,"unlink",tile.getBlockPos(),"")),"stale closedwireless nonce rejected");var fresh=(ClassicPhaseGeneratorMenu)p.containerMenu;h.assertTrue(ClassicWirelessProtocol.handle(p,new ClassicWirelessProtocol.Request(fresh.containerId,ClassicWirelessProtocol.OPEN_TOKEN,"open_phasegen",tile.getBlockPos(),"","")),"repeat native wirelessopen");var repeated=(ClassicWirelessMenu)p.containerMenu;h.assertTrue(ClassicWirelessProtocol.handle(p,request(repeated,"unlink",tile.getBlockPos(),""))&&graph.nodeForGenerator(own)==null,"real unlink generatorbranch");p.moveTo(tile.getBlockPos().getX()+20,tile.getBlockPos().getY(),tile.getBlockPos().getZ(),0,0);h.assertFalse(ClassicWirelessProtocol.handle(p,request(repeated,"link",node.getBlockPos(),"phase-local-fixture")),"distant native wirelessaction rejected");h.succeed();
        }
    }
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void phase_generator_native_source_recipe_consumption_world_collection_and_earned_power(GameTestHelper h){
        try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){
            var p=actors.player();var level=h.getLevel();var table=h.absolutePos(new BlockPos(1,1,1));level.setBlockAndUpdate(table,Blocks.CRAFTING_TABLE.defaultBlockState());var craft=new CraftingMenu(91,p.getInventory(),ContainerLevelAccess.create(level,table));p.containerMenu=craft;
            // Declared source material fixtures; ordinary mined/smelted acquisition is separately covered.
            craft.getSlot(1).set(s(ClassicMaterials.CRYSTAL_LOW.get()));craft.getSlot(2).set(s(ClassicMaterials.MACHINE_FRAME.get().asItem()));craft.getSlot(3).set(s(ClassicMaterials.CRYSTAL_LOW.get()));craft.getSlot(4).set(s(ClassicFusion.MATTER_UNIT.get()));craft.getSlot(6).set(s(ClassicFusion.MATTER_UNIT.get()));h.assertTrue(craft.getSlot(0).getItem().is(ClassicPhaseGenerators.ITEM.get()),"real native ResultSlot exact source2rowrecipe");var generator=craft.getSlot(0).remove(1);craft.getSlot(0).onTake(p,generator);for(int slot:new int[]{1,2,3,4,6})h.assertTrue(craft.getSlot(slot).getItem().isEmpty(),"one actual native source ingredientconsumed");h.assertTrue(cn.academy.port.tutorial.TutorialStorage.get(p).visible("phase_generator"),"actual crafted event unlocks existing classic guidepage");p.closeContainer();near(p,h.absolutePos(BASE));p.setItemInHand(InteractionHand.MAIN_HAND,generator);h.assertTrue(ClassicPhaseGenerators.ITEM.get().place(new BlockPlaceContext(p,InteractionHand.MAIN_HAND,generator,new BlockHitResult(Vec3.atCenterOf(h.absolutePos(BASE)),Direction.UP,h.absolutePos(BASE),false))).consumesAction()&&generator.isEmpty(),"actual crafted generatorplaced");var tile=(ClassicPhaseGeneratorBlockEntity)h.getBlockEntity(BASE);
            var source=h.absolutePos(new BlockPos(6,1,6));level.setBlockAndUpdate(source,ClassicFusion.PHASE_BLOCK.get().defaultBlockState());level.setBlockAndUpdate(source.above(),Blocks.AIR.defaultBlockState());level.setBlockAndUpdate(source.above(2),Blocks.AIR.defaultBlockState());level.setBlockAndUpdate(source.above(3),Blocks.AIR.defaultBlockState());p.getInventory().clearContent();p.setItemInHand(InteractionHand.MAIN_HAND,s(ClassicFusion.MATTER_UNIT.get()));p.moveTo(source.getX()+.5,source.getY()+2,source.getZ()+.5,0,90);var used=ClassicFusion.MATTER_UNIT.get().use(level,p,InteractionHand.MAIN_HAND);h.assertTrue(used.getResult().consumesAction()&&used.getObject().is(ClassicFusion.PHASE_MATTER_UNIT.get()),"genuine source block collected via actual matterunit rightclick");h.assertTrue(level.isEmptyBlock(source),"source collection physically consumes declared worldfluid");tile.setItem(0,used.getObject());var portable=s(AcademyCraft.DEVELOPER.get());tile.setItem(2,portable);tick(h,tile,11);h.assertValueEqual(tile.liquid(),0,"earned1000mB drained at100pergenerationtick");equal(h,500,ClassicEnergyItemHelper.getEnergy(portable),"genuine collected phase generates exactly500IF into empty native portable");equal(h,0,tile.getEnergy(),"no excess inventedpower");h.assertValueEqual(tile.getItem(1).getCount(),1,"exact one real empty shellrefund");h.assertTrue(tile.getItem(0).isEmpty(),"exact one real fullcontainerconsumed");h.succeed();
        }
    }
    @GameTest(template=TEMPLATE,batch=BATCH,timeoutTicks=20)
    public static void phase_generator_native_source_packet_snapshots_10_20ticks_before_acquisition_and_charge(GameTestHelper h){
        var tile=tile(h);tile.buffer().load(0,2000);var unit=s(ClassicEnergyItems.ENERGY_UNIT.get());tile.setItem(2,unit);tick(h,tile,10);var ten=tile.getUpdatePacket().getTag();h.assertTrue(ten.contains("liquid")&&!ten.contains("energy"),"source tick10 publishes only liquid");h.assertValueEqual(ten.getInt("liquid"),1000,"source liquid snapshot after generation");equal(h,300,tile.getEnergy(),"native after10 ticks finite item recharge");tick(h,tile,9);tile.setItem(0,s(ClassicFusion.PHASE_MATTER_UNIT.get()));tick(h,tile,1);var twenty=tile.getUpdatePacket().getTag();h.assertTrue(twenty.contains("energy")&&twenty.contains("liquid"),"source tick20 publishes both independent clocks");equal(h,620,twenty.getDouble("energy"),"source energy snapshot before twentieth20IF native itemcharge");h.assertValueEqual(twenty.getInt("liquid"),0,"source liquid snapshot before newunit acquisition");equal(h,600,tile.getEnergy(),"actual twentiethcharge leaves600IF");h.assertValueEqual(tile.liquid(),1000,"actual twentiethacquisition adds wholeunit after snapshot");var partial=new net.minecraft.nbt.CompoundTag();partial.putInt("liquid",1234);tile.handleUpdateTag(partial,h.getLevel().registryAccess());equal(h,600,tile.presentationEnergy(),"liquid-only update retains lastenergy");h.assertValueEqual(tile.liquid(),1234,"liquid-only presentation update");partial=new net.minecraft.nbt.CompoundTag();partial.putDouble("energy",123.625);tile.handleUpdateTag(partial,h.getLevel().registryAccess());equal(h,123.625,tile.presentationEnergy(),"energy-only presentation update");h.assertValueEqual(tile.liquid(),1234,"energy-only update retains lastliquid");h.succeed();
    }

}
