/* AcademyCraft1.0.7 Teleporter native fixtures, GPLv3. Compiled here; execution belongs to main. */
package cn.academy.port.gametest;
import cn.academy.port.*;
import cn.academy.port.api.SkillAttackEvent;
import cn.academy.port.core.*;
import cn.academy.port.develop.*;
import cn.academy.port.machine.*;
import cn.academy.port.skill.*;
import com.mojang.authlib.GameProfile;
import io.netty.channel.embedded.EmbeddedChannel;
import net.minecraft.network.Connection;
import net.minecraft.network.protocol.PacketFlow;
import net.minecraft.server.network.CommonListenerCookie;
import net.minecraft.world.level.GameType;
import net.neoforged.neoforge.network.registration.NetworkRegistry;
import net.minecraft.core.*;
import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.*;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.npc.Villager;
import net.minecraft.world.item.*;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.*;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.common.util.FakePlayer;
import net.neoforged.neoforge.event.level.LevelEvent;
import net.neoforged.neoforge.gametest.*;
import java.util.*;
@GameTestHolder("academy") @PrefixGameTestTemplate(false) @EventBusSubscriber(modid="academy")
public final class AcademyTeleporterProgressionRuntimeTests {
 private static final String TEMPLATE="teleporter_progression_empty";private AcademyTeleporterProgressionRuntimeTests(){}
 @SubscribeEvent public static void install(LevelEvent.Load e){if(!GameTestHooks.isGametestEnabled()||!(e.getLevel() instanceof ServerLevel world))return;var tag=new CompoundTag();var size=new ListTag();size.add(IntTag.valueOf(64));size.add(IntTag.valueOf(16));size.add(IntTag.valueOf(64));tag.put("size",size);var blocks=new ListTag();var first=new CompoundTag();var pos=new ListTag();pos.add(IntTag.valueOf(0));pos.add(IntTag.valueOf(0));pos.add(IntTag.valueOf(0));first.put("pos",pos);first.putInt("state",0);blocks.add(first);tag.put("blocks",blocks);tag.put("entities",new ListTag());var palette=new ListTag();var air=new CompoundTag();air.putString("Name","minecraft:air");palette.add(air);tag.put("palette",palette);world.getStructureManager().getOrCreate(ResourceLocation.fromNamespaceAndPath("academy",TEMPLATE)).load(world.registryAccess().lookupOrThrow(Registries.BLOCK),tag);}
 @GameTest(template=TEMPLATE,batch="academy_teleporter_progression",timeoutTicks=10)
 public static void penetrate_open_air_step_overshoot_force_cost_fall_reset_and_counter(GameTestHelper h){var f=new Fixture(h);var p=f.connectedPlayer();var s=ready(p,PenetrateTeleport.ID,2,0);Vec3 from=p.position();p.fallDistance=40;double cp=s.cp;var d=PenetrateTeleport.destination(h.getLevel(),p.getEyePosition(),ClassicRaytrace.direction(p),0,cp);Vec3 expected=new Vec3(d.position().x(),d.position().y(),d.position().z());h.assertTrue(PenetrateTeleport.start(p,1)&&PenetrateTeleport.release(p,1),"source release executes");near(h,p.getZ(),expected.z,"source thirteen .8 advances");near(h,p.getY(),expected.y,"eye-origin destination retained");double distance=from.distanceTo(expected);near(h,s.cp,(float)cp-(float)(distance*14),"requested source float CP");near(h,s.overload,80,"source overload");near(h,s.exp(PenetrateTeleport.ID),TeleporterProgressionRules.penetrateExperience(distance),"distance EXP");h.assertValueEqual(s.cooldowns.get(PenetrateTeleport.ID),50,"source 50 tick cooldown");near(h,p.fallDistance,0,"fall reset");h.assertValueEqual(p.getPersistentData().getInt("ac_tpcount"),1,"original persistent counter");h.assertTrue(p.getPersistentData().getBoolean("ac_teleporter_ignore_barrier"),"classic achievement fact recorded");h.assertFalse(PenetrateTeleport.release(p,1),"duplicate release denied");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_teleporter_progression",timeoutTicks=10)
 public static void penetrate_unavailable_still_executes_with_CP_floor_and_no_block_break(GameTestHelper h){var f=new Fixture(h);var p=f.connectedPlayer();var s=ready(p,PenetrateTeleport.ID,2,0);s.cp=14;var eye=p.getEyePosition();var probe=new BlockPos((int)eye.x,(int)eye.y,(int)eye.z);for(int z=0;z<4;z++){var pos=probe.offset(0,0,z);h.getLevel().setBlock(pos,Blocks.BEDROCK.defaultBlockState(),3);h.getLevel().setBlock(pos.above(),Blocks.BEDROCK.defaultBlockState(),3);}var d=PenetrateTeleport.destination(h.getLevel(),eye,ClassicRaytrace.direction(p),0,14);h.assertFalse(d.available(),"source stage1 unavailable at truncation-based probe, including negative coordinates");h.assertTrue(PenetrateTeleport.start(p,1)&&PenetrateTeleport.release(p,1),"deferred terminate does not return");near(h,s.cp,0,"force consumes overshoot above finite CP");near(h,s.overload,80,"force overload retained");h.assertTrue(s.exp(PenetrateTeleport.ID)>0,"canonical unavailable teleport trains");h.assertTrue(h.getLevel().getBlockState(probe).is(Blocks.BEDROCK),"barrier remains intact");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_teleporter_progression",timeoutTicks=10)
 public static void mark_zero_tick_below_three_aborts_and_tick_one_charge_succeeds(GameTestHelper h){var f=new Fixture(h);var p=f.connectedPlayer();var s=ready(p,MarkTeleport.ID,2,0);double cp=s.cp;h.assertTrue(MarkTeleport.start(p,1),"zero tick context");h.assertFalse(MarkTeleport.release(p,1),"distance below three free abort");near(h,s.cp,cp,"no abort CP");h.assertTrue(s.cooldowns.isEmpty()&&s.exp(MarkTeleport.ID)==0,"no abort cooldown or EXP");h.assertTrue(MarkTeleport.start(p,2),"fresh nonce starts");Vec3 from=p.position();h.runAtTickTime(1,()->{MarkTeleport.tick(p);MarkTeleport.tick(p);h.assertValueEqual(MarkTeleport.heldTicks(p),1,"same world tick cannot charge twice");Vec3 expected=MarkTeleport.destination(p,0,s.cp,1);double distance=from.distanceTo(expected);h.assertTrue(MarkTeleport.release(p,2),"canonical first tick four block release");near(h,p.getZ(),expected.z,"server destination");near(h,s.cp,cp-(float)distance*12,"source distance float CP");near(h,s.overload,40,"source overload");near(h,s.exp(MarkTeleport.ID),TeleporterProgressionRules.markExperience(distance),"source EXP");h.assertValueEqual(s.cooldowns.get(MarkTeleport.ID),30,"source cooldown");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_teleporter_progression",timeoutTicks=10)
 public static void mark_real_block_face_head_adjustment_and_entity_eye_offset(GameTestHelper h){var f=new Fixture(h);var p=f.player();ready(p,MarkTeleport.ID,2,0);var at=BlockPos.containing(p.getEyePosition().add(0,0,4));h.getLevel().setBlock(at,Blocks.STONE.defaultBlockState(),3);Vec3 block=MarkTeleport.destination(p,0,1000,6);near(h,block.z,at.getZ()-.6,"north face offset .6");near(h,block.y,at.getY()+1.7,"source side anchor");var head=new BlockPos((int)block.x,(int)(block.y+1),(int)block.z);h.getLevel().setBlock(head,Blocks.BEDROCK.defaultBlockState(),3);Vec3 adjusted=MarkTeleport.destination(p,0,1000,6);near(h,adjusted.y,block.y-1.25,"non-air side head lowers by1.25");h.getLevel().setBlock(at,Blocks.AIR.defaultBlockState(),3);h.getLevel().setBlock(head,Blocks.AIR.defaultBlockState(),3);var target=f.target(p.position().add(0,0,5));Vec3 entity=MarkTeleport.destination(p,0,1000,6);near(h,entity.y,target.getY()+target.getEyeHeight(),"classic entity feet plus eye");near(h,entity.z,target.getZ(),"entity hit reports feet not hitbox intercept");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_teleporter_progression",timeoutTicks=10)
 public static void flesh_native_bypass_armor_protected_training_and_cached_tick_target(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,FleshRipping.ID,3,0);var target=f.target(p.position().add(0,0,4));target.getAttribute(Attributes.ARMOR).setBaseValue(30);var hook=new Hook(p);f.hook(hook);double cp=s.cp;h.assertTrue(FleshRipping.start(p,1),"server captures initial target safely");p.setYHeadRot(90);h.assertTrue(FleshRipping.release(p,1),"stored target unchanged between server ticks");near(h,target.getHealth(),195,"five damage bypasses actual native armor30");near(h,hook.damage,5,"source damage");near(h,s.cp,cp-130,"source CP");near(h,s.overload,60,"source overload");near(h,s.exp(FleshRipping.ID),.005F,"source EXP");h.assertValueEqual(s.cooldowns.get(FleshRipping.ID),90,"source cooldown");h.assertFalse(FleshRipping.release(p,1),"one committed attack");s.cooldowns.clear();s.cooldownMaxTicks.clear();p.setYHeadRot(0);target.invulnerableTime=0;hook.zero=true;h.assertTrue(FleshRipping.start(p,2)&&FleshRipping.release(p,2),"damage pipeline may reject attack");near(h,target.getHealth(),195,"native zero damage protection honored");near(h,s.exp(FleshRipping.ID),2*.005F,"source target acquisition still trains");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_teleporter_progression",timeoutTicks=10)
 public static void flesh_wall_occludes_miss_is_free_and_low_CP_first_tick_terminates(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,FleshRipping.ID,3,0);f.target(p.position().add(0,0,4));var wall=BlockPos.containing(p.getEyePosition().add(0,0,2));h.getLevel().setBlock(wall,Blocks.BEDROCK.defaultBlockState(),3);double cp=s.cp;h.assertTrue(FleshRipping.start(p,1),"held source targeting");h.assertFalse(FleshRipping.release(p,1),"wall hit has no living target");near(h,s.cp,cp,"miss is free");h.assertTrue(s.cooldowns.isEmpty()&&s.exp(FleshRipping.ID)==0,"miss earns nothing");h.getLevel().setBlock(wall,Blocks.AIR.defaultBlockState(),3);s.cp=129;h.assertTrue(FleshRipping.start(p,2),"source CP check occurs on held tick");h.runAtTickTime(1,()->{FleshRipping.tick(p);h.assertFalse(FleshRipping.active(p),"below130 CP ends");near(h,s.cp,129,"insufficient CP termination free");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_teleporter_progression",timeoutTicks=10)
 public static void nonce_slot_ingress_lifecycle_and_nonfinite_aim_guards(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,PenetrateTeleport.ID,2,0);h.assertTrue(bind(s,0,PenetrateTeleport.ID),"real selectable preset");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("skill_start",PenetrateTeleport.ID)),"raw skill-name ingress denied");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press","0")),"unbound nonce ingress denied");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:01")),"noncanonical nonce denied");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:1")),"authenticated slot starts");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_release_token","0:2")),"stale terminal cannot release live context");h.assertTrue(PenetrateTeleport.active(p),"live hold retained");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_abort_token","0:1")),"matching terminal ends");h.assertFalse(PenetrateTeleport.start(p,1),"replay tombstone");h.assertTrue(PenetrateTeleport.start(p,2),"new nonce starts");AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("toggle",""));h.assertFalse(PenetrateTeleport.active(p),"toggle abort disposes hold");s.activated=true;p.setYHeadRot(Float.NaN);h.assertFalse(PenetrateTeleport.start(p,3),"nonfinite native aim fails closed");p.setYHeadRot(0);s.cp=Double.NaN;h.assertFalse(PenetrateTeleport.start(p,3),"nonfinite CP fails closed");s.cp=s.maxCp();h.assertTrue(PenetrateTeleport.start(p,3),"valid new context");PenetrateTeleport.remove(p);h.assertFalse(PenetrateTeleport.active(p),"logout/dimension/death explicit lifecycle disposal");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_teleporter_progression_learning",timeoutTicks=20)
 public static void portable_use_and_common_GUI_ingress_genuinely_learn_both_level_two_targets(GameTestHelper h){var f=new Fixture(h);var p=f.player();for(String id:List.of(PenetrateTeleport.ID,MarkTeleport.ID)){DevelopmentController.remove(p);var s=AbilityStorage.get(p);s.selectCategory("teleporter");s.setLevel(2);var skill=SkillCatalog.find(s.category,id).orElseThrow();for(var r:skill.requirements()){s.learn(r.id());s.experience.put(r.id(),r.exp());}var stack=new ItemStack(AcademyCraft.DEVELOPER.get());p.setItemInHand(InteractionHand.MAIN_HAND,stack);new DeveloperItemEnergy(stack,DeveloperType.PORTABLE).energy(10000);h.assertTrue(AcademyCraft.DEVELOPER.get().use(h.getLevel(),p,InteractionHand.MAIN_HAND).getResult().consumesAction(),"actual portable DeveloperMenu opening action");h.assertFalse(s.learned(id),"target never fixture granted");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("learn",id)),"genuine server common learning ingress");int ticks=130;for(int tick=1;tick<=ticks;tick++){DevelopmentController.tick(p,snapshot->{});if(tick<ticks)h.assertFalse(s.learned(id),"no early learning");}h.assertTrue(s.learned(id)&&s.exp(id)==0&&DevelopmentController.process(p).state()==DevelopmentProcess.State.DONE,"target genuinely earned at zero mastery");near(h,new DeveloperItemEnergy(stack,DeveloperType.PORTABLE).energy(),6100,"finite 3900 IF drained");s.activated=true;h.assertTrue(bind(s,0,id),"canonical preset path accepts earned skill");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:1")),"genuinely earned zero mastery slot activation");h.assertTrue(id.equals(PenetrateTeleport.ID)?PenetrateTeleport.active(p):MarkTeleport.active(p),"natural learned context is active");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_abort_token","0:1")),"natural learned context cleans up");}h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_teleporter_progression_learning",timeoutTicks=20)
 public static void physical_Normal_GUI_genuinely_learns_flesh_with_two_original_prerequisites(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=AbilityStorage.get(p);s.selectCategory("teleporter");s.setLevel(3);for(var r:SkillCatalog.find(s.category,FleshRipping.ID).orElseThrow().requirements()){s.learn(r.id());s.experience.put(r.id(),r.exp());}var portable=new ItemStack(AcademyCraft.DEVELOPER.get());p.setItemInHand(InteractionHand.MAIN_HAND,portable);new DeveloperItemEnergy(portable,DeveloperType.PORTABLE).energy(10000);h.assertFalse(DevelopmentController.startSkill(p,FleshRipping.ID),"portable cannot learn level3");var item=MachineDevelopers.NORMAL_ITEM.get();var stack=new ItemStack(item);p.setItemInHand(InteractionHand.MAIN_HAND,stack);var base=h.absolutePos(new BlockPos(12,1,14));h.assertTrue(item.place(new BlockPlaceContext(p,InteractionHand.MAIN_HAND,stack,new BlockHitResult(Vec3.atCenterOf(base),Direction.UP,base,false))).consumesAction(),"physical eight-cell normal developer");var machine=(MachineDeveloperBlockEntity)h.getLevel().getBlockEntity(base);p.moveTo(base.getX()+.5,base.getY(),base.getZ()-1.5,0,0);machine.battery().load(50000);h.assertFalse(s.learned(FleshRipping.ID),"target never fixture granted");h.assertTrue(machine.use(p),"real Normal DeveloperMenu route");String nonce=MachineDeveloperSessions.activeToken(p).orElseThrow().toString();h.assertFalse(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",UUID.randomUUID()+":"+FleshRipping.ID)),"forged GUI session denied");s.experience.put(PenetrateTeleport.ID,.499);h.assertFalse(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",nonce+":"+FleshRipping.ID)),"second prerequisite remains required");s.experience.put(PenetrateTeleport.ID,.5);h.assertTrue(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",nonce+":"+FleshRipping.ID)),"genuine common registry path");for(int tick=1;tick<=147;tick++){DevelopmentController.tick(p,snapshot->{});if(tick<147)h.assertFalse(s.learned(FleshRipping.ID),"seven source21-tick stimulations");}h.assertTrue(s.learned(FleshRipping.ID)&&s.exp(FleshRipping.ID)==0,"genuinely earned zero EXP");near(h,machine.battery().getEnergy(),44855,"finite5145 IF drain");s.activated=true;h.assertTrue(bind(s,0,FleshRipping.ID),"earned target preset path");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:1")),"zero mastery genuine slot activation");h.assertTrue(FleshRipping.active(p),"no mastery cheat is needed");FleshRipping.abort(p,1);h.succeed();}
 private static boolean bind(AbilityProgress s,int slot,String id){return s.presets.edit(0,slot,id,value->cn.academy.port.preset.PresetSkills.selectable(s,value));}private static AbilityProgress ready(ServerPlayer p,String id,int level,double exp){var s=AbilityStorage.get(p);s.selectCategory("teleporter");s.setLevel(level);s.learn(id);s.experience.put(id,exp);s.activated=true;return s;}private static void near(GameTestHelper h,double a,double b,String why){h.assertTrue(Math.abs(a-b)<1E-4,why+" actual="+a+" expected="+b);}
 private static final class Fixture{final GameTestHelper h;final List<ServerPlayer> players=new ArrayList<>();final List<EmbeddedChannel> channels=new ArrayList<>();final List<Entity> entities=new ArrayList<>();final List<Object> hooks=new ArrayList<>();boolean closed;Fixture(GameTestHelper h){this.h=h;h.testInfo.addListener(new GameTestListener(){public void testStructureLoaded(GameTestInfo i){}public void testPassed(GameTestInfo i,GameTestRunner r){cleanup();}public void testFailed(GameTestInfo i,GameTestRunner r){cleanup();}public void testAddedForRerun(GameTestInfo i,GameTestInfo n,GameTestRunner r){cleanup();}});}FakePlayer player(){var p=new FakePlayer(h.getLevel(),new GameProfile(UUID.randomUUID(),"[AC-TP-Progress]"));players.add(p);Vec3 at=h.absoluteVec(new Vec3(10.5,1,10.5));p.moveTo(at.x,at.y,at.z,0,0);p.setYHeadRot(0);p.setNoGravity(true);p.setDeltaMovement(Vec3.ZERO);p.getAbilities().instabuild=false;return p;}
 /** Official FakePlayer connection.teleport is a no-op. Movement fixtures use the ordinary
  * native ServerPlayer listener after actual PlayerList admission and GameTest mock registration. */
 ServerPlayer connectedPlayer(){var level=h.getLevel();var server=level.getServer();var uuid=UUID.randomUUID();var cookie=CommonListenerCookie.createInitial(new GameProfile(uuid,"ACTP"+uuid.toString().substring(0,8)),false);var p=new ServerPlayer(server,level,cookie.gameProfile(),cookie.clientInformation());players.add(p);var connection=new Connection(PacketFlow.SERVERBOUND);var channel=new EmbeddedChannel(connection);channels.add(channel);NetworkRegistry.configureMockConnection(connection);try{server.getPlayerList().placeNewPlayer(connection,p,cookie);h.assertTrue(server.getPlayerList().getPlayer(p.getUUID())==p&&p.serverLevel()==level,"exact owned ServerPlayer admitted in native test world");h.assertTrue(p.getClass()==ServerPlayer.class,"no FakePlayer teleport override");var at=h.absoluteVec(new Vec3(10.5,1,10.5));p.moveTo(at.x,at.y,at.z,0,0);p.setYHeadRot(0);p.setNoGravity(true);p.setDeltaMovement(Vec3.ZERO);p.setGameMode(GameType.SURVIVAL);
  // Independently establish the fixture's real teleport capability before invoking either skill.
  p.teleportTo(at.x+.125,at.y,at.z);near(h,p.getX(),at.x+.125,"native listener really applies teleport");p.teleportTo(at.x,at.y,at.z);near(h,p.getX(),at.x,"native listener restores fixture origin");return p;
 }catch(RuntimeException failure){try{cleanup();}catch(RuntimeException next){failure.addSuppressed(next);}throw failure;}}
 Villager target(Vec3 at){var v=h.spawnWithNoFreeWill(EntityType.VILLAGER,new Vec3(1,1,1));entities.add(v);v.moveTo(at.x,at.y,at.z,0,0);v.setNoAi(true);v.setNoGravity(true);v.setDeltaMovement(Vec3.ZERO);v.getAttribute(Attributes.MAX_HEALTH).setBaseValue(200);v.setHealth(200);return v;}void hook(Object o){hooks.add(o);NeoForge.EVENT_BUS.register(o);}void cleanup(){if(closed)return;closed=true;for(var o:hooks)NeoForge.EVENT_BUS.unregister(o);for(var p:players){PenetrateTeleport.remove(p);MarkTeleport.remove(p);FleshRipping.remove(p);DevelopmentController.remove(p);MachineDeveloperSessions.close(p);AbilityStorage.remove(p);var list=h.getLevel().getServer().getPlayerList();if(list.getPlayer(p.getUUID())==p)list.remove(p);else p.discard();}for(var e:entities)e.discard();for(var channel:channels)channel.finishAndReleaseAll();}}
 public static final class Hook{final ServerPlayer owner;double damage;boolean zero;Hook(ServerPlayer p){owner=p;}@SubscribeEvent public void attack(SkillAttackEvent e){if(e.player==owner&&e.skill.equals("teleporter.flesh_ripping")){damage=e.amount;if(zero)e.amount=0;}}}
}
