/* AcademyCraft1.0.7 VecManip Lv2 native fixtures, GPLv3; see NOTICE. */
package cn.academy.port.gametest;

import cn.academy.port.*;
import cn.academy.port.core.*;
import cn.academy.port.develop.*;
import cn.academy.port.machine.*;
import cn.academy.port.skill.*;
import cn.academy.port.preset.PresetSkills;
import com.mojang.authlib.GameProfile;
import io.netty.channel.embedded.EmbeddedChannel;
import io.netty.buffer.Unpooled;
import net.minecraft.network.Connection;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.protocol.PacketFlow;
import net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket;
import net.minecraft.server.network.CommonListenerCookie;
import net.minecraft.world.level.GameType;
import net.neoforged.neoforge.network.registration.NetworkRegistry;
import net.minecraft.core.*;
import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.*;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.npc.Villager;
import net.minecraft.world.entity.projectile.*;
import net.minecraft.world.item.*;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.*;
import net.neoforged.bus.api.*;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.common.util.FakePlayer;
import net.neoforged.neoforge.event.entity.living.LivingIncomingDamageEvent;
import net.neoforged.neoforge.event.level.ExplosionEvent;
import net.neoforged.neoforge.event.level.LevelEvent;
import net.neoforged.neoforge.gametest.*;
import java.util.*;
import java.util.function.IntConsumer;

import cn.academy.port.api.SkillReflectEvent;
import cn.academy.port.api.SkillAttackEvent;
/** Compiled in isolation only. Parent owns native execution and final GUI/client/audio acceptance. */
@GameTestHolder("academy") @PrefixGameTestTemplate(false) @EventBusSubscriber(modid="academy")
public final class AcademyVectorFinalRuntimeTests {
    private static final String TEMPLATE="vector_final_empty";
    @SubscribeEvent public static void install(LevelEvent.Load event){
        if(!GameTestHooks.isGametestEnabled()||!(event.getLevel() instanceof ServerLevel world))return;
        var tag=new CompoundTag();var size=new ListTag();size.add(IntTag.valueOf(64));size.add(IntTag.valueOf(32));size.add(IntTag.valueOf(64));tag.put("size",size);
        var blocks=new ListTag();var first=new CompoundTag();var pos=new ListTag();pos.add(IntTag.valueOf(0));pos.add(IntTag.valueOf(0));pos.add(IntTag.valueOf(0));first.put("pos",pos);first.putInt("state",0);blocks.add(first);tag.put("blocks",blocks);tag.put("entities",new ListTag());
        var palette=new ListTag();var air=new CompoundTag();air.putString("Name","minecraft:air");palette.add(air);tag.put("palette",palette);
        world.getStructureManager().getOrCreate(ResourceLocation.fromNamespaceAndPath("academy",TEMPLATE)).load(world.registryAccess().lookupOrThrow(Registries.BLOCK),tag);
    }
 @GameTest(template=TEMPLATE,batch="academy_vector_final_01",timeoutTicks=30)
 public static void physical_Advanced_DeveloperMenu_genuinely_learns_unlearned_targets_with_finite_IF(GameTestHelper h){var f=new Fixture(h);var p=f.player();var item=MachineDevelopers.ADVANCED_ITEM.get();var stack=new ItemStack(item);p.setItemInHand(InteractionHand.MAIN_HAND,stack);var base=h.absolutePos(new BlockPos(24,1,28));h.assertTrue(item.place(new BlockPlaceContext(p,InteractionHand.MAIN_HAND,stack,new BlockHitResult(Vec3.atCenterOf(base),Direction.UP,base,false))).consumesAction(),"Physical eight-cell Advanced Developer placed");var machine=(MachineDeveloperBlockEntity)h.getLevel().getBlockEntity(base);p.moveTo(base.getX()+.5,base.getY(),base.getZ()-1.5,0,0);
  for(String id:List.of(VecReflection.ID,PlasmaCannon.ID)){DevelopmentController.remove(p);var s=AbilityStorage.get(p);s.selectCategory("vecmanip");int level=id.equals(VecReflection.ID)?4:5;s.setLevel(level);String parent=level==4?VecDeviation.ID:"storm_wing";s.learn(parent);h.assertFalse(s.learned(id),"Target has never been fixture-granted");machine.battery().load(200000);h.assertTrue(machine.use(p)&&MachineDeveloperSessions.activeToken(p).isPresent(),"Actual server Developer screen route and finite machine session");String token=MachineDeveloperSessions.activeToken(p).orElseThrow().toString();h.assertFalse(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",UUID.randomUUID()+":"+id)),"Forged sender-session denied");s.experience.remove(parent);h.assertFalse(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",token+":"+id)),"Actual source learned-parent gate");s.learn(parent);s.level=level-1;h.assertFalse(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",token+":"+id)),"Actual source category level gate");s.level=level;h.assertTrue(s.exp(parent)==0&&MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",token+":"+id)),"Zero mastery parent is sufficient");int ticks=level==4?176:240;for(int t=1;t<=ticks;t++){DevelopmentController.tick(p,x->{});if(t<ticks)h.assertFalse(s.learned(id),"No early or debug target grant");}h.assertTrue(s.learned(id)&&s.exp(id)==0&&DevelopmentController.process(p).state()==DevelopmentProcess.State.DONE,"Genuine source learning process completed");near(h,machine.battery().getEnergy(),200000-ticks*40,"Finite Advanced IF7040/9600");s.activated=true;h.assertTrue(bind(s,0,id),"Actually earned zero mastery target binds");MachineDeveloperSessions.close(p);}h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_vector_final_02",timeoutTicks=10)
 public static void real_wire_toggle_nonce_delegates_preserve_both_persistent_contexts_and_V_ends(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,VecReflection.ID,0);s.extraOverload=ClassicRules.EXTRA_OVERLOAD_CAP[s.level];bind(s,0,VecReflection.ID);h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("skill_start",VecReflection.ID)),"Arbitrary skill-name wire denied");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:01")),"Noncanonical physical nonce denied");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:1")),"Actual bound-slot starts toggle");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_abort_token","0:9")),"Forged terminal nonce denied");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_release_token","0:1"))&&VecReflection.active(p),"Source key-up preserves toggle");s.learn(VecDeviation.ID);VecDeviation.start(p,1);s.interfering=true;VecReflection.tick(p);VecDeviation.tick(p);h.assertTrue(VecReflection.active(p)&&VecDeviation.active(p),"Both contextActivate skills survive interference delegate abort");s.interfering=false;h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("preset_switch","1"))&&VecReflection.active(p)&&VecDeviation.active(p),"Actual preset flush preserves both persistent contexts");AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("abort_active",""));h.assertFalse(VecReflection.active(p)||VecDeviation.active(p),"Actual V route ends both");h.assertTrue(s.cooldowns.isEmpty(),"No invented toggle cooldown");h.assertFalse(VecReflection.start(p,1),"Retired physical nonce replay denied");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_vector_final_03",timeoutTicks=10)
 public static void native_arrows_snowballs_potions_and_caster_preserve_speed_marker_difficulty_and_visited(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,VecReflection.ID,0);var arrow=new Arrow(EntityType.ARROW,h.getLevel());f.entity(arrow,p.position().add(0,.1,2));arrow.setBaseDamage(9);var snow=new Snowball(EntityType.SNOWBALL,h.getLevel());f.entity(snow,p.position().add(1,0,2));var potion=new ThrownPotion(EntityType.POTION,h.getLevel());f.entity(potion,p.position().add(-1,0,2));var mob=f.mob(p.position().add(2,0,2));VecReflection.start(p,1);h.runAtTickTime(1,()->{arrow.setDeltaMovement(new Vec3(.3,.4,0));snow.setDeltaMovement(new Vec3(.2,.1,0));potion.setDeltaMovement(new Vec3(.2,.1,0));VecReflection.tick(p);near(h,arrow.getDeltaMovement().length(),.5,"Source reflection preserves projectile speed");near(h,arrow.getBaseDamage(),9,"Reflection never zeros Arrow damage");h.assertTrue(VecDeviation.marked(p)&&VecDeviation.marked(arrow)&&VecDeviation.marked(snow)&&VecDeviation.marked(potion),"Shared source persistent mark including caster");h.assertFalse(VecDeviation.marked(mob),"Original Mob exclusion");near(h,s.exp(VecReflection.ID),.0008F+.0008F*.1F+.0008F*1.4F+.0008F,"Source difficulty-weighted EXP");double cp=s.cp;VecReflection.tick(p);near(h,s.cp,cp,"Same native time cannot reapply costs");arrow.setDeltaMovement(new Vec3(.6,0,0));h.runAtTickTime(2,()->{VecReflection.tick(p);near(h,s.cp,(float)cp-VecReflectionSession.normalCp(s.exp(VecReflection.ID)),"Visited never reconsumes entity cost");h.assertTrue(arrow.getDeltaMovement().x>0,"Mark does not freeze future physics");h.succeed();});});}
 @GameTest(template=TEMPLATE,batch="academy_vector_final_04",timeoutTicks=10)
 public static void native_fireball_reconstruction_retains_large_power_owner_position_and_speed(GameTestHelper h){var f=new Fixture(h);var p=f.player();ready(p,VecReflection.ID,0);var owner=f.mob(p.position().add(12,0,0));var large=new LargeFireball(h.getLevel(),owner,Vec3.ZERO,3);f.entity(large,p.position().add(2,0,2));var small=new SmallFireball(EntityType.SMALL_FIREBALL,h.getLevel());small.setOwner(owner);f.entity(small,p.position().add(-2,0,2));VecReflection.start(p,1);h.runAtTickTime(1,()->{large.setDeltaMovement(new Vec3(.3,.4,0));small.setDeltaMovement(new Vec3(.6,0,0));Vec3 at=large.position();VecReflection.tick(p);h.assertTrue(large.isRemoved()&&small.isRemoved(),"Old fireballs discarded");var fresh=h.getLevel().getEntitiesOfClass(LargeFireball.class,new AABB(p.position(),p.position()).inflate(5)).stream().filter(VecDeviation::marked).findFirst().orElseThrow();h.assertTrue(fresh.getOwner()==owner&&fresh.position().equals(at),"Source owner and position retained");near(h,fresh.getDeltaMovement().length(),.5,"Source speed retained");h.assertValueEqual(fresh.saveWithoutId(new CompoundTag()).getInt("ExplosionPower"),3,"Large source explosion power retained");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_vector_final_05",timeoutTicks=90)
 public static void admitted_native_player_damage_reflects_direct_source_with_forced_CP_and_no_attack_cancel(GameTestHelper h){var f=new Fixture(h);var p=f.connectedPlayer();var attacker=f.mob(p.position().add(5,0,0));h.runAtTickTime(61,()->{var s=ready(p,VecReflection.ID,.5);p.setHealth(20);attacker.setHealth(20);p.invulnerableTime=attacker.invulnerableTime=0;double cp=s.cp;h.assertTrue(VecReflection.start(p,1),"Reflection starts after real spawn protection");h.assertTrue(p.hurt(p.damageSources().mobAttack(attacker),10),"Actual native hurt accepted");near(h,s.cp,cp-175,"Preaward forced damage CP175");near(h,s.exp(VecReflection.ID),.5+10*.0004F,"Source damage experience");near(h,attacker.getHealth(),20-VecReflectionSession.ratio(.5)*10,"Actual direct source receives reflected damage");near(h,p.getHealth(),20-(10-VecReflectionSession.ratio(.5)*10),"Source passby branch never pre-cancels native attack");h.assertTrue(s.cooldowns.isEmpty(),"No damage reflection cooldown");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_vector_final_06",timeoutTicks=10)
 public static void actual_skill_reflect_event_is_cancelled_free_and_protected_damage_keeps_resources(GameTestHelper h){var f=new Fixture(h);var p=f.player();var attacker=f.player();var s=ready(p,VecReflection.ID,0);VecReflection.start(p,1);double cp=s.cp;var reflect=new SkillReflectEvent(attacker,"electromaster.railgun",p);NeoForge.EVENT_BUS.post(reflect);h.assertTrue(reflect.isCanceled(),"Actual source-style reflectible beam gate canceled");near(h,s.cp,cp,"ReflectEvent is free");near(h,s.exp(VecReflection.ID),0,"ReflectEvent grants no EXP");var protected_=new LivingIncomingDamageEvent(p,new net.neoforged.neoforge.common.damagesource.DamageContainer(p.damageSources().generic(),4));protected_.setCanceled(true);VecReflection.hurt(protected_);near(h,s.cp,cp,"Canceled incoming native event never spends CP");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_vector_final_07",timeoutTicks=80)
 public static void authoritative_plasma_float_charge_cost_ready_hold_and_release_cooldown(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,PlasmaCannon.ID,0);var target=f.mob(p.position().add(0,0,20));double cp=s.cp;h.assertTrue(PlasmaCannon.start(p,1),"Server charge starts");Vec3 initial=p.position().add(0,15,0);f.ticks(66,t->{PlasmaCannon.tick(p);int ticks=PlasmaCannon.heldTicks(p);PlasmaCannon.tick(p);h.assertValueEqual(PlasmaCannon.heldTicks(p),ticks,"Same world time cannot advance or double debit");if(t==60){near(h,s.cp,cp-59*18,"Source strict less sixty threshold pays59 novice ticks");h.assertTrue(PlasmaCannon.position(p).equals(initial),"Captured charge position never follows caster");}if(t==65){near(h,s.cp,cp-59*18,"Ready hold free of CP");h.assertTrue(PlasmaCannon.release(p,1)&&PlasmaCannon.moving(p),"Authoritative fully charged release");near(h,s.exp(PlasmaCannon.ID),.008F,"One source release award");h.assertValueEqual(s.cooldowns.get(PlasmaCannon.ID),PlasmaCannonSession.cooldown(.008F),"Source postaward cooldown");h.assertFalse(PlasmaCannon.release(p,1),"Duplicate release cannot launch twice");s.activated=false;s.interfering=true;h.assertFalse(PlasmaCannon.abort(p,1),"Detached source flight cannot receive later key-abort");}if(t==66){h.assertTrue(PlasmaCannon.active(p)&&PlasmaCannon.moving(p),"Detached source flight survives deactivation/interference after key-up");near(h,PlasmaCannon.position(p).distanceTo(initial),1,"Source unit step during detached flight");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_vector_final_08",timeoutTicks=50)
 public static void early_collision_detonates_at_destination_and_native_explosion_cancellation_is_respected(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,PlasmaCannon.ID,1);var target=f.mob(p.position().add(0,0,20));var hook=new CaptureExplosion();f.hook(hook);PlasmaCannon.start(p,1);f.ticks(31,t->{if(t==30){PlasmaCannon.tick(p);h.assertTrue(PlasmaCannon.release(p,1),"Master30 charge released");h.getLevel().setBlock(BlockPos.containing(PlasmaCannon.position(p).add(0,-.5,.5)),Blocks.STONE.defaultBlockState(),3);}else PlasmaCannon.tick(p);if(t==31){h.assertFalse(PlasmaCannon.active(p),"Travel collision terminates context");h.assertTrue(hook.seen&&hook.center!=null&&hook.center.distanceTo(target.position())<2,"Explosion centered at fixed target destination despite distant high collision");near(h,hook.radius,15,"Postaward capped master radius15");h.assertTrue(target.getHealth()<=0,"Source explicit damage occurs before protected native explosion");h.assertValueEqual(target.invulnerableTime,-1,"Source reset invulnerability follows attack");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_vector_final_09",timeoutTicks=10)
 public static void early_release_resource_failure_and_nonfinite_native_aim_do_not_award_or_launch(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,PlasmaCannon.ID,0);PlasmaCannon.start(p,1);h.assertFalse(PlasmaCannon.release(p,1)||PlasmaCannon.active(p),"Early release ends without launch");near(h,s.exp(PlasmaCannon.ID),0,"Early release no EXP");h.assertTrue(s.cooldowns.isEmpty(),"Early release no cooldown");ready(p,PlasmaCannon.ID,0);h.assertTrue(PlasmaCannon.start(p,2),"New physical press starts");s.cp=17;h.runAtTickTime(1,()->{PlasmaCannon.tick(p);h.assertFalse(PlasmaCannon.active(p),"Insufficient charge CP ends");near(h,s.exp(PlasmaCannon.ID),0,"CP failure no EXP");s.cp=Double.NaN;h.assertFalse(PlasmaCannon.start(p,3),"Nonfinite CP denied");s.cp=s.maxCp();p.yRotO=Float.NaN;h.assertFalse(PlasmaCannon.start(p,3)||VecReflection.start(p,1),"Native nonfinite prior rotation denied");h.succeed();});}
 private static AbilityProgress ready(ServerPlayer p,String id,double exp){var s=AbilityStorage.get(p);s.selectCategory("vecmanip");s.setLevel(id.equals(PlasmaCannon.ID)?5:4);s.learn(id);s.experience.put(id,exp);s.extraOverload=ClassicRules.EXTRA_OVERLOAD_CAP[s.level];s.activated=true;s.overloadFine=true;return s;}
 private static boolean bind(AbilityProgress s,int slot,String id){return s.presets.edit(0,slot,id,x->PresetSkills.selectable(s,x));}
 private static void near(GameTestHelper h,double a,double b,String why){h.assertTrue(Math.abs(a-b)<1E-5,why+" actual="+a+" expected="+b);}
    private static final class Fixture {
        final GameTestHelper h;final List<ServerPlayer> players=new ArrayList<>();final List<EmbeddedChannel> channels=new ArrayList<>();final List<Entity> entities=new ArrayList<>();final List<Object> hooks=new ArrayList<>();boolean closed;
        Fixture(GameTestHelper h){this.h=h;h.testInfo.addListener(new GameTestListener(){public void testStructureLoaded(GameTestInfo i){}public void testPassed(GameTestInfo i,GameTestRunner r){cleanup();}public void testFailed(GameTestInfo i,GameTestRunner r){cleanup();}public void testAddedForRerun(GameTestInfo i,GameTestInfo n,GameTestRunner r){cleanup();}});}
        FakePlayer player(){var p=new FakePlayer(h.getLevel(),new GameProfile(UUID.randomUUID(),"[AC-VecFinal]"));players.add(p);Vec3 at=h.absoluteVec(new Vec3(24.5,4,24.5));p.moveTo(at.x,at.y,at.z,0,0);p.setYHeadRot(0);p.yRotO=p.xRotO=0;p.setNoGravity(true);p.setDeltaMovement(Vec3.ZERO);p.getAbilities().instabuild=false;return p;}
        /** Real native PlayerList admission and official mock connection; no socket or fabricated teleport override. */
        ServerPlayer connectedPlayer(){var level=h.getLevel();var server=level.getServer();var cookie=CommonListenerCookie.createInitial(new GameProfile(UUID.randomUUID(),"ACVecFinalProbe"),false);var p=new ServerPlayer(server,level,cookie.gameProfile(),cookie.clientInformation());players.add(p);var connection=new Connection(PacketFlow.SERVERBOUND);var channel=new EmbeddedChannel(connection);channels.add(channel);NetworkRegistry.configureMockConnection(connection);server.getPlayerList().placeNewPlayer(connection,p,cookie);h.assertTrue(server.getPlayerList().getPlayer(p.getUUID())==p,"Owned native PlayerList fixture admitted");Vec3 at=h.absoluteVec(new Vec3(24.5,4,24.5));p.moveTo(at.x,at.y,at.z,0,0);p.setYHeadRot(0);p.yRotO=p.xRotO=0;p.setNoGravity(true);p.setDeltaMovement(Vec3.ZERO);p.setGameMode(GameType.SURVIVAL);return p;}
        void floor(ServerPlayer p){h.getLevel().setBlock(BlockPos.containing(p.position().add(0,-1,0)),Blocks.STONE.defaultBlockState(),3);}
        <T extends Entity> T entity(T e){entities.add(e);h.getLevel().addFreshEntity(e);return e;}
        <T extends Entity> T entity(T e,Vec3 at){e.setPos(at);e.setNoGravity(true);e.setDeltaMovement(Vec3.ZERO);return entity(e);}
        Villager mob(Vec3 at){var v=new Villager(EntityType.VILLAGER,h.getLevel());v.setNoAi(true);return entity(v,at);}
        void hook(Object o){hooks.add(o);NeoForge.EVENT_BUS.register(o);}
        void ticks(int n,IntConsumer callback){for(int i=1;i<=n;i++){int t=i;h.runAtTickTime(t,()->{if(!closed)callback.accept(t);});}}
        void cleanup(){if(closed)return;closed=true;for(var o:hooks)NeoForge.EVENT_BUS.unregister(o);for(var p:players){VecReflection.remove(p);PlasmaCannon.remove(p);VecDeviation.remove(p);DevelopmentController.remove(p);MachineDeveloperSessions.close(p);AbilityStorage.remove(p);var list=h.getLevel().getServer().getPlayerList();if(list.getPlayer(p.getUUID())==p)list.remove(p);else p.discard();}for(var e:entities)e.discard();for(var channel:channels)channel.finishAndReleaseAll();}
    }
 public static final class CaptureExplosion{boolean seen;Vec3 center;float radius;@SubscribeEvent public void protect(ExplosionEvent.Start e){seen=true;center=e.getExplosion().center();radius=e.getExplosion().radius();e.setCanceled(true);}}
}
