package cn.academy.port.gametest;
import cn.academy.port.*;
import cn.academy.port.api.*;
import cn.academy.port.core.AbilityProgress;
import cn.academy.port.develop.*;
import cn.academy.port.machine.*;
import cn.academy.port.skill.*;
import com.mojang.authlib.GameProfile;
import net.minecraft.core.*;
import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.*;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.npc.Villager;
import net.minecraft.world.item.*;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.*;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.common.util.FakePlayer;
import net.neoforged.neoforge.event.level.LevelEvent;
import net.neoforged.neoforge.gametest.*;
import java.util.*;
import java.util.function.IntConsumer;
/** Native world/GameTest fixtures, compiled ONLY by the isolated worker. Main lane owns execution.
 * Combat fixtures seed declared skill state; learning fixture never grants either target skill. */
@GameTestHolder("academy") @PrefixGameTestTemplate(false) @EventBusSubscriber(modid="academy")
public final class AcademyMeltdownerBeamRuntimeTests {
 private static final String TEMPLATE="meltdowner_beam_empty";private AcademyMeltdownerBeamRuntimeTests(){}
 @SubscribeEvent public static void install(LevelEvent.Load e){if(!GameTestHooks.isGametestEnabled()||!(e.getLevel() instanceof ServerLevel world))return;var tag=new CompoundTag();var size=new ListTag();size.add(IntTag.valueOf(64));size.add(IntTag.valueOf(8));size.add(IntTag.valueOf(64));tag.put("size",size);var blocks=new ListTag();var first=new CompoundTag();var pos=new ListTag();pos.add(IntTag.valueOf(0));pos.add(IntTag.valueOf(0));pos.add(IntTag.valueOf(0));first.put("pos",pos);first.putInt("state",0);blocks.add(first);tag.put("blocks",blocks);tag.put("entities",new ListTag());var palette=new ListTag();var air=new CompoundTag();air.putString("Name","minecraft:air");palette.add(air);tag.put("palette",palette);world.getStructureManager().getOrCreate(ResourceLocation.fromNamespaceAndPath("academy",TEMPLATE)).load(world.registryAccess().lookupOrThrow(Registries.BLOCK),tag);}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_beam",timeoutTicks=35)
 public static void minimum20_beam_attacks_through_bedrock_and_keeps_captured_costs(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,Meltdowner.ID,0);var target=f.target(p.position().add(0,0,15));var hook=new Hook(p);f.hook(hook);var wall=BlockPos.containing(p.getEyePosition().add(0,0,3));h.getLevel().setBlock(wall,Blocks.BEDROCK.defaultBlockState(),3);double cp=s.cp;h.assertTrue(Meltdowner.start(p,1),"authenticated hold starts");h.assertFalse(Meltdowner.start(p,1),"duplicate token refuses");f.ticks(20,tick->{Meltdowner.tick(p);int held=Meltdowner.heldTicks(p);Meltdowner.tick(p);h.assertValueEqual(Meltdowner.heldTicks(p),held,"same tick cannot double charge");if(tick==20){s.experience.put(Meltdowner.ID,.5);h.assertTrue(Meltdowner.release(p),"20tickshot");h.assertValueEqual(hook.count(target),1,"entity phase ignores bedrock line occlusion");double lateral=p.getEyePosition().y-target.getY();near(h,hook.damage(target),14.4F*(1+(.2F-1)*(Math.min(50,(float)Math.abs(lateral))/50)),"original lateral attenuation");near(h,s.cp,cp-200,"20real CP10 ticks");h.assertValueEqual(s.cooldowns.get(Meltdowner.ID),240,"captured novicecooldown");h.assertTrue(h.getLevel().getBlockState(wall).is(Blocks.BEDROCK),"233333hardness keeps bedrock");h.assertFalse(Meltdowner.release(p),"release replay denied");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_beam",timeoutTicks=50)
 public static void early_release_and_key_abort_never_fire_or_award(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,Meltdowner.ID,0);var target=f.target(p.position().add(0,0,10));var hook=new Hook(p);f.hook(hook);Meltdowner.start(p);f.ticks(39,tick->{Meltdowner.tick(p);if(tick==19){h.assertFalse(Meltdowner.release(p),"19tickrelease notshot");h.assertValueEqual(hook.count(target),0,"noearlyattack");h.assertTrue(s.cooldowns.isEmpty()&&s.exp(Meltdowner.ID)==0,"noearlycooldownEXP");s.overload=0;s.overloadFine=true;h.assertTrue(Meltdowner.start(p),"independent charged-abort fixture starts");}if(tick==39){h.assertValueEqual(Meltdowner.heldTicks(p),20,"abort after real20tickready charge");Meltdowner.abort(p);h.assertFalse(Meltdowner.active(p),"abort removes context");h.assertValueEqual(hook.count(target),0,"ready-keyabort never fires");h.assertTrue(s.cooldowns.isEmpty()&&s.exp(Meltdowner.ID)==0,"ready-keyabort still no EXP/cooldown");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_beam",timeoutTicks=120)
 public static void strict101_timeout_pays_final_tick_and_never_shoots(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,Meltdowner.ID,0);double cp=s.cp;Meltdowner.start(p);f.ticks(101,tick->{Meltdowner.tick(p);if(tick==100)h.assertTrue(Meltdowner.active(p),"tick100allowed");if(tick==101){h.assertFalse(Meltdowner.active(p),"tick101terminates");near(h,s.cp,cp-1010,"101paidCPticks");h.assertTrue(s.cooldowns.isEmpty()&&s.exp(Meltdowner.ID)==0,"timeout noEXPcooldown");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_beam",timeoutTicks=60)
 public static void first_reflection_stops_forward_targets_and_attacks_original10range(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,Meltdowner.ID,0);var reflector=f.target(p.position().add(0,0,8));var receiver=f.target(p.position().add(0,0,14));var farther=f.target(p.position().add(0,0,30));var hook=new Hook(p);hook.reflector=reflector;f.hook(hook);Meltdowner.start(p);f.ticks(40,tick->{Meltdowner.tick(p);if(tick==40){h.assertTrue(Meltdowner.release(p),"40cappedshot");h.assertValueEqual(hook.count(reflector),0,"reflection intercepted beforeattack");h.assertValueEqual(hook.count(receiver),1,"reflector head ray10hits nativeentity");near(h,hook.damage(receiver),10,"novice .5*20reflecteddamage");h.assertValueEqual(hook.count(farther),0,"forward targets afterreflector notattacked");near(h,s.exp(Meltdowner.ID),1.2F*.002F,"source40EXPafterreflection");h.assertValueEqual(s.cooldowns.get(Meltdowner.ID),360,"40capturedcooldown");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_beam",timeoutTicks=20)
 public static void basic_mine_first_tick_acquires_then_real_stone_drop_and_cooldown(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,MineRayBasic.ID,0);var at=BlockPos.containing(p.getEyePosition().add(0,0,3));h.getLevel().setBlock(at,Blocks.STONE.defaultBlockState(),3);double cp=s.cp;MineRayBasic.start(p);f.ticks(9,tick->{MineRayBasic.tick(p);if(tick==1)h.assertTrue(h.getLevel().getBlockState(at).is(Blocks.STONE),"firsttickcapture nohardnessdecrement");if(tick==8)h.assertTrue(h.getLevel().getBlockState(at).is(Blocks.STONE),"seven.2subtractions leave .1");if(tick==9){h.assertTrue(h.getLevel().isEmptyBlock(at),"eighthsubtraction breaksstone");near(h,s.exp(MineRayBasic.ID),.0005F,"one block trains .0005");near(h,s.cp,cp-108,"9CP12ticks");h.assertTrue(h.getLevel().getEntitiesOfClass(ItemEntity.class,new AABB(at).inflate(2)).stream().anyMatch(e->e.getItem().is(Items.COBBLESTONE)),"native fortune0stonecobble drop");MineRayBasic.release(p);h.assertValueEqual(s.cooldowns.get(MineRayBasic.ID),40,"novice40cooldown");h.assertFalse(MineRayBasic.release(p),"minerelease replaydenied");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_beam",timeoutTicks=20)
 public static void failed_CP_progress_tick_still_breaks_and_awards(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,MineRayBasic.ID,1);var at=BlockPos.containing(p.getEyePosition().add(0,0,3));h.getLevel().setBlock(at,Blocks.DIRT.defaultBlockState(),3);MineRayBasic.start(p);f.ticks(3,tick->{if(tick==3)s.cp=0;MineRayBasic.tick(p);if(tick==3){h.assertTrue(h.getLevel().isEmptyBlock(at),"failedconsume tick still finishes .5dirt");h.assertFalse(MineRayBasic.active(p),"failedCPends aftermining");h.assertValueEqual(s.cooldowns.get(MineRayBasic.ID),20,"master20cooldown");near(h,s.cp,0,"no inventedCP");near(h,s.levelExperience,.0005F,"failedtickstillawardsblockEXPthoughmasterycapped");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_beam",timeoutTicks=20)
 public static void harvest3_denial_protection_and_unbreakable_reset(GameTestHelper h){var f=new Fixture(h);var p=f.player();ready(p,MineRayBasic.ID,0);var at=BlockPos.containing(p.getEyePosition().add(0,0,3));var hook=new Hook(p);f.hook(hook);h.getLevel().setBlock(at,Blocks.OBSIDIAN.defaultBlockState(),3);MineRayBasic.start(p);f.ticks(6,tick->{if(tick==3){h.getLevel().setBlock(at,Blocks.STONE.defaultBlockState(),3);hook.blockDenied=true;}if(tick==5){hook.blockDenied=false;h.getLevel().setBlock(at,Blocks.BEDROCK.defaultBlockState(),3);}MineRayBasic.tick(p);if(tick<=4)h.assertTrue(MineRayBasic.target(p).equals(MineRayBasicSession.Cell.NONE),"hightier/protectionnoacquire");if(tick==6){h.assertTrue(h.getLevel().getBlockState(at).is(Blocks.BEDROCK),"unbreakableFloatMAXstillstanding");h.assertTrue(hook.blockProbes>=4,"source events include rechecked rejectedtargets");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_beam",timeoutTicks=20)
 public static void source_captured_hardness_breaks_replacement_block_without_rechecking(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,MineRayBasic.ID,1);var at=BlockPos.containing(p.getEyePosition().add(0,0,3));h.getLevel().setBlock(at,Blocks.DIRT.defaultBlockState(),3);MineRayBasic.start(p);f.ticks(3,tick->{if(tick==3)h.getLevel().setBlock(at,Blocks.BEDROCK.defaultBlockState(),3);MineRayBasic.tick(p);if(tick==3){h.assertTrue(h.getLevel().isEmptyBlock(at),"source keeps original .5hardness evenafterbedrockreplacement");MineRayBasic.abort(p);h.assertValueEqual(s.cooldowns.get(MineRayBasic.ID),20,"ordinaryabortappliescooldown");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_beam",timeoutTicks=30)
 public static void authenticated_preset_nonce_and_lifecycle_cleanup_preserve_oldpaths(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,Meltdowner.ID,0);s.learn(MineRayBasic.ID);h.assertTrue(Alphabet.bind(s,0,Meltdowner.ID),"realpresetbind");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:01")),"noncanonicalnonceblocks");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:1")),"authenticatedslotsstart");h.assertTrue(Meltdowner.active(p),"beamcontextlive");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_abort","0")),"Meltdowner key-abort authenticated before other-page edit");h.assertFalse(Meltdowner.active(p),"Meltdowner callback ends beam before mapping edit");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("preset_edit","1:0:mine_ray_basic")),"otherpageeditaccepted");h.assertFalse(Meltdowner.active(p),"mapping edit preserves callback-ended beam");h.assertFalse(Meltdowner.start(p,1),"retirednoncecannotrestart");h.assertTrue(Meltdowner.start(p,2),"newnoncelive");Meltdowner.remove(p);h.assertTrue(s.cooldowns.isEmpty()&&s.exp(Meltdowner.ID)==0,"lifecyclechargecleanupnoeffects");s.overload=0;s.overloadFine=true;h.assertTrue(MineRayBasic.start(p,1),"minestart");MineRayBasic.remove(p);h.assertTrue(s.cooldowns.isEmpty(),"lifecycleminecleanupnocooldown");h.assertTrue(s.canUse(Meltdowner.ID)&&s.canUse(MineRayBasic.ID),"both skills otherwise usable before malformed aim");float previousHeadYaw=p.getYHeadRot();double cpBeforeInvalidAim=s.cp,overloadBeforeInvalidAim=s.overload;p.setYHeadRot(Float.NaN);h.assertTrue(Float.isNaN(p.getYHeadRot()),"native head-yaw setter actually stores malformed float");try{h.assertFalse(Meltdowner.start(p),"Meltdowner rejects genuinely nonfinite head yaw");h.assertFalse(MineRayBasic.start(p),"MineRayBasic rejects genuinely nonfinite head yaw");h.assertFalse(Meltdowner.active(p)||MineRayBasic.active(p),"malformed aim creates neither context");near(h,s.cp,cpBeforeInvalidAim,"malformed aim spends no CP");near(h,s.overload,overloadBeforeInvalidAim,"malformed aim spends no overload");}finally{p.setYHeadRot(previousHeadYaw);}h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_beam_learning",timeoutTicks=30)
 public static void physical_Normal_session_genuinely_learns_both_targets_with_finite5145IF(GameTestHelper h){var f=new Fixture(h);var p=f.player();var item=MachineDevelopers.NORMAL_ITEM.get();var stack=new ItemStack(item);p.setItemInHand(InteractionHand.MAIN_HAND,stack);var base=h.absolutePos(new BlockPos(5,1,8));h.assertTrue(item.place(new BlockPlaceContext(p,InteractionHand.MAIN_HAND,stack,new BlockHitResult(Vec3.atCenterOf(base),Direction.UP,base,false))).consumesAction(),"physical8cellNormalplacement");var machine=(MachineDeveloperBlockEntity)h.getLevel().getBlockEntity(base);p.moveTo(base.getX()+.5,base.getY(),base.getZ()-1.5,0,0);
  for(String id:List.of(Meltdowner.ID,MineRayBasic.ID)){DevelopmentController.remove(p);var s=AbilityStorage.get(p);s.selectCategory("meltdowner");s.setLevel(3);for(var r:SkillCatalog.find("meltdowner",id).orElseThrow().requirements()){s.learn(r.id());s.experience.put(r.id(),r.exp());}h.assertFalse(s.learned(id),"target neverfixturegranted");machine.battery().load(50000);h.assertTrue(machine.use(p),"senderboundNormalGUI");var token=MachineDeveloperSessions.activeToken(p).orElseThrow().toString();h.assertFalse(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",UUID.randomUUID()+":"+id)),"forgedmachine nonceblocked");h.assertTrue(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",token+":"+id)),"sharedregistrypermitsgenuinelevel3learning");for(int tick=1;tick<=147;++tick){DevelopmentController.tick(p,snapshot->{});if(tick<147)h.assertFalse(s.learned(id),"noearlylearn");}h.assertTrue(s.learned(id)&&s.exp(id)==0&&DevelopmentController.process(p).state()==DevelopmentProcess.State.DONE,"actualNormalprocesslearnszeroEXP");near(h,machine.battery().getEnergy(),44855,"5145realIFdrain");h.assertTrue(s.presets.currentSkill(0).isEmpty(),"learningneverautobinds");s.activated=true;h.assertTrue(Alphabet.bind(s,0,id),"naturallyearnedpresetbinding");}
  h.succeed();}
 private static final class Alphabet {static boolean bind(AbilityProgress s,int slot,String id){return s.presets.edit(0,slot,id,value->cn.academy.port.preset.PresetSkills.selectable(s,value));}}
 private static AbilityProgress ready(ServerPlayer p,String id,double exp){var s=AbilityStorage.get(p);s.selectCategory("meltdowner");s.setLevel(3);s.learn(id);s.experience.put(id,exp);s.activated=true;return s;}
 private static void near(GameTestHelper h,double actual,double expected,String why){h.assertTrue(Math.abs(actual-expected)<1E-6,why+" actual="+actual+" expected="+expected);}
 private static final class Fixture {final GameTestHelper h;final List<ServerPlayer> players=new ArrayList<>();final List<Entity> entities=new ArrayList<>();final List<Object> hooks=new ArrayList<>();boolean closed;Fixture(GameTestHelper h){this.h=h;h.testInfo.addListener(new GameTestListener(){public void testStructureLoaded(GameTestInfo i){}public void testPassed(GameTestInfo i,GameTestRunner r){cleanup();}public void testFailed(GameTestInfo i,GameTestRunner r){cleanup();}public void testAddedForRerun(GameTestInfo old,GameTestInfo next,GameTestRunner r){cleanup();}});}FakePlayer player(){var p=new FakePlayer(h.getLevel(),new GameProfile(UUID.randomUUID(),"[AC-MD-Beams]"));players.add(p);var at=h.absoluteVec(new Vec3(5.5,1,5.5));p.moveTo(at.x,at.y,at.z,0,0);p.setYHeadRot(0);p.setNoGravity(true);p.getAbilities().instabuild=false;return p;}Villager target(Vec3 at){var v=h.spawnWithNoFreeWill(EntityType.VILLAGER,new Vec3(1,1,1));entities.add(v);v.moveTo(at.x,at.y,at.z,0,0);v.setYHeadRot(0);v.setNoAi(true);v.setNoGravity(true);v.getAttribute(Attributes.MAX_HEALTH).setBaseValue(200);v.setHealth(200);return v;}void hook(Object hook){hooks.add(hook);NeoForge.EVENT_BUS.register(hook);}void ticks(int count,IntConsumer body){for(int tick=1;tick<=count;tick++){int now=tick;h.runAtTickTime(tick,()->{if(!closed)body.accept(now);});}}void cleanup(){if(closed)return;closed=true;for(var hook:hooks)NeoForge.EVENT_BUS.unregister(hook);for(var p:players){Meltdowner.remove(p);MineRayBasic.remove(p);DevelopmentController.remove(p);AbilityStorage.remove(p);p.discard();}for(var e:entities)e.discard();}}
 public static final class Hook {final ServerPlayer owner;final Map<Entity,Integer> counts=new IdentityHashMap<>();final Map<Entity,Double> damage=new IdentityHashMap<>();Entity reflector;boolean blockDenied;int blockProbes;Hook(ServerPlayer p){owner=p;}@SubscribeEvent public void attack(SkillAttackEvent e){if(e.player==owner&&e.skill.equals("meltdowner.meltdowner")){counts.merge(e.target,1,Integer::sum);damage.put(e.target,e.amount);}}@SubscribeEvent public void reflect(SkillReflectEvent e){if(e.attacker==owner&&e.skill.equals("meltdowner.meltdowner")&&e.target==reflector)e.setCanceled(true);}@SubscribeEvent public void block(SkillBlockDestroyEvent e){if(e.player==owner){blockProbes++;if(blockDenied)e.setCanceled(true);}}int count(Entity e){return counts.getOrDefault(e,0);}double damage(Entity e){return damage.getOrDefault(e,0D);}}
}
