/* AcademyCraft1.0.7 late-combat native regression fixtures, GPLv3; see NOTICE. */
package cn.academy.port.gametest;
import cn.academy.port.*;
import cn.academy.port.api.*;
import cn.academy.port.core.*;
import cn.academy.port.develop.*;
import cn.academy.port.machine.*;
import cn.academy.port.skill.*;
import com.mojang.authlib.GameProfile;
import io.netty.channel.embedded.EmbeddedChannel;
import net.minecraft.network.Connection;
import net.minecraft.network.protocol.PacketFlow;
import net.minecraft.server.network.CommonListenerCookie;
import net.minecraft.world.level.GameType;
import net.neoforged.neoforge.network.registration.NetworkRegistry;
import net.minecraft.core.*;
import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.*;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.npc.Villager;
import net.minecraft.world.item.*;
import net.minecraft.world.item.crafting.*;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.*;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.common.util.FakePlayer;
import net.neoforged.neoforge.event.level.LevelEvent;
import net.neoforged.neoforge.gametest.*;
import java.util.*;
import java.util.function.IntConsumer;
/** Compiled by the isolated stage ONLY; main owns native execution. Combat tests declare seeded learned
 * state; Advanced learning never fixture-grants any target. No commands, infinite battery or GUI grant. */
@GameTestHolder("academy") @PrefixGameTestTemplate(false) @EventBusSubscriber(modid="academy")
public final class AcademyMeltdownerLateCombatRuntimeTests {
 private static final String TEMPLATE="meltdowner_late_empty";private AcademyMeltdownerLateCombatRuntimeTests(){}
 @SubscribeEvent public static void install(LevelEvent.Load event){if(!GameTestHooks.isGametestEnabled()||!(event.getLevel() instanceof ServerLevel world))return;var tag=new CompoundTag();var size=new ListTag();size.add(IntTag.valueOf(64));size.add(IntTag.valueOf(16));size.add(IntTag.valueOf(64));tag.put("size",size);var blocks=new ListTag();var first=new CompoundTag();var pos=new ListTag();pos.add(IntTag.valueOf(0));pos.add(IntTag.valueOf(0));pos.add(IntTag.valueOf(0));first.put("pos",pos);first.putInt("state",0);blocks.add(first);tag.put("blocks",blocks);tag.put("entities",new ListTag());var palette=new ListTag();var air=new CompoundTag();air.putString("Name","minecraft:air");palette.add(air);tag.put("palette",palette);world.getStructureManager().getOrCreate(ResourceLocation.fromNamespaceAndPath("academy",TEMPLATE)).load(world.registryAccess().lookupOrThrow(Registries.BLOCK),tag);}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late",timeoutTicks=20)
 public static void barrage_native_plain_25_damage_cost_and_same_nonce_reentry(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,RayBarrage.ID,4,0);var target=f.target(p.position().add(0,0,8));var hook=new Hook(p);hook.reentry=true;f.hook(hook);double cp=s.cp;h.assertTrue(RayBarrage.start(p,1),"authenticated sourceinstantaction");near(h,hook.damage(target),25,"originalplain25");h.assertValueEqual(hook.count(target),1,"one damageevent");h.assertFalse(hook.reentered,"nativeevent cannotreentercommittingaction");near(h,s.cp,cp-450,"original450CP");near(h,s.overload,300,"original300strain");h.assertValueEqual(s.cooldowns.get(RayBarrage.ID),100,"original100ticks");near(h,s.exp(RayBarrage.ID),.005F,"source .005EXP");h.assertFalse(RayBarrage.start(p,1),"replaydenied");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late",timeoutTicks=20)
 public static void barrage_original_failedconsume_still_executes_and_protected_attack_trains(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,RayBarrage.ID,4,0);s.cp=0;var target=f.target(p.position().add(0,0,8));var hook=new Hook(p);hook.zero=true;f.hook(hook);h.assertTrue(RayBarrage.start(p,1),"deferredterminate sourceexecutes");h.assertValueEqual(hook.count(target),1,"nativeevent invokeddespitefailedCP");near(h,target.getHealth(),200,"mutable nativeprotection zero damagehonored");near(h,s.cp,0,"failedconsumption no inventedCP");near(h,s.overload,0,"failedconsumption no strain");near(h,s.exp(RayBarrage.ID),.005F,"canonical executeEXP remains");h.assertValueEqual(s.cooldowns.get(RayBarrage.ID),100,"canonical cooldownremains");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late",timeoutTicks=20)
 public static void real_silbarn_enables_body_yaw_barrage_wedge_without_LOS_gate(GameTestHelper h){var f=new Fixture(h);var p=f.player();ready(p,RayBarrage.ID,4,0);var support=new SilbarnEntity(p);support.setPos(p.getEyePosition().add(0,0,3));support.setDeltaMovement(Vec3.ZERO);h.getLevel().addFreshEntity(support);f.entities.add(support);var inside=f.target(p.position().add(2,0,8));var outside=f.target(p.position().add(7,0,8));var hook=new Hook(p);f.hook(hook);var wall=BlockPos.containing(p.getEyePosition().add(1,0,5));h.getLevel().setBlock(wall,Blocks.BEDROCK.defaultBlockState(),3);h.assertTrue(RayBarrage.start(p,1),"actualnative supporttargetselected");h.assertTrue(support.isHit(),"originalforcedselfcollisionmarksSilbarn");h.assertValueEqual(hook.count(inside),1,"withininclusive55yaw110pitch wedge");near(h,hook.damage(inside),10,"source scatter10");h.assertValueEqual(hook.count(outside),0,"bodyangularfilterexcludesoutsider");h.assertTrue(h.getLevel().getBlockState(wall).is(Blocks.BEDROCK),"barrage neverdestroyssourceblocks");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late",timeoutTicks=65)
 public static void canonical_two_piece_recipe_real_item_use_and_native_silbarn_physics(GameTestHelper h){var f=new Fixture(h);var p=f.player();ready(p,RayBarrage.ID,4,0);var input=CraftingInput.of(2,1,List.of(new ItemStack(cn.academy.port.survival.ClassicMaterials.IMAG_SILICON_PIECE.get()),new ItemStack(cn.academy.port.survival.ClassicMaterials.IMAG_SILICON_PIECE.get())));var recipe=h.getLevel().getRecipeManager().byKey(ResourceLocation.fromNamespaceAndPath("academy","classic/silbarn_01")).orElseThrow().value();h.assertTrue(recipe instanceof CraftingRecipe,"realshapelessrecipe registered");var crafting=(CraftingRecipe)recipe;h.assertTrue(crafting.matches(input,h.getLevel()),"originaltwoimaginarysiliconpieces");var output=crafting.assemble(input,h.getLevel().registryAccess());h.assertTrue(output.is(MeltdownerLateEntities.SILBARN.get())&&output.getCount()==1,"originalSiliconBarnoutput");output.setCount(2);p.setItemInHand(InteractionHand.MAIN_HAND,output);var result=MeltdownerLateEntities.SILBARN.get().use(h.getLevel(),p,InteractionHand.MAIN_HAND);h.assertTrue(result.getResult().consumesAction()&&output.getCount()==1,"native rightclickconsumesonesurvivalitem");var list=h.getLevel().getEntitiesOfClass(SilbarnEntity.class,new AABB(p.position(),p.position()).inflate(4));h.assertValueEqual(list.size(),1,"real nativeentityspawned");var entity=list.getFirst();f.entities.add(entity);entity.setNoGravity(true);entity.setPos(p.getEyePosition().add(0,5,0));entity.setDeltaMovement(new Vec3(0,0,1));Vec3 before=entity.position();int first=entity.tickCount;h.runAtTickTime(1,()->{near(h,entity.getZ(),before.z+.8,"original firststepdrag.8");near(h,entity.getDeltaMovement().z,.8,"originalvelocitydrag");h.assertTrue(entity.isPickable()&&!entity.isHit(),"native pickableunhitSupport");});h.runAtTickTime(51,()->{h.assertTrue(entity.getDeltaMovement().y<0,"gravitystartsafterupdate50");entity.collideWithSelf();h.assertTrue(entity.isHit(),"forcedcollision");});h.runAtTickTime(61,()->{h.assertTrue(entity.isRemoved(),"native10tickdeadcallback");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late",timeoutTicks=25)
 public static void jet_server_authoritative_tick16_extrapolation_collision_and_gravity_cleanup(GameTestHelper h){var f=new Fixture(h);var p=f.connectedPlayer();p.setNoGravity(false);var s=ready(p,JetEngine.ID,4,0);Vec3 start=p.position();var target=f.target(start.add(0,.5,3));var hook=new Hook(p);f.hook(hook);double cp=s.cp;h.assertTrue(JetEngine.start(p,1),"authenticmarkingcontext");h.assertTrue(JetEngine.release(p,1),"releasecapturedsource endpoint");Vec3 destination=JetEngine.target(p);near(h,destination.z,start.z+12,"canonical12range");near(h,destination.y,start.y+p.getEyeHeight()+1.65,"canonical destinationeyeplus1.65");near(h,s.cp,cp-60,"reversedactual60CP");near(h,s.overload,170,"reversedactual170strain");h.assertTrue(p.isNoGravity(),"temporary authoritativeflightgravity");h.assertFalse(JetEngine.release(p,1),"duplicate releasenoextra debit");f.ticks(16,tick->{JetEngine.tick(p);Vec3 expected=start.lerp(destination,tick/8F);near(h,p.getX(),expected.x,"authoritativeX");near(h,p.getY(),expected.y,"authoritativeY");near(h,p.getZ(),expected.z,"authoritativeZ");if(tick==8)h.assertTrue(JetEngine.active(p),"reachesdestinationwithoutclamptermination");if(tick==16){h.assertFalse(JetEngine.active(p),"movement16thenend");h.assertFalse(p.isNoGravity(),"preexistinggravity restored");near(h,p.getZ(),start.z+24,"originalextrapolates2xrange");h.assertTrue(hook.count(target)>0,"native livingentitysweep");near(h,hook.damage(target),7,"capturednovicecollision7");near(h,s.exp(JetEngine.ID),.004F,"releaseonlyEXP");h.assertValueEqual(s.cooldowns.get(JetEngine.ID),60,"capturedrelease60cooldown");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late",timeoutTicks=10)
 public static void jet_marking_gate_release_failure_abort_and_low_postrelease_CP(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,JetEngine.ID,4,0);double cp=s.cp;JetEngine.start(p,1);JetEngine.abort(p,1);near(h,s.cp,cp,"markingabortfree");h.assertTrue(s.cooldowns.isEmpty()&&s.exp(JetEngine.ID)==0,"abortnopaymentEXPcooldown");h.assertFalse(JetEngine.start(p,1),"aborttombstonestartnonce");h.assertTrue(JetEngine.start(p,2),"newcontext");s.cp=59;h.assertFalse(JetEngine.release(p,2),"insufficientactualCP60");h.assertFalse(JetEngine.active(p),"failedreleaseends");s.cp=170;h.assertTrue(JetEngine.start(p,3)&&JetEngine.release(p,3),"successfulsourceCP60debit");Vec3 position=p.position();h.runAtTickTime(1,()->{JetEngine.tick(p);h.assertFalse(JetEngine.active(p),"sourcecontinuingaffordability170gate");h.assertTrue(p.position().equals(position),"unaffordablenexttickneverdisplaces");near(h,s.cp,110,"only60debit");near(h,s.exp(JetEngine.ID),.004F,"releaseawardretained");h.succeed();});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late",timeoutTicks=25)
 public static void missile_tick0_spawn_tick8_nearest_target_through_bedrock_and_resistance_reset(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,ElectronMissile.ID,5,0);var nearest=f.target(p.position().add(0,0,3));var farther=f.target(p.position().add(0,0,4.5));var hook=new Hook(p);f.hook(hook);h.getLevel().setBlock(BlockPos.containing(p.getEyePosition().add(0,0,1.5)),Blocks.BEDROCK.defaultBlockState(),3);double cp=s.cp;h.assertTrue(ElectronMissile.start(p,1),"authenticatedmissilehold");near(h,s.overload,200,"initial200floor");f.ticks(17,tick->{if(tick==9||tick==17)nearest.invulnerableTime=999;ElectronMissile.tick(p);int held=ElectronMissile.heldTicks(p);ElectronMissile.tick(p);h.assertValueEqual(ElectronMissile.heldTicks(p),held,"nativetickdeduplicated");if(tick==1)h.assertValueEqual(ElectronMissile.ballCount(p),1,"firstnativeholdticksourceindex0orb");if(tick==8)h.assertValueEqual(hook.count(nearest),0,"noattackbeforesourceindex8");if(tick==9){h.assertValueEqual(hook.count(nearest),1,"nearestlivingatindex8");h.assertValueEqual(hook.count(farther),0,"one target only");near(h,s.cp,cp-9*12-60,"9tickCPplusoneattack");near(h,nearest.getHealth(),190,"native resistanceexplicitlyreset");}if(tick==17){h.assertValueEqual(hook.count(nearest),2,"secondindex16strikedespiteinvul999");near(h,nearest.getHealth(),180,"twooriginal10damagehits");near(h,s.exp(ElectronMissile.ID),2*.001F,"attackonlyEXP");ElectronMissile.release(p,1);h.assertValueEqual(s.cooldowns.get(ElectronMissile.ID),700,"originalalways700cooldown");h.assertValueEqual(ElectronMissile.ballCount(p),0,"releaseorbsremoved");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late",timeoutTicks=95)
 public static void missile_five_orb_cap_inclusive80_timeout_paid82_ticks_and_overload_floor(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,ElectronMissile.ID,5,0);double cp=s.cp;ElectronMissile.start(p,1);f.ticks(82,tick->{s.overload=0;ElectronMissile.tick(p);if(tick==41)h.assertValueEqual(ElectronMissile.ballCount(p),5,"sourceindices0..40fillfivehold");if(tick<=81)near(h,s.overload,200,"floorpersists");if(tick==81)h.assertTrue(ElectronMissile.active(p),"sourceindex80allowed");if(tick==82){h.assertFalse(ElectronMissile.active(p),"sourceindex81timeout");near(h,s.cp,cp-82*12,"timeoutstillpayfinalCP12");h.assertValueEqual(s.cooldowns.get(ElectronMissile.ID),700,"timeoutcooldown700");near(h,s.exp(ElectronMissile.ID),0,"emptytargetholdnoEXP");h.assertValueEqual(ElectronMissile.ballCount(p),0,"timeoutallorbsremoved");h.succeed();}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late",timeoutTicks=20)
 public static void missile_failed_tick_and_attack_CP_and_native_protection_preserve_order(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,ElectronMissile.ID,5,0);var target=f.target(p.position().add(0,0,3));var hook=new Hook(p);hook.zero=true;f.hook(hook);ElectronMissile.start(p,1);f.ticks(9,tick->{if(tick==9)s.cp=71;ElectronMissile.tick(p);if(tick==9){h.assertValueEqual(hook.count(target),0,"12tickleaves59cannotpayattack60");h.assertValueEqual(ElectronMissile.ballCount(p),1,"failedattackkeepsorb");near(h,s.cp,59,"onlytickCPpaid");ElectronMissile.release(p,1);s.cooldowns.clear();s.cooldownMaxTicks.clear();s.overload=0;s.overloadFine=true;s.cp=11;h.assertTrue(ElectronMissile.start(p,2),"newfailedtickhold");h.runAtTickTime(10,()->{ElectronMissile.tick(p);h.assertFalse(ElectronMissile.active(p),"insufficient12endsbeforeballspawn");h.assertValueEqual(ElectronMissile.ballCount(p),0,"noorbwhenfirsttickCPfails");h.assertValueEqual(s.cooldowns.get(ElectronMissile.ID),700,"failedtickendcooldown");h.succeed();});}});}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late",timeoutTicks=20)
 public static void nonce_authenticated_terminal_requests_and_lifecycle_finite_guards(GameTestHelper h){var f=new Fixture(h);var p=f.player();var s=ready(p,JetEngine.ID,4,0);h.assertTrue(bind(s,0,JetEngine.ID),"nativecanonicalpresetbind");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:01")),"noncanonicalnonce denied");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press_token","0:1")),"authenticatedboundslotstarts");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_release_token","0:2")),"forgedterminalnonce denied");h.assertTrue(JetEngine.active(p),"forgedreleasecannotreplacehold");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_release","0")),"unnoncedlegacyreleasecannotbypasslatefence");h.assertTrue(JetEngine.active(p),"legacyreleaseleavescurrentholdalive");h.assertTrue(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_release_token","0:1")),"matchingnonce startsflight");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_abort_token","0:2")),"forgedabort cannotremoveflight");JetEngine.remove(p);h.assertFalse(JetEngine.active(p),"lifecycleflightdisposed");h.assertTrue(p.isNoGravity(),"ownedpreviousnoGravityrestored");s.cooldowns.clear();s.cooldownMaxTicks.clear();s.overload=0;s.overloadFine=true;s.cp=Double.NaN;h.assertFalse(JetEngine.start(p,2),"nonfiniteCPfailclosed");s.cp=s.maxCp();float yaw=p.getYHeadRot();p.setYHeadRot(Float.NaN);try{h.assertFalse(JetEngine.start(p,2),"genuineNaNheadyawdenied");}finally{p.setYHeadRot(yaw);}s.level=5;s.learn(ElectronMissile.ID);h.assertTrue(ElectronMissile.start(p,1),"validmissilelifecyclefixture");ElectronMissile.remove(p);h.assertTrue(s.cooldowns.isEmpty(),"lifecyclemissilediscardnoinventedcooldown");h.succeed();}
 @GameTest(template=TEMPLATE,batch="academy_meltdowner_late_learning",timeoutTicks=30)
 public static void physical_Advanced_GUI_genuinely_learns_three_targets_with_finite_IF(GameTestHelper h){var f=new Fixture(h);var p=f.player();var item=MachineDevelopers.ADVANCED_ITEM.get();var stack=new ItemStack(item);p.setItemInHand(InteractionHand.MAIN_HAND,stack);var base=h.absolutePos(new BlockPos(10,1,14));h.assertTrue(item.place(new BlockPlaceContext(p,InteractionHand.MAIN_HAND,stack,new BlockHitResult(Vec3.atCenterOf(base),Direction.UP,base,false))).consumesAction(),"physical8cellAdvancedplacement");var machine=(MachineDeveloperBlockEntity)h.getLevel().getBlockEntity(base);p.moveTo(base.getX()+.5,base.getY(),base.getZ()-1.5,0,0);
  for(String id:List.of(RayBarrage.ID,JetEngine.ID,ElectronMissile.ID)){DevelopmentController.remove(p);var s=AbilityStorage.get(p);s.selectCategory("meltdowner");int level=id.equals(ElectronMissile.ID)?5:4;s.setLevel(level);var skill=SkillCatalog.find("meltdowner",id).orElseThrow();for(var req:skill.requirements()){s.learn(req.id());s.experience.put(req.id(),req.exp());}h.assertFalse(s.learned(id),"targetneverfixturegranted");machine.battery().load(200000);h.assertTrue(machine.use(p),"authenticAdvancedGUIsession");String nonce=MachineDeveloperSessions.activeToken(p).orElseThrow().toString();h.assertFalse(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",UUID.randomUUID()+":"+id)),"forgedlearningnonce denied");h.assertTrue(MachineDeveloperSessions.request(p,new AcademyNetwork.Request("machine_learn",nonce+":"+id)),"genuinecommonregistrylearningingress");int ticks=level==4?176:240;for(int tick=1;tick<=ticks;tick++){DevelopmentController.tick(p,snapshot->{});if(tick<ticks)h.assertFalse(s.learned(id),"source15TPSplusoneperstimulation noearlylearn");}h.assertTrue(s.learned(id)&&s.exp(id)==0&&DevelopmentController.process(p).state()==DevelopmentProcess.State.DONE,"genuinelyAdvancedlearnedzeroEXP");near(h,machine.battery().getEnergy(),200000-(level==4?7040:9600),"actualfiniteIFdrain");h.assertTrue(s.presets.currentSkill(0).isEmpty(),"learningneverautobinds");s.activated=true;h.assertTrue(bind(s,0,id),"naturallyearnedskillbindsactualpreset");}
  h.succeed();}
 private static boolean bind(AbilityProgress s,int slot,String id){return s.presets.edit(0,slot,id,value->cn.academy.port.preset.PresetSkills.selectable(s,value));}
 private static AbilityProgress ready(ServerPlayer p,String id,int level,double exp){var s=AbilityStorage.get(p);s.selectCategory("meltdowner");s.setLevel(level);s.learn(id);s.experience.put(id,exp);s.activated=true;return s;}
 private static void near(GameTestHelper h,double a,double b,String why){h.assertTrue(Math.abs(a-b)<1E-5,why+" actual="+a+" expected="+b);}
 private static final class Fixture{final GameTestHelper h;final List<ServerPlayer> players=new ArrayList<>();final List<EmbeddedChannel> channels=new ArrayList<>();final List<Entity> entities=new ArrayList<>();final List<Object> hooks=new ArrayList<>();boolean closed;Fixture(GameTestHelper h){this.h=h;h.testInfo.addListener(new GameTestListener(){public void testStructureLoaded(GameTestInfo i){}public void testPassed(GameTestInfo i,GameTestRunner r){cleanup();}public void testFailed(GameTestInfo i,GameTestRunner r){cleanup();}public void testAddedForRerun(GameTestInfo i,GameTestInfo n,GameTestRunner r){cleanup();}});}FakePlayer player(){var p=new FakePlayer(h.getLevel(),new GameProfile(UUID.randomUUID(),"[AC-MD-Late]"));players.add(p);Vec3 at=h.absoluteVec(new Vec3(10.5,1,10.5));p.moveTo(at.x,at.y,at.z,0,0);p.setYHeadRot(0);p.setNoGravity(true);p.setDeltaMovement(Vec3.ZERO);p.getAbilities().instabuild=false;return p;}/** FakePlayer's connection deliberately no-ops teleport. Flight uses a real owned native
  * ServerPlayer and official GameTest mock channel, not a fake movement override or socket. */
 ServerPlayer connectedPlayer(){var level=h.getLevel();var server=level.getServer();var cookie=CommonListenerCookie.createInitial(new GameProfile(UUID.randomUUID(),"ACMDFlightProbe"),false);var p=new ServerPlayer(server,level,cookie.gameProfile(),cookie.clientInformation());players.add(p);var connection=new Connection(PacketFlow.SERVERBOUND);var channel=new EmbeddedChannel(connection);channels.add(channel);NetworkRegistry.configureMockConnection(connection);try{server.getPlayerList().placeNewPlayer(connection,p,cookie);h.assertTrue(server.getPlayerList().getPlayer(p.getUUID())==p,"native PlayerList admits exact owned flight fixture");var at=h.absoluteVec(new Vec3(10.5,1,10.5));p.moveTo(at.x,at.y,at.z,0,0);p.setYHeadRot(0);p.setNoGravity(true);p.setDeltaMovement(Vec3.ZERO);p.setGameMode(GameType.SURVIVAL);return p;}catch(RuntimeException failure){try{cleanup();}catch(RuntimeException next){failure.addSuppressed(next);}throw failure;}}
 Villager target(Vec3 at){var v=h.spawnWithNoFreeWill(EntityType.VILLAGER,new Vec3(1,1,1));entities.add(v);v.moveTo(at.x,at.y,at.z,0,0);v.setYHeadRot(0);v.setNoAi(true);v.setNoGravity(true);v.setDeltaMovement(Vec3.ZERO);v.getAttribute(Attributes.MAX_HEALTH).setBaseValue(200);v.setHealth(200);return v;}void hook(Object o){hooks.add(o);NeoForge.EVENT_BUS.register(o);}void ticks(int count,IntConsumer body){for(int tick=1;tick<=count;tick++){int now=tick;h.runAtTickTime(tick,()->{if(!closed)body.accept(now);});}}void cleanup(){if(closed)return;closed=true;for(var o:hooks)NeoForge.EVENT_BUS.unregister(o);for(var p:players){RayBarrage.remove(p);JetEngine.remove(p);ElectronMissile.remove(p);DevelopmentController.remove(p);MachineDeveloperSessions.close(p);AbilityStorage.remove(p);var list=h.getLevel().getServer().getPlayerList();if(list.getPlayer(p.getUUID())==p)list.remove(p);else p.discard();}for(var e:entities)e.discard();for(var channel:channels)channel.finishAndReleaseAll();}}
 public static final class Hook{final ServerPlayer owner;final Map<Entity,Integer> counts=new IdentityHashMap<>();final Map<Entity,Double> damages=new IdentityHashMap<>();boolean zero,reentry,reentered;Hook(ServerPlayer p){owner=p;}@SubscribeEvent public void attack(SkillAttackEvent e){if(e.player!=owner||!Set.of("meltdowner.ray_barrage","meltdowner.jet_engine","meltdowner.electron_missile").contains(e.skill))return;counts.merge(e.target,1,Integer::sum);damages.put(e.target,e.amount);if(zero)e.amount=0;if(reentry)reentered|=RayBarrage.start(owner,2);}int count(Entity e){return counts.getOrDefault(e,0);}double damage(Entity e){return damages.getOrDefault(e,0D);}}
}
