/* AcademyCraft1.0.7 commands, owned native dispatcher fixtures. GPLv3; see NOTICE. */
package cn.academy.port.gametest;

import cn.academy.port.*;
import cn.academy.port.achievements.*;
import cn.academy.port.command.ClassicAbilityCommands;
import cn.academy.port.core.ClassicSkillConfiguration;
import cn.academy.port.preset.PresetSkills;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import net.minecraft.commands.*;
import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.contents.TranslatableContents;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.*;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.level.LevelEvent;
import net.neoforged.neoforge.gametest.*;
import java.io.*;
import java.util.*;

/** No socket or screen claims: real PlayerList, production registered commands and NBT codec. */
@GameTestHolder("academy_commands") @PrefixGameTestTemplate(false) @EventBusSubscriber(modid="academy")
public final class AcademyCommandRuntimeTests {
 @SubscribeEvent public static void template(LevelEvent.Load e){if(!GameTestHooks.isGametestEnabled()||!Boolean.getBoolean("academy.commands.qa")||!(e.getLevel() instanceof ServerLevel w))return;var t=new CompoundTag();var size=new ListTag();for(int i=0;i<3;i++)size.add(IntTag.valueOf(12));t.put("size",size);var blocks=new ListTag();var cell=new CompoundTag();var pos=new ListTag();for(int i=0;i<3;i++)pos.add(IntTag.valueOf(0));cell.put("pos",pos);cell.putInt("state",0);blocks.add(cell);t.put("blocks",blocks);t.put("entities",new ListTag());var palette=new ListTag();var air=new CompoundTag();air.putString("Name","minecraft:air");palette.add(air);t.put("palette",palette);w.getStructureManager().getOrCreate(ResourceLocation.fromNamespaceAndPath("academy_commands","runtime_empty")).load(w.registryAccess().lookupOrThrow(Registries.BLOCK),t);}
 private static int execute(GameTestHelper h,CommandSourceStack source,String command){try{return h.getLevel().getServer().getCommands().getDispatcher().execute(command,source);}catch(CommandSyntaxException bad){throw new AssertionError("actual dispatcher rejected "+command,bad);}}
 private static CommandSourceStack self(ServerPlayer p,Messages out){return p.createCommandSourceStack().withPermission(4).withSource(out);}
 private static CommandSourceStack console(GameTestHelper h,Messages out){return h.getLevel().getServer().createCommandSourceStack().withPermission(4).withSource(out);}
 private static String target(ServerPlayer p,String args){return "aimp "+p.getGameProfile().getName()+" "+args;}
 private static void close(GameTestHelper h,double a,double b,String label){h.assertTrue(Math.abs(a-b)<1E-5,label+": "+a+" vs "+b);}
 private static final class Messages implements CommandSource {final List<Component> values=new ArrayList<>();public void sendSystemMessage(Component c){values.add(c);}public boolean acceptsSuccess(){return true;}public boolean acceptsFailure(){return true;}public boolean shouldInformAdmins(){return false;}boolean key(String key){return values.stream().anyMatch(c->c.getContents() instanceof TranslatableContents t&&t.getKey().equals(key));}void clear(){values.clear();}}

 @GameTest(template="runtime_empty",batch="academy_commands",timeoutTicks=20)
 public static void production_registration_permission_self_warning_persisted_marker_help_and_console_target(GameTestHelper h){
  try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){var p=actors.player();var out=new Messages();var src=self(p,out);var dispatcher=p.server.getCommands().getDispatcher();
   for(String root:List.of("aim","aimp","acach")){h.assertTrue(dispatcher.getRoot().getChild(root)!=null,"actual Commands registration "+root);try{dispatcher.execute(root+" help",src.withPermission(0));throw new AssertionError("permission0 accepted "+root);}catch(CommandSyntaxException denied){h.assertTrue(!ClassicAbilityCommands.active(p),"denied command cannot mutate persisted cheat flag");}}
   h.assertValueEqual(execute(h,console(h,out),"aim cheats_on"),0,"console /aim cannot silently choose a player");h.assertTrue(out.key("ac.command.noplayer"),"console gets original player-only diagnostic");out.clear();
   h.assertValueEqual(execute(h,src,"aim cheats_on"),1,"explicit opt-in accepted");h.assertTrue(ClassicAbilityCommands.active(p)&&out.key("ac.command.aim.warning"),"original persisted marker and warning");var bytes=new ByteArrayOutputStream();NbtIo.writeCompressed(p.getPersistentData(),bytes);h.assertTrue(NbtIo.readCompressed(new ByteArrayInputStream(bytes.toByteArray()),NbtAccounter.unlimitedHeap()).getCompound("PlayerPersisted").getBoolean("aim_cheats"),"self opt-in survives real compressed player NBT");
   execute(h,src,"aim cheats_off");h.assertFalse(ClassicAbilityCommands.active(p),"explicit opt-out stored immediately");out.clear();execute(h,src,"aim help");h.assertTrue(p.server.getWorldData().isAllowCommands()&&ClassicAbilityCommands.active(p),"test world allowCommands faithfully reactivates next self command");h.assertValueEqual(out.values.size(),13,"original help list count");h.assertTrue(out.key("ac.command.aim.maxout")&&!out.key("ac.command.aim.unlearn"),"source omitted unlearn help quirk retained");
   out.clear();h.assertValueEqual(execute(h,console(h,out),"aimp "+p.getGameProfile().getName().toLowerCase(Locale.ROOT)+" cat electromaster"),0,"/aimp exact case target lookup");h.assertTrue(out.key("ac.command.noplayer"),"bad target gets original diagnostic");execute(h,console(h,out),target(p,"cat electromaster"));h.assertTrue(AbilityStorage.get(p).category.equals("electromaster")&&AbilityStorage.get(p).level==1,"console acts on supplied real online player only");h.succeed();
  }catch(IOException io){throw new AssertionError(io);}
 }

 public static final class LearnEvents {final ServerPlayer p;int calls;LearnEvents(ServerPlayer p){this.p=p;}@SubscribeEvent public void learned(cn.academy.port.api.SkillLearnEvent e){if(e.getEntity()==p)calls++;}}
 @GameTest(template="runtime_empty",batch="academy_commands",timeoutTicks=20)
 public static void indexes_disabled_prerequisite_bypass_and_learn_all_raw_bitset_without_fake_acquisition_events(GameTestHelper h){
  try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){var p=actors.player();var src=console(h,new Messages());var s=AbilityStorage.get(p);var events=new LearnEvents(p);NeoForge.EVENT_BUS.register(events);var snapshot=SkillCatalog.configurationSnapshot();
   try{execute(h,src,target(p,"cat electromaster"));var rail=ClassicSkillConfiguration.key("electromaster","railgun");SkillCatalog.refreshConfiguration(Map.of(rail,new ClassicSkillConfiguration.Flags(false,true)));execute(h,src,target(p,"learn railgun"));h.assertTrue(s.level==1&&s.learned("railgun")&&!s.learned("thunder_bolt")&&!SkillCatalog.enabled(s.category,"railgun"),"administrator override bypasses original level/dependencies/live disabled flag");h.assertValueEqual(events.calls,1,"single learn emits actual event");execute(h,src,target(p,"learn 0"));h.assertTrue(s.learned("arc_gen"),"integer zero resolves original first category skill identity");
    execute(h,src,target(p,"reset"));execute(h,src,target(p,"cat electromaster"));execute(h,src,target(p,"level 5"));s.cp=31;s.overload=9;double rawCp=s.baseCp(),rawO=s.baseOverload();int before=events.calls;execute(h,src,target(p,"learn_all"));h.assertValueEqual(s.experience.size(),(int)SkillCatalog.ALL.stream().filter(v->v.category().equals(s.category)).count(),"all source category registrations learned, including disabled/passive");h.assertValueEqual(events.calls,before,"learn_all uses direct source bitset with no acquired-skill events");close(h,s.baseCp(),rawCp,"raw maximum remains cached without source event");close(h,s.baseOverload(),rawO,"raw overload cache remains");close(h,s.cp,31,"learn_all does not refill CP");close(h,s.overload,9,"learn_all does not clear overload");execute(h,src,target(p,"cat meltdowner"));execute(h,src,target(p,"learn_all"));h.assertFalse(ClassicAchievements.earned(p,"meltdowner.rad_intensify"),"bulk grant does not invent actual individual acquisition achievement");h.succeed();
   }finally{SkillCatalog.applyConfigurationSnapshot(snapshot);NeoForge.EVENT_BUS.unregister(events);}
  }
 }

 @GameTest(template="runtime_empty",batch="academy_commands",timeoutTicks=20)
 public static void unlearn_retains_raw_mastery_capacity_presets_cooldowns_across_cold_codec_without_authorizing_cast(GameTestHelper h){
  try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){var p=actors.player();var src=console(h,new Messages());var s=AbilityStorage.get(p);execute(h,src,target(p,"cat electromaster"));execute(h,src,target(p,"learn arc_gen"));execute(h,src,target(p,"exp arc_gen 0.75"));s.activated=true;s.presets.edit(0,0,"arc_gen",id->PresetSkills.selectable(s,id));s.setCooldown("arc_gen",91);execute(h,src,target(p,"unlearn arc_gen"));h.assertFalse(s.learned("arc_gen"),"unlearn clears only learned identity");close(h,s.exp("arc_gen"),.75,"source raw mastery retained before reload");h.assertTrue(s.presets.currentSkill(0).equals("arc_gen")&&s.cooldowns.get("arc_gen")==91,"source raw saved mapping and cooldown retain identity");var bytes=new ByteArrayOutputStream();NbtIo.writeCompressed(AbilityStorage.encode(s),bytes);var cold=AbilityStorage.decode(NbtIo.readCompressed(new ByteArrayInputStream(bytes.toByteArray()),NbtAccounter.unlimitedHeap()));h.assertFalse(cold.learned("arc_gen"),"cold retained mastery never grants learning");close(h,cold.exp("arc_gen"),.75,"compressed cold mastery retained");h.assertTrue(cold.presets.currentSkill(0).equals("arc_gen")&&cold.cooldowns.get("arc_gen")==91&&!PresetSkills.mappedUsable(cold,"arc_gen"),"raw identity remains while modern cast eligibility rejects it");h.assertFalse(AcademyGameplay.requestFromClient(p,new AcademyNetwork.Request("slot_press","0")),"actual authenticated ingress refuses unlearned raw mapping");execute(h,src,target(p,"learn arc_gen"));close(h,s.exp("arc_gen"),.75,"relearning restores old source mastery");execute(h,src,target(p,"learn brain_course"));double learnedMax=s.baseCp();execute(h,src,target(p,"unlearn brain_course"));close(h,s.baseCp(),learnedMax,"unlearn emits no max recalculation event");AbilityStorage.remove(p);close(h,AbilityStorage.get(p).baseCp(),learnedMax,"native cache drop/rebind preserves persisted source calculated raw maximum");h.succeed();
  }catch(IOException io){throw new AssertionError(io);}
 }

 @GameTest(template="runtime_empty",batch="academy_commands",timeoutTicks=20)
 public static void same_category_level_noops_fullcp_delays_maxout_float_boundaries_and_customized_radiation_mastery(GameTestHelper h){
  try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){var p=actors.player();var src=console(h,new Messages());var s=AbilityStorage.get(p);execute(h,src,target(p,"cat electromaster"));execute(h,src,target(p,"learn arc_gen"));s.levelExperience=.4;s.extraCp=7;s.extraOverload=2;s.activated=true;s.cp=11;s.overload=19;s.cpDelay=12;s.overloadDelay=8;s.overloadFine=false;execute(h,src,target(p,"cat electromaster"));execute(h,src,target(p,"level 1"));h.assertTrue(s.learned("arc_gen")&&s.activated&&s.levelExperience==.4&&s.extraCp==7&&s.cp==11&&s.overload==19,"source same category and same level are complete noops");execute(h,src,target(p,"fullcp"));close(h,s.cp,s.maxCp(),"fullcp direct max assignment");h.assertTrue(s.overload==0&&!s.overloadFine&&s.cpDelay==12&&s.overloadDelay==8,"fullcp preserves source overload flag and both delays");execute(h,src,target(p,"maxout"));close(h,s.levelExperience,100,"source maxout raw100");
   for(String bad:List.of("exp arc_gen NaN","exp arc_gen Infinity","exp arc_gen -0.01","exp arc_gen 1.01","exp arc_gen nope","learn","unlearn","level 0","level 6","level none"))h.assertValueEqual(execute(h,src,target(p,bad)),0,"bounded malformed command "+bad);h.assertTrue(s.learned("arc_gen")&&Double.isFinite(s.exp("arc_gen"))&&s.level==1,"rejected float/syntax inputs leave finite state");execute(h,src,target(p,"exp arc_gen 0.4"));close(h,s.exp("arc_gen"),(double).4F,"source single-precision setter");execute(h,src,target(p,"exp charging 0.8"));h.assertFalse(s.learned("charging"),"exp setter cannot learn missing skill");execute(h,src,target(p,"level 3"));h.assertTrue(s.extraCp==0&&s.extraOverload==0&&s.levelExperience==0,"changed level resets growth through source level event semantics");s.levelExperience=.7;s.extraCp=9;s.extraOverload=3;execute(h,src,target(p,"cat meltdowner"));h.assertTrue(s.level==3&&s.levelExperience==.7&&s.extraCp==9&&s.extraOverload==3&&s.activated&&s.experience.isEmpty(),"direct category change preserves positive level/growth/progress/active while clears skills");execute(h,src,target(p,"learn rad_intensify"));double actual=s.exp("rad_intensify");execute(h,src,target(p,"exp rad_intensify 1"));close(h,s.exp("rad_intensify"),actual,"customized radiation getter ignores raw command mastery setter");h.assertTrue(s.experience.get("rad_intensify")==1,"source raw setter still stores float mastery");execute(h,src,target(p,"reset"));h.assertTrue(!s.hasCategory()&&s.level==0&&!s.activated&&s.levelExperience==.7&&s.extraCp==9,"reset keeps source growth/progress but removes category/activation");h.succeed();
  }
 }

 @GameTest(template="runtime_empty",batch="academy_commands",timeoutTicks=20)
 public static void acach_known_id_success_is_distinct_from_parent_gate_repeat_and_unknown_id(GameTestHelper h){
  try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){var p=actors.player();var out=new Messages();var src=self(p,out);h.assertValueEqual(execute(h,src,"acach electromaster.lv2"),1,"known achievement yields original successful command result even when parent gate blocks actual award");h.assertFalse(ClassicAchievements.earned(p,"electromaster.lv2"),"command never bypasses real parent gate");h.assertTrue(out.key("ac.command.successful"),"source knownID result diagnostic");execute(h,src,"acach electromaster.lv1");h.assertTrue(ClassicAchievements.earned(p,"electromaster.lv1"),"self default command target receives actual native criterion");execute(h,console(h,out),"acach electromaster.lv2 "+p.getGameProfile().getName().toLowerCase(Locale.ROOT));h.assertTrue(ClassicAchievements.earned(p,"electromaster.lv2"),"original achievement target lookup supports case-insensitive native name");h.assertValueEqual(execute(h,src,"acach electromaster.lv2"),1,"repeat known achievement success retained without double completion");h.assertValueEqual(execute(h,src,"acach no_such_classic_id"),0,"unknown achievement rejected");h.assertValueEqual(execute(h,console(h,out),"acach electromaster.lv1"),0,"console default sender is not a player target");h.succeed();
  }
 }
 @GameTest(template="runtime_empty",batch="academy_commands",timeoutTicks=20)
 public static void source_transient_cooldown_storage_live_clone_real_death_and_persisted_self_optin(GameTestHelper h){
  try(var actors=new AcademyWirelessDeviceRuntimeTests.NativeMenuActors(h)){var p=actors.player();execute(h,self(p,new Messages()),"aim cheats_on");var s=AbilityStorage.get(p);s.changeCategoryClassic("electromaster");s.learn("arc_gen");s.setCooldown("arc_gen",91);AbilityStorage.save(p);var disk=p.getPersistentData().getCompound("academy:classic_progress");h.assertFalse(disk.contains("cooldowns")||disk.contains("cooldown_max"),"original CooldownData has no NBT storage; saved ability payload omits both transient ledgers");h.assertTrue(AbilityStorage.encode(s).getCompound("cooldowns").getInt("arc_gen")==91,"client live sync still contains actual HUD cooldown");
   var replacement=actors.player();replacement.restoreFrom(p,true);var copied=AbilityStorage.get(replacement);h.assertTrue(copied.cooldowns.get("arc_gen")==91&&ClassicAbilityCommands.active(replacement),"actual native nondeath clone retains live source cooldown and Forge PlayerPersisted opt-in");replacement.setInvulnerable(false);replacement.hurt(replacement.damageSources().fellOutOfWorld(),Float.MAX_VALUE);h.assertTrue(!replacement.isAlive()&&copied.cooldowns.isEmpty()&&copied.cooldownMaxTicks.isEmpty(),"real native player death clears both source cooldown ledgers before persistence");h.succeed();
  }
 }
}
