package oracle;
import java.util.*;import java.lang.reflect.*;
import cn.academy.port.*;import cn.academy.port.terminal.*;import cn.academy.port.wireless.*;import cn.academy.port.solar.*;import cn.academy.port.machine.*;import cn.academy.port.tutorial.*;
import net.minecraft.core.BlockPos;import net.minecraft.nbt.*;import net.minecraft.server.level.*;import net.minecraft.world.level.block.entity.BlockEntity;import net.minecraft.world.phys.*;import net.neoforged.neoforge.network.PacketDistributor;import net.minecraft.network.RegistryFriendlyByteBuf;import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;
public final class TerminalIngressOracle {
 static int assertions,groups;static String group="initial";
 static void eq(Object actual,Object expected){assertions++;if(!Objects.equals(actual,expected))throw new AssertionError(group+": "+actual+" != "+expected);}
 static void begin(String name){group=name;groups++;}
 static final BlockPos M=new BlockPos(1,0,0),N=new BlockPos(2,0,0),G=new BlockPos(3,0,0),R=new BlockPos(3,1,0),OTHER=new BlockPos(9,0,0),PART=new BlockPos(1,1,0);
 static class Generator implements ImagFluxGenerator {double energy=100;public double getEnergy(){return energy;}public double getBandwidth(){return 10;}public double getProvidedEnergy(double ask){double got=Math.min(energy,ask);energy-=got;return got;}}
 static class Receiver implements ImagFluxReceiver {double energy;public double getEnergy(){return energy;}public double getMaxEnergy(){return 100;}public double getRequiredEnergy(){return 100-energy;}public double getBandwidth(){return 10;}public double injectEnergy(double n){double accept=Math.min(n,100-energy);energy+=accept;return n-accept;}public double pullEnergy(double n){double got=Math.min(n,energy);energy-=got;return got;}}
 static class Env {ServerLevel world=new ServerLevel();ServerPlayer player=new ServerPlayer(world);ClassicWirelessMatrixBlockEntity matrix=new ClassicWirelessMatrixBlockEntity(M);ClassicWirelessNodeBlockEntity node=new ClassicWirelessNodeBlockEntity(N);Generator generator=new Generator();Receiver receiver=new Receiver();ClassicWirelessGraph graph;
  Env(){TerminalStorage.clear();world.tiles.put(M,matrix);world.tiles.put(N,node);world.tiles.put(G,new BlockEntity(G));world.tiles.put(R,new MachineDeveloperBlockEntity(R));world.generators.put(G,generator);world.receivers.put(R,receiver);graph=ClassicWirelessSavedData.get(world).graph();eq(graph.createNetwork(pos(M),"SSID-Actual","matrix-secret"),true);TerminalStorage.get(player).restore(true,List.of("skill_tree","freq_transmitter","media_player"));PacketDistributor.client.clear();PacketDistributor.server.clear();look(M);}
  void look(BlockPos p){world.hit=new HitResult(HitResult.Type.BLOCK,p);}
  boolean req(String kind,BlockPos target,BlockPos selected,String pass){look(target);return raw(new TerminalNetwork.FrequencyRequest(target,selected,pass,kind));}
  boolean raw(TerminalNetwork.FrequencyRequest request){return TerminalFrequencySessions.request(player,request);}
  boolean authMatrix(){return req("authorize_matrix",M,M,"matrix-secret");}boolean authNode(){return req("authorize_node",N,N,"node-secret");}
 }
 static ClassicWirelessGraph.Pos pos(BlockPos p){return ClassicWirelessSavedData.pos(p);}
 static CompoundTag packet(){var delivery=PacketDistributor.client.getLast();return ((AcademyNetwork.ClientData)delivery.payload()).data();}
 static void cleanPackets(){for(var delivery:PacketDistributor.client){eq(delivery.payload() instanceof AcademyNetwork.ClientData,true);CompoundTag data=((AcademyNetwork.ClientData)delivery.payload()).data();for(String key:data.getAllKeys()){eq(key.toLowerCase().contains("password"),false);eq(data.getString(key).contains("matrix-secret"),false);eq(data.getString(key).contains("node-secret"),false);}}}
 static void deny(Env env,TerminalNetwork.FrequencyRequest request,boolean response){var before=env.graph.snapshot();int count=PacketDistributor.client.size();eq(env.raw(request),false);eq(env.graph.snapshot(),before);eq(PacketDistributor.client.size(),count+(response?1:0));if(response){eq(packet().getBoolean("accepted"),false);eq(packet().getLong("pos"),request.target().asLong());eq(packet().getLong("selected"),request.selected().asLong());}}
 public static void main(String[] args)throws Exception {network();frequency();rayPreflight();session();lifecycle();codec();coldLink();System.out.println("SUMMARY|modern-ingress|"+groups+"|"+assertions);}
 static void network(){begin("network sender and command ingress");Env e=new Env();
  eq(TerminalNetwork.valid(null),false);for(int failure=0;failure<4;failure++){e.player.removed=failure==0;e.player.alive=failure!=1;e.player.spectator=failure==2;e.world.server.sameThread=failure!=3;eq(TerminalNetwork.valid(e.player),false);eq(TerminalNetwork.request(e.player,new AcademyNetwork.Request("terminal_open","")),false);}e.player.removed=false;e.player.alive=true;e.player.spectator=false;e.world.server.sameThread=true;eq(TerminalNetwork.valid(e.player),true);
  for(AcademyNetwork.Request request:Arrays.asList(null,new AcademyNetwork.Request(null,""),new AcademyNetwork.Request("terminal_open",null),new AcademyNetwork.Request("terminal_open","junk"),new AcademyNetwork.Request("terminal_close","junk"),new AcademyNetwork.Request("terminal_install",""),new AcademyNetwork.Request("terminal_app","unknown"),new AcademyNetwork.Request("terminal_app","thirdparty:future"))){int count=PacketDistributor.client.size();eq(TerminalNetwork.request(e.player,request),false);eq(PacketDistributor.client.size(),count);}
  TerminalStorage.get(e.player).restore(false,List.of("skill_tree","thirdparty:future"));eq(TerminalNetwork.request(e.player,new AcademyNetwork.Request("terminal_open","")),false);eq(e.player.chat.getLast().key(),"ac.terminal.notinstalled");eq(TerminalNetwork.request(e.player,new AcademyNetwork.Request("terminal_app","skill_tree")),false);
  TerminalStorage.get(e.player).restore(true,List.of("freq_transmitter","media_player","skill_tree","thirdparty:future"));eq(TerminalNetwork.request(e.player,new AcademyNetwork.Request("terminal_open","")),true);eq(packet().getString("kind"),"terminal_open");eq(TerminalNetwork.request(e.player,new AcademyNetwork.Request("terminal_app","media_player")),true);eq(packet().getString("kind"),"terminal_app");eq(packet().getString("app"),"media_player");
  int tutorials=TutorialNetwork.opens;eq(TerminalNetwork.request(e.player,new AcademyNetwork.Request("terminal_app","tutorial")),true);eq(TutorialNetwork.opens,tutorials+1);int syncs=AcademyNetwork.syncs;eq(TerminalNetwork.request(e.player,new AcademyNetwork.Request("terminal_app","skill_tree")),true);eq(AcademyNetwork.syncs,syncs+1);
  TerminalNetwork.sync(e.player);eq(packet().getString("kind"),"terminal_state");eq(packet().getBoolean("isInstalled"),true);eq(TerminalStorage.decode(packet()).savedAppIds().contains("thirdparty:future"),true);TerminalNetwork.installed(e.player,null);eq(packet().getString("kind"),"terminal_installed");TerminalNetwork.installed(e.player,"skill_tree");eq(packet().getString("kind"),"terminal_app_installed");TerminalNetwork.installEffect(e.player);eq(packet().getString("kind"),"terminal_install_effect");cleanPackets();
 }
 static void frequency(){begin("frequency malformed sender and app gates");Env e=new Env();
  var query=new TerminalNetwork.FrequencyRequest(M,M,"","query_matrix");for(int failure=0;failure<4;failure++){e.player.removed=failure==0;e.player.alive=failure!=1;e.player.spectator=failure==2;e.world.server.sameThread=failure!=3;deny(e,query,false);}e.player.removed=false;e.player.alive=true;e.player.spectator=false;e.world.server.sameThread=true;
  for(var request:Arrays.asList(null,new TerminalNetwork.FrequencyRequest(null,M,"","query_matrix"),new TerminalNetwork.FrequencyRequest(M,null,"","query_matrix"),new TerminalNetwork.FrequencyRequest(M,M,null,"query_matrix"),new TerminalNetwork.FrequencyRequest(M,M,"",null),new TerminalNetwork.FrequencyRequest(M,M,"","unrecognized"),new TerminalNetwork.FrequencyRequest(M,M,"x".repeat(129),"query_matrix"),new TerminalNetwork.FrequencyRequest(M,M,"bad\npass","query_matrix"),new TerminalNetwork.FrequencyRequest(M,M,"bad\u0000pass","query_matrix"))){deny(e,request,false);}
  TerminalStorage.get(e.player).restore(false,List.of("freq_transmitter"));deny(e,query,false);TerminalStorage.get(e.player).restore(true,List.of());deny(e,query,false);TerminalStorage.get(e.player).restore(true,List.of("freq_transmitter"));
  begin("finite world ray permissions and loaded endpoints");e.world.hit=new HitResult(HitResult.Type.MISS,null);deny(e,query,true);e.look(N);deny(e,query,true);e.look(M);e.world.unloaded.add(M);deny(e,query,true);e.world.unloaded.clear();e.world.denied.add(M);deny(e,query,true);e.world.denied.clear();
  eq(e.req("query_matrix",M,M,""),true);eq(packet().getString("name"),"SSID-Actual");eq(packet().getString("status"),"e6");eq(e.world.lastClip.from,e.player.eye);eq(e.world.lastClip.to,e.player.eye.add(e.player.look.scale(4)));
  e.matrix.available=false;deny(e,query,true);e.matrix.available=true;e.graph.removeNetwork(pos(M));deny(e,query,true);eq(packet().getString("status"),"e0");eq(e.graph.createNetwork(pos(M),"SSID-Actual","matrix-secret"),true);
  for(String bad:List.of("wrong","MATRIX-secret"," matrix-secret","matrix-secret ","")){eq(e.req("authorize_matrix",M,M,bad),false);eq(packet().getString("status"),"e1");}eq(e.authMatrix(),true);eq(packet().getString("name"),"SSID-Actual");eq(e.req("link_matrix",N,M,"untrusted-client-ignored"),true);eq(e.graph.networkAt(pos(N)).matrix(),pos(M));eq(e.graph.networkAt(pos(M)).load(),1);eq(e.req("link_matrix",N,M,""),true);eq(e.graph.networkAt(pos(M)).load(),1);
  for(String bad:List.of("wrong","NODE-secret"," node-secret","node-secret ","")){eq(e.req("authorize_node",N,N,bad),false);eq(packet().getString("status"),"e1");}eq(e.authNode(),true);eq(packet().getString("name"),"NodeActual");eq(e.req("link_node",G,N,"client-pass-ignored"),true);eq(e.graph.nodeForGenerator(pos(G)),pos(N));eq(e.req("link_node",R,N,""),true);eq(e.graph.nodeForReceiver(pos(R)),pos(N));eq(e.graph.connectionAt(pos(N)).load(),2);eq(e.req("link_node",R,N,""),true);eq(e.graph.connectionAt(pos(N)).load(),2);
  begin("canonical matrix raw response correlation");var part=new ClassicWirelessMatrixBlockEntity(PART);part.root=e.matrix;e.world.tiles.put(PART,part);eq(e.req("query_matrix",PART,PART,""),true);eq(packet().getLong("pos"),PART.asLong());eq(packet().getLong("selected"),PART.asLong());eq(e.req("authorize_matrix",PART,PART,"matrix-secret"),true);eq(e.req("link_matrix",N,PART,""),true);eq(packet().getLong("selected"),PART.asLong());eq(packet().getLong("pos"),N.asLong());cleanPackets();
 }
 static void rayPreflight(){begin("ray finite geometry diagonal chunk preflight and raw hit permission");Env e=new Env();e.player.eye=new Vec3(15.5,0,15.5);e.player.look=new Vec3(0.25,0,0.25);e.look(M);e.world.unloaded.add(new BlockPos(16,0,16));int calls=e.world.clips;deny(e,new TerminalNetwork.FrequencyRequest(M,M,"","query_matrix"),true);eq(e.world.clips,calls);e.world.unloaded.clear();eq(e.req("query_matrix",M,M,""),true);eq(e.world.clips,calls+1);
  for(Vec3 bad:List.of(new Vec3(Double.NaN,0,0),new Vec3(0,Double.POSITIVE_INFINITY,0),new Vec3(0,0,Double.NEGATIVE_INFINITY))){e.player.eye=bad;e.player.look=new Vec3(1,0,0);calls=e.world.clips;deny(e,new TerminalNetwork.FrequencyRequest(M,M,"","query_matrix"),true);eq(e.world.clips,calls);}
  e.player.eye=new Vec3(0,0,0);for(Vec3 bad:List.of(new Vec3(Double.NaN,0,0),new Vec3(0,Double.POSITIVE_INFINITY,0),new Vec3(0,0,Double.NEGATIVE_INFINITY))){e.player.look=bad;calls=e.world.clips;deny(e,new TerminalNetwork.FrequencyRequest(M,M,"","query_matrix"),true);eq(e.world.clips,calls);}
  e.player.look=new Vec3(1,0,0);var part=new ClassicWirelessMatrixBlockEntity(PART);part.root=e.matrix;e.world.tiles.put(PART,part);e.look(PART);e.world.denied.add(PART);deny(e,new TerminalNetwork.FrequencyRequest(M,M,"","query_matrix"),true);e.world.denied.clear();eq(e.raw(new TerminalNetwork.FrequencyRequest(M,M,"","query_matrix")),true);
 }
 static void session()throws Exception {begin("transient authorization scope and revocation");
  Env e=new Env();eq(e.req("link_matrix",N,M,"matrix-secret"),false);eq(packet().getString("status"),"e2");eq(e.req("link_node",G,N,"node-secret"),false);eq(packet().getString("status"),"e3");eq(e.authMatrix(),true);var stranger=new ServerPlayer(e.world);TerminalStorage.get(stranger).restore(true,List.of("freq_transmitter"));e.look(N);eq(TerminalFrequencySessions.request(stranger,new TerminalNetwork.FrequencyRequest(N,M,"matrix-secret","link_matrix")),false);
  e.world.tiles.put(OTHER,new BlockEntity(OTHER));eq(e.req("link_matrix",N,OTHER,""),false);eq(e.req("link_matrix",N,M,""),false);eq(e.authMatrix(),true);e.graph.changeNetworkPassword(pos(M),"changed");eq(e.req("link_matrix",N,M,""),false);e.graph.changeNetworkPassword(pos(M),"matrix-secret");eq(e.authMatrix(),true);eq(e.req("authorize_matrix",M,M,"wrong"),false);eq(e.req("link_matrix",N,M,""),false);
  eq(e.authNode(),true);e.node.password="changed";eq(e.req("link_node",G,N,""),false);e.node.password="node-secret";eq(e.authNode(),true);eq(e.req("authorize_node",N,N,"wrong"),false);eq(e.req("link_node",G,N,""),false);
  for(String command:List.of("terminal_close","terminal_open","terminal_app")){eq(e.authNode(),true);eq(TerminalNetwork.request(e.player,new AcademyNetwork.Request(command,command.equals("terminal_app")?"settings":"")),true);eq(e.req("link_node",G,N,""),false);}
  eq(e.authNode(),true);TerminalFrequencySessions.remove(e.player);eq(e.req("link_node",G,N,""),false);eq(e.authNode(),true);TerminalFrequencySessions.clear();eq(e.req("link_node",G,N,""),false);
  begin("session endpoint identity dimension removal expiration");e=new Env();eq(e.authNode(),true);var replacement=new ClassicWirelessNodeBlockEntity(N);e.world.tiles.put(N,replacement);eq(e.req("link_node",G,N,""),false);e.world.tiles.put(N,e.node);eq(e.req("link_node",G,N,""),false);eq(e.authNode(),true);e.node.removed=true;eq(e.req("link_node",G,N,""),false);e.node.removed=false;eq(e.req("link_node",G,N,""),false);
  eq(e.authMatrix(),true);ServerLevel old=e.player.world;e.player.world=new ServerLevel();e.player.world.tiles.put(N,new ClassicWirelessNodeBlockEntity(N));e.player.world.tiles.put(M,new ClassicWirelessMatrixBlockEntity(M));e.player.world.hit=new HitResult(HitResult.Type.BLOCK,N);eq(TerminalFrequencySessions.request(e.player,new TerminalNetwork.FrequencyRequest(N,M,"","link_matrix")),false);e.player.world=old;eq(e.req("link_matrix",N,M,""),false);
  eq(e.authMatrix(),true);expire(e.player);eq(e.req("link_matrix",N,M,""),false);eq(e.req("link_matrix",N,M,""),false);
  begin("selected source survives player movement and capacity range graph gates");e=new Env();eq(e.authMatrix(),true);e.player.eye=new Vec3(100,10,100);e.player.look=new Vec3(0,0,1);eq(e.req("link_matrix",N,M,""),true);eq(e.world.lastClip.to,new Vec3(100,10,104));
  e=new Env();e.matrix.capacity=0;eq(e.authMatrix(),true);eq(e.req("link_matrix",N,M,""),false);e.matrix.capacity=8;e.matrix.range=0.5;eq(e.req("link_matrix",N,M,""),false);
  e=new Env();eq(e.authNode(),true);e.node.capacity=0;eq(e.req("link_node",G,N,""),false);e.node.capacity=8;e.node.range=0.5;eq(e.req("link_node",G,N,""),false);e.node.range=16;eq(e.req("link_node",OTHER,N,""),false);
 }
 static void expire(ServerPlayer p)throws Exception{Field f=TerminalFrequencySessions.class.getDeclaredField("SESSIONS");f.setAccessible(true);Map map=(Map)f.get(null);Object old=map.get(p);RecordComponent[] fields=old.getClass().getRecordComponents();Object[] values=new Object[fields.length];Class<?>[] types=new Class<?>[fields.length];for(int i=0;i<fields.length;i++){Method accessor=fields[i].getAccessor();accessor.setAccessible(true);values[i]=accessor.invoke(old);types[i]=fields[i].getType();if(fields[i].getName().equals("expiry"))values[i]=System.nanoTime()-1;}Constructor<?> ctor=old.getClass().getDeclaredConstructor(types);ctor.setAccessible(true);map.put(p,ctor.newInstance(values));}
 static void lifecycle(){begin("actual common lifecycle capability cleanup and persistent state");Env e=new Env();e.world.server.players.add(e.player);eq(e.authNode(),true);TerminalEvents.death(new net.neoforged.neoforge.event.entity.living.LivingDeathEvent(e.player));eq(e.req("link_node",G,N,""),false);eq(TerminalStorage.get(e.player).terminalInstalled(),true);eq(TerminalStorage.get(e.player).isInstalled("freq_transmitter"),true);
  eq(e.authNode(),true);TerminalEvents.respawn(new net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerRespawnEvent(e.player));eq(packet().getString("kind"),"terminal_state");eq(e.req("link_node",G,N,""),false);
  eq(e.authNode(),true);TerminalEvents.dimension(new net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerChangedDimensionEvent(e.player));eq(e.req("link_node",G,N,""),false);
  eq(e.authNode(),true);TerminalEvents.logout(new net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerLoggedOutEvent(e.player));eq(e.req("link_node",G,N,""),false);eq(TerminalStorage.get(e.player).isInstalled("freq_transmitter"),true);TerminalEvents.login(new net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerLoggedInEvent(e.player));eq(packet().getString("kind"),"terminal_state");
  eq(e.authNode(),true);var replacement=new ServerPlayer(e.world);TerminalEvents.clone(new net.neoforged.neoforge.event.entity.player.PlayerEvent.Clone(e.player,replacement));eq(TerminalStorage.get(replacement).terminalInstalled(),true);eq(TerminalStorage.get(replacement).isInstalled("freq_transmitter"),true);eq(e.req("link_node",G,N,""),false);
  TerminalEvents.stopping(new net.neoforged.neoforge.event.server.ServerStoppingEvent(e.world.server));eq(e.player.data.getCompound(TerminalStorage.KEY).getBoolean("isInstalled"),true);eq(e.authNode(),true);TerminalEvents.stopped(new net.neoforged.neoforge.event.server.ServerStoppedEvent());eq(e.req("link_node",G,N,""),false);eq(TerminalStorage.get(e.player).isInstalled("freq_transmitter"),true);
 }
 static void codec(){begin("actual codec client outbound and server payload registration");Env e=new Env();var source=new TerminalNetwork.FrequencyRequest(PART,N,"node-secret","authorize_node");var wire=new RegistryFriendlyByteBuf();TerminalNetwork.FrequencyRequest.CODEC.encode(wire,source);eq(wire.bounds,List.of(128,32));eq(TerminalNetwork.FrequencyRequest.CODEC.decode(wire),source);eq(source.type(),TerminalNetwork.FrequencyRequest.TYPE);try{TerminalNetwork.FrequencyRequest.CODEC.encode(new RegistryFriendlyByteBuf(),new TerminalNetwork.FrequencyRequest(M,N,"x".repeat(129),"query_matrix"));throw new AssertionError("password codec bound absent");}catch(IllegalArgumentException expected){}try{TerminalNetwork.FrequencyRequest.CODEC.encode(new RegistryFriendlyByteBuf(),new TerminalNetwork.FrequencyRequest(M,N,"","x".repeat(33)));throw new AssertionError("kind codec bound absent");}catch(IllegalArgumentException expected){}
  TerminalNetwork.requestOpen();TerminalNetwork.requestClose();TerminalNetwork.requestApp("freq_transmitter");TerminalNetwork.requestFrequency(M,N,"node-secret","authorize_node");eq(PacketDistributor.server.size(),4);eq(PacketDistributor.server.get(0),new AcademyNetwork.Request("terminal_open",""));eq(PacketDistributor.server.get(1),new AcademyNetwork.Request("terminal_close",""));eq(PacketDistributor.server.get(2),new AcademyNetwork.Request("terminal_app","freq_transmitter"));eq(PacketDistributor.server.get(3),new TerminalNetwork.FrequencyRequest(M,N,"node-secret","authorize_node"));
  var registration=new RegisterPayloadHandlersEvent();TerminalNetwork.register(registration);eq(registration.handler.type,TerminalNetwork.FrequencyRequest.TYPE);e.look(M);registration.handler.receiver.accept(new TerminalNetwork.FrequencyRequest(M,M,"","query_matrix"),new RegisterPayloadHandlersEvent.Context(e.player));eq(packet().getString("name"),"SSID-Actual");int count=PacketDistributor.client.size();registration.handler.receiver.accept(source,new RegisterPayloadHandlersEvent.Context(new net.minecraft.world.entity.player.Player()));eq(PacketDistributor.client.size(),count);cleanPackets();
 }
 static void coldLink()throws Exception {begin("actual common ingress class linking without client namespaces");var url=TerminalIngressOracle.class.getProtectionDomain().getCodeSource().getLocation();try(var loader=new java.net.URLClassLoader(new java.net.URL[]{url},null){protected Class<?> loadClass(String name,boolean resolve)throws ClassNotFoundException {if(name.startsWith("net.minecraft.client.")||name.startsWith("cn.academy.port.client."))throw new ClassNotFoundException("client linkage forbidden "+name);return super.loadClass(name,resolve);}}){for(String name:List.of("cn.academy.port.terminal.TerminalNetwork","cn.academy.port.terminal.TerminalFrequencySessions","cn.academy.port.terminal.TerminalStorage","cn.academy.port.terminal.TerminalEvents","cn.academy.port.wireless.ClassicWirelessGraph")){eq(Class.forName(name,true,loader).getName(),name);}}}
}
