/* AcademyCraft1.0.7 RBContextC/JEContextC/EMContextC and original entity renderers adaptation.
 * Copyright Lambda Innovation. GPLv3; LambdaLib geometry MIT. See NOTICE. GPU/audio parity pending. */
package cn.academy.port.client;
import cn.academy.port.client.ClassicMeltdownerBeamTimeline.*;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.*;
import com.mojang.math.Axis;
import net.minecraft.Util;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.renderer.*;
import net.minecraft.client.resources.sounds.AbstractTickableSoundInstance;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.*;
import net.minecraft.util.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.ClipContext;
import net.minecraft.world.phys.*;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.*;
import org.joml.Matrix4f;
import java.util.*;
import static cn.academy.port.client.ClassicMeltdownerLateTimeline.*;
/** Authenticated cosmetic contexts. Server owns Jet movement; this class NEVER writes player position/velocity. */
@EventBusSubscriber(modid="academy",value=Dist.CLIENT)
public final class ClassicMeltdownerLateEffects {
 private static final List<String> SKILLS=List.of(BARRAGE,JET,MISSILE);
 private static final Map<String,Map<Integer,Context>> CONTEXTS=new HashMap<>();private static final Map<String,Tokens> TOKENS=new HashMap<>();private static final Map<String,ClassicMeltdownerStarterTimeline.Input> INPUTS=new HashMap<>();private static final Map<String,Long> NONCES=new HashMap<>();private static final Map<String,Boolean> ABORTED=new HashMap<>();
 static{for(String s:SKILLS){CONTEXTS.put(s,new HashMap<>());TOKENS.put(s,new Tokens());INPUTS.put(s,new ClassicMeltdownerStarterTimeline.Input());}}
 private static final ClassicMeltdownerStarterTimeline.PauseClock CLOCK=new ClassicMeltdownerStarterTimeline.PauseClock();private static final Random RANDOM=new Random();
 private static final List<Ray> RAYS=new ArrayList<>();private static final List<Particle> PARTICLES=new ArrayList<>();private static final List<RaySound> SOUNDS=new ArrayList<>();
 private static final ResourceLocation WHITE=texture("port/white"),MD=texture("effects/md_particle"),RIPPLE=texture("effects/ripple"),DIAMOND=texture("effects/diamond_shield"),BALL_GLOW=texture("effects/mdball/glow"),FRAGMENT=texture("entities/silbarn_frag");private static final ResourceLocation[] BALL_TEXTURES=seq("effects/mdball/",5),RAY_TEXTURES={texture("effects/mdray_small/blend_in"),texture("effects/mdray_small/tile"),texture("effects/mdray_small/blend_out")};
 private static ClientLevel activeLevel;private static Player activePlayer;private static Object activeConnection;private static volatile long epoch;private static MultiBufferSource.BufferSource buffers;
 private static final double FRAGMENT_THETA=RANDOM.nextDouble()*Math.PI*2,FRAGMENT_YAW_RATE=Math.sin(FRAGMENT_THETA)*25,FRAGMENT_PITCH_RATE=Math.cos(FRAGMENT_THETA)*25;
 private ClassicMeltdownerLateEffects(){}
 public static boolean owns(String id){return SKILLS.contains(id);}public static boolean held(String id){return JET.equals(id)||MISSILE.equals(id);}
 public static long startLocal(String id){if(!owns(id))return 0;Minecraft mc=Minecraft.getInstance();sync(mc);clock(mc);Context old=mc.player==null?null:CONTEXTS.get(id).remove(mc.player.getId());if(old!=null){TOKENS.get(id).end(old.key,old.token);old.hide();}long n=INPUTS.get(id).press();NONCES.put(id,n);ABORTED.remove(id);return n;}
 /** Hides held visuals immediately; retains nonce for the independent server-authenticated terminal request. */
 public static void endLocal(String id){if(!owns(id))return;Minecraft mc=Minecraft.getInstance();sync(mc);INPUTS.get(id).end();ABORTED.put(id,true);Context c=mc.player==null?null:CONTEXTS.get(id).get(mc.player.getId());if(c!=null&&held(id))c.hide();}
 public static void releaseLocal(String id){if(!owns(id))return;Minecraft mc=Minecraft.getInstance();sync(mc);INPUTS.get(id).end();ABORTED.put(id,false);Context c=mc.player==null?null:CONTEXTS.get(id).get(mc.player.getId());if(c!=null){c.marking=false;if(MISSILE.equals(id))c.hide();}}
 public static long localNonce(String id){return NONCES.getOrDefault(id,0L);}
 public static boolean delegateActive(String id){if(!owns(id))return false;Minecraft mc=Minecraft.getInstance();sync(mc);Context c=mc.player==null?null:CONTEXTS.get(id).get(mc.player.getId());return INPUTS.get(id).heldPending()||c!=null&&c.shown&&c.valid(mc);}
 public static void receive(CompoundTag input){if(input==null)return;CompoundTag t=input.copy();String kind=t.getString("kind"),skill=skill(kind);if(skill==null||!t.contains("entity",Tag.TAG_INT)||!t.hasUUID("entity_uuid")||!t.contains("token",Tag.TAG_LONG)||t.getLong("token")<=0||!t.contains("input",Tag.TAG_LONG)||t.getLong("input")<0)return;
  if(kind.endsWith("_preray")||kind.endsWith("_ray")){if(!vectorTags(t,"x","y","z")||!vectorTags(t,"dx","dy","dz")||!Double.isFinite(vec(t,"dx","dy","dz").lengthSqr())||vec(t,"dx","dy","dz").lengthSqr()<1E-12||!t.contains("length",Tag.TAG_DOUBLE)||!Double.isFinite(t.getDouble("length"))||t.getDouble("length")<0||t.getDouble("length")>32)return;}
  if(kind.equals("ray_barrage_preray")&&!t.contains("hit",Tag.TAG_BYTE))return;
  if(kind.equals("ray_barrage_scatter")&&(!vectorTags(t,"x","y","z")||!t.contains("yaw",Tag.TAG_FLOAT)||!t.contains("pitch",Tag.TAG_FLOAT)||!Float.isFinite(t.getFloat("yaw"))||!Float.isFinite(t.getFloat("pitch"))))return;
  if(kind.equals("jet_engine_trigger")&&(!vectorTags(t,"x","y","z")||!vectorTags(t,"tx","ty","tz")||vec(t,"x","y","z").distanceToSqr(vec(t,"tx","ty","tz"))>400))return;
  if(kind.equals("jet_engine_step")&&(!vectorTags(t,"x","y","z")||!index(t,1,16)))return;
  if(kind.equals("electron_missile_ball")&&(!index(t,0,20)||!t.contains("life",Tag.TAG_INT)||t.getInt("life")!=2333333||!vectorTags(t,"offset_x","offset_y","offset_z")||Math.abs(t.getDouble("offset_x"))>1.31||Math.abs(t.getDouble("offset_z"))>1.31||t.getDouble("offset_y")<.39||t.getDouble("offset_y")>1.81))return;
  if(kind.equals("electron_missile_ray")&&(!index(t,8,200)||t.getInt("index")%8!=0||!t.contains("ball",Tag.TAG_INT)||t.getInt("ball")<0||t.getInt("ball")>20))return;
  if(kind.equals("electron_missile_update")&&!index(t,0,201))return;
  Minecraft mc=Minecraft.getInstance();ClientLevel level=mc.level;Player local=mc.player;Object connection=mc.getConnection();long generation=epoch;mc.execute(()->{
   if(level==null||local==null||mc.level!=level||mc.player!=local||mc.getConnection()!=connection||epoch!=generation)return;sync(mc);clock(mc);int id=t.getInt("entity");UUID uuid=t.getUUID("entity_uuid");long token=t.getLong("token"),nonce=t.getLong("input");boolean localPacket=id==local.getId();if(localPacket&&(!uuid.equals(local.getUUID())||!INPUTS.get(skill).accepts(nonce)))return;Entity entity=level.getEntity(id);Caster key=new Caster(id,uuid);Map<Integer,Context> all=CONTEXTS.get(skill);Tokens history=TOKENS.get(skill);Context c=all.get(id);
   if(c!=null&&!c.key.equals(key)){if(c.valid(mc))return;all.remove(id);history.end(c.key,c.token);c.hide();c=null;}
   if(kind.endsWith("_end")&&!kind.equals("jet_engine_mark_end")){if(c==null&&(!valid(mc,entity)||!entity.getUUID().equals(uuid))||!history.end(key,token))return;if(localPacket)AcademyClient.acceptedSingleEnd(skill,nonce,token);if(c!=null&&c.token<=token){all.remove(id);c.hide();}if(localPacket){INPUTS.get(skill).complete(nonce);if(NONCES.getOrDefault(skill,0L)==nonce)NONCES.remove(skill);}return;}
   if(kind.endsWith("_start")){if(!valid(mc,entity)||!entity.getUUID().equals(uuid)||all.size()>=128&&c==null||!history.start(key,token))return;if(c!=null)c.hide();boolean shown=!localPacket||BARRAGE.equals(skill)||INPUTS.get(skill).mayShowStart(nonce);all.put(id,new Context((Player)entity,skill,level,connection,token,nonce,shown,localPacket));if(localPacket)AcademyClient.acceptedSingleStart(skill,nonce,token);return;}
   if(c==null||c.token!=token||c.nonce!=nonce||!history.active(key,token)||!c.valid(mc))return;
   switch(kind){
    case "ray_barrage_preray"->{if(c.preRay)return;c.preRay=true;addRay(c,t,t.getBoolean("hit")?PRE_HIT:PRE_PLAIN,null);}
    case "ray_barrage_scatter"->{if(c.scatter)return;c.scatter=true;var dirs=new ArrayList<Vec3>();for(var sr:subrays(RANDOM)){double[] d=direction(t.getFloat("yaw")+sr.yaw(),t.getFloat("pitch")+sr.pitch());dirs.add(new Vec3(d[0],d[1],d[2]));}if(RAYS.size()<256){Ray ray=new Ray(c,vec(t,"x","y","z"),dirs,15,BARRAGE_RAY,CLOCK.elapsed());RAYS.add(ray);sound(ray,.5F);}}
    case "jet_engine_mark_end"->c.marking=false;
    case "jet_engine_trigger"->{if(c.triggering)return;c.marking=false;if(c.local)c.shown=!ABORTED.getOrDefault(skill,false);c.triggering=true;c.target=vec(t,"tx","ty","tz");c.triggerAt=CLOCK.elapsed();}
    case "jet_engine_step"->{if(!c.triggering||!c.steps.accept(t.getInt("index")))return;c.flightTicks=t.getInt("index");}
    case "electron_missile_ball"->{int i=t.getInt("index");if(c.ballIndices.get(i)||c.balls.size()>=5)return;c.ballIndices.set(i);c.balls.put(i,new Ball(vec(t,"offset_x","offset_y","offset_z"),CLOCK.elapsed()));}
    case "electron_missile_ray"->{int i=t.getInt("index"),ball=t.getInt("ball");if(!c.attacks.accept(i))return;c.balls.remove(ball);addRay(c,t,SMALL,null);}
    case "electron_missile_update"->{if(!c.shown||!c.updates.accept(t.getInt("index")))return;for(int i=0,n=missileParticleCount(RANDOM);i<n;i++)addParticle(v(missileParticle(p(c.caster.position()),random(.5,1),random(0,Math.PI*2),random(-1.2,0))),new Vec3(random(-.02,.02),random(.01,.05),random(-.02,.02)),false);}
    default->{}
   }
  });}
 private static String skill(String kind){return switch(kind){case "ray_barrage_start","ray_barrage_scatter","ray_barrage_preray","ray_barrage_end"->BARRAGE;case "jet_engine_start","jet_engine_mark_end","jet_engine_trigger","jet_engine_step","jet_engine_end"->JET;case "electron_missile_start","electron_missile_ball","electron_missile_ray","electron_missile_update","electron_missile_end"->MISSILE;default->null;};}
 private static void addRay(Context c,CompoundTag t,Spec spec,List<Vec3> dirs){if(RAYS.size()>=256)return;var ray=new Ray(c,vec(t,"x","y","z"),dirs==null?List.of(vec(t,"dx","dy","dz").normalize()):dirs,t.getDouble("length"),spec,CLOCK.elapsed());RAYS.add(ray);sound(ray,spec==PRE_HIT||spec==PRE_PLAIN?.8F:.5F);}
 private static void sound(Ray r,float volume){if(SOUNDS.size()>=128)return;var sound=new RaySound(r,volume);SOUNDS.add(sound);Minecraft.getInstance().getSoundManager().play(sound);}
 public static void clear(){epoch++;clearOwned();}
 private static void clearOwned(){Minecraft mc=Minecraft.getInstance();for(var m:CONTEXTS.values()){for(var c:m.values())c.hide();m.clear();}for(var t:TOKENS.values())t.clear();for(var i:INPUTS.values())i.clear();NONCES.clear();ABORTED.clear();for(var sound:SOUNDS){sound.finish();mc.getSoundManager().stop(sound);}SOUNDS.clear();RAYS.clear();PARTICLES.clear();CLOCK.clear();}
 private static void sync(Minecraft mc){if(activeLevel==mc.level&&activePlayer==mc.player&&activeConnection==mc.getConnection())return;epoch++;clearOwned();activeLevel=mc.level;activePlayer=mc.player;activeConnection=mc.getConnection();}
 private static void clock(Minecraft mc){CLOCK.update(Util.getMillis(),mc.level!=null&&!mc.isPaused());}
 private static boolean valid(Minecraft mc,Entity e){return e instanceof Player&&e.level()==mc.level&&!e.isRemoved()&&e.isAlive()&&!e.isSpectator()&&mc.level.getEntity(e.getId())==e;}
 @SubscribeEvent public static void tick(ClientTickEvent.Post e){Minecraft mc=Minecraft.getInstance();sync(mc);clock(mc);if(mc.level==null||mc.player==null)return;if(!mc.player.isAlive()){clear();return;}SOUNDS.removeIf(s->!mc.getSoundManager().isActive(s));if(mc.isPaused())return;PARTICLES.removeIf(part->!part.tick());for(String skill:SKILLS){var iter=CONTEXTS.get(skill).values().iterator();while(iter.hasNext()){Context c=iter.next();if(!c.valid(mc)){iter.remove();TOKENS.get(skill).end(c.key,c.token);c.hide();continue;}if(!c.shown)continue;c.ticks++;if(JET.equals(skill)&&c.triggering){if(c.local)c.caster.getAbilities().setWalkingSpeed(JET_WALK);for(int i=0;i<=10;i++)addParticle(v(jetParticle(p(c.caster.position()),c.local,random(-.3,.3),random(-.3,.3),random(-.3,.3))),new Vec3(random(-.02,.02),random(-.02,.02),random(-.02,.02)),false);}}}
  RAYS.removeIf(ray->{if(!ray.valid(mc))return true;ray.ticks++;if(ray.spec==SMALL){Vec3 at=ray.origin.add(0,ClassicMeltdownerBeamTimeline.RAY_EYE_HEIGHT,0).add(v(ClassicMeltdownerBeamTimeline.entityDirection(point(ray.directions.getFirst()))).scale(random(0,10)));addParticle(at,new Vec3(random(-.015,.015),random(-.015,.015),random(-.015,.015)),false);}return ray.ticks>ray.spec.lifeTicks();});}
 @SubscribeEvent public static void render(RenderLevelStageEvent e){if(e.getStage()!=RenderLevelStageEvent.Stage.AFTER_PARTICLES)return;Minecraft mc=Minecraft.getInstance();sync(mc);clock(mc);if(mc.level==null||mc.player==null||!mc.player.isAlive())return;if(buffers==null)buffers=MultiBufferSource.immediate(new ByteBufferBuilder(65536));PoseStack poses=e.getPoseStack();Vec3 camera=e.getCamera().getPosition();float partial=e.getPartialTick().getGameTimeDeltaPartialTick(false),old[]=RenderSystem.getShaderColor().clone();poses.pushPose();try{RenderSystem.setShaderColor(1,1,1,1);
  for(var c:CONTEXTS.get(JET).values())if(c.shown&&c.valid(mc)){if(c.local&&c.marking)ripple(c,poses,camera);if(c.triggering&&c.ticks>0)diamond(c,poses,camera);}
  for(var c:CONTEXTS.get(MISSILE).values())if(c.shown&&c.valid(mc))for(var ball:c.balls.values())ball(c,ball,e,poses,camera);
  for(var r:RAYS)if(r.valid(mc))ray(r,camera,poses.last().pose());for(var particle:PARTICLES){poses.pushPose();Vec3 at=particle.previous.lerp(particle.position,partial);poses.translate(at.x-camera.x,at.y-camera.y,at.z-camera.z);if(particle.fragment){poses.mulPose(Axis.YP.rotationDegrees(particle.yaw));poses.mulPose(Axis.ZP.rotationDegrees(particle.pitch));}else poses.mulPose(e.getCamera().rotation());quad(Material.type(particle.fragment?FRAGMENT:MD,1,false,false),poses.last().pose(),ClassicMeltdownerStarterTimeline.particleQuad(particle.size),255,255,255,particle.alpha());poses.popPose();}
 }finally{poses.popPose();RenderSystem.setShaderColor(old[0],old[1],old[2],old[3]);}}
 private static void ripple(Context c,PoseStack poses,Vec3 camera){Vec3 eye=c.caster.getEyePosition(),end=eye.add(vec(ClassicMeltdownerStarterTimeline.direction(c.caster.getYHeadRot(),c.caster.getXRot())).scale(12));var hit=c.level.clip(new ClipContext(eye,end,ClipContext.Block.COLLIDER,ClipContext.Fluid.NONE,c.caster));Vec3 at=hit.getType()==HitResult.Type.MISS?end:hit.getLocation();long age=CLOCK.elapsed()-c.created;for(int i=0;i<3;i++){long mod=ripplePhase(age,i);float size=rippleSize(mod);poses.pushPose();poses.translate(at.x-camera.x,at.y-camera.y+rippleHeight(mod),at.z-camera.z);poses.scale(size,1,size);VertexConsumer out=buffers.getBuffer(Material.type(RIPPLE,0,false,true));Matrix4f m=poses.last().pose();vertex(out,m,new Vec3(-.5,0,-.5),0,0,51,255,51,.7*rippleAlpha(mod));vertex(out,m,new Vec3(.5,0,-.5),0,1,51,255,51,.7*rippleAlpha(mod));vertex(out,m,new Vec3(.5,0,.5),1,1,51,255,51,.7*rippleAlpha(mod));vertex(out,m,new Vec3(-.5,0,.5),1,0,51,255,51,.7*rippleAlpha(mod));buffers.endBatch(Material.type(RIPPLE,0,false,true));poses.popPose();}}
 private static void diamond(Context c,PoseStack poses,Vec3 camera){var point=ClassicMeltdownerStarterTimeline.shieldPosition(p(c.caster.position()),c.caster.getEyeHeight(),c.caster.getYHeadRot(),c.caster.getXRot(),c.local);poses.pushPose();poses.translate(point.x()-camera.x,point.y()-camera.y,point.z()-camera.z);poses.mulPose(Axis.YP.rotationDegrees(-c.caster.getYHeadRot()));poses.mulPose(Axis.XP.rotationDegrees(c.caster.getXRot()));poses.scale(DIAMOND_SCALE,DIAMOND_SCALE,DIAMOND_SCALE);RenderType type=Material.type(DIAMOND,0,false,true);VertexConsumer out=buffers.getBuffer(type);Matrix4f m=poses.last().pose();for(int i=0;i<DIAMOND_TRIANGLES.length;i+=3){for(int j:new int[]{0,1,2,2}){int k=DIAMOND_TRIANGLES[i+j];double[] at=DIAMOND_VERTICES[k],uv=DIAMOND_UVS[k];vertex(out,m,new Vec3(at[0],at[1],at[2]),(float)uv[0],(float)uv[1],255,255,255,1);}}buffers.endBatch(type);poses.popPose();}
 private static void ball(Context c,Ball b,RenderLevelStageEvent e,PoseStack poses,Vec3 camera){long age=CLOCK.elapsed()-b.created;b.wiggle.frame(CLOCK.elapsed()+1,b.random,RANDOM);Vec3 at=c.caster.position().add(vec(ClassicMeltdownerStarterTimeline.modernBallOffset(p(b.offset),c.local))).add(vec(ClassicMeltdownerStarterTimeline.ballJitter(age)));double alpha=ClassicMeltdownerStarterTimeline.ballAlpha(2333333,age);float size=ClassicMeltdownerStarterTimeline.ballSize(2333333,age);poses.pushPose();poses.translate(at.x-camera.x,at.y-camera.y,at.z-camera.z);poses.mulPose(e.getCamera().rotation());quad(Material.type(BALL_GLOW,0,false,false),poses.last().pose(),ClassicMeltdownerStarterTimeline.billboard(.7F*size,false),255,255,255,alpha*(.3+.7*b.wiggle.alpha));quad(Material.type(BALL_TEXTURES[b.wiggle.texture],0,false,false),poses.last().pose(),ClassicMeltdownerStarterTimeline.billboard(.5F*size,false),255,255,255,alpha*(.8+.2*b.wiggle.alpha));poses.popPose();}
 private static void ray(Ray r,Vec3 camera,Matrix4f matrix){long age=CLOCK.elapsed()-r.created;r.wiggle.frame(CLOCK.elapsed()+1,RANDOM);double width=ClassicMeltdownerLateTimeline.width(r.spec,age,r.wiggle.width),length=r.length*ClassicMeltdownerBeamTimeline.lengthScale(r.spec,age),alpha=ClassicMeltdownerBeamTimeline.alpha(r.spec,age),glow=ClassicMeltdownerBeamTimeline.glowAlpha(r.spec,age,r.wiggle.glow);for(Vec3 direction:r.directions){Point origin=point(r.origin.subtract(camera)),raw=point(direction);Glow g;CylinderFrame f;if(r.spec==BARRAGE_RAY){Point dir=ClassicMeltdownerBeamTimeline.entityDirection(raw),end=origin.add(dir.scale(length)),up=origin.cross(dir).normalize();g=new Glow(origin,origin.add(dir.scale(r.spec.glowWidth())),end.subtract(dir.scale(r.spec.glowWidth())),end,up);f=unfixedFrame(origin,dir);}else{
  // All these original entities use world ctor, so getPlayer()==null: ALWAYS third-person ViewOptimize.
  g=ClassicMeltdownerBeamTimeline.glow(origin,raw,length,point(Vec3.ZERO),false,r.spec.glowWidth());f=ClassicMeltdownerBeamTimeline.cylinderFrame(origin,raw,length,false);}
  board(Material.type(RAY_TEXTURES[0],1,false,false),matrix,g.from(),g.mid1(),g.up(),r.spec.glowWidth()*width,glow);board(Material.type(RAY_TEXTURES[1],1,false,false),matrix,g.mid1(),g.mid2(),g.up(),r.spec.glowWidth()*width,glow);board(Material.type(RAY_TEXTURES[2],1,false,false),matrix,g.mid2(),g.to(),g.up(),r.spec.glowWidth()*width,glow);cylinder(f,matrix,length,r.spec.inner()*width,.98,216,248,216,230/255.0*alpha);cylinder(f,matrix,length,r.spec.outer()*width,1,106,242,106,50/255.0*alpha);}}
 private static CylinderFrame unfixedFrame(Point origin,Point direction){double yaw=-Math.PI/2+Math.atan2(direction.x(),direction.z()),pitch=Math.atan2(direction.y(),Math.sqrt(direction.x()*direction.x()+direction.z()*direction.z()));return new CylinderFrame(origin,new Point(Math.cos(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.sin(yaw)*Math.cos(pitch)),new Point(-Math.cos(yaw)*Math.sin(pitch),Math.cos(pitch),Math.sin(yaw)*Math.sin(pitch)),new Point(Math.sin(yaw),0,Math.cos(yaw)));}
 private static void cylinder(CylinderFrame f,Matrix4f m,double length,double radius,double fix,int r,int g,int b,double alpha){RenderType type=Material.type(WHITE,2,true,false);VertexConsumer out=buffers.getBuffer(type);for(var q:ClassicMeltdownerStarterTimeline.cylinder(length,radius,fix))for(var v:List.of(q.a(),q.b(),q.c(),q.d()))vertex(out,m,v(f.apply(v.point())),v.u(),v.v(),r,g,b,alpha);buffers.endBatch(type);}
 private static void board(RenderType t,Matrix4f m,Point from,Point to,Point up,double width,double alpha){Point half=up.scale(width/2);VertexConsumer out=buffers.getBuffer(t);vertex(out,m,v(from.add(half)),0,1,255,255,255,alpha);vertex(out,m,v(from.subtract(half)),0,0,255,255,255,alpha);vertex(out,m,v(to.subtract(half)),1,0,255,255,255,alpha);vertex(out,m,v(to.add(half)),1,1,255,255,255,alpha);buffers.endBatch(t);}
 private static void quad(RenderType type,Matrix4f m,ClassicMeltdownerStarterTimeline.Quad q,int r,int g,int b,double alpha){VertexConsumer out=buffers.getBuffer(type);for(var v:List.of(q.a(),q.b(),q.c(),q.d()))vertex(out,m,vec(v.point()),v.u(),v.v(),r,g,b,alpha);buffers.endBatch(type);}
 private static void vertex(VertexConsumer out,Matrix4f m,Vec3 p,float u,float v,int r,int g,int b,double alpha){out.addVertex(m,(float)p.x,(float)p.y,(float)p.z).setUv(u,v).setColor(r,g,b,Mth.clamp((int)Math.round(alpha*255),0,255));}
 public static void fragments(Vec3 at){Minecraft mc=Minecraft.getInstance();sync(mc);if(mc.level==null)return;int count=18+RANDOM.nextInt(27-18);for(int i=0;i<count&&PARTICLES.size()<4096;i++){double speed=random(.08,.18),sq=speed*speed,x=RANDOM.nextDouble()*speed,y=RANDOM.nextDouble()*Math.sqrt(sq-x*x),z=Math.sqrt(Math.max(0,sq-x*x-y*y));x*=RANDOM.nextBoolean()?1:-1;y*=RANDOM.nextBoolean()?1:-1;z*=RANDOM.nextBoolean()?1:-1;PARTICLES.add(new Particle(at,new Vec3(x,y+.2,z),true));}}
 private static void addParticle(Vec3 p,Vec3 v,boolean fragment){if(PARTICLES.size()<4096)PARTICLES.add(new Particle(p,v,fragment));}
 private static final class Particle{Vec3 position,previous,velocity;final boolean fragment;final int life;final double opacity;final float size;float yaw,pitch;int age;Particle(Vec3 p,Vec3 v,boolean f){position=previous=p;velocity=v;fragment=f;life=f?10000000:25+RANDOM.nextInt(30);opacity=f?1:random(.3,.6);size=f?.1F:.05F+RANDOM.nextFloat()*(.07F-.05F);if(f){yaw=RANDOM.nextFloat()*360;pitch=-90+RANDOM.nextFloat()*180;}}boolean tick(){age++;previous=position;position=position.add(velocity);if(fragment){velocity=velocity.add(0,-.03,0);yaw+=FRAGMENT_YAW_RATE;pitch+=FRAGMENT_PITCH_RATE;}return fragment?age<=life:ClassicMeltdownerStarterTimeline.particleAlive(age,life);}double alpha(){return opacity*(fragment?Math.min(1,age/5.0):ClassicMeltdownerStarterTimeline.particleAlpha(age,life));}}
 private static final class Ball{final Vec3 offset;final long created;final Random random=new Random();final ClassicMeltdownerStarterTimeline.BallWiggle wiggle=new ClassicMeltdownerStarterTimeline.BallWiggle();Ball(Vec3 p,long c){offset=p;created=c;}}
 private static final class Context{final Player caster;final String skill;final ClientLevel level;final Object connection;final Caster key;final long token,nonce,created;final boolean local;boolean shown,marking,triggering,preRay,scatter;int ticks,flightTicks;long triggerAt;Vec3 target;final BitSet ballIndices=new BitSet(21);final Map<Integer,Ball> balls=new LinkedHashMap<>();final ParticleSequence updates=new ParticleSequence(),attacks=new ParticleSequence(),steps=new ParticleSequence();Context(Player p,String s,ClientLevel l,Object con,long t,long n,boolean show,boolean local){caster=p;skill=s;level=l;connection=con;key=new Caster(p.getId(),p.getUUID());token=t;nonce=n;created=CLOCK.elapsed();shown=show;this.local=local;marking=JET.equals(s);}boolean valid(Minecraft mc){return level==mc.level&&connection==mc.getConnection()&&ClassicMeltdownerLateEffects.valid(mc,caster)&&key.uuid().equals(caster.getUUID());}void hide(){if(local&&triggering&&shown)caster.getAbilities().setWalkingSpeed(RESTORE_WALK);shown=marking=false;balls.clear();}}
 private static final class Ray{final Player caster;final UUID uuid;final ClientLevel level;final Object connection;final Vec3 origin;final List<Vec3> directions;final double length;final Spec spec;final long created;int ticks;final ClassicMeltdownerStarterTimeline.RayWiggle wiggle=new ClassicMeltdownerStarterTimeline.RayWiggle();Ray(Context c,Vec3 p,List<Vec3> d,double len,Spec s,long time){caster=c.caster;uuid=c.key.uuid();level=c.level;connection=c.connection;origin=p;directions=List.copyOf(d);length=len;spec=s;created=time;}boolean valid(Minecraft mc){return level==mc.level&&connection==mc.getConnection()&&ClassicMeltdownerLateEffects.valid(mc,caster)&&caster.getUUID().equals(uuid);}}
 private static final class RaySound extends AbstractTickableSoundInstance{final Ray ray;boolean finished;RaySound(Ray ray,float volume){super(SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("academy",RAY_SOUND)),SoundSource.MASTER,RandomSource.create());this.ray=ray;this.volume=volume;pitch=1;looping=false;x=ray.origin.x;y=ray.origin.y;z=ray.origin.z;}void finish(){finished=true;stop();}@Override public void tick(){if(finished||!ray.valid(Minecraft.getInstance()))finish();}}
 private static boolean index(CompoundTag t,int a,int b){return t.contains("index",Tag.TAG_INT)&&t.getInt("index")>=a&&t.getInt("index")<=b;}
 private static boolean vectorTags(CompoundTag t,String x,String y,String z){return t.contains(x,Tag.TAG_DOUBLE)&&t.contains(y,Tag.TAG_DOUBLE)&&t.contains(z,Tag.TAG_DOUBLE)&&Double.isFinite(t.getDouble(x))&&Double.isFinite(t.getDouble(y))&&Double.isFinite(t.getDouble(z));}
 private static Vec3 vec(CompoundTag t,String x,String y,String z){return new Vec3(t.getDouble(x),t.getDouble(y),t.getDouble(z));}private static ClassicMeltdownerStarterTimeline.Point p(Vec3 p){return new ClassicMeltdownerStarterTimeline.Point(p.x,p.y,p.z);}private static Vec3 vec(ClassicMeltdownerStarterTimeline.Point p){return new Vec3(p.x(),p.y(),p.z());}private static Point point(Vec3 p){return new Point(p.x,p.y,p.z);}private static Vec3 v(Point p){return new Vec3(p.x(),p.y(),p.z());}private static Vec3 v(ClassicMeltdownerStarterTimeline.Point p){return vec(p);}private static double random(double a,double b){return a+RANDOM.nextDouble()*(b-a);}private static ResourceLocation texture(String p){return ResourceLocation.fromNamespaceAndPath("academy","textures/"+p+".png");}private static ResourceLocation[] seq(String p,int count){ResourceLocation[] a=new ResourceLocation[count];for(int i=0;i<count;i++)a[i]=texture(p+i);return a;}
 private static final class Material extends RenderType{private record Key(ResourceLocation t,int shader,boolean cull,boolean overlay){}private static final Map<Key,RenderType> TYPES=new HashMap<>();private Material(String n,VertexFormat f,VertexFormat.Mode m,int s,boolean cr,boolean sort,Runnable set,Runnable reset){super(n,f,m,s,cr,sort,set,reset);}static RenderType type(ResourceLocation t,int shader,boolean cull,boolean overlay){return TYPES.computeIfAbsent(new Key(t,shader,cull,overlay),key->create("academy_classic_late_"+key.t.getPath()+"_"+shader+"_"+cull+"_"+overlay,DefaultVertexFormat.POSITION_TEX_COLOR,VertexFormat.Mode.QUADS,4096,false,false,CompositeState.builder().setShaderState(new ShaderStateShard(shader==2?GameRenderer::getPositionTexColorShader:shader==1?ClassicMeltdownerStarterEffects.CutoffShader::get:ClassicMeltdownerStarterEffects.CutoffShader::zero)).setTextureState(new TextureStateShard(t,false,false)).setTransparencyState(TRANSLUCENT_TRANSPARENCY).setCullState(cull?CULL:NO_CULL).setDepthTestState(overlay?NO_DEPTH_TEST:LEQUAL_DEPTH_TEST).setWriteMaskState(overlay?COLOR_WRITE:COLOR_DEPTH_WRITE).setLightmapState(NO_LIGHTMAP).setOverlayState(NO_OVERLAY).setOutputState(PARTICLES_TARGET).createCompositeState(false)));}}
}
