/* AcademyCraft1.0.7 loctele_new.xml/LocationTeleport.Gui adaptation. GPLv3; see NOTICE. */
package cn.academy.port.client;
import net.minecraft.Util;
import cn.academy.port.ClassicHudConfig;
import net.minecraft.client.gui.*;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.nbt.*;
import net.minecraft.network.chat.Component;
import java.util.*;
/** Original .24-scale palette/layout/fades and native text editing; authoritative rows contain server CP/stat. */
public final class ClassicLocationTeleportScreen extends Screen {
 private final long nonce;private List<CompoundTag> locations=List.of();private CompoundTag snapshot;private long opened,listUpdated;private EditBox input;private int scroll;private boolean closing;private final ClassicHudFont font=new ClassicHudFont();
 public ClassicLocationTeleportScreen(long nonce,CompoundTag t){super(Component.translatable("ac.ability.teleporter.location_teleport.name"));this.nonce=nonce;update(t);opened=Util.getMillis();}public boolean matches(long n){return n==nonce;}public void update(CompoundTag t){snapshot=t.copy();var list=t.getList("locations",Tag.TAG_COMPOUND);var out=new ArrayList<CompoundTag>();for(int i=0;i<Math.min(256,list.size());i++)out.add(list.getCompound(i).copy());locations=List.copyOf(out);scroll=Math.min(scroll,Math.max(0,locations.size()-5));listUpdated=Util.getMillis();}
 @Override protected void init(){font.use(ClassicHudConfig.SPEC.isLoaded()?ClassicHudConfig.FONT.get():"Microsoft YaHei");int x=(int)(width/2.0+20*.24+45.277*.24),y=(int)(height/2.0-179.166*.24+18*.24+(Math.min(5,locations.size()-scroll))*82*.24+19.698*.24);String previous=input==null?"":input.getValue();input=new EditBox(minecraft.font,x,y,67,13,Component.literal("Add..."));input.setMaxLength(16);input.setBordered(false);input.setTextColor(0xffa4d4e9);input.setValue(previous);addRenderableWidget(input);}
 private void send(String action,String body){AcademyClient.request(action,nonce+":"+body);}private void add(){send("location_add",input.getValue());input.setValue("");}
 private static double blend(double age,double offset,double length){return Math.max(0,Math.min(1,(age-offset)/length));}
 private static ClassicHudTimeline.Rgba color(double r,double g,double b,double a){return new ClassicHudTimeline.Rgba(r,g,b,a);}private void panel(ClassicHudCanvas c,double x,double y,double w,double h){c.fill(x,y,w,h,color(53/255.0,53/255.0,53/255.0,128/255.0),false);var line=color(122/255.0,146/255.0,156/255.0,.62);c.fill(x,y,w,2,line,false);c.fill(x,y+h-2,w,2,line,false);c.fill(x,y,2,h,line,false);c.fill(x+w-2,y,2,h,line,false);}
 @Override public void render(GuiGraphics g,int mouseX,int mouseY,float partial){double x0=width/2.0+20*.24,y0=height/2.0-179.166*.24,age=(Util.getMillis()-listUpdated)/1000.0,mx=(mouseX-x0)/.24,my=(mouseY-y0)/.24;int visible=Math.min(5,locations.size()-scroll);g.pose().pushPose();g.pose().translate(x0,y0,0);g.pose().scale(.24F,.24F,1);var canvas=new ClassicHudCanvas(g);canvas.begin();try{panel(canvas,0,0,442,530*blend((Util.getMillis()-opened)/1000.0,0,.4));List<String> info=List.of();double iy=0;
  for(int row=0;row<visible;row++){var l=locations.get(scroll+row);double y=18+row*82;boolean hover=mx>=0&&mx<442&&my>=y&&my<y+80;double a=blend(age,row*.06,.2)*(hover?.4:.1);canvas.fill(0,y,442,80,color(1,1,1,a),false);font.draw(canvas,l.getString("name"),45.277,y+16.126,43,color(l.getString("error").isEmpty()?193/255.0:162/255.0,l.getString("error").isEmpty()?207/255.0:162/255.0,l.getString("error").isEmpty()?213/255.0:162/255.0,blend(age,row*.06+.1,.1)),false,false);if(l.getString("error").isEmpty())icon(canvas,"guis/icons/icon_location_on",335,y+29.916,blend(age,row*.06+.03,.1)*(inside(mx,my,335,y+29.916,33.333,33.333)?1:.7));icon(canvas,"guis/icons/icon_clear",375,y+29.916,blend(age,row*.06+.05,.1)*(inside(mx,my,375,y+29.916,33.333,33.333)?1:.7));if(hover){var texts=new ArrayList<String>();texts.add(l.getString("dimension"));texts.add(String.format(Locale.ROOT,"(%.0f, %.0f, %.0f)",l.getFloat("x"),l.getFloat("y"),l.getFloat("z")));texts.add(String.format(Locale.ROOT,"%.0f CP",l.getFloat("cp")));if(!l.getString("error").isEmpty())texts.add(Component.translatable("ac.gui.loctele."+l.getString("error")).getString());info=texts;iy=y;}}
  double addY=18+visible*82;boolean addHover=mx>=0&&mx<442&&my>=addY&&my<addY+80;canvas.fill(0,addY,442,80,color(1,1,1,blend(age,visible*.06,.2)*(addHover?.4:.1)),false);if(input.getValue().isEmpty()&&!input.isFocused())font.draw(canvas,"Add...",45.277,addY+19.698,43,color(164/255.0,212/255.0,233/255.0,.4*blend(age,visible*.06,.1)),false,false);icon(canvas,"guis/check",375.833,addY+29.916,blend(age,visible*.06,.1)*(inside(mx,my,375.833,addY+29.916,33.333,33.333)?1:.7));if(addHover){info=List.of(snapshot.getString("dimension"),String.format(Locale.ROOT,"(%.0f, %.0f, %.0f)",snapshot.getFloat("x"),snapshot.getFloat("y"),snapshot.getFloat("z")));iy=addY;}
  if(!info.isEmpty()){double wide=40;for(String s:info)wide=Math.max(wide,font.width(s,40,false)+40);double ix=-43.333-wide;panel(canvas,ix,iy,wide,info.size()*42+40);for(int i=0;i<info.size();i++){String s=info.get(i);font.draw(canvas,s,ix+wide-20-font.width(s,40,false),iy+20+i*42,40,color(193/255.0,207/255.0,213/255.0,1),false,false);}}
 }finally{canvas.end();g.pose().popPose();}input.setX((int)(x0+45.277*.24));input.setY((int)(y0+(18+visible*82+19.698)*.24));input.render(g,mouseX,mouseY,partial);}
 private static boolean inside(double x,double y,double left,double top,double w,double h){return x>=left&&x<left+w&&y>=top&&y<top+h;}
 private static void icon(ClassicHudCanvas c,String path,double x,double y,double alpha){c.rect(ClassicHudCanvas.texture(path),x,y,33.333,33.333,color(193/255.0,207/255.0,213/255.0,alpha));}
 @Override public boolean mouseClicked(double x,double y,int button){if(button==0){double mx=(x-width/2.0-20*.24)/.24,my=(y-height/2.0+179.166*.24)/.24;int visible=Math.min(5,locations.size()-scroll);for(int row=0;row<visible;row++){double ry=18+row*82;if(my>=ry&&my<ry+80){var l=locations.get(scroll+row);if(mx>=335&&mx<368.333&&my>=ry+29.916&&my<ry+63.249&&l.getString("error").isEmpty()){closing=true;send("location_perform",Integer.toString(l.getInt("id")));minecraft.setScreen(null);return true;}if(mx>=375&&mx<408.333&&my>=ry+29.916&&my<ry+63.249){send("location_remove",Integer.toString(l.getInt("id")));return true;}}}if(my>=18+visible*82&&my<98+visible*82){if(mx>=375.833&&mx<409.166&&my>=47.916+visible*82&&my<81.249+visible*82){add();return true;}if(mx>=0&&mx<442){setFocused(input);input.setFocused(true);return true;}}}return super.mouseClicked(x,y,button);}
 @Override public boolean keyPressed(int key,int scan,int mods){if((key==257||key==335)&&input.isFocused()){add();return true;}return super.keyPressed(key,scan,mods);}@Override public boolean mouseScrolled(double x,double y,double sx,double sy){scroll=Math.max(0,Math.min(Math.max(0,locations.size()-5),scroll-(int)Math.signum(sy)));return true;}
 @Override public boolean isPauseScreen(){return false;}@Override public void removed(){font.release();if(!closing)send("location_close","");ClassicTeleporterFinalEffects.hideLocal("location_teleport");}public void closeFromServer(){closing=true;minecraft.setScreen(null);}
}
