/* AcademyCraft1.0.7 PTContextC/MTContextC/FRContextC client adapters. GPLv3; see NOTICE. */
package cn.academy.port.client;
import cn.academy.port.skill.*;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.*;
import com.mojang.math.Axis;
import net.minecraft.Util;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.renderer.*;
import net.minecraft.client.resources.sounds.AbstractTickableSoundInstance;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.*;
import net.minecraft.util.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.phys.*;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.*;
import net.neoforged.neoforge.common.NeoForge;
import org.joml.Matrix4f;
import java.util.*;
import static cn.academy.port.skill.TeleporterProgressionRules.*;
/** Cosmetic-only adapter: no inventory/resource/damage/movement mutation, and no client endpoint upload.
 * The destination biped and red target corners are local-only in both first/third person, like classic. */
@EventBusSubscriber(modid="academy",value=Dist.CLIENT)
public final class ClassicTeleporterProgressionEffects {
 private static final Set<String> IDS=Set.of(PENETRATE,MARK,FLESH);private static final Map<String,Long> NONCES=new HashMap<>();private static final Map<String,Boolean> SHOW=new HashMap<>();private static final Map<String,Map<UUID,Context>> CONTEXTS=new HashMap<>();private static final Map<String,Map<UUID,Long>> CLOSED=new HashMap<>();private static final List<Particle> PARTICLES=new ArrayList<>();private static final List<Splash> BLOOD=new ArrayList<>();private static final List<FollowSound> SOUNDS=new ArrayList<>();private static final Random RANDOM=new Random();private static long nextNonce;
 private static final ResourceLocation TP_PARTICLE=texture("effects/tp_particle");private static final ResourceLocation[] MARK_TEXTURES=seq("effects/tp_mark/",7),BLOOD_TEXTURES=seq("effects/blood_splash/",10);
 private static ClientLevel activeLevel;private static Player activePlayer;private static Object activeConnection;private static volatile long epoch;private static MultiBufferSource.BufferSource buffers;
 static{for(String id:IDS){CONTEXTS.put(id,new HashMap<>());CLOSED.put(id,new HashMap<>());}}private ClassicTeleporterProgressionEffects(){}
 public static boolean owns(String id){return IDS.contains(id);}public static long startLocal(String id){if(!owns(id))return 0;sync(Minecraft.getInstance());long nonce=++nextNonce;NONCES.put(id,nonce);SHOW.put(id,true);return nonce;}public static long localNonce(String id){return NONCES.getOrDefault(id,0L);}public static void endLocal(String id){if(owns(id))SHOW.put(id,false);}public static boolean delegateActive(String id){return owns(id)&&SHOW.getOrDefault(id,false);}
 public static void receive(CompoundTag raw){if(raw==null)return;var t=raw.copy();String kind=t.getString("kind"),id=kind.endsWith("_start")?kind.substring(0,kind.length()-6):kind.endsWith("_end")?kind.substring(0,kind.length()-4):"";if(!owns(id)||!t.contains("entity",Tag.TAG_INT)||!t.hasUUID("entity_uuid")||!t.contains("token",Tag.TAG_LONG)||t.getLong("token")<=0||!t.contains("input",Tag.TAG_LONG)||t.getLong("input")<0||!t.contains("exp",Tag.TAG_DOUBLE)||!Double.isFinite(t.getDouble("exp"))||t.getDouble("exp")<0||t.getDouble("exp")>1)return;
  Minecraft mc=Minecraft.getInstance();ClientLevel level=mc.level;Player local=mc.player;Object connection=mc.getConnection();long generation=epoch;mc.execute(()->{if(level==null||local==null||level!=mc.level||local!=mc.player||connection!=mc.getConnection()||generation!=epoch)return;sync(mc);Entity caster=level.getEntity(t.getInt("entity"));UUID uuid=t.getUUID("entity_uuid");if(!(caster instanceof Player player)||!uuid.equals(caster.getUUID()))return;boolean isLocal=caster==local;long token=t.getLong("token"),nonce=t.getLong("input");if(isLocal&&nonce!=localNonce(id))return;var contexts=CONTEXTS.get(id);var closed=CLOSED.get(id);Context c=contexts.get(uuid);if(token<=closed.getOrDefault(uuid,0L)||c!=null&&token<c.token)return;
   if(kind.endsWith("_start")){if(c!=null&&token==c.token)return;if(contexts.size()>=128&&!contexts.containsKey(uuid))return;contexts.put(uuid,new Context(player,id,token,nonce,t.getDouble("exp"),level,connection,isLocal));if(isLocal)AcademyClient.acceptedSingleStart(id,nonce,token);return;}
   if(c!=null&&(c.token!=token||c.nonce!=nonce))return;contexts.remove(uuid);if(closed.size()>=256&&!closed.containsKey(uuid))closed.clear();closed.put(uuid,token);if(isLocal)AcademyClient.acceptedSingleEnd(id,nonce,token);if(isLocal)SHOW.put(id,false);
   if(PENETRATE.equals(id)||MARK.equals(id)&&t.getBoolean("success"))sound(player,"tp.tp",.5F);
   if(FLESH.equals(id)&&t.getBoolean("success")&&t.contains("target",Tag.TAG_INT)&&t.hasUUID("target_uuid")){Entity target=level.getEntity(t.getInt("target"));if(target==null||!target.getUUID().equals(t.getUUID("target_uuid")))return;sound(player,"tp.guts",.6F);int count=ClassicTeleporterTimeline.bloodCount(4+RANDOM.nextInt(2));for(int i=0;i<count&&BLOOD.size()<512;i++){double theta=random(0,Math.PI*2),r=.5*random(.8*target.getBbWidth(),target.getBbWidth());Vec3 at=target.position().add(r*Math.sin(theta),random(0,target.getBbHeight()),r*Math.cos(theta));
    // Modern remote player position is already feet; legacy ACRenderingHelper+1.6 compensated old renderer anchoring.
    BLOOD.add(new Splash(at,.8F+RANDOM.nextFloat()*.5F));}int tier=t.getInt("critical_tier");if(tier>=0&&tier<=2&&player==local)NeoForge.EVENT_BUS.post(new ClassicFirstSkillEffects.TeleporterCriticalHitEvent(player,target,tier));}
  });}
 @SubscribeEvent public static void tick(ClientTickEvent.Post e){Minecraft mc=Minecraft.getInstance();sync(mc);if(mc.level==null||mc.isPaused())return;PARTICLES.removeIf(p->!p.tick());BLOOD.removeIf(s->!ClassicTeleporterTimeline.bloodAlive(++s.age));SOUNDS.removeIf(s->s.isStopped());for(String id:IDS){var all=CONTEXTS.get(id);all.values().removeIf(c->!c.valid(mc));for(Context c:all.values()){if(!c.local||!SHOW.getOrDefault(id,false))continue;c.ticks++;double exp=AcademyClient.state.exp(id),cp=AcademyClient.state.cp;Vec3 eye=c.caster.getEyePosition(),direction=new Vec3(TeleporterProgressionRules.direction(c.caster.getYHeadRot(),c.caster.getXRot()).x(),TeleporterProgressionRules.direction(c.caster.getYHeadRot(),c.caster.getXRot()).y(),TeleporterProgressionRules.direction(c.caster.getYHeadRot(),c.caster.getXRot()).z());
  if(PENETRATE.equals(id)){var d=PenetrateTeleport.destination(c.level,eye,direction,exp,cp);c.position=new Vec3(d.position().x(),d.position().y(),d.position().z());c.available=d.available();}else if(MARK.equals(id)){c.position=MarkTeleport.destination(c.caster,exp,cp,c.ticks);c.available=true;}else{var target=FleshRipping.target(c.caster,c.exp);c.target=target instanceof EntityHitResult h?h.getEntity():null;c.position=target.getType()==HitResult.Type.MISS?eye.add(direction.scale(fleshRange(c.exp))):target.getLocation();}
  if(!FLESH.equals(id)&&c.available&&RANDOM.nextDouble()<.4&&PARTICLES.size()<2048)PARTICLES.add(new Particle(c.position.add(random(-1,1),random(.2,1.6)-1.6,random(-1,1)),new Vec3(random(-.03,.03),random(0,.05),random(-.03,.03)),.1F+RANDOM.nextFloat()*.1F,random(.6,.8)));}}
 }
 @SubscribeEvent public static void render(RenderLevelStageEvent e){if(e.getStage()!=RenderLevelStageEvent.Stage.AFTER_PARTICLES)return;Minecraft mc=Minecraft.getInstance();sync(mc);if(mc.level==null)return;if(buffers==null)buffers=MultiBufferSource.immediate(new ByteBufferBuilder(65536));PoseStack poses=e.getPoseStack();Vec3 camera=e.getCamera().getPosition();float partial=e.getPartialTick().getGameTimeDeltaPartialTick(false);float[] shaderColor=RenderSystem.getShaderColor().clone();poses.pushPose();try{RenderSystem.setShaderColor(1,1,1,1);poses.translate(-camera.x,-camera.y,-camera.z);
  for(String id:IDS)for(Context c:CONTEXTS.get(id).values())if(c.local&&c.valid(mc)&&SHOW.getOrDefault(id,false)&&c.ticks>0){if(FLESH.equals(id))corners(c,poses);else biped(c,poses);}
  for(Particle p:PARTICLES){poses.pushPose();Vec3 at=p.previous.lerp(p.position,partial);poses.translate(at.x,at.y,at.z);poses.mulPose(e.getCamera().rotation());billboard(Material.type(TP_PARTICLE,false,true),poses.last().pose(),p.size,255,255,255,p.alpha*ClassicTeleporterTimeline.particleAlpha(p.age));poses.popPose();}
  for(Splash s:BLOOD){poses.pushPose();poses.translate(s.position.x,s.position.y,s.position.z);poses.mulPose(e.getCamera().rotation());billboard(Material.type(BLOOD_TEXTURES[ClassicTeleporterTimeline.bloodFrame(s.age)],false,false),poses.last().pose(),s.size,213,29,29,200/255.0);poses.popPose();}
 }finally{poses.popPose();RenderSystem.setShaderColor(shaderColor[0],shaderColor[1],shaderColor[2],shaderColor[3]);}}
 private static void biped(Context c,PoseStack poses){poses.pushPose();poses.translate(c.position.x,c.position.y,c.position.z);poses.mulPose(Axis.YP.rotationDegrees(-c.caster.getYRot()));poses.scale(-.0625F,-.0625F,.0625F);RenderType type=Material.type(MARK_TEXTURES[ClassicTeleporterTimeline.markFrame(c.ticks)],true,false);VertexConsumer out=buffers.getBuffer(type);for(var box:ClassicTeleporterTimeline.BIPED)for(var quad:ClassicTeleporterTimeline.mesh(box))for(var v:List.of(quad.a(),quad.b(),quad.c(),quad.d()))vertex(out,poses.last().pose(),new Vec3(v.x(),v.y(),v.z()),v.u(),v.v(),255,c.available?255:51,c.available?255:51,1);buffers.endBatch(type);poses.popPose();}
 private static void corners(Context c,PoseStack poses){double width=c.target==null?1:c.target.getBbWidth()*1.2F,height=c.target==null?1:c.target.getBbHeight()*1.2F;Vec3 at=c.position.add(-width/2,ClassicTeleporterTimeline.markerBob(Util.getMillis()),-width/2);int r=c.target==null?74:185,g=c.target==null?74:25,b=g,alpha=c.target==null?160:180;VertexConsumer out=buffers.getBuffer(Material.CORNERS);double length=.2*width;for(int i=0;i<8;i++){int corner=i%4;Vec3 start=at.add(corner==1||corner==2?width:0,i>=4?height:0,corner>=2?width:0);double yaw=-Math.PI/2*corner;line(out,poses.last(),start,start.add(0,i<4?length:-length,0),r,g,b,alpha);line(out,poses.last(),start,start.add(length*Math.cos(yaw),0,-length*Math.sin(yaw)),r,g,b,alpha);line(out,poses.last(),start,start.add(length*Math.sin(yaw),0,length*Math.cos(yaw)),r,g,b,alpha);}buffers.endBatch(Material.CORNERS);}
 private static void line(VertexConsumer out,PoseStack.Pose p,Vec3 a,Vec3 b,int r,int g,int blue,int alpha){Vec3 normal=b.subtract(a).normalize();for(Vec3 v:List.of(a,b))out.addVertex(p.pose(),(float)v.x,(float)v.y,(float)v.z).setColor(r,g,blue,alpha).setNormal(p,(float)normal.x,(float)normal.y,(float)normal.z);}
 private static void billboard(RenderType type,Matrix4f m,float size,int r,int g,int b,double alpha){VertexConsumer out=buffers.getBuffer(type);vertex(out,m,new Vec3(-size/2,-size*.25,0),0,1,r,g,b,alpha);vertex(out,m,new Vec3(size/2,-size*.25,0),1,1,r,g,b,alpha);vertex(out,m,new Vec3(size/2,size*.75,0),1,0,r,g,b,alpha);vertex(out,m,new Vec3(-size/2,size*.75,0),0,0,r,g,b,alpha);buffers.endBatch(type);}
 private static void vertex(VertexConsumer out,Matrix4f m,Vec3 v,float u,float texV,int r,int g,int b,double alpha){out.addVertex(m,(float)v.x,(float)v.y,(float)v.z).setUv(u,texV).setColor(r,g,b,Mth.clamp((int)Math.round(alpha*255),0,255));}
 private static final class Context{final Player caster;final String id;final UUID uuid;final int entity;final long token,nonce;final double exp;final ClientLevel level;final Object connection;final boolean local;int ticks;Vec3 position;Entity target;boolean available=true;Context(Player p,String id,long token,long nonce,double exp,ClientLevel level,Object connection,boolean local){caster=p;this.id=id;uuid=p.getUUID();entity=p.getId();this.token=token;this.nonce=nonce;this.exp=exp;this.level=level;this.connection=connection;this.local=local;position=p.position();}boolean valid(Minecraft mc){return level==mc.level&&connection==mc.getConnection()&&caster.isAlive()&&!caster.isRemoved()&&level.getEntity(entity)==caster&&uuid.equals(caster.getUUID());}}
 private static final class Particle{Vec3 previous,position;final Vec3 velocity;final float size;final double alpha;int age;Particle(Vec3 p,Vec3 v,float size,double alpha){previous=position=p;velocity=v;this.size=size;this.alpha=alpha;}boolean tick(){previous=position;position=position.add(velocity);return ClassicTeleporterTimeline.particleAlive(++age);}}
 private static final class Splash{final Vec3 position;final float size;int age;Splash(Vec3 p,float s){position=p;size=s;}}
 private static void sound(Entity p,String id,float volume){var s=new FollowSound(p,id,volume);SOUNDS.add(s);Minecraft.getInstance().getSoundManager().play(s);}private static final class FollowSound extends AbstractTickableSoundInstance{final Entity caster;final ClientLevel level;FollowSound(Entity p,String id,float volume){super(SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("academy",id)),SoundSource.MASTER,RandomSource.create());caster=p;level=Minecraft.getInstance().level;this.volume=volume;pitch=1;tick();}public void tick(){if(caster.isRemoved()||Minecraft.getInstance().level!=level){stop();return;}x=caster.getX();y=caster.getY();z=caster.getZ();}void finish(){stop();}}
 private static void sync(Minecraft mc){if(activeLevel==mc.level&&activePlayer==mc.player&&activeConnection==mc.getConnection())return;clear();activeLevel=mc.level;activePlayer=mc.player;activeConnection=mc.getConnection();}
 public static void clear(){for(String id:IDS){CONTEXTS.get(id).clear();CLOSED.get(id).clear();}NONCES.clear();SHOW.clear();PARTICLES.clear();BLOOD.clear();for(var s:SOUNDS)s.finish();SOUNDS.clear();epoch++;}
 private static double random(double a,double b){return a+RANDOM.nextDouble()*(b-a);}private static ResourceLocation texture(String p){return ResourceLocation.fromNamespaceAndPath("academy","textures/"+p+".png");}private static ResourceLocation[] seq(String p,int count){ResourceLocation[] a=new ResourceLocation[count];for(int i=0;i<count;i++)a[i]=texture(p+i);return a;}
 private static final class Material extends RenderType{private record Key(ResourceLocation texture,boolean overlay,boolean depthWrite){}private static final Map<Key,RenderType> TYPES=new HashMap<>();private Material(String n,VertexFormat f,VertexFormat.Mode m,int s,boolean c,boolean sort,Runnable set,Runnable reset){super(n,f,m,s,c,sort,set,reset);}static RenderType type(ResourceLocation t,boolean overlay,boolean depthWrite){return TYPES.computeIfAbsent(new Key(t,overlay,depthWrite),k->create("academy_classic_tp_"+k.texture.getPath()+"_"+overlay+"_"+depthWrite,DefaultVertexFormat.POSITION_TEX_COLOR,VertexFormat.Mode.QUADS,4096,false,false,CompositeState.builder().setShaderState(new ShaderStateShard(overlay?ClassicSkillAlphaShader::get:ClassicMeltdownerStarterEffects.CutoffShader::zero)).setTextureState(new TextureStateShard(t,false,false)).setTransparencyState(TRANSLUCENT_TRANSPARENCY).setCullState(NO_CULL).setLightmapState(NO_LIGHTMAP).setOverlayState(NO_OVERLAY).setDepthTestState(overlay?NO_DEPTH_TEST:LEQUAL_DEPTH_TEST).setWriteMaskState(depthWrite?COLOR_DEPTH_WRITE:COLOR_WRITE).setOutputState(PARTICLES_TARGET).createCompositeState(false)));}static final RenderType CORNERS=create("academy_classic_flesh_corners",DefaultVertexFormat.POSITION_COLOR_NORMAL,VertexFormat.Mode.LINES,2048,false,false,CompositeState.builder().setShaderState(new ShaderStateShard(GameRenderer::getRendertypeLinesShader)).setLineState(new LineStateShard(OptionalDouble.of(3))).setTransparencyState(TRANSLUCENT_TRANSPARENCY).setCullState(NO_CULL).setWriteMaskState(COLOR_DEPTH_WRITE).setOutputState(PARTICLES_TARGET).createCompositeState(false));}
}
