/* AcademyCraft1.0.7 VecReflectionContextC/PlasmaCannonContextC effects. GPLv3; see NOTICE. */
package cn.academy.port.client;
import cn.academy.port.skill.PlasmaCannonSession;
import com.mojang.blaze3d.vertex.*;
import com.mojang.math.Axis;
import net.minecraft.Util;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.resources.sounds.AbstractTickableSoundInstance;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.*;
import net.minecraft.util.*;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.level.ClipContext;
import net.minecraft.world.phys.*;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.*;
import org.joml.Matrix4f;
import org.joml.Vector4f;
import java.util.*;
/** Client cosmetics consume bounded server context tokens; no client position or duration is trusted by gameplay. */
@EventBusSubscriber(modid="academy",value=Dist.CLIENT)
public final class ClassicVectorFinalEffects {
 private static final Random RANDOM=new Random();private static final ClassicVectorStarterTimeline.Tokens TOKENS=new ClassicVectorStarterTimeline.Tokens();private static final Map<String,Long> INPUTS=new HashMap<>(),EVENTS=new LinkedHashMap<>();private static final Map<Integer,Plasma> PLASMAS=new LinkedHashMap<>();private static final List<Wave> WAVES=new ArrayList<>();private static final List<Ripple> RIPPLES=new ArrayList<>();private static final ResourceLocation GLOW=ResourceLocation.fromNamespaceAndPath("academy","textures/effects/glow_circle.png");private static ClientLevel level;private static Entity player;private static Object connection;private static boolean reflection,predictedPlasma;private static long nextInput,clock,lastWall=Util.getMillis();private static float lastFrame;private static MultiBufferSource.BufferSource buffers;
 private ClassicVectorFinalEffects(){}
 public static boolean owns(String id){return id.equals("vec_reflection")||id.equals("plasma_cannon");}
 public static long startLocal(String id){var mc=Minecraft.getInstance();synchronize(mc);if(!owns(id)||mc.player==null||mc.level==null)return 0;long input=++nextInput;INPUTS.put(id,input);if(id.equals("vec_reflection")){reflection=!reflection;RIPPLES.clear();lastFrame=clock/1000F;}else predictedPlasma=true;return input;}
 public static void endLocal(String id){if(id.equals("vec_reflection")){reflection=false;RIPPLES.clear();}else if(id.equals("plasma_cannon")){predictedPlasma=false;var mc=Minecraft.getInstance();if(mc.player!=null){var p=PLASMAS.get(mc.player.getId());if(p!=null&&!p.released&&!p.go)p.end();}}}
 /** Ready cannon continues moving after key release, until authoritative termination. Toggle release is empty. */
 public static void releaseLocal(String id){if(id.equals("plasma_cannon")){predictedPlasma=false;var mc=Minecraft.getInstance();var p=mc.player==null?null:PLASMAS.get(mc.player.getId());if(p!=null)p.released=true;}}
 /** Accepted exact local END fences subsequent entity/wave/sound envelopes. */
 public static void terminateContext(long input,long token){var mc=Minecraft.getInstance();if(mc.player==null||input<=0||token<=0)return;TOKENS.end("vec_reflection",mc.player.getId(),token);if(INPUTS.getOrDefault("vec_reflection",0L)==input)endLocal("vec_reflection");}
 public static long localNonce(String id){return INPUTS.getOrDefault(id,0L);}public static boolean active(String id){var mc=Minecraft.getInstance();return id.equals("vec_reflection")?reflection:id.equals("plasma_cannon")&&(predictedPlasma||mc.player!=null&&PLASMAS.containsKey(mc.player.getId())&&!PLASMAS.get(mc.player.getId()).dead&&!PLASMAS.get(mc.player.getId()).released&&!PLASMAS.get(mc.player.getId()).go);}
 public static boolean anyActive(){return active("vec_reflection")||active("plasma_cannon");}public static float consumptionHint(){return 0;} // Source implements IStateProvider only; no IConsumptionProvider hint.
 public static boolean charging(){var mc=Minecraft.getInstance();var p=mc.player==null?null:PLASMAS.get(mc.player.getId());return p!=null&&!p.go&&!p.released&&!p.dead&&p.age<p.charge;}
 public static void receive(CompoundTag data){if(data==null)return;var tag=data.copy();var mc=Minecraft.getInstance();ClientLevel target=mc.level;Entity local=mc.player;Object conn=mc.getConnection();mc.execute(()->{if(target==null||target!=mc.level||local!=mc.player||conn!=mc.getConnection())return;synchronize(mc);advance(mc);String kind=tag.getString("kind"),id=kind.startsWith("vec_reflection")?"vec_reflection":"plasma_cannon";int casterId=tag.getInt("entity");long token=tag.getLong("token"),input=tag.getLong("input");if(token<=0)return;Entity caster=target.getEntity(casterId);boolean mine=caster==mc.player;
  if(kind.endsWith("_start")){if(caster==null||!TOKENS.start(id,casterId,token)||mine&&input>0&&input!=INPUTS.getOrDefault(id,0L))return;if(id.equals("vec_reflection")){if(mine){if(AcademyClient.contextStartCancelled(id,input,token))return;reflection=true;lastFrame=clock/1000F;AcademyClient.acceptedContextStart(id,input,token,true);}}else{Vec3 at=point(tag);float charge=tag.getFloat("charge");if(!finite(at)||!Float.isFinite(charge)||charge<30||charge>60||PLASMAS.size()>=128)return;var old=PLASMAS.remove(casterId);if(old!=null)old.close();var p=new Plasma(caster,token,at,charge);PLASMAS.put(casterId,p);mc.getSoundManager().play(p.sound);if(mine){predictedPlasma=false;AcademyClient.acceptedSingleStart(id,input,token);}}return;}
  if(kind.endsWith("_end")){if(!TOKENS.end(id,casterId,token))return;if(id.equals("vec_reflection")){if(mine){if(!AcademyClient.acceptedContextEnd(id,input,token))endLocal(id);}}else{var p=PLASMAS.get(casterId);if(p!=null&&p.token==token)p.end();if(mine){AcademyClient.acceptedSingleEnd(id,input,token);predictedPlasma=false;}}return;}
  if(caster==null||!TOKENS.live(id,casterId,token))return;String key=id+":"+casterId+":"+token;long seq=tag.getLong("sequence");if(seq<=0||seq<=EVENTS.getOrDefault(key,0L))return;EVENTS.put(key,seq);while(EVENTS.size()>512){var it=EVENTS.keySet().iterator();it.next();it.remove();}Vec3 at=point(tag);if(!finite(at))return;
  if(id.equals("vec_reflection")){float yaw=tag.getFloat("yaw"),pitch=tag.getFloat("pitch");if(!Float.isFinite(yaw)||!Float.isFinite(pitch))return;if(kind.equals("vec_reflection_entity")){var entity=target.getEntity(tag.getInt("target"));Vec3 v=new Vec3(tag.getDouble("vx"),tag.getDouble("vy"),tag.getDouble("vz"));if(entity!=null&&finite(v)){entity.setDeltaMovement(v);entity.hasImpulse=true;}}if(WAVES.size()<256){for(int ring=0;ring<2;ring++)WAVES.add(new Wave(at,yaw,pitch,ring));}play(at,ClassicVectorFinalTimeline.REFLECTION_SOUND,.5F);
  }else{var p=PLASMAS.get(casterId);if(p==null||p.token!=token||p.dead)return;if(kind.equals("plasma_cannon_go")){Vec3 dest=new Vec3(tag.getDouble("dx"),tag.getDouble("dy"),tag.getDouble("dz"));if(!finite(dest))return;p.go=true;p.destination=dest;p.tornadoDead=true;}else if(kind.equals("plasma_cannon_position"))p.at=at;else if(kind.equals("plasma_cannon_ready")&&mine)play(caster.position(),ClassicVectorFinalTimeline.READY_SOUND,.5F);}
 });}
 private static Vec3 point(CompoundTag t){return new Vec3(t.getDouble("x"),t.getDouble("y"),t.getDouble("z"));}private static boolean finite(Vec3 v){return Double.isFinite(v.x)&&Double.isFinite(v.y)&&Double.isFinite(v.z);}
 private static SoundEvent sound(String name){return SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("academy",name));}private static void play(Vec3 at,String name,float volume){var mc=Minecraft.getInstance();if(mc.level!=null)mc.level.playLocalSound(at.x,at.y,at.z,sound(name),SoundSource.MASTER,volume,1,false);}
 public static void clear(){for(var p:PLASMAS.values())p.close();PLASMAS.clear();WAVES.clear();RIPPLES.clear();TOKENS.clear();INPUTS.clear();EVENTS.clear();reflection=predictedPlasma=false;clock=0;lastWall=Util.getMillis();lastFrame=0;}
 private static void synchronize(Minecraft mc){if(level==mc.level&&player==mc.player&&connection==mc.getConnection())return;clear();level=mc.level;player=mc.player;connection=mc.getConnection();}private static void advance(Minecraft mc){long wall=Util.getMillis();if(mc.level!=null&&!mc.isPaused())clock+=Math.max(0,wall-lastWall);lastWall=wall;}
 @SubscribeEvent public static void tick(ClientTickEvent.Post e){var mc=Minecraft.getInstance();synchronize(mc);advance(mc);if(mc.level==null||mc.player==null)return;if(!mc.player.isAlive()||!AcademyClient.state.category.equals("vecmanip")){reflection=predictedPlasma=false;RIPPLES.clear();for(var p:PLASMAS.values())if(p.caster==mc.player)p.end();}else if(!AcademyClient.state.overloadFine){reflection=predictedPlasma=false;RIPPLES.clear();var p=PLASMAS.get(mc.player.getId());if(p!=null&&!p.go&&!p.released)p.end();}else if(!AcademyClient.state.activated||AcademyClient.state.interfering){predictedPlasma=false;var p=PLASMAS.get(mc.player.getId());if(p!=null&&!p.go&&!p.released)p.end();}if(mc.isPaused())return;WAVES.removeIf(w->++w.age>=15);PLASMAS.values().removeIf(p->{p.age++;if(p.caster.isRemoved())p.end();if(p.go&&!p.dead){var moved=PlasmaCannonSession.move(new double[]{p.at.x,p.at.y,p.at.z},new double[]{p.destination.x,p.destination.y,p.destination.z});p.at=new Vec3(moved[0],moved[1],moved[2]);}if(p.tornadoDead)p.deadTicks++;if(p.dead&&Math.abs(p.alpha)<=1E-3F&&p.deadTicks>=30){p.close();return true;}return false;});}
 @SubscribeEvent public static void render(RenderLevelStageEvent e){if(e.getStage()!=RenderLevelStageEvent.Stage.AFTER_PARTICLES)return;var mc=Minecraft.getInstance();synchronize(mc);advance(mc);if(mc.level==null||mc.player==null)return;if(buffers==null)buffers=MultiBufferSource.immediate(new ByteBufferBuilder(65536));var poses=e.getPoseStack();Vec3 camera=e.getCamera().getPosition();poses.pushPose();try{poses.translate(-camera.x,-camera.y,-camera.z);
  if(!WAVES.isEmpty()){var out=buffers.getBuffer(ClassicVectorFinalRenderTypes.WAVE);for(var w:WAVES){double a=ClassicVectorStarterTimeline.waveAlpha(w.age,w.life,w.delay);if(a<=0)continue;double size=ClassicVectorStarterTimeline.waveSize(w.age,w.size);poses.pushPose();poses.translate(w.at.x,w.at.y,w.at.z);poses.mulPose(Axis.YP.rotationDegrees(-w.yaw));poses.mulPose(Axis.XP.rotationDegrees(w.pitch));poses.translate(0,0,ClassicVectorStarterTimeline.waveDepth(w.age,w.offset));var m=poses.last().pose();quad(out,m,-size/2,-size/2,size*1.5,0,(float)a);poses.popPose();}buffers.endBatch(ClassicVectorFinalRenderTypes.WAVE);}
  for(var p:PLASMAS.values()){
   if(p.deadTicks<30){var out=buffers.getBuffer(ClassicVectorFinalRenderTypes.TORNADO);float a=(float)ClassicVectorFinalTimeline.tornadoAlpha(p.age,p.tornadoDead,p.deadTicks);double time=clock/250.0-p.timeOffset;var m=poses.last().pose();for(var ring:p.rings){double[] data=ClassicVectorFinalTimeline.ring(ring,time);for(int i=0;i<20;i++){double r0=i/20.0*Math.PI*2,r1=(i+1)/20.0*Math.PI*2,x0=Math.sin(r0)*data[2]+data[0]+p.ground.x,x1=Math.sin(r1)*data[2]+data[0]+p.ground.x,z0=Math.cos(r0)*data[2]+data[1]+p.ground.z,z1=Math.cos(r1)*data[2]+data[1]+p.ground.z,y0=p.ground.y+ring.y()+ring.width()/2,y1=p.ground.y+ring.y()-ring.width()/2;float u=(float)(i/20.0-data[3]);vertex(out,m,x0,y0,z0,u,0,a);vertex(out,m,x0,y1,z0,u,1,a);vertex(out,m,x1,y1,z1,u+.05F,1,a);vertex(out,m,x1,y0,z1,u+.05F,0,a);}}buffers.endBatch(ClassicVectorFinalRenderTypes.TORNADO);}
   float dt=Math.max(0,(clock-p.lastFrame)/1000F);p.alpha=ClassicVectorFinalTimeline.bodyAlpha(p.alpha,dt,p.dead);p.lastFrame=clock;if(ClassicVectorFinalShader.get()==null)continue;var ballData=new ArrayList<Vector4f>();for(var b:p.balls){double[] at=ClassicVectorFinalTimeline.ball(b,dt);var v=new Vector4f((float)(p.at.x+at[0]),(float)(p.at.y+at[1]),(float)(p.at.z+at[2]),1);poses.last().pose().transform(v);v.w=(float)at[3];ballData.add(v);}ClassicVectorFinalShader.set(p.alpha*p.alpha,ballData);var out=buffers.getBuffer(ClassicVectorFinalRenderTypes.PLASMA);poses.pushPose();poses.translate(p.at.x,p.at.y,p.at.z);Vec3 delta=p.at.subtract(camera);float yaw=(float)Math.toDegrees(Math.atan2(-delta.x,delta.z)),pitch=(float)Math.toDegrees(-Math.atan2(delta.y,Math.sqrt(delta.x*delta.x+delta.z*delta.z)));poses.mulPose(Axis.YP.rotationDegrees(-yaw+180));poses.mulPose(Axis.XP.rotationDegrees(-pitch));quad(out,poses.last().pose(),-11,-11,22,0,1);buffers.endBatch(ClassicVectorFinalRenderTypes.PLASMA);poses.popPose();
  }
 }finally{poses.popPose();}}
 @SubscribeEvent public static void overlay(RenderGuiLayerEvent.Pre e){if(!e.getName().equals(ResourceLocation.withDefaultNamespace("crosshair")))return;var mc=Minecraft.getInstance();synchronize(mc);advance(mc);if(!reflection||mc.level==null)return;float now=clock/1000F,dt=Math.max(0,now-lastFrame);lastFrame=now;var g=e.getGuiGraphics();float width=g.guiWidth(),height=g.guiHeight();RIPPLES.removeIf(r->{r.age+=dt;return r.age>=r.life;});if(RANDOM.nextFloat()<dt*1.6F&&RIPPLES.size()<256)RIPPLES.add(new Ripple((.8F+RANDOM.nextFloat()*.4F)*110,2,RANDOM.nextFloat()*width,RANDOM.nextFloat()*height));var c=new ClassicHudCanvas(g);c.begin();try{for(var r:RIPPLES){double a=.4F*ClassicVectorStarterTimeline.rippleAlpha(r.age,r.life),size=ClassicVectorStarterTimeline.rippleSize(r.size,r.age)/2.0,x=ClassicVectorStarterTimeline.rippleX(r.x,width),y=ClassicVectorStarterTimeline.rippleY(r.y,height);c.rect(GLOW,x-size/2,y-size/2,size,size,0,1,1,0,new ClassicHudTimeline.Rgba(a,a,a,a),ClassicSkillAlphaShader.get(),null);}}finally{c.end();}}
 private static void quad(VertexConsumer o,Matrix4f m,double x,double y,double size,double z,float a){vertex(o,m,x,y,z,0,0,a);vertex(o,m,x,y+size,z,0,1,a);vertex(o,m,x+size,y+size,z,1,1,a);vertex(o,m,x+size,y,z,1,0,a);}private static void vertex(VertexConsumer o,Matrix4f m,double x,double y,double z,float u,float v,float a){o.addVertex(m,(float)x,(float)y,(float)z).setUv(u,v).setColor(1,1,1,Mth.clamp(a,0,1));}
 private static final class Plasma{final Entity caster;final long token;final float charge;final List<ClassicVectorFinalTimeline.Ball> balls=ClassicVectorFinalTimeline.balls(RANDOM);final double timeOffset=RANDOM.nextDouble()*20;final List<ClassicVectorFinalTimeline.Ring> rings=ClassicVectorFinalTimeline.rings(RANDOM);final Vec3 ground;final FollowingSound sound;Vec3 at,destination;boolean go,dead,tornadoDead,released;int age,deadTicks;float alpha;long lastFrame=clock;Plasma(Entity e,long token,Vec3 at,float charge){caster=e;this.token=token;this.at=at;this.charge=charge;var hit=e.level().clip(new ClipContext(at,at.add(0,-20,0),ClipContext.Block.COLLIDER,ClipContext.Fluid.NONE,e));ground=hit.getLocation();sound=new FollowingSound(e);}void end(){dead=tornadoDead=true;sound.close();}void close(){sound.close();Minecraft.getInstance().getSoundManager().stop(sound);}}
 private static final class Wave{final Vec3 at;final float yaw,pitch;final int life,delay;final double offset,size;int age;Wave(Vec3 at,float yaw,float pitch,int ring){this.at=at;this.yaw=yaw;this.pitch=pitch;life=8+RANDOM.nextInt(4);offset=ring*1.5-.3+RANDOM.nextDouble()*.6;size=1.1*(.8+RANDOM.nextDouble()*.4);delay=ring*2-1+RANDOM.nextInt(2);}}
 private static final class Ripple{final float size,life,x,y;float age;Ripple(float s,float l,float x,float y){size=s;life=l;this.x=x;this.y=y;}}
 private static final class FollowingSound extends AbstractTickableSoundInstance{final Entity caster;final ClientLevel world;FollowingSound(Entity e){super(sound(ClassicVectorFinalTimeline.PLASMA_SOUND),SoundSource.MASTER,RandomSource.create());caster=e;world=Minecraft.getInstance().level;volume=1;looping=false;tick();}@Override public void tick(){if(world!=Minecraft.getInstance().level||caster.isRemoved()){stop();return;}x=caster.getX();y=caster.getY();z=caster.getZ();}void close(){stop();}}
}
