/* Copyright(c) Lambda Innovation,2013-2016. AcademyCraft STContextC/Flashing adapters.
 * GPLv3; see NOTICE. Original TP particles/marking biped are adapted, not placeholder sprites. */
package cn.academy.port.client;
import cn.academy.port.skill.*;
import com.mojang.blaze3d.platform.InputConstants;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.*;
import com.mojang.math.Axis;
import net.minecraft.Util;
import net.minecraft.client.*;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.renderer.*;
import net.minecraft.client.resources.sounds.AbstractTickableSoundInstance;
import net.minecraft.util.RandomSource;
import net.minecraft.nbt.*;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.phys.*;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.*;
import net.neoforged.neoforge.common.NeoForge;
import org.joml.Matrix4f;
import org.lwjgl.glfw.GLFW;
import java.util.*;
import static cn.academy.port.skill.TeleporterFinalRules.*;
/** Cosmetic-only server token envelopes; local fixed A/D/W/S delegates send bounded direction IDs. */
@EventBusSubscriber(modid="academy",value=Dist.CLIENT)
public final class ClassicTeleporterFinalEffects {
 private static final Set<String> IDS=Set.of(LOCATION,SHIFT,FLASH);private static final Map<String,Long> NONCES=new HashMap<>();private static final Map<String,Boolean> SHOW=new HashMap<>();private static final Map<String,Map<UUID,Context>> CONTEXTS=new HashMap<>();private static final Map<String,Map<UUID,Long>> CLOSED=new HashMap<>();private static final List<Particle> PARTICLES=new ArrayList<>();private static final Map<UUID,Long> PLACED=new HashMap<>();private static final List<FollowSound> SOUNDS=new ArrayList<>();private static final Random RANDOM=new Random();private static long nextNonce,epoch;private static ClientLevel level;private static Player player;private static Object connection;private static int performing=-1,gravity;private static long hopSequence;private static final int[] KEYS={GLFW.GLFW_KEY_A,GLFW.GLFW_KEY_D,GLFW.GLFW_KEY_W,GLFW.GLFW_KEY_S};private static final String[] LETTERS={"a","d","w","s"};private static MultiBufferSource.BufferSource buffers;private static final ResourceLocation TP=texture("effects/tp_particle");private static final ResourceLocation[] MARKS=new ResourceLocation[7];
 static{for(String id:IDS){CONTEXTS.put(id,new HashMap<>());CLOSED.put(id,new HashMap<>());}for(int i=0;i<7;i++)MARKS[i]=texture("effects/tp_mark/"+i);}private ClassicTeleporterFinalEffects(){}
 public static boolean owns(String id){return IDS.contains(id);}public static long startLocal(String id){if(!owns(id))return 0;sync(Minecraft.getInstance());long n=++nextNonce;NONCES.put(id,n);SHOW.put(id,true);return n;}public static long localNonce(String id){return NONCES.getOrDefault(id,0L);}public static boolean delegateActive(String id){return owns(id)&&SHOW.getOrDefault(id,false);}public static boolean anyActive(){return delegateActive(FLASH);}
 public static void hideLocal(String id){if(!owns(id))return;SHOW.put(id,false);if(FLASH.equals(id)){performing=-1;}}public static void endLocal(String id){hideLocal(id);if(LOCATION.equals(id)&&Minecraft.getInstance().screen instanceof ClassicLocationTeleportScreen s)s.closeFromServer();}
 public static boolean locationScreen(){return Minecraft.getInstance().screen instanceof ClassicLocationTeleportScreen;}
 public static boolean flashMode(){var p=Minecraft.getInstance().player;return p!=null&&delegateActive(FLASH)&&CONTEXTS.get(FLASH).containsKey(p.getUUID());}
 public static boolean directionOverrides(KeyMapping mapping){if(!flashMode()||mapping.getKey().getType()!=InputConstants.Type.KEYSYM)return false;for(int key:KEYS)if(mapping.getKey().getValue()==key)return true;return false;}
 public static double consumptionHint(){return flashMode()&&performing>0?flashConsumption(CONTEXTS.get(FLASH).get(Minecraft.getInstance().player.getUUID()).exp):0;}
 public static void appendKeys(List<ClassicAbilityHud.KeyHint> out){if(!flashMode())return;for(int i=0;i<4;i++)out.add(new ClassicAbilityHud.KeyHint("TP_Flashing",i+1,LETTERS[i],Component.literal(LETTERS[i].toUpperCase(Locale.ROOT)),-1,performing==i+1?ClassicAbilityHud.DelegateVisual.ACTIVE:ClassicAbilityHud.DelegateVisual.IDLE,0,1));}
 public static void receive(CompoundTag raw){if(raw==null)return;var t=raw.copy();String kind=t.getString("kind"),id=IDS.stream().filter(v->kind.startsWith(v+"_")).findFirst().orElse("");if(id.isEmpty()||!t.hasUUID("entity_uuid")||!t.contains("entity",Tag.TAG_INT)||!t.contains("token",Tag.TAG_LONG)||t.getLong("token")<=0||!t.contains("input",Tag.TAG_LONG)||t.getLong("input")<0||!t.contains("exp",Tag.TAG_DOUBLE)||!Double.isFinite(t.getDouble("exp"))||t.getDouble("exp")<0||t.getDouble("exp")>1)return;Minecraft mc=Minecraft.getInstance();var atLevel=mc.level;var atPlayer=mc.player;var atConnection=mc.getConnection();long generation=epoch;mc.execute(()->{if(atLevel==null||atPlayer==null||atLevel!=mc.level||atPlayer!=mc.player||atConnection!=mc.getConnection()||generation!=epoch)return;sync(mc);Entity e=mc.level.getEntity(t.getInt("entity"));if(!(e instanceof Player caster)||!caster.getUUID().equals(t.getUUID("entity_uuid")))return;boolean local=caster==mc.player;long token=t.getLong("token"),nonce=t.getLong("input");if(local&&nonce!=localNonce(id))return;var all=CONTEXTS.get(id);var closed=CLOSED.get(id);Context c=all.get(caster.getUUID());long last=closed.getOrDefault(caster.getUUID(),0L);boolean afterEnd=kind.equals(SHIFT+"_placed")||kind.equals(SHIFT+"_critical");if(token<last||token==last&&!afterEnd||c!=null&&token<c.token)return;
  if(kind.equals(LOCATION+"_list")){if(!local||!delegateActive(id)||t.getList("locations",Tag.TAG_COMPOUND).size()>256)return;if(c==null)all.put(caster.getUUID(),new Context(caster,id,token,nonce,t.getDouble("exp"),local));else if(c.token!=token)return;if(mc.screen instanceof ClassicLocationTeleportScreen screen&&screen.matches(nonce))screen.update(t);else mc.setScreen(new ClassicLocationTeleportScreen(nonce,t));return;}
  if(kind.endsWith("_start")){if(c!=null&&token==c.token)return;if(all.size()>=128&&!all.containsKey(caster.getUUID()))return;if(local&&FLASH.equals(id)&&AcademyClient.contextStartCancelled(id,nonce,token))return;all.put(caster.getUUID(),new Context(caster,id,token,nonce,t.getDouble("exp"),local));if(local&&FLASH.equals(id)){performing=-1;hopSequence=0;AcademyClient.acceptedContextStart(FLASH,nonce,token,true);}else if(local&&SHIFT.equals(id))AcademyClient.acceptedSingleStart(id,nonce,token);return;}
  if(c!=null&&(c.token!=token||c.nonce!=nonce))return;
  if(kind.equals(SHIFT+"_critical")){if(t.getInt("critical_tier")<0||t.getInt("critical_tier")>2||!t.hasUUID("target_uuid"))return;Entity target=mc.level.getEntity(t.getInt("target"));if(target!=null&&target.getUUID().equals(t.getUUID("target_uuid"))&&caster==mc.player)NeoForge.EVENT_BUS.post(new ClassicFirstSkillEffects.TeleporterCriticalHitEvent(caster,target,t.getInt("critical_tier")));return;}
  if(kind.equals(SHIFT+"_placed")){if(token<=PLACED.getOrDefault(caster.getUUID(),0L))return;if(PLACED.size()>=256&&!PLACED.containsKey(caster.getUUID()))PLACED.clear();PLACED.put(caster.getUUID(),token);sound(caster,"tp.tp_shift",.5F);return;}
  if(kind.equals(FLASH+"_perform")){if(c==null||!t.contains("hop",Tag.TAG_LONG)||t.getLong("hop")<=c.lastHop||t.getLong("hop")>4096)return;c.lastHop=t.getLong("hop");sound(caster,"tp.tp_flashing",1);if(local)gravity=40;return;}
  if(!kind.endsWith("_end"))return;boolean deferred=local&&FLASH.equals(id)&&AcademyClient.acceptedContextEnd(id,nonce,token);if(local&&SHIFT.equals(id))AcademyClient.acceptedSingleEnd(id,nonce,token);if(!deferred)all.remove(caster.getUUID());if(closed.size()>=256&&!closed.containsKey(caster.getUUID()))closed.clear();closed.put(caster.getUUID(),token);if(local&&!deferred)endLocal(id);if(SHIFT.equals(id)&&t.getBoolean("success")&&finite(t)){Vec3 target=new Vec3(t.getDouble("x"),t.getDouble("y"),t.getDouble("z")),origin=caster.position().add(0,-.5,0);Vec3 dir=target.subtract(origin).normalize();double distance=target.distanceTo(origin),move=1,cumulative=move;Vec3 cursor=origin;while(cumulative<=distance&&PARTICLES.size()<2048){cursor=cursor.add(dir.scale(move));PARTICLES.add(new Particle(cursor,new Vec3(random(-.05,.05),random(-.02,.05),random(-.05,.05)),.1F+RANDOM.nextFloat()*.1F,random(.6,.8)));move=random(.6,1);cumulative+=move;}}});}
 @SubscribeEvent public static void tick(ClientTickEvent.Post event){Minecraft mc=Minecraft.getInstance();sync(mc);if(mc.level==null||mc.isPaused())return;PARTICLES.removeIf(p->!p.tick());SOUNDS.removeIf(FollowSound::finished);for(String id:IDS)CONTEXTS.get(id).values().removeIf(c->!c.valid(mc));if(flashMode()){Context c=CONTEXTS.get(FLASH).get(mc.player.getUUID());if(performing>0&&AcademyClient.state.cp<flashConsumption(c.exp)&&!mc.player.getAbilities().instabuild)performing=-1;if(performing>0){c.position=Flashing.destination(c.caster,c.exp,performing);c.ticks++;c.markTicks++;spawnMark(c);}else c.ticks++;}for(Context c:CONTEXTS.get(SHIFT).values())if(c.local&&delegateActive(SHIFT)){c.ticks++;var dest=ShiftTeleport.trace(c.caster,c.exp).position();c.position=new Vec3(dest.getX()+.5,dest.getY(),dest.getZ()+.5);if(c.ticks%3==0)c.targets=ShiftTeleport.targets(c.caster,c.exp);}}
 /** Original local-only gravity compensation:39 active START increments, then removal on40. */
 @SubscribeEvent public static void preTick(ClientTickEvent.Pre e){var mc=Minecraft.getInstance();sync(mc);if(mc.player!=null&&!mc.player.isAlive()){gravity=0;return;}if(gravity<=0||mc.player==null||mc.level==null||mc.screen!=null||mc.isPaused())return;if(--gravity>0&&!mc.player.getAbilities().flying&&!mc.player.onGround())mc.player.setDeltaMovement(mc.player.getDeltaMovement().add(0,.072,0));}
 private static void spawnMark(Context c){if(RANDOM.nextDouble()<.4&&PARTICLES.size()<2048)PARTICLES.add(new Particle(c.position.add(random(-1,1),random(.2,1.6)-1.6,random(-1,1)),new Vec3(random(-.03,.03),random(0,.05),random(-.03,.03)),.1F+RANDOM.nextFloat()*.1F,random(.6,.8)));}
 @SubscribeEvent public static void render(RenderLevelStageEvent e){if(e.getStage()!=RenderLevelStageEvent.Stage.AFTER_PARTICLES)return;var mc=Minecraft.getInstance();sync(mc);if(mc.level==null)return;if(buffers==null)buffers=MultiBufferSource.immediate(new ByteBufferBuilder(65536));var poses=e.getPoseStack();Vec3 camera=e.getCamera().getPosition();float partial=e.getPartialTick().getGameTimeDeltaPartialTick(false);float[] old=RenderSystem.getShaderColor().clone();poses.pushPose();try{RenderSystem.setShaderColor(1,1,1,1);poses.translate(-camera.x,-camera.y,-camera.z);for(Context c:CONTEXTS.get(SHIFT).values())if(c.local&&c.valid(mc)&&delegateActive(SHIFT)&&c.ticks>0){corners(poses,c.position,1.2F,1.2F,139,139,139,180);for(Entity target:c.targets)if(!target.isRemoved())corners(poses,target.position(),target.getBbWidth(),target.getBbHeight(),235,81,81,180);}if(flashMode()&&performing>0){Context c=CONTEXTS.get(FLASH).get(mc.player.getUUID());biped(c,poses);}for(Particle p:PARTICLES){poses.pushPose();Vec3 at=p.previous.lerp(p.position,partial);poses.translate(at.x,at.y,at.z);poses.mulPose(e.getCamera().rotation());billboard(poses.last().pose(),p.size,p.alpha*ClassicTeleporterTimeline.particleAlpha(p.age));poses.popPose();}}finally{poses.popPose();RenderSystem.setShaderColor(old[0],old[1],old[2],old[3]);}}
 private static void biped(Context c,PoseStack poses){poses.pushPose();poses.translate(c.position.x,c.position.y,c.position.z);poses.mulPose(Axis.YP.rotationDegrees(-c.caster.getYRot()));poses.scale(-.0625F,-.0625F,.0625F);var type=Material.type(MARKS[ClassicTeleporterTimeline.markFrame(c.markTicks)],true,false);var out=buffers.getBuffer(type);for(var box:ClassicTeleporterTimeline.BIPED)for(var q:ClassicTeleporterTimeline.mesh(box))for(var v:List.of(q.a(),q.b(),q.c(),q.d()))vertex(out,poses.last().pose(),new Vec3(v.x(),v.y(),v.z()),v.u(),v.v(),1);buffers.endBatch(type);poses.popPose();}
 private static void corners(PoseStack poses,Vec3 pos,float width,float height,int r,int g,int b,int alpha){Vec3 at=pos.add(-width/2,ClassicTeleporterTimeline.markerBob(Util.getMillis()),-width/2);var out=buffers.getBuffer(Material.CORNERS);double length=.2*width;for(int i=0;i<8;i++){int j=i%4;Vec3 a=at.add(j==1||j==2?width:0,i>=4?height:0,j>=2?width:0);double yaw=-Math.PI/2*j;line(out,poses.last(),a,a.add(0,i<4?length:-length,0),r,g,b,alpha);line(out,poses.last(),a,a.add(length*Math.cos(yaw),0,-length*Math.sin(yaw)),r,g,b,alpha);line(out,poses.last(),a,a.add(length*Math.sin(yaw),0,length*Math.cos(yaw)),r,g,b,alpha);}buffers.endBatch(Material.CORNERS);}
 private static void line(VertexConsumer out,PoseStack.Pose p,Vec3 a,Vec3 b,int r,int g,int blue,int alpha){Vec3 n=b.subtract(a).normalize();for(Vec3 v:List.of(a,b))out.addVertex(p.pose(),(float)v.x,(float)v.y,(float)v.z).setColor(r,g,blue,alpha).setNormal(p,(float)n.x,(float)n.y,(float)n.z);}
 private static void billboard(Matrix4f m,float size,double alpha){var type=Material.type(TP,false,true);var out=buffers.getBuffer(type);vertex(out,m,new Vec3(-size/2,-size*.25,0),0,1,alpha);vertex(out,m,new Vec3(size/2,-size*.25,0),1,1,alpha);vertex(out,m,new Vec3(size/2,size*.75,0),1,0,alpha);vertex(out,m,new Vec3(-size/2,size*.75,0),0,0,alpha);buffers.endBatch(type);}private static void vertex(VertexConsumer out,Matrix4f m,Vec3 p,float u,float v,double alpha){out.addVertex(m,(float)p.x,(float)p.y,(float)p.z).setUv(u,v).setColor(255,255,255,Math.max(0,Math.min(255,(int)Math.round(alpha*255))));}
 private static final class Context{final Player caster;final String id;final long token,nonce;final double exp;final ClientLevel level;final Object connection;final boolean local;long lastHop;int ticks,markTicks;Vec3 position;List<Entity> targets=List.of();Context(Player p,String id,long token,long nonce,double exp,boolean local){caster=p;this.id=id;this.token=token;this.nonce=nonce;this.exp=exp;this.local=local;level=Minecraft.getInstance().level;connection=Minecraft.getInstance().getConnection();position=p.position();}boolean valid(Minecraft mc){return level==mc.level&&connection==mc.getConnection()&&caster.isAlive()&&!caster.isRemoved()&&level.getEntity(caster.getId())==caster;}}
 private static final class Particle{Vec3 position,previous;final Vec3 velocity;final float size;final double alpha;int age;Particle(Vec3 p,Vec3 v,float size,double a){position=previous=p;velocity=v;this.size=size;alpha=a;}boolean tick(){previous=position;position=position.add(velocity);return ClassicTeleporterTimeline.particleAlive(++age);}}
 private static boolean finite(CompoundTag t){return t.contains("x",Tag.TAG_DOUBLE)&&t.contains("y",Tag.TAG_DOUBLE)&&t.contains("z",Tag.TAG_DOUBLE)&&Double.isFinite(t.getDouble("x"))&&Double.isFinite(t.getDouble("y"))&&Double.isFinite(t.getDouble("z"));}private static double random(double a,double b){return a+RANDOM.nextDouble()*(b-a);}private static ResourceLocation texture(String p){return ResourceLocation.fromNamespaceAndPath("academy","textures/"+p+".png");}private static void sound(Entity p,String id,float volume){var mc=Minecraft.getInstance();if(mc.level==null)return;if(id.equals("tp.tp_flashing")){var s=new FollowSound(p,id,volume);if(SOUNDS.size()>=256)SOUNDS.remove(0).finish();SOUNDS.add(s);mc.getSoundManager().play(s);}else mc.level.playLocalSound(p.getX(),p.getY(),p.getZ(),SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("academy",id)),SoundSource.MASTER,volume,1,false);}
 private static final class FollowSound extends AbstractTickableSoundInstance {final Entity caster;final ClientLevel level;int age;FollowSound(Entity p,String id,float volume){super(SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("academy",id)),SoundSource.MASTER,RandomSource.create());caster=p;level=Minecraft.getInstance().level;this.volume=volume;pitch=1;tick();}public void tick(){if(caster.isRemoved()||Minecraft.getInstance().level!=level){stop();return;}x=(float)caster.getX();y=(float)caster.getY();z=(float)caster.getZ();age++;}boolean finished(){if(age>400)stop();return isStopped();}void finish(){stop();}}
 /** Accepted local END disposes only this exact context; the copied render/audio bodies stay unchanged. */
 public static void terminateContext(long input,long token){var mc=Minecraft.getInstance();if(mc.player==null)return;var all=CONTEXTS.get(FLASH);Context c=all.get(mc.player.getUUID());if(c!=null&&c.nonce==input&&c.token==token){all.remove(mc.player.getUUID());CLOSED.get(FLASH).merge(mc.player.getUUID(),token,Math::max);}endLocal(FLASH);}
 /** Source direction callbacks; only AcademyClient's shared registry polls physical keys. */
 public static void direction(long input,long token,int direction,ClassicClientInputBinding.Edge edge,boolean silent){var mc=Minecraft.getInstance();if(mc.player==null||direction<1||direction>4)return;Context c=CONTEXTS.get(FLASH).get(mc.player.getUUID());if(c==null||c.token!=token||c.nonce!=input||!c.valid(mc))return;if(edge==ClassicClientInputBinding.Edge.DOWN){performing=direction;c.markTicks=0;}else if(performing==direction){if(edge==ClassicClientInputBinding.Edge.UP&&!silent)AcademyClient.request("flashing_direction_owned",input+":"+token+":"+(++hopSequence)+":"+direction);performing=-1;}}
 private static void sync(Minecraft mc){if(level==mc.level&&player==mc.player&&connection==mc.getConnection())return;clear();level=mc.level;player=mc.player;connection=mc.getConnection();}public static void clear(){for(String id:IDS){CONTEXTS.get(id).clear();CLOSED.get(id).clear();}NONCES.clear();SHOW.clear();PLACED.clear();PARTICLES.clear();for(var s:SOUNDS)s.finish();SOUNDS.clear();performing=-1;gravity=0;epoch++;}
 private static final class Material extends RenderType{private record Key(ResourceLocation t,boolean overlay,boolean depthWrite){}private static final Map<Key,RenderType> TYPES=new HashMap<>();private Material(String n,VertexFormat f,VertexFormat.Mode m,int s,boolean c,boolean sort,Runnable set,Runnable reset){super(n,f,m,s,c,sort,set,reset);}static RenderType type(ResourceLocation t,boolean overlay,boolean write){return TYPES.computeIfAbsent(new Key(t,overlay,write),k->create("academy_classic_tp_final_"+k.t.getPath()+"_"+overlay+"_"+write,DefaultVertexFormat.POSITION_TEX_COLOR,VertexFormat.Mode.QUADS,4096,false,false,CompositeState.builder().setShaderState(new ShaderStateShard(overlay?ClassicSkillAlphaShader::get:ClassicMeltdownerStarterEffects.CutoffShader::zero)).setTextureState(new TextureStateShard(t,false,false)).setTransparencyState(TRANSLUCENT_TRANSPARENCY).setCullState(NO_CULL).setLightmapState(NO_LIGHTMAP).setOverlayState(NO_OVERLAY).setDepthTestState(overlay?NO_DEPTH_TEST:LEQUAL_DEPTH_TEST).setWriteMaskState(write?COLOR_DEPTH_WRITE:COLOR_WRITE).setOutputState(PARTICLES_TARGET).createCompositeState(false)));}static final RenderType CORNERS=create("academy_classic_shift_corners",DefaultVertexFormat.POSITION_COLOR_NORMAL,VertexFormat.Mode.LINES,2048,false,false,CompositeState.builder().setShaderState(new ShaderStateShard(GameRenderer::getRendertypeLinesShader)).setLineState(new LineStateShard(OptionalDouble.of(3))).setTransparencyState(TRANSLUCENT_TRANSPARENCY).setCullState(NO_CULL).setDepthTestState(NO_DEPTH_TEST).setWriteMaskState(COLOR_DEPTH_WRITE).setOutputState(PARTICLES_TARGET).createCompositeState(false));}
}
