/* Actual cached official NeoForge event bus and native compressed NBT, with no game bootstrap. GPLv3. */
package cn.academy.port.api;
import cn.academy.port.AbilityStorage;
import cn.academy.port.core.*;
import net.minecraft.nbt.*;
import net.neoforged.bus.api.*;
import java.io.*;
import java.util.*;
public final class ClassicActivationAndSetXpBusStorageTest {
 static int checks;
 static void check(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}
 static void flags(AbilityProgress s){check(!s.overloadFine&&s.interfering&&s.cpDelay==13&&s.overloadDelay==21,"setters preserve overload lock/interference/recovery delays");}
 static AbilityProgress cold(AbilityProgress s)throws IOException{var bytes=new ByteArrayOutputStream();NbtIo.writeCompressed(AbilityStorage.encodeSaved(s),bytes);return AbilityStorage.decodeSaved(NbtIo.readCompressed(new ByteArrayInputStream(bytes.toByteArray()),NbtAccounter.unlimitedHeap()),s.cpDataConfig());}
 public static void main(String[] args)throws IOException{
  for(var type:List.of(AbilityActivateEvent.class,AbilityDeactivateEvent.class,SkillExpChangedEvent.class))check(!ICancellableEvent.class.isAssignableFrom(type),"source activation/raw-XP events are noncancellable");
  var bus=BusBuilder.builder().build();var s=new AbilityProgress();s.changeCategoryClassic("electromaster");s.learn("arc_gen");s.restoreCalculatedMaxima(9999,444);s.extraCp=100.125f;s.extraOverload=33.25f;s.cp=713.125f;s.overload=17.75f;s.levelExperience=7.7f;s.overloadFine=false;s.interfering=true;s.cpDelay=13;s.overloadDelay=21;s.presets.edit(0,0,"arc_gen",id->true);s.setCooldown("arc_gen",81);
  var phases=new ArrayList<String>();int[] counts={0,0,0,0,0};
  s.bindActivationEvents(value->{if(value)bus.post(new AbilityActivateEvent(null,s));else bus.post(new AbilityDeactivateEvent(null,s));});
  bus.addListener(EventPriority.HIGHEST,AbilityActivateEvent.class,e->{counts[0]++;phases.add("activate-high");check(e.state==s&&s.activated&&s.isActivated()&&s.cp==713.125f&&s.overload==17.75f&&s.baseCp()==9999,"activation HIGHEST sees changed flag and retained resources/cache");flags(s);});
  bus.addListener(EventPriority.LOWEST,AbilityActivateEvent.class,e->phases.add("activate-low"));
  bus.addListener(EventPriority.HIGHEST,AbilityDeactivateEvent.class,e->{counts[1]++;phases.add("deactivate-high");check(e.state==s&&!s.activated&&!s.isActivated(),"deactivation HIGHEST sees changed live flag");flags(s);});
  bus.addListener(EventPriority.LOWEST,AbilityDeactivateEvent.class,e->phases.add("deactivate-low"));
  s.setActivateState(true);check(phases.equals(List.of("activate-high","activate-low")),"actual bus source synchronous activation priority");var exact=AbilityStorage.encode(s);phases.clear();s.setActivateState(true);check(phases.isEmpty()&&AbilityStorage.encode(s).equals(exact)&&counts[0]==1,"same activation is exact state/event no-op");
  s.setActivateState(false);check(phases.equals(List.of("deactivate-high","deactivate-low"))&&s.cp==713.125f&&s.overload==17.75f&&s.extraCp==100.125f&&s.levelExperience==7.7f&&s.presets.currentSkill(0).equals("arc_gen")&&s.cooldowns.get("arc_gen")==81,"deactivation only changes flag, preserves source ledgers/preset/cooldown");phases.clear();s.setActivateState(false);check(phases.isEmpty()&&counts[1]==1,"duplicate deactivation posts no event");
  s.bindProgressEvents((id,effects)->{counts[2]++;effects.run();},(lv,effects)->effects.run(),award->bus.post(new SkillExpChangedEvent(null,award.category(),award.skill(),s)),award->{counts[4]++;bus.post(new SkillExpAddedEvent(null,award.category(),award.skill(),s,award.amount()));});
  bus.addListener(EventPriority.HIGHEST,SkillExpChangedEvent.class,e->{counts[3]++;phases.add("changed-high:"+e.skill);check(e.state==s&&e.category.equals("electromaster")&&e.skill.equals("arc_gen")&&s.experience.get("arc_gen")==((double).2f)&&s.levelExperience==7.7f&&s.cp==713.125f&&s.overload==17.75f&&s.baseCp()==9999&&s.extraCp==100.125f,"Changed HIGHEST sees raw float write without progress/refill/recalc");flags(s);});
  bus.addListener(EventPriority.LOWEST,SkillExpChangedEvent.class,e->phases.add("changed-low:"+e.skill));
  s.setSkillExp("arc_gen",.2f);check(phases.equals(List.of("changed-high:arc_gen","changed-low:arc_gen"))&&counts[2]==0&&counts[3]==1&&counts[4]==0,"learned raw setter emits Changed only");phases.clear();s.setSkillExp("arc_gen",.2f);check(phases.size()==2&&counts[3]==2&&counts[4]==0,"equal raw writes still emit exactly one Changed");
  exact=AbilityStorage.encode(s);phases.clear();s.setSkillExp("charging",.8f);check(phases.isEmpty()&&!s.learned("charging")&&AbilityStorage.encode(s).equals(exact)&&counts[3]==2,"unlearned setter leaves both independent slots and events untouched");boolean wrong=false;try{s.setSkillExp("space_fluct",.8f);}catch(IllegalStateException e){wrong=true;}check(wrong&&phases.isEmpty()&&AbilityStorage.encode(s).equals(exact),"wrong-category raw setter rejects before mutation");
  var restored=cold(s);check(restored.learned("arc_gen")&&restored.experience.get("arc_gen")==((double).2f)&&restored.baseCp()==9999&&restored.baseOverload()==444&&restored.cp==713.125f&&restored.overload==17.75f&&restored.extraCp==100.125f&&restored.levelExperience==7.7f&&!restored.activated,"actual compressed native NBT preserves raw XP and unchanged cached/resource/progress state");check(restored.cooldowns.isEmpty()&&restored.presets.currentSkill(0).equals("arc_gen")&&counts[0]==1&&counts[1]==1&&counts[3]==2,"disk omits source-transient cooldown and restore emits no activation/XP events");
  s.bindCategoryChanges(effects->bus.post(new CategoryChangeEvent(null,s,effects)));bus.addListener(EventPriority.HIGHEST,CategoryChangeEvent.class,e->{phases.add("category-high");check(!s.hasCategory()&&s.activated,"category HIGHEST sees category gone before CP NORMAL deactivation");});bus.addListener(EventPriority.NORMAL,CategoryChangeEvent.class,AbilityCategoryLifecycle::changed);bus.addListener(EventPriority.LOWEST,CategoryChangeEvent.class,e->phases.add("category-low"));
  s.bindCalculations(request->{if(request.kind==AbilityCalculation.Kind.MAX_CP)phases.add("maxcp");if(request.kind==AbilityCalculation.Kind.MAX_OVERLOAD)phases.add("maxoverload");});s.setActivateState(true);phases.clear();s.changeCategoryClassic("");check(phases.equals(List.of("category-high","deactivate-high","deactivate-low","maxcp","maxoverload","category-low")),"actual common category handler nests deactivation before source recalc/refill");check(!s.activated&&s.experience.isEmpty()&&s.presets.currentSkill(0).isEmpty()&&s.cooldowns.isEmpty()&&s.extraCp==100.125f&&s.levelExperience==7.7f,"category removal retains training/progress and clears source identities");phases.clear();s.changeCategoryClassic("");check(phases.isEmpty(),"duplicate category removal posts nothing");wrong=false;try{s.setActivateState(true);}catch(IllegalStateException e){wrong=true;}check(wrong&&!s.activated&&phases.isEmpty(),"no-category activation rejects before flag/event mutation");s.activated=true;check(!s.isActivated(),"raw active flag without category does not report activated");wrong=false;try{s.setActivateState(true);}catch(IllegalStateException e){wrong=true;}check(wrong&&s.activated&&phases.isEmpty(),"source category precondition precedes same-state return");s.setActivateState(false);check(phases.equals(List.of("deactivate-high","deactivate-low")),"no-category deactivation is legal");
  var nestedBus=BusBuilder.builder().build();var nested=new AbilityProgress();nested.changeCategoryClassic("teleporter");var nestedPhases=new ArrayList<String>();nested.bindActivationEvents(value->{if(value)nestedBus.post(new AbilityActivateEvent(null,nested));else nestedBus.post(new AbilityDeactivateEvent(null,nested));});nestedBus.addListener(EventPriority.HIGHEST,AbilityActivateEvent.class,e->{nestedPhases.add("activate-high:true");nested.setActivateState(false);});nestedBus.addListener(EventPriority.HIGHEST,AbilityDeactivateEvent.class,e->nestedPhases.add("deactivate-high:"+e.state.activated));nestedBus.addListener(EventPriority.LOWEST,AbilityDeactivateEvent.class,e->nestedPhases.add("deactivate-low:"+e.state.activated));nestedBus.addListener(EventPriority.LOWEST,AbilityActivateEvent.class,e->nestedPhases.add("activate-low:"+e.state.activated));nested.setActivateState(true);check(nestedPhases.equals(List.of("activate-high:true","deactivate-high:false","deactivate-low:false","activate-low:false"))&&!nested.activated,"actual priority bus preserves synchronous listener reentry and live-state observation");
  var raw=new AbilityProgress();raw.changeCategoryClassic("electromaster");raw.learn("arc_gen");int[] rawChanged={0};raw.bindProgressEvents((id,effects)->effects.run(),(lv,effects)->effects.run(),award->rawChanged[0]++,award->{throw new AssertionError("raw setter must not emit Added");});for(float value:new float[]{-.25f,1.25f,Float.NaN,Float.POSITIVE_INFINITY}){raw.setSkillExp("arc_gen",value);check(Float.floatToIntBits(raw.experience.get("arc_gen").floatValue())==Float.floatToIntBits(value),"direct core setter retains source raw float without clamping");var bounded=cold(raw);check(Double.isFinite(bounded.exp("arc_gen"))&&bounded.exp("arc_gen")>=0&&bounded.exp("arc_gen")<=1,"existing modern cold-storage guard remains bounded");}check(rawChanged[0]==4,"raw value writes each emit Changed exactly once");
  System.out.println("PASS "+checks+" actual NeoForge activation/Changed priority, reentry, no-op/precondition and compressed native-NBT checks; no game bootstrap");
 }
}
