package oracle;
import cn.academy.port.terminal.*; import java.util.*; import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player; import net.minecraft.world.item.*;import net.minecraft.world.level.Level;
import net.minecraft.world.InteractionHand; import net.neoforged.neoforge.common.NeoForge;import net.minecraft.nbt.*;
public final class TerminalModernOracle {
 static int assertions,permutations,scenarios;static final List<String> ORDER=List.of("settings","tutorial","skill_tree","freq_transmitter","media_player");
 static void eq(Object a,Object b){assertions++;if(!Objects.equals(a,b))throw new AssertionError(a+" != "+b);}
 static Set<String> names(TerminalState d){return new TreeSet<>(d.installedApps());}
 static void resetSignals(){TerminalNetwork.calls.clear();NeoForge.EVENT_BUS.events.clear();}
 static void row(String key,TerminalState d,ItemStack stack,Player player){int syncs=player instanceof ServerPlayer p?p.syncs:0;System.out.println("ROW|"+key+"|"+d.terminalInstalled()+"|"+String.join(",",names(d))+"|"+stack.getCount()+"|"+syncs+"|"+NeoForge.EVENT_BUS.events.size()+"|"+String.join(",",TerminalNetwork.calls)+"|"+player.chat.stream().map(c->c.key).reduce((a,b)->a+","+b).orElse(""));scenarios++;}
 public static void main(String[] args)throws Exception{String[] apps=ORDER.toArray(String[]::new);permute(apps,0);persistence();coldLink();System.out.println("SUMMARY|modern|"+permutations+"|"+scenarios+"|"+assertions);}
 static void permute(String[] apps,int pos)throws Exception{if(pos==apps.length){run(apps);return;}for(int i=pos;i<apps.length;i++){Collections.swap(Arrays.asList(apps),pos,i);permute(apps,pos+1);Collections.swap(Arrays.asList(apps),pos,i);}}
 static void run(String[] apps){
  permutations++;TerminalNetwork.order=List.copyOf(Arrays.asList(apps));String prefix=String.join(",",apps);var baseline=new TerminalState();eq(baseline.installedApps(),List.of("settings","tutorial"));eq(baseline.savedAppIds(),Set.of());
  for(boolean remote:new boolean[]{false,true})for(boolean creative:new boolean[]{false,true}){
   Player p=remote?new Player():new ServerPlayer();p.getAbilities().instabuild=creative;var d=remote?new TerminalState():TerminalStorage.get((ServerPlayer)p);var installer=new TerminalInstallerItem(new Item.Properties());eq(installer.properties.stackSize,1);var stack=new ItemStack(installer,3);p.stack=stack;var world=new Level(remote);resetSignals();
   installer.use(world,p,InteractionHand.MAIN_HAND);row(prefix+"/terminal/"+remote+"/"+creative+"/first",d,stack,p);eq(stack.getCount(),remote||creative?3:2);eq(d.terminalInstalled(),!remote);
   installer.use(world,p,InteractionHand.MAIN_HAND);row(prefix+"/terminal/"+remote+"/"+creative+"/repeat",d,stack,p);
   for(String name:List.of("skill_tree","freq_transmitter","media_player")){
    var item=new TerminalAppItem(new Item.Properties(),name);eq(item.properties.stackSize,64);var token=new ItemStack(item,4);p.stack=token;item.use(world,p,InteractionHand.MAIN_HAND);row(prefix+"/app/"+name+"/"+remote+"/"+creative+"/first",d,token,p);eq(token.getCount(),remote||creative?4:3);
    item.use(world,p,InteractionHand.MAIN_HAND);row(prefix+"/app/"+name+"/"+remote+"/"+creative+"/repeat",d,token,p);eq(token.getCount(),remote||creative?4:3);
   }
   eq(d.installedApps(),remote?List.of("settings","tutorial"):ORDER);if(p instanceof ServerPlayer server)eq(server.syncs,4);eq(NeoForge.EVENT_BUS.events.size(),remote?0:4);eq(TerminalNetwork.calls.size(),remote?0:5);eq(p.getInventory().changes,remote||creative?0:4);
  }
  for(String name:List.of("skill_tree","freq_transmitter","media_player")){var p=new ServerPlayer();var d=TerminalStorage.get(p);var item=new TerminalAppItem(new Item.Properties(),name);var token=new ItemStack(item,2);p.stack=token;resetSignals();item.use(new Level(false),p,InteractionHand.MAIN_HAND);row(prefix+"/absent/"+name,d,token,p);eq(token.getCount(),2);eq(p.syncs,0);}
  var direct=new TerminalState();eq(direct.installApp("skill_tree"),true);eq(direct.terminalInstalled(),false);eq(direct.installApp("skill_tree"),false);eq(direct.installApp("settings"),false);eq(direct.installApp("foreign:absent"),false);eq(direct.installTerminal(),true);eq(direct.installTerminal(),false);eq(direct.installApp(null),false);eq(direct.isInstalled(null),false);eq(TerminalState.knownApp(null),false);eq(TerminalState.knownApp("thirdparty:absent"),false);
  for(String name:List.of("settings","tutorial","unknown")){try{new TerminalAppItem(new Item.Properties(),name);throw new AssertionError("unexpected installer "+name);}catch(IllegalArgumentException expected){}}
  // A client-side world never mutates an actual ServerPlayer, even for crosswired test inputs.
  {var p=new ServerPlayer();var item=new TerminalInstallerItem(new Item.Properties());p.stack=new ItemStack(item,2);resetSignals();item.use(new Level(true),p,InteractionHand.MAIN_HAND);eq(p.stack.getCount(),2);eq(TerminalStorage.get(p).terminalInstalled(),false);eq(p.syncs,0);eq(p.chat.size(),0);eq(NeoForge.EVENT_BUS.events.size(),0);}
  {var p=new ServerPlayer();TerminalStorage.get(p).installTerminal();var item=new TerminalAppItem(new Item.Properties(),"skill_tree");p.stack=new ItemStack(item,2);resetSignals();item.use(new Level(true),p,InteractionHand.MAIN_HAND);eq(p.stack.getCount(),2);eq(TerminalStorage.get(p).isInstalled("skill_tree"),false);eq(p.syncs,0);eq(p.chat.size(),0);eq(NeoForge.EVENT_BUS.events.size(),0);}
  // Newly explicit server ingress guards: empty, wrong item, and invalid sender never consume or mutate.
  var installer=new TerminalInstallerItem(new Item.Properties());for(int guard=0;guard<3;guard++){var p=new ServerPlayer();p.valid=guard!=2;p.stack=new ItemStack(guard==1?new Item(new Item.Properties()):installer,guard==0?0:2);resetSignals();installer.use(new Level(false),p,InteractionHand.MAIN_HAND);eq(TerminalStorage.get(p).terminalInstalled(),false);eq(p.syncs,0);eq(p.stack.getCount(),guard==0?0:2);eq(NeoForge.EVENT_BUS.events.size(),0);}
 }
 static void persistence(){
  for(int mask=0;mask<8;mask++)for(boolean terminal:new boolean[]{false,true}){var d=new TerminalState();if(terminal)d.installTerminal();for(int i=0;i<3;i++)if((mask&(1<<i))!=0)d.installApp(ORDER.get(i+2));var tag=TerminalStorage.encode(d);eq(tag.getInt("schema"),1);eq(tag.getAllKeys(),Set.of("schema","isInstalled","installedApps"));var restored=TerminalStorage.decode(tag);eq(names(restored),names(d));eq(restored.savedAppIds(),d.savedAppIds());eq(restored.terminalInstalled(),terminal);eq(restored.installApp("skill_tree"),!d.isInstalled("skill_tree"));}
  var ids=new ArrayList<>(List.of("media_player","thirdparty:future","thirdparty:future"));var d=new TerminalState();d.restore(true,ids);ids.clear();eq(d.savedAppIds(),Set.of("media_player","thirdparty:future"));eq(d.isInstalled("thirdparty:future"),false);var tag=TerminalStorage.encode(d);eq(tag.getList("installedApps",8).get(0).getAsString(),"media_player");eq(TerminalStorage.decode(tag).savedAppIds(),d.savedAppIds());try{d.savedAppIds().clear();throw new AssertionError("mutable saved IDs");}catch(UnsupportedOperationException expected){}try{d.installedApps().clear();throw new AssertionError("mutable app list");}catch(UnsupportedOperationException expected){}
  // Legacy installedList bitsets cannot silently become modern numeric app IDs.
  var legacy=new CompoundTag();legacy.putBoolean("isInstalled",true);var bitset=new ListTag();bitset.add(StringTag.valueOf("numeric-bitset-evidence"));legacy.put("installedList",bitset);var decoded=TerminalStorage.decode(legacy);eq(decoded.terminalInstalled(),true);eq(decoded.savedAppIds(),Set.of());
  var missing=TerminalStorage.decode(new CompoundTag());eq(missing.terminalInstalled(),false);eq(missing.installedApps(),List.of("settings","tutorial"));
  var original=new ServerPlayer();TerminalStorage.get(original).restore(true,List.of("skill_tree","thirdparty:future"));TerminalFrequencySessions.sessions.add(original);TerminalStorage.remove(original);eq(TerminalFrequencySessions.sessions.contains(original),false);eq(TerminalStorage.get(original).savedAppIds(),Set.of("skill_tree","thirdparty:future"));
  var replacement=new ServerPlayer();TerminalFrequencySessions.sessions.add(original);TerminalFrequencySessions.sessions.add(replacement);TerminalStorage.clone(original,replacement);eq(TerminalStorage.get(replacement).savedAppIds(),Set.of("skill_tree","thirdparty:future"));eq(TerminalStorage.get(replacement).terminalInstalled(),true);eq(TerminalFrequencySessions.sessions.isEmpty(),true);TerminalStorage.get(original).installApp("media_player");eq(TerminalStorage.get(replacement).isInstalled("media_player"),false);TerminalFrequencySessions.sessions.add(replacement);TerminalStorage.clear();eq(TerminalFrequencySessions.sessions.isEmpty(),true);
 }
 static void coldLink()throws Exception{var url=TerminalModernOracle.class.getProtectionDomain().getCodeSource().getLocation();try(var loader=new java.net.URLClassLoader(new java.net.URL[]{url},null){protected Class<?> loadClass(String name,boolean resolve)throws ClassNotFoundException{if(name.startsWith("net.minecraft.client.")||name.startsWith("cn.academy.port.client."))throw new ClassNotFoundException("client dependency forbidden: "+name);return super.loadClass(name,resolve);}}){Class<?> state=Class.forName("cn.academy.port.terminal.TerminalState",true,loader);Object value=state.getConstructor().newInstance();eq(state.getMethod("terminalInstalled").invoke(value),false);Class<?> storage=Class.forName("cn.academy.port.terminal.TerminalStorage",true,loader);Object encoded=storage.getMethod("encode",state).invoke(null,value);eq(encoded.getClass().getName(),"net.minecraft.nbt.CompoundTag");for(String name:List.of("TerminalInstallerItem","TerminalAppItem","TerminalInstalledEvent","AppInstalledEvent"))Class.forName("cn.academy.port.terminal."+name,true,loader);}}
}